import type { GovernanceGraphInput } from "./governance-graph-types";

const generatedAt = "2026-06-03T00:00:00.000Z";
export const demoGovernanceGraphInput: GovernanceGraphInput = { generatedAt, applications: [
  { vendorName:"Slack Technologies", applicationName:"Slack", ownerName:"engineering@example.com", annualCost:180000, renewalDate:"2026-07-18", domains:["RENEWALS","SAAS_RATIONALISATION"], duplicateWith:["Teams"], findings:[{ id:"slack-renewal-risk", sourceDomain:"RENEWALS", title:"Slack renewal risk", riskLevel:"HIGH", potentialAnnualSavings:54000, evidenceRefs:["renewal-slack-45-days"], renewalDays:45, duplicateWith:["Teams"] }], evidenceRefs:["renewal-slack-45-days"] },
  { vendorName:"Zoom", applicationName:"Zoom", ownerName:"it@example.com", annualCost:95000, renewalDate:"2026-08-02", domains:["RENEWALS","SAAS_RATIONALISATION"], duplicateWith:["Teams"], findings:[{ id:"zoom-duplicate-communications", sourceDomain:"SAAS_RATIONALISATION", title:"Zoom duplicate communications", riskLevel:"HIGH", potentialAnnualSavings:28500, evidenceRefs:["duplicate-zoom-teams"], duplicateWith:["Teams"] }], evidenceRefs:["duplicate-zoom-teams"] },
  { vendorName:"Tableau", applicationName:"Tableau", ownerName:"data@example.com", annualCost:140000, renewalDate:"2026-08-29", domains:["RENEWALS","SAAS_RATIONALISATION"], overlapWith:["Power BI"], findings:[{ id:"tableau-high-cost-low-usage", sourceDomain:"RENEWALS", title:"Tableau high-cost low-usage", riskLevel:"HIGH", potentialAnnualSavings:35000, evidenceRefs:["usage-tableau-29pct"], renewalDays:87, overlapWith:["Power BI"] }], evidenceRefs:["usage-tableau-29pct"] },
  { vendorName:"Dropbox", applicationName:"Dropbox", annualCost:52000, domains:["SHADOW_IT","SAAS_RATIONALISATION","OWNERSHIP"], duplicateWith:["OneDrive"], findings:[{ id:"dropbox-duplicate-storage", sourceDomain:"SAAS_RATIONALISATION", title:"Dropbox duplicate storage", riskLevel:"HIGH", potentialAnnualSavings:20800, evidenceRefs:["duplicate-dropbox-onedrive"], duplicateWith:["OneDrive"] }, { id:"dropbox-no-owner", sourceDomain:"OWNERSHIP", title:"Dropbox no owner", riskLevel:"HIGH", evidenceRefs:["duplicate-dropbox-onedrive"] }], evidenceRefs:["duplicate-dropbox-onedrive"] },
  { vendorName:"OpenAI", applicationName:"ChatGPT", annualCost:36000, domains:["AI_GOVERNANCE","SHADOW_IT","OWNERSHIP"], findings:[{ id:"chatgpt-ai-policy-gap", sourceDomain:"AI_GOVERNANCE", title:"ChatGPT AI policy gap", riskLevel:"HIGH", potentialAnnualSavings:10200, evidenceRefs:["oauth-app-chatgpt","signin-chatgpt-34-users"] }], evidenceRefs:["oauth-app-chatgpt","signin-chatgpt-34-users"] },
  { vendorName:"Anthropic", applicationName:"Claude", annualCost:24000, domains:["AI_GOVERNANCE","OWNERSHIP"], findings:[{ id:"claude-ownerless-ai-app", sourceDomain:"AI_GOVERNANCE", title:"Claude ownerless AI app", riskLevel:"HIGH", evidenceRefs:["owner-gap-claude"] }], evidenceRefs:["owner-gap-claude"] },
  { vendorName:"Microsoft", applicationName:"Microsoft Copilot", ownerName:"ai-governance@example.com", annualCost:15120, domains:["AI_GOVERNANCE"], findings:[{ id:"copilot-policy-gap", sourceDomain:"AI_GOVERNANCE", title:"Microsoft Copilot policy gap", riskLevel:"HIGH", evidenceRefs:["signin-copilot-42-users"] }], evidenceRefs:["signin-copilot-42-users"] },
  { vendorName:"GitHub", applicationName:"GitHub Copilot", ownerName:"engineering@example.com", annualCost:2280, domains:["AI_GOVERNANCE"], findings:[{ id:"github-copilot-code-risk", sourceDomain:"AI_GOVERNANCE", title:"GitHub Copilot source code exposure", riskLevel:"HIGH", evidenceRefs:["signin-github-copilot-11-users"] }], evidenceRefs:["signin-github-copilot-11-users"] },
  { vendorName:"Box", applicationName:"Box", ownerName:"legal@example.com", annualCost:60000, renewalDate:"2026-09-07", domains:["RENEWALS","SAAS_RATIONALISATION"], findings:[{ id:"box-missing-usage-data", sourceDomain:"RENEWALS", title:"Box missing usage data", riskLevel:"MEDIUM", evidenceRefs:["contract-box"] }], evidenceRefs:["contract-box"] },
  { vendorName:"Miro", applicationName:"Miro", ownerName:"product@example.com", annualCost:38000, domains:["SAAS_RATIONALISATION","OWNERSHIP"], overlapWith:["Lucid"], findings:[{ id:"miro-stale-owner", sourceDomain:"OWNERSHIP", title:"Miro stale owner", riskLevel:"MEDIUM", evidenceRefs:["owner-miro-stale"], overlapWith:["Lucid"] }], evidenceRefs:["owner-miro-stale"] },
  { vendorName:"Salesforce", applicationName:"Salesforce", ownerName:"revenue@example.com", annualCost:240000, domains:["RENEWALS","EXECUTIVE_VALUE"], findings:[], evidenceRefs:["contract-salesforce"] },
  { vendorName:"HubSpot", applicationName:"HubSpot", ownerName:"marketing@example.com", annualCost:120000, domains:["OWNERSHIP","SAAS_RATIONALISATION","RENEWALS"], findings:[{ id:"hubspot-ownership-conflict", sourceDomain:"OWNERSHIP", title:"HubSpot ownership conflict", riskLevel:"HIGH", evidenceRefs:["owner-conflict-hubspot"] }], evidenceRefs:["owner-conflict-hubspot"] },
  { vendorName:"Microsoft", applicationName:"OneDrive", ownerName:"it@example.com", annualCost:0, domains:["M365_OPTIMISATION","SAAS_RATIONALISATION"], duplicateWith:["Dropbox"], findings:[], evidenceRefs:["m365-onedrive"] },
  { vendorName:"Microsoft", applicationName:"Teams", ownerName:"collaboration@example.com", annualCost:0, domains:["M365_OPTIMISATION","SAAS_RATIONALISATION"], duplicateWith:["Slack","Zoom"], findings:[], evidenceRefs:["m365-teams"] },
  { vendorName:"Microsoft", applicationName:"Power BI", ownerName:"data@example.com", annualCost:0, domains:["M365_OPTIMISATION","SAAS_RATIONALISATION"], overlapWith:["Tableau"], findings:[], evidenceRefs:["m365-power-bi"] },
] };
