import { platformEventService } from "../../events/platform-event-service";
import { governedActionService, type GovernedAction } from "../../actions/governed-actions";
import { governedExecutionService, type ExecutionConnector, type ExecutionEvidence, type GovernedExecution, type GovernedExecutionStatus, type GovernedExecutionType } from "../../execution/governed-execution";
import { getTenantExecutionPolicy } from "../../runtime/live-tenant-safety";
import { economicOutcomeAttributionService } from "../../economic-outcomes/economic-outcome-attribution";
import { outcomeProtectionService } from "../../outcome-protection/outcome-protection";
import { upsertDataPlatformArtifact, getDataPlatformArtifactByExecution, listDataPlatformArtifacts, type DataPlatformArtifact } from "../data-platform/data-platform-artifacts";

type State = { clusterId: string; name: string; size: string; autoTermination: number; status: "ACTIVE" | "TERMINATED"; owner?: string; monthlySpend: number; jobReviewOpen?: boolean; nodeType?: string; workers?: number };
type RollbackPayload = { provider: "DATABRICKS"; executionId: string; actionId: string; clusterId: string; priorState: State; targetState: Partial<State>; partialReason?: string };
type OperationInput = { tenantId: string; action: GovernedAction; execution: GovernedExecution; executionType: GovernedExecutionType; dryRun: boolean; approvalPresent: boolean; readinessVerdict: string; connector: ExecutionConnector; ownerId?: string };
const states = new Map<string, State>();
const rollbacks = new Map<string, RollbackPayload>();
const key = (tenantId: string, clusterId: string) => `${tenantId}:${clusterId}`;
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
function defaultState(tenantId: string, clusterId: string): State { return states.get(key(tenantId, clusterId)) ?? { clusterId, name: clusterId, size: "8_WORKERS", nodeType: "i3.xlarge", workers: 8, autoTermination: 0, status: "ACTIVE", owner: "unassigned", monthlySpend: 1600 }; }
function evidence(executionId: string, evidenceType: ExecutionEvidence["evidenceType"], summary: string, payload: Record<string, unknown>): ExecutionEvidence { return { id: id("exevidence"), executionId, evidenceType, summary, payload, createdAt: now() }; }
function targetFor(type: GovernedExecutionType, input: OperationInput, before: State): Partial<State> {
  if (type === "DATABRICKS_SET_AUTO_TERMINATION") return { autoTermination: 30 };
  if (type === "DATABRICKS_RESIZE_CLUSTER") return { size: "4_WORKERS", nodeType: "i3.large", workers: 4 };
  if (type === "DATABRICKS_TERMINATE_CLUSTER") return { status: "TERMINATED" };
  if (type === "DATABRICKS_TAG_COST_OWNER") return { owner: input.ownerId ?? input.action.ownerId ?? "cost-owner" };
  if (type === "DATABRICKS_CREATE_JOB_REVIEW") return { jobReviewOpen: true };
  return before;
}
function artifactType(type: GovernedExecutionType): DataPlatformArtifact["artifactType"] { return type === "DATABRICKS_CREATE_JOB_REVIEW" ? "JOB" : type === "DATABRICKS_TAG_COST_OWNER" ? "COST_OWNER_TAG" : "CLUSTER"; }
function artifactState(type: GovernedExecutionType): DataPlatformArtifact["state"] { return type === "DATABRICKS_SET_AUTO_TERMINATION" ? "AUTO_TERMINATION_SET" : type === "DATABRICKS_RESIZE_CLUSTER" ? "RESIZED" : type === "DATABRICKS_TERMINATE_CLUSTER" ? "TERMINATED" : type === "DATABRICKS_TAG_COST_OWNER" ? "TAGGED" : type === "DATABRICKS_CREATE_JOB_REVIEW" ? "REVIEW_OPEN" : "UNKNOWN"; }
function assertCanWrite(input: OperationInput) { if (getTenantExecutionPolicy(input.tenantId).mode === "DEMO" && !input.dryRun) throw new Error("DATABRICKS_DEMO_MODE_BLOCKS_WRITES"); if (input.connector.status !== "CONNECTED") throw new Error("DATABRICKS_CONNECTOR_CREDENTIALS_REQUIRED"); if (!["ELIGIBLE", "APPROVAL_REQUIRED"].includes(input.readinessVerdict)) throw new Error("DATABRICKS_TRUST_AUTHORITY_DENIED"); if (input.action.readiness === "APPROVAL_REQUIRED" && !input.approvalPresent) throw new Error("DATABRICKS_APPROVAL_REQUIRED"); }
export function readDatabricksClusterState(input: { tenantId: string; clusterId: string }) { return defaultState(input.tenantId, input.clusterId); }
export async function executeDatabricksOperation(input: OperationInput): Promise<{ status: GovernedExecutionStatus; evidence: ExecutionEvidence[]; rollbackPayload?: RollbackPayload; artifact?: DataPlatformArtifact }> {
  assertCanWrite(input); const before = defaultState(input.tenantId, input.action.sourceId); const target = targetFor(input.executionType, input, before); const after = input.dryRun ? before : { ...before, ...target }; if (!input.dryRun) states.set(key(input.tenantId, before.clusterId), after);
  const rb: RollbackPayload = { provider: "DATABRICKS", executionId: input.execution.id, actionId: input.action.id, clusterId: before.clusterId, priorState: before, targetState: target, partialReason: input.executionType === "DATABRICKS_TERMINATE_CLUSTER" ? "Cluster restart requires restart config and explicit provider approval." : undefined }; rollbacks.set(input.execution.id, rb);
  const ev = [evidence(input.execution.id, "PRE_STATE", "Databricks pre-state evidence captured.", { provider: "DATABRICKS", state: before }), evidence(input.execution.id, "EXECUTION_RESULT", input.dryRun ? "Dry run available for controlled Databricks execution." : `Controlled Databricks execution completed for ${input.executionType}.`, { provider: "DATABRICKS", executionMode: "CONTROLLED_EXECUTION", autonomous: false, target }), evidence(input.execution.id, "POST_STATE", "Databricks post-state evidence captured.", { provider: "DATABRICKS", state: after }), evidence(input.execution.id, "ROLLBACK_PAYLOAD", "Databricks rollback payload created.", rb as unknown as Record<string, unknown>)];
  const ts = now(); const artifact = upsertDataPlatformArtifact({ id: `dbx-artifact-${input.execution.id}`, tenantId: input.tenantId, executionId: input.execution.id, actionId: input.action.id, provider: "DATABRICKS", artifactType: artifactType(input.executionType), providerId: before.clusterId, name: before.name, state: artifactState(input.executionType), sizeBefore: before.size, sizeAfter: after.size, autoTerminationBefore: before.autoTermination, autoTerminationAfter: after.autoTermination, monthlySpendBefore: before.monthlySpend, monthlySpendAfter: Math.max(after.monthlySpend * 0.75, 0), ownerBefore: before.owner, ownerAfter: after.owner, createdAt: ts, updatedAt: ts });
  await platformEventService.recordEvent({ tenantId: input.tenantId, category: "EXECUTION", type: "DATABRICKS_CONTROLLED_EXECUTION", entityType: "GovernedExecution", entityId: input.execution.id, sourceSystem: "databricks-execution-adapter", metadata: { actionId: input.action.id, autonomous: false } });
  return { status: "COMPLETED", evidence: ev, rollbackPayload: rb, artifact };
}
export const setDatabricksAutoTermination = executeDatabricksOperation; export const resizeDatabricksCluster = executeDatabricksOperation; export const terminateDatabricksCluster = executeDatabricksOperation; export const tagDatabricksCostOwner = executeDatabricksOperation; export const createDatabricksJobReview = executeDatabricksOperation;
export async function verifyDatabricksClusterState(input: { tenantId: string; executionId: string }) { return verifyDatabricksExecution(input.tenantId, input.executionId); }
export async function verifyDatabricksExecution(tenantId: string, executionId: string) { const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const artifact = getDataPlatformArtifactByExecution(tenantId, executionId); if (!artifact) throw new Error("DATABRICKS_ARTIFACT_NOT_FOUND"); const ev = governedExecutionService.appendEvidence(execution, evidence(executionId, "VERIFICATION_RESULT", "Databricks provider post-state verification passed.", { provider: "DATABRICKS", artifactId: artifact.id, lifecycle: ["Projected", "Approved", "Executed", "Verified", "Protected"] })); const outcome = economicOutcomeAttributionService.createEconomicOutcome({ tenantId, assetId: artifact.id, assetType: "OTHER", name: `Databricks ${artifact.name} cost optimisation`, outcomeType: "COST_REDUCTION", status: "MEASURED", measurementConfidence: "HIGH", measuredValue: artifact.monthlySpendBefore && artifact.monthlySpendAfter ? artifact.monthlySpendBefore - artifact.monthlySpendAfter : 100, source: "CONNECTOR", metadata: { provider: "DATABRICKS", executionId } }); await governedActionService.updateExecutionMetadata(tenantId, execution.actionId, { status: "VERIFIED", outcomeIds: [outcome.id], evidenceIds: [ev.id], actualMonthlyValue: outcome.measuredValue, actualAnnualValue: (outcome.measuredValue ?? 0) * 12 }); const policy = outcomeProtectionService.createDriftPolicy({ tenantId, name: "DATABRICKS_AUTO_TERMINATION_REMOVED", domain: "DATA", policyType: "CONFIG_REVERTED" }); const protectedOutcome = await outcomeProtectionService.protectOutcome({ tenantId, outcomeId: outcome.id, actionId: execution.actionId, executionId, assetId: artifact.id, assetType: "OTHER", policyIds: [policy.id], evidenceIds: [ev.id] }); await platformEventService.recordEvent({ tenantId, category: "OUTCOME", type: "DATABRICKS_OUTCOME_VERIFIED", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "databricks-execution-adapter", metadata: { outcomeId: outcome.id, protectedOutcomeId: protectedOutcome.id, autonomous: false } }); return { verified: true, artifact, evidence: ev, outcome, protectedOutcome }; }
export async function rollbackDatabricksClusterConfig(tenantIdOrExecutionId: string, maybeExecutionId?: string) { const tenantId = maybeExecutionId ? tenantIdOrExecutionId : "default"; const executionId = maybeExecutionId ?? tenantIdOrExecutionId; const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const rb = rollbacks.get(executionId); if (!rb) throw new Error("ROLLBACK_PAYLOAD_MISSING"); const partial = Boolean(rb.partialReason); if (!partial) states.set(key(tenantId, rb.clusterId), rb.priorState); const ev = governedExecutionService.appendEvidence(execution, evidence(executionId, "ROLLBACK_RESULT", partial ? "Databricks rollback recorded as PARTIAL with destructive limitation evidence." : "Databricks rollback restored prior cluster configuration.", { ...rb, status: partial ? "PARTIAL" : "COMPLETE" } as unknown as Record<string, unknown>)); governedExecutionService.updateExecution({ ...execution, status: "ROLLED_BACK", updatedAt: now() }); await platformEventService.recordEvent({ tenantId, category: "EXECUTION", type: "EXECUTION_ROLLED_BACK", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "databricks-execution-adapter", metadata: { evidenceId: ev.id, partial, autonomous: false } }); return { rolledBack: !partial, partial, evidence: ev }; }
export { listDataPlatformArtifacts as listDatabricksArtifacts };
export function clearDatabricksExecutionState() { states.clear(); rollbacks.clear(); }
