import { governedActionService, type GovernedActionDomain, type GovernedActionPriority } from "../actions/governed-actions";
import { platformEventService } from "../events/platform-event-service";
import { getPersistenceProvider, PersistenceStore } from "../persistence/persistence-provider";
import { PersistenceCollections } from "../persistence/persistence-collections";

export type ProtectedOutcomeStatus = "PROTECTED" | "AT_RISK" | "DRIFTED" | "REMEDIATION_OPEN" | "RESOLVED" | "ARCHIVED";
export type ProtectedOutcome = { id: string; tenantId: string; outcomeId: string; actionId?: string; executionId?: string; assetId?: string; assetType?: "AI_ASSET" | "M365" | "SAAS" | "CLOUD" | "ITAM" | "APPLICATION" | "OTHER"; name: string; description?: string; status: ProtectedOutcomeStatus; valueType: "SAVINGS" | "COST_AVOIDANCE" | "PRODUCTIVITY" | "RISK_REDUCTION" | "REVENUE_ENABLEMENT" | "OTHER"; protectedMonthlyValue?: number; protectedAnnualValue?: number; retainedMonthlyValue?: number; retainedAnnualValue?: number; driftedMonthlyValue?: number; driftedAnnualValue?: number; currency?: string; protectionStart: string; lastCheckedAt?: string; nextCheckAt?: string; policyIds: string[]; driftFindingIds: string[]; evidenceIds: string[]; createdAt: string; updatedAt: string };
export type DriftPolicy = { id: string; tenantId: string; name: string; description?: string; domain: GovernedActionDomain; policyType: "LICENSE_REASSIGNMENT" | "USAGE_REACTIVATION" | "OWNER_REMOVED" | "SPEND_REAPPEARED" | "ASSET_RECREATED" | "CONFIG_REVERTED" | "WORKFLOW_REENABLED" | "MODEL_ROUTE_REVERTED" | "CUSTOM"; checkFrequency: "DAILY" | "WEEKLY" | "MONTHLY"; threshold?: number; enabled: boolean; createdAt: string; updatedAt: string };
export type DriftSeverity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type DriftSignalType = "LICENSE_REASSIGNED" | "USAGE_RETURNED" | "SPEND_RETURNED" | "OWNER_REMOVED" | "ASSET_RECREATED" | "CONFIG_REVERTED" | "WORKFLOW_REENABLED" | "MODEL_ROUTE_REVERTED" | "MANUAL_SIGNAL";
export type DriftSignal = { id: string; tenantId: string; protectedOutcomeId: string; policyId: string; signalType: DriftSignalType; severity: DriftSeverity; observedValue?: number; threshold?: number; source: "CONNECTOR" | "OUTCOME_LEDGER" | "MANUAL" | "DEMO" | "SYSTEM"; detectedAt: string; metadata?: Record<string, unknown> };
export type DriftFinding = { id: string; tenantId: string; protectedOutcomeId: string; signalIds: string[]; status: "OPEN" | "ACKNOWLEDGED" | "REMEDIATION_CREATED" | "RESOLVED" | "DISMISSED"; severity: DriftSeverity; driftType: "VALUE_LEAKAGE" | "CONTROL_BREAKDOWN" | "RECURRING_WASTE" | "OWNERSHIP_DRIFT" | "POLICY_DRIFT" | "UNKNOWN"; estimatedMonthlyLeakage?: number; estimatedAnnualLeakage?: number; reason: string; recommendedAction: string; createdAt: string; updatedAt: string };
export type RetentionCheck = { id: string; tenantId: string; protectedOutcomeId: string; result: "PASSED" | "FAILED" | "AT_RISK" | "UNKNOWN"; retainedMonthlyValue?: number; retainedAnnualValue?: number; driftedMonthlyValue?: number; driftedAnnualValue?: number; evidenceIds: string[]; checkedAt: string };
export type DriftRemediationAction = { id: string; tenantId: string; protectedOutcomeId: string; driftFindingId: string; governedActionId?: string; status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CANCELLED"; actionType: "REOPEN_GOVERNED_ACTION" | "CREATE_NEW_GOVERNED_ACTION" | "REQUEST_OWNER_REVIEW" | "REAPPLY_EXECUTION" | "CREATE_TICKET" | "MANUAL_REVIEW"; description: string; createdAt: string; updatedAt: string };

type ProtectOutcomeInput = Partial<Omit<ProtectedOutcome, "id" | "status" | "policyIds" | "driftFindingIds" | "evidenceIds" | "createdAt" | "updatedAt" | "protectionStart">> & { tenantId: string; outcomeId?: string; policyIds?: string[]; evidenceIds?: string[]; protectionStart?: string };
type DriftPolicyInput = Omit<Partial<DriftPolicy>, "createdAt" | "updatedAt"> & { tenantId: string; name: string; domain: GovernedActionDomain; policyType: DriftPolicy["policyType"] };
type DriftSignalInput = Partial<DriftSignal> & { tenantId: string; protectedOutcomeId: string; policyId: string; signalType: DriftSignalType; severity: DriftSeverity; source?: DriftSignal["source"] };
type RemediationInput = { tenantId: string; driftFindingId: string; actionType: DriftRemediationAction["actionType"]; description?: string };
type ResolveInput = { tenantId: string; driftFindingId: string; notes?: string };

function now() { return new Date().toISOString(); }
function id(prefix: string) { return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`; }
function uniq(values: Array<string | undefined | null>) { return Array.from(new Set(values.filter((value): value is string => typeof value === "string" && value.trim().length > 0))); }
function nextCheck(from: string, frequency: DriftPolicy["checkFrequency"] = "WEEKLY") { const date = new Date(from); date.setUTCDate(date.getUTCDate() + (frequency === "DAILY" ? 1 : frequency === "MONTHLY" ? 30 : 7)); return date.toISOString(); }
function eventCategory(type: string) { return type.startsWith("DRIFT") ? "DRIFT" as const : "OUTCOME" as const; }
function priority(severity: DriftSeverity): GovernedActionPriority { return severity === "CRITICAL" ? "CRITICAL" : severity === "HIGH" ? "HIGH" : severity === "MEDIUM" ? "MEDIUM" : "LOW"; }
function driftType(signalType: DriftSignalType): DriftFinding["driftType"] { if (["LICENSE_REASSIGNED", "SPEND_RETURNED", "ASSET_RECREATED"].includes(signalType)) return "VALUE_LEAKAGE"; if (signalType === "OWNER_REMOVED") return "OWNERSHIP_DRIFT"; if (["CONFIG_REVERTED", "WORKFLOW_REENABLED", "MODEL_ROUTE_REVERTED"].includes(signalType)) return "POLICY_DRIFT"; return "UNKNOWN"; }
function isMaterial(severity: DriftSeverity) { return severity === "MEDIUM" || severity === "HIGH" || severity === "CRITICAL"; }

export class OutcomeProtectionRepository {
  readonly outcomes = new PersistenceStore<ProtectedOutcome>(getPersistenceProvider(), PersistenceCollections.PROTECTED_OUTCOMES);
  readonly policies = new PersistenceStore<DriftPolicy>(getPersistenceProvider(), PersistenceCollections.DRIFT_POLICIES);
  readonly signals = new PersistenceStore<DriftSignal & { createdAt: string; updatedAt: string }>(getPersistenceProvider(), PersistenceCollections.DRIFT_SIGNALS);
  readonly findings = new PersistenceStore<DriftFinding>(getPersistenceProvider(), PersistenceCollections.DRIFT_FINDINGS);
  readonly checks = new PersistenceStore<RetentionCheck & { tenantId: string; createdAt: string; updatedAt: string }>(getPersistenceProvider(), PersistenceCollections.RETENTION_CHECKS);
  readonly remediations = new PersistenceStore<DriftRemediationAction>(getPersistenceProvider(), PersistenceCollections.DRIFT_REMEDIATION_ACTIONS);
  clear() { this.outcomes.clearAll(); this.policies.clearAll(); this.signals.clearAll(); this.findings.clearAll(); this.checks.clearAll(); this.remediations.clearAll(); }
}

// Helper: get outcome from cache (sync) or throw
function getOutcomeCached(repo: OutcomeProtectionRepository, tenantId: string, id: string) {
  return repo.outcomes.getCached(tenantId, id);
}

export class OutcomeProtectionService {
  constructor(private readonly repo = new OutcomeProtectionRepository()) {}
  clear() { this.repo.clear(); }

  async protectOutcome(input: ProtectOutcomeInput) {
    const action = input.actionId ? await governedActionService.get(input.tenantId, input.actionId) : null;
    if (input.actionId && !action) throw new Error("ACTION_NOT_FOUND");
    if (action && !["VERIFIED", "RETAINED"].includes(action.status)) throw new Error("OUTCOME_NOT_VERIFIED");
    if (!input.outcomeId && !action?.outcomeIds.length) throw new Error("OUTCOME_LINK_REQUIRED");
    const timestamp = now();
    const outcome: ProtectedOutcome = { id: id("pout"), tenantId: input.tenantId, outcomeId: input.outcomeId ?? action!.outcomeIds[0], actionId: input.actionId, executionId: input.executionId, assetId: input.assetId ?? action?.sourceId, assetType: input.assetType, name: input.name ?? action?.title ?? "Protected outcome", description: input.description, status: "PROTECTED", valueType: input.valueType ?? "SAVINGS", protectedMonthlyValue: input.protectedMonthlyValue ?? action?.actualMonthlyValue ?? action?.projectedMonthlyValue, protectedAnnualValue: input.protectedAnnualValue ?? action?.actualAnnualValue ?? action?.projectedAnnualValue, retainedMonthlyValue: input.retainedMonthlyValue, retainedAnnualValue: input.retainedAnnualValue, driftedMonthlyValue: input.driftedMonthlyValue, driftedAnnualValue: input.driftedAnnualValue, currency: input.currency ?? "USD", protectionStart: input.protectionStart ?? timestamp, nextCheckAt: nextCheck(timestamp), policyIds: uniq(input.policyIds ?? []), driftFindingIds: [], evidenceIds: uniq([...(input.evidenceIds ?? []), ...(action?.evidenceIds ?? [])]), createdAt: timestamp, updatedAt: timestamp };
    await this.repo.outcomes.upsert(outcome);
    await this.recordEvent(outcome.tenantId, "OUTCOME_PROTECTED", "ProtectedOutcome", outcome.id, { outcomeId: outcome.outcomeId, actionId: outcome.actionId });
    return outcome;
  }

  async createProtectedOutcomeFromAction(tenantId: string, actionId: string) { return this.protectOutcome({ tenantId, actionId }); }
  createDriftPolicy(input: DriftPolicyInput) { const timestamp = now(); const policy: DriftPolicy = { id: input.id ?? id("dpol"), tenantId: input.tenantId, name: input.name, description: input.description, domain: input.domain, policyType: input.policyType, checkFrequency: input.checkFrequency ?? "WEEKLY", threshold: input.threshold, enabled: input.enabled ?? true, createdAt: timestamp, updatedAt: timestamp }; this.repo.policies.upsert(policy).catch(() => {}); this.repo.policies.setCached(policy); return policy; }
  listPolicies(tenantId: string) { return this.repo.policies.listCached(tenantId); }

  async runRetentionCheck(tenantId: string, protectedOutcomeId: string) {
    const outcome = this.repo.outcomes.getCached(tenantId, protectedOutcomeId); if (!outcome) throw new Error("PROTECTED_OUTCOME_NOT_FOUND");
    const signals = this.listSignals(tenantId, protectedOutcomeId); const max = signals.reduce<DriftSeverity | null>((acc, signal) => !acc || ["LOW", "MEDIUM", "HIGH", "CRITICAL"].indexOf(signal.severity) > ["LOW", "MEDIUM", "HIGH", "CRITICAL"].indexOf(acc) ? signal.severity : acc, null);
    const result: RetentionCheck["result"] = !max ? "PASSED" : max === "LOW" ? "AT_RISK" : "FAILED"; const timestamp = now(); const driftedMonthlyValue = result === "FAILED" ? signals.reduce((s, signal) => s + (signal.observedValue ?? 0), 0) || outcome.protectedMonthlyValue : result === "AT_RISK" ? signals.reduce((s, signal) => s + (signal.observedValue ?? 0), 0) : 0;
    const check: RetentionCheck & { tenantId: string; createdAt: string; updatedAt: string } = { id: id("rcheck"), tenantId, protectedOutcomeId, result, retainedMonthlyValue: result === "PASSED" ? outcome.protectedMonthlyValue : Math.max((outcome.protectedMonthlyValue ?? 0) - (driftedMonthlyValue ?? 0), 0), retainedAnnualValue: result === "PASSED" ? outcome.protectedAnnualValue : Math.max((outcome.protectedAnnualValue ?? 0) - ((driftedMonthlyValue ?? 0) * 12), 0), driftedMonthlyValue, driftedAnnualValue: (driftedMonthlyValue ?? 0) * 12, evidenceIds: uniq([...outcome.evidenceIds, ...signals.map((signal) => signal.id)]), checkedAt: timestamp, createdAt: timestamp, updatedAt: timestamp };
    await this.repo.checks.upsert(check);
    const updated: ProtectedOutcome = { ...outcome, status: result === "PASSED" ? "PROTECTED" : result === "AT_RISK" ? "AT_RISK" : "DRIFTED", retainedMonthlyValue: check.retainedMonthlyValue, retainedAnnualValue: check.retainedAnnualValue, driftedMonthlyValue: check.driftedMonthlyValue, driftedAnnualValue: check.driftedAnnualValue, lastCheckedAt: timestamp, nextCheckAt: nextCheck(timestamp), updatedAt: timestamp };
    await this.repo.outcomes.upsert(updated);
    await this.recordEvent(tenantId, result === "PASSED" ? "RETENTION_CHECK_PASSED" : result === "AT_RISK" ? "RETENTION_CHECK_AT_RISK" : "RETENTION_CHECK_FAILED", "ProtectedOutcome", protectedOutcomeId, { checkId: check.id });
    return check;
  }

  async recordDriftSignal(input: DriftSignalInput) { const outcome = this.repo.outcomes.getCached(input.tenantId, input.protectedOutcomeId); if (!outcome) throw new Error("PROTECTED_OUTCOME_NOT_FOUND"); const ts = now(); const signal: DriftSignal & { createdAt: string; updatedAt: string } = { id: input.id ?? id("dsig"), tenantId: input.tenantId, protectedOutcomeId: input.protectedOutcomeId, policyId: input.policyId, signalType: input.signalType, severity: input.severity, observedValue: input.observedValue, threshold: input.threshold, source: input.source ?? "SYSTEM", detectedAt: input.detectedAt ?? ts, metadata: input.metadata, createdAt: ts, updatedAt: ts }; await this.repo.signals.upsert(signal); await this.recordEvent(signal.tenantId, "DRIFT_SIGNAL_RECORDED", "ProtectedOutcome", signal.protectedOutcomeId, { signalId: signal.id, severity: signal.severity }); if (isMaterial(signal.severity)) await this.createDriftFindingFromSignal(signal); return signal; }
  async createDriftFindingFromSignal(input: DriftSignal | { tenantId: string; signalId: string }) { const signal = "signalId" in input ? this.repo.signals.getCached(input.tenantId, input.signalId) : input; if (!signal) throw new Error("DRIFT_SIGNAL_NOT_FOUND"); if (!isMaterial(signal.severity)) return null; const timestamp = now(); const finding: DriftFinding = { id: id("dfind"), tenantId: signal.tenantId, protectedOutcomeId: signal.protectedOutcomeId, signalIds: [signal.id], status: "OPEN", severity: signal.severity, driftType: driftType(signal.signalType), estimatedMonthlyLeakage: signal.observedValue, estimatedAnnualLeakage: signal.observedValue ? signal.observedValue * 12 : undefined, reason: `${signal.signalType} detected for protected outcome.`, recommendedAction: "Review drift and create remediation if value leakage is confirmed.", createdAt: timestamp, updatedAt: timestamp }; await this.repo.findings.upsert(finding); const outcome = this.repo.outcomes.getCached(finding.tenantId, finding.protectedOutcomeId); if (outcome) await this.repo.outcomes.upsert({ ...outcome, status: "DRIFTED", driftFindingIds: uniq([...outcome.driftFindingIds, finding.id]), driftedMonthlyValue: finding.estimatedMonthlyLeakage ?? outcome.driftedMonthlyValue, driftedAnnualValue: finding.estimatedAnnualLeakage ?? outcome.driftedAnnualValue, updatedAt: timestamp }); await this.recordEvent(finding.tenantId, "DRIFT_DETECTED", "ProtectedOutcome", finding.protectedOutcomeId, { findingId: finding.id, driftType: finding.driftType }); return finding; }
  async createDriftRemediationAction(input: RemediationInput) { const finding = this.repo.findings.getCached(input.tenantId, input.driftFindingId); if (!finding) throw new Error("DRIFT_FINDING_NOT_FOUND"); const outcome = this.repo.outcomes.getCached(input.tenantId, finding.protectedOutcomeId); if (!outcome) throw new Error("PROTECTED_OUTCOME_NOT_FOUND"); let governedActionId: string | undefined; if (input.actionType === "CREATE_NEW_GOVERNED_ACTION") { const action = await governedActionService.create({ tenantId: input.tenantId, title: `Remediate drift: ${outcome.name}`, description: input.description ?? finding.recommendedAction, domain: "OTHER", sourceType: "DRIFT_EVENT", sourceId: finding.id, status: "READY", priority: priority(finding.severity), readiness: "APPROVAL_REQUIRED", blastRadius: finding.severity === "CRITICAL" ? "HIGH" : "MEDIUM", rollbackCapability: "PARTIAL", recommendationIds: [], evidenceIds: [...finding.signalIds], outcomeIds: [outcome.outcomeId] }); governedActionId = action.id; }
    const timestamp = now(); const remediation: DriftRemediationAction = { id: id("drem"), tenantId: input.tenantId, protectedOutcomeId: outcome.id, driftFindingId: finding.id, governedActionId, status: "OPEN", actionType: input.actionType, description: input.description ?? finding.recommendedAction, createdAt: timestamp, updatedAt: timestamp }; await this.repo.remediations.upsert(remediation); await this.repo.findings.upsert({ ...finding, status: "REMEDIATION_CREATED", updatedAt: timestamp }); await this.repo.outcomes.upsert({ ...outcome, status: "REMEDIATION_OPEN", updatedAt: timestamp }); await this.recordEvent(input.tenantId, "DRIFT_REMEDIATION_CREATED", "ProtectedOutcome", outcome.id, { remediationId: remediation.id, governedActionId }); return remediation; }
  async resolveDriftFinding(input: ResolveInput) { const finding = this.repo.findings.getCached(input.tenantId, input.driftFindingId); if (!finding) throw new Error("DRIFT_FINDING_NOT_FOUND"); const timestamp = now(); const resolved = { ...finding, status: "RESOLVED" as const, updatedAt: timestamp }; await this.repo.findings.upsert(resolved); const outcome = this.repo.outcomes.getCached(input.tenantId, finding.protectedOutcomeId); if (outcome) await this.repo.outcomes.upsert({ ...outcome, status: "RESOLVED", driftedMonthlyValue: 0, driftedAnnualValue: 0, updatedAt: timestamp }); await this.recordEvent(input.tenantId, "DRIFT_RESOLVED", "ProtectedOutcome", finding.protectedOutcomeId, { findingId: finding.id, notes: input.notes }); return resolved; }

  listProtectedOutcomes(tenantId: string, filters: Partial<Pick<ProtectedOutcome, "status" | "assetType" | "valueType">> = {}) { return this.repo.outcomes.listCached(tenantId).filter((outcome) => (!filters.status || outcome.status === filters.status) && (!filters.assetType || outcome.assetType === filters.assetType) && (!filters.valueType || outcome.valueType === filters.valueType)); }
  getProtectedOutcomeDetail(tenantId: string, outcomeId: string) { const outcome = this.repo.outcomes.getCached(tenantId, outcomeId); if (!outcome) return null; return { outcome, policies: outcome.policyIds.map((policyId) => this.repo.policies.getCached(tenantId, policyId)).filter(Boolean), signals: this.listSignals(tenantId, outcomeId), findings: this.repo.findings.listCached(tenantId).filter((finding) => finding.protectedOutcomeId === outcomeId), retentionChecks: this.repo.checks.listCached(tenantId).filter((check) => check.protectedOutcomeId === outcomeId), remediations: this.repo.remediations.listCached(tenantId).filter((row) => row.protectedOutcomeId === outcomeId) }; }
  listSignals(tenantId: string, protectedOutcomeId: string) { return this.repo.signals.listCached(tenantId).filter((signal) => signal.protectedOutcomeId === protectedOutcomeId); }
  getOutcomeProtectionDashboard(tenantId: string) { const outcomes = this.listProtectedOutcomes(tenantId); const findings = this.repo.findings.listCached(tenantId).filter((finding) => ["OPEN", "ACKNOWLEDGED", "REMEDIATION_CREATED"].includes(finding.status)); const retained = outcomes.filter((outcome) => outcome.status === "PROTECTED" || outcome.status === "RESOLVED").length; return { protectedOutcomes: outcomes.length, retainedOutcomes: retained, atRiskOutcomes: outcomes.filter((outcome) => outcome.status === "AT_RISK").length, driftedOutcomes: outcomes.filter((outcome) => outcome.status === "DRIFTED").length, remediationOpen: outcomes.filter((outcome) => outcome.status === "REMEDIATION_OPEN").length, protectedMonthlyValue: outcomes.reduce((s, o) => s + (o.protectedMonthlyValue ?? 0), 0), protectedAnnualValue: outcomes.reduce((s, o) => s + (o.protectedAnnualValue ?? 0), 0), retainedMonthlyValue: outcomes.reduce((s, o) => s + (o.retainedMonthlyValue ?? o.protectedMonthlyValue ?? 0), 0), retainedAnnualValue: outcomes.reduce((s, o) => s + (o.retainedAnnualValue ?? o.protectedAnnualValue ?? 0), 0), driftedMonthlyValue: outcomes.reduce((s, o) => s + (o.driftedMonthlyValue ?? 0), 0), driftedAnnualValue: outcomes.reduce((s, o) => s + (o.driftedAnnualValue ?? 0), 0), retentionRate: outcomes.length ? Math.round((retained / outcomes.length) * 100) : 100, openDriftFindings: findings, upcomingChecks: outcomes.filter((outcome) => outcome.nextCheckAt).sort((a, b) => String(a.nextCheckAt).localeCompare(String(b.nextCheckAt))).slice(0, 5) }; }

  private recordEvent(tenantId: string, type: string, entityType: string, entityId: string, metadata: Record<string, unknown> = {}) { return platformEventService.recordEvent({ tenantId, category: eventCategory(type), type, entityType, entityId, sourceSystem: "outcome-protection-engine", metadata: { ...metadata, autonomous: false } }); }
}

export const outcomeProtectionService = new OutcomeProtectionService();
export const protectOutcome = (input: ProtectOutcomeInput) => outcomeProtectionService.protectOutcome(input);
export const createProtectedOutcomeFromAction = (tenantId: string, actionId: string) => outcomeProtectionService.createProtectedOutcomeFromAction(tenantId, actionId);
export const createDriftPolicy = (input: DriftPolicyInput) => outcomeProtectionService.createDriftPolicy(input);
export const runRetentionCheck = (tenantId: string, protectedOutcomeId: string) => outcomeProtectionService.runRetentionCheck(tenantId, protectedOutcomeId);
export const recordDriftSignal = (input: DriftSignalInput) => outcomeProtectionService.recordDriftSignal(input);
export const createDriftFindingFromSignal = (input: DriftSignal | { tenantId: string; signalId: string }) => outcomeProtectionService.createDriftFindingFromSignal(input);
export const createDriftRemediationAction = (input: RemediationInput) => outcomeProtectionService.createDriftRemediationAction(input);
export const resolveDriftFinding = (input: ResolveInput) => outcomeProtectionService.resolveDriftFinding(input);
export const getOutcomeProtectionDashboard = (tenantId: string) => outcomeProtectionService.getOutcomeProtectionDashboard(tenantId);
export const listProtectedOutcomes = (tenantId: string, filters?: Partial<Pick<ProtectedOutcome, "status" | "assetType" | "valueType">>) => outcomeProtectionService.listProtectedOutcomes(tenantId, filters);
export const getProtectedOutcomeDetail = (tenantId: string, id: string) => outcomeProtectionService.getProtectedOutcomeDetail(tenantId, id);
