import { platformEventService } from "../../events/platform-event-service";
import { governedActionService, type GovernedAction } from "../../actions/governed-actions";
import { governedExecutionService, type ExecutionConnector, type ExecutionEvidence, type GovernedExecution, type GovernedExecutionStatus, type GovernedExecutionType } from "../../execution/governed-execution";
import { getTenantExecutionPolicy } from "../../runtime/live-tenant-safety";
import { economicOutcomeAttributionService } from "../../economic-outcomes/economic-outcome-attribution";
import { outcomeProtectionService } from "../../outcome-protection/outcome-protection";
import { getAzureArtifactByExecution, listAzureArtifacts, upsertAzureArtifact, type AzureArtifact } from "./azure-artifacts";

type AzureResourceState = { resourceId: string; name: string; resourceType: AzureArtifact["artifactType"]; state: "ACTIVE" | "STOPPED" | "DELETED"; sku?: string; sqlTier?: string; owner?: string; monthlyCost: number; reviewCreated?: boolean };
type AzureRollbackPayload = { provider: "AZURE"; executionId: string; actionId: string; resourceId: string; priorState: AzureResourceState; targetState: Partial<AzureResourceState>; partialReason?: string };
type AzureOperationInput = { tenantId: string; action: GovernedAction; execution: GovernedExecution; executionType: GovernedExecutionType; dryRun: boolean; approvalPresent: boolean; readinessVerdict: string; connector: ExecutionConnector; ownerId?: string };
const states = new Map<string, AzureResourceState>();
const rollbacks = new Map<string, AzureRollbackPayload>();
const key = (tenantId: string, resourceId: string) => `${tenantId}:${resourceId}`;
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
function resourceTypeFor(type: GovernedExecutionType): AzureArtifact["artifactType"] { if (type.includes("SQL")) return "SQL"; if (type.includes("MANAGED_DISK")) return "MANAGED_DISK"; if (type.includes("PUBLIC_IP")) return "PUBLIC_IP"; if (type.includes("SAVINGS_PLAN")) return "SAVINGS_PLAN"; if (type.includes("RI_REVIEW")) return "RESERVED_INSTANCE"; return "VM"; }
function defaultState(tenantId: string, resourceId: string, executionType: GovernedExecutionType): AzureResourceState { const existing = states.get(key(tenantId, resourceId)); if (existing) return existing; const resourceType = resourceTypeFor(executionType); return { resourceId, name: resourceId, resourceType, state: "ACTIVE", sku: resourceType === "VM" ? "Standard_D8s_v5" : undefined, sqlTier: resourceType === "SQL" ? "P2" : undefined, owner: "unassigned", monthlyCost: resourceType === "SAVINGS_PLAN" || resourceType === "RESERVED_INSTANCE" ? 2200 : 850 }; }
function evidence(executionId: string, evidenceType: ExecutionEvidence["evidenceType"], summary: string, payload: Record<string, unknown>): ExecutionEvidence { return { id: id("exevidence"), executionId, evidenceType, summary, payload, createdAt: now() }; }
function targetFor(type: GovernedExecutionType, input: AzureOperationInput): Partial<AzureResourceState> { if (type === "AZURE_RIGHTSIZE_VM") return { sku: "Standard_D2s_v5" }; if (type === "AZURE_STOP_VM" || type === "AZURE_STOP_SQL") return { state: "STOPPED" }; if (type === "AZURE_START_VM" || type === "AZURE_START_SQL") return { state: "ACTIVE" }; if (type === "AZURE_MODIFY_SQL") return { sqlTier: "S1" }; if (type === "AZURE_DELETE_MANAGED_DISK" || type === "AZURE_RELEASE_PUBLIC_IP") return { state: "DELETED" }; if (type === "AZURE_TAG_OWNER") return { owner: input.ownerId ?? input.action.ownerId ?? "cost-owner" }; if (type === "AZURE_CREATE_RI_REVIEW" || type === "AZURE_CREATE_SAVINGS_PLAN_REVIEW") return { reviewCreated: true }; return {}; }
function artifactState(type: GovernedExecutionType, after: AzureResourceState): AzureArtifact["state"] { if (type === "AZURE_TAG_OWNER") return "TAGGED"; if (type === "AZURE_RIGHTSIZE_VM" || type === "AZURE_MODIFY_SQL") return "RESIZED"; if (type === "AZURE_STOP_VM" || type === "AZURE_STOP_SQL") return "STOPPED"; if (type === "AZURE_DELETE_MANAGED_DISK" || type === "AZURE_RELEASE_PUBLIC_IP") return "DELETED"; if (type === "AZURE_CREATE_RI_REVIEW" || type === "AZURE_CREATE_SAVINGS_PLAN_REVIEW") return "REVIEW_CREATED"; return after.state === "ACTIVE" ? "ACTIVE" : after.state === "STOPPED" ? "STOPPED" : after.state === "DELETED" ? "DELETED" : "UNKNOWN"; }
function assertCanWrite(input: AzureOperationInput) { if (getTenantExecutionPolicy(input.tenantId).mode === "DEMO" && !input.dryRun) throw new Error("AZURE_DEMO_MODE_BLOCKS_WRITES"); if (input.connector.status !== "CONNECTED") throw new Error("AZURE_CONNECTOR_UNHEALTHY_OR_CREDENTIALS_REQUIRED"); if (!["ELIGIBLE", "APPROVAL_REQUIRED"].includes(input.readinessVerdict)) throw new Error("AZURE_TRUST_AUTHORITY_DENIED"); if (input.action.readiness === "APPROVAL_REQUIRED" && !input.approvalPresent) throw new Error("AZURE_APPROVAL_REQUIRED"); if (!input.action.evidenceIds.length) throw new Error("AZURE_EVIDENCE_REQUIRED"); }
export function readAzureVmState(input: { tenantId: string; resourceId: string }) { return defaultState(input.tenantId, input.resourceId, "AZURE_RIGHTSIZE_VM"); }
export async function executeAzureOperation(input: AzureOperationInput): Promise<{ status: GovernedExecutionStatus; evidence: ExecutionEvidence[]; rollbackPayload?: AzureRollbackPayload; artifact?: AzureArtifact }> { assertCanWrite(input); const before = defaultState(input.tenantId, input.action.sourceId, input.executionType); const target = targetFor(input.executionType, input); const after = input.dryRun ? before : { ...before, ...target }; if (!input.dryRun) states.set(key(input.tenantId, before.resourceId), after); const partialReason = input.executionType === "AZURE_DELETE_MANAGED_DISK" ? "Managed Disk deletion can only be partially rolled back from backup/snapshot evidence." : input.executionType === "AZURE_RELEASE_PUBLIC_IP" ? "Public IP release can only be partially rolled back because reallocation is not guaranteed." : undefined; const rollbackPayload: AzureRollbackPayload = { provider: "AZURE", executionId: input.execution.id, actionId: input.action.id, resourceId: before.resourceId, priorState: before, targetState: target, partialReason }; rollbacks.set(input.execution.id, rollbackPayload); const executionEvidence = [evidence(input.execution.id, "PRE_STATE", "Azure pre-state evidence captured.", { provider: "AZURE", state: before }), evidence(input.execution.id, "EXECUTION_RESULT", input.dryRun ? "Dry run available for controlled Azure execution." : `Controlled Azure execution completed for ${input.executionType}.`, { provider: "AZURE", executionMode: "CONTROLLED_EXECUTION", autonomous: false, target }), evidence(input.execution.id, "POST_STATE", "Azure post-state evidence captured.", { provider: "AZURE", state: after }), evidence(input.execution.id, "ROLLBACK_PAYLOAD", "Azure rollback payload created.", rollbackPayload as unknown as Record<string, unknown>)]; const ts = now(); const artifact = upsertAzureArtifact({ id: `azure-artifact-${input.execution.id}`, tenantId: input.tenantId, executionId: input.execution.id, actionId: input.action.id, artifactType: before.resourceType, resourceId: before.resourceId, state: artifactState(input.executionType, after), monthlyCostBefore: before.monthlyCost, monthlyCostAfter: Math.max(before.monthlyCost * 0.7, 0), ownerBefore: before.owner, ownerAfter: after.owner, createdAt: ts, updatedAt: ts }); await platformEventService.recordEvent({ tenantId: input.tenantId, category: "EXECUTION", type: "AZURE_CONTROLLED_EXECUTION", entityType: "GovernedExecution", entityId: input.execution.id, sourceSystem: "azure-execution-adapter", metadata: { actionId: input.action.id, autonomous: false } }); return { status: "COMPLETED", evidence: executionEvidence, rollbackPayload, artifact }; }
export const rightsizeAzureVm = executeAzureOperation; export const stopAzureVm = executeAzureOperation; export const startAzureVm = executeAzureOperation; export const modifyAzureSql = executeAzureOperation; export const stopAzureSql = executeAzureOperation; export const startAzureSql = executeAzureOperation; export const deleteManagedDisk = executeAzureOperation; export const releasePublicIp = executeAzureOperation; export const tagOwner = executeAzureOperation; export const createReservedInstanceReview = executeAzureOperation; export const createSavingsPlanReview = executeAzureOperation;
export async function verifyAzureState(input: { tenantId: string; executionId: string }) { return verifyAzureExecution(input.tenantId, input.executionId); }
export async function verifyAzureExecution(tenantId: string, executionId: string) { const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const artifact = getAzureArtifactByExecution(tenantId, executionId); if (!artifact) throw new Error("AZURE_ARTIFACT_NOT_FOUND"); const verificationEvidence = governedExecutionService.appendEvidence(execution, evidence(executionId, "VERIFICATION_RESULT", "Azure provider state verification passed.", { provider: "AZURE", artifactId: artifact.id, lifecycle: ["Projected", "Approved", "Executed", "Verified", "Protected"] })); const outcome = economicOutcomeAttributionService.createEconomicOutcome({ tenantId, assetId: artifact.id, assetType: "CLOUD", name: `Azure ${artifact.resourceId} cost optimisation`, outcomeType: "COST_REDUCTION", status: "MEASURED", measurementConfidence: "HIGH", measuredValue: artifact.monthlyCostBefore && artifact.monthlyCostAfter ? artifact.monthlyCostBefore - artifact.monthlyCostAfter : 100, source: "CONNECTOR", metadata: { provider: "AZURE", executionId } }); await governedActionService.updateExecutionMetadata(tenantId, execution.actionId, { status: "VERIFIED", outcomeIds: [outcome.id], evidenceIds: [verificationEvidence.id], actualMonthlyValue: outcome.measuredValue, actualAnnualValue: (outcome.measuredValue ?? 0) * 12 }); const policyName = artifact.artifactType === "VM" ? "AZURE_VM_RESIZED_BACK" : artifact.artifactType === "SQL" ? "AZURE_SQL_REVERTED" : artifact.state === "DELETED" ? "AZURE_RESOURCE_RECREATED" : "AZURE_SPEND_RETURNED"; const policy = outcomeProtectionService.createDriftPolicy({ tenantId, name: policyName, domain: "CLOUD", policyType: artifact.state === "TAGGED" ? "OWNER_REMOVED" : artifact.state === "DELETED" ? "ASSET_RECREATED" : "CONFIG_REVERTED" }); const protectedOutcome = await outcomeProtectionService.protectOutcome({ tenantId, outcomeId: outcome.id, actionId: execution.actionId, executionId, assetId: artifact.id, assetType: "CLOUD", policyIds: [policy.id], evidenceIds: [verificationEvidence.id] }); await platformEventService.recordEvent({ tenantId, category: "OUTCOME", type: "AZURE_OUTCOME_VERIFIED", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "azure-execution-adapter", metadata: { outcomeId: outcome.id, protectedOutcomeId: protectedOutcome.id, autonomous: false } }); return { verified: true, artifact, evidence: verificationEvidence, outcome, protectedOutcome }; }
export async function rollbackAzureExecution(tenantId: string, executionId: string) { const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const rollbackPayload = rollbacks.get(executionId); if (!rollbackPayload) throw new Error("ROLLBACK_PAYLOAD_MISSING"); const partial = Boolean(rollbackPayload.partialReason); if (!partial) states.set(key(tenantId, rollbackPayload.resourceId), rollbackPayload.priorState); const rollbackEvidence = governedExecutionService.appendEvidence(execution, evidence(executionId, "ROLLBACK_RESULT", partial ? "Azure rollback recorded as PARTIAL with destructive limitation evidence." : "Azure rollback restored prior resource configuration.", { ...rollbackPayload, status: partial ? "PARTIAL" : "COMPLETE" } as unknown as Record<string, unknown>)); governedExecutionService.updateExecution({ ...execution, status: "ROLLED_BACK", updatedAt: now() }); await platformEventService.recordEvent({ tenantId, category: "EXECUTION", type: "EXECUTION_ROLLED_BACK", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "azure-execution-adapter", metadata: { evidenceId: rollbackEvidence.id, partial, autonomous: false } }); return { rolledBack: !partial, partial, evidence: rollbackEvidence }; }
export { listAzureArtifacts };
export function clearAzureExecutionState() { states.clear(); rollbacks.clear(); }
