import type { BasePlaybook } from "./base-playbook";

type C = { email:string; displayName:string; assignedLicenses?:string[]; usedApps?:string[]; cost?:number; trustBand?:string; isAdmin?:boolean; isCreativeLeadership?:boolean; owner?:string; addOn?:string; addOnUsage?:"LOW"|"STALE"|"UNKNOWN"|"ACTIVE"; storageConsumption?:number; inactiveDays?:number; contractorFlag?:boolean; legalHold?:boolean; };
const ex=(c:C)=>[c.isAdmin?"admin":null,c.isCreativeLeadership?"creative leadership":null,c.trustBand==="QUARANTINED"?"quarantined trust":null].filter(Boolean) as string[];
const base=(id:string,name:string)=>({id,name,vendor:"adobe",action:"REVIEW",riskClass:"B" as const,description:name,triggerConditions:[],requiredEvidence:[],exclusionRules:[],recommendedAction:"REVIEW",defaultExecutionMode:"APPROVAL_REQUIRED" as const,expectedSavingsModel:"pricing-authority-backed only",verificationMethod:"review",rollbackConsiderations:"n/a"});

export const adobeAllAppsToSingleAppRightsize: BasePlaybook<C> = { ...base("ADOBE_ALL_APPS_TO_SINGLE_APP_RIGHTSIZE","Adobe All Apps to Single App Rightsize"), evaluate(i){ const matched=(i.assignedLicenses??[]).includes("CREATIVE_CLOUD_ALL_APPS") && new Set(i.usedApps??[]).size===1; return {matched,reason:matched?"All Apps with single app family usage":"No single-app pattern",recommendedAction:"RIGHTSIZE_REVIEW",estimatedMonthlySaving:Number(i.cost??0),subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{usedApps:i.usedApps,assignedLicenses:i.assignedLicenses},exclusions:ex(i),requiredSignals:["assignedLicenses","usedApps"]}; }};
export const adobeAcrobatProRightsize: BasePlaybook<C> = { ...base("ADOBE_ACROBAT_PRO_RIGHTSIZE","Adobe Acrobat Pro Rightsize"), evaluate(i){ const matched=(i.assignedLicenses??[]).includes("ACROBAT_PRO") && (i.usedApps??[]).every(a=>["ACROBAT_READER","ADOBE_SIGN"].includes(a)); return {matched,reason:matched?"Pro assigned with reader/sign-only usage":"No Acrobat rightsize pattern",recommendedAction:"RIGHTSIZE_REVIEW",estimatedMonthlySaving:Number(i.cost??0),subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{usedApps:i.usedApps},exclusions:ex(i),requiredSignals:["assignedLicenses","usedApps"]}; }};
export const adobeVideoSuiteRightsize: BasePlaybook<C> = { ...base("ADOBE_VIDEO_SUITE_RIGHTSIZE","Adobe Video Suite Rightsize"), evaluate(i){ const hasVideo=(i.assignedLicenses??[]).some(s=>["PREMIERE_PRO","AFTER_EFFECTS"].includes(s)); const matched=hasVideo && (i.usedApps??[]).every(a=>["PHOTOSHOP","ILLUSTRATOR","ACROBAT_READER"].includes(a)); return {matched,reason:matched?"Video assigned but image/doc usage only":"No video rightsize pattern",recommendedAction:"RIGHTSIZE_REVIEW",estimatedMonthlySaving:Number(i.cost??0),subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{assignedLicenses:i.assignedLicenses,usedApps:i.usedApps},exclusions:ex(i),requiredSignals:["assignedLicenses","usedApps"]}; }};
export const adobeLowUsageCreativeCloudRightsize: BasePlaybook<C> = { ...base("ADOBE_LOW_USAGE_CREATIVE_CLOUD_RIGHTSIZE","Adobe Low Usage Creative Cloud Rightsize"), evaluate(i){ const matched=(i.inactiveDays??0)>60 && (i.assignedLicenses??[]).length>0; return {matched,reason:matched?"Low/stale usage pattern":"No low usage pattern",recommendedAction:"RIGHTSIZE_REVIEW",estimatedMonthlySaving:Number(i.cost??0),subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{inactiveDays:i.inactiveDays},exclusions:ex(i),requiredSignals:["inactiveDays","assignedLicenses"]}; }};

export const adobeStockAddonReclaim = { ...base("ADOBE_STOCK_ADDON_RECLAIM","Adobe Stock Add-on Reclaim"), evaluate(i:C){ const matched=i.addOn==="STOCK" && ["LOW","STALE","UNKNOWN"].includes(String(i.addOnUsage)); return {matched,reason:matched?"Stock add-on low/stale/unknown usage":"No stock candidate",recommendedAction:"ADDON_REVIEW",estimatedMonthlySaving:Number(i.cost??0),subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{addOnUsage:i.addOnUsage,owner:i.owner},exclusions:ex(i),requiredSignals:["addOn","addOnUsage"]}; }};
export const adobeFireflyCreditsReview = { ...base("ADOBE_FIREFLY_CREDITS_REVIEW","Adobe Firefly Credits Review"), evaluate: adobeStockAddonReclaim.evaluate };
export const adobeFrameIoReclaim = { ...base("ADOBE_FRAME_IO_RECLAIM","Adobe Frame.io Reclaim"), evaluate: adobeStockAddonReclaim.evaluate };
export const adobeSubstanceReclaim = { ...base("ADOBE_SUBSTANCE_RECLAIM","Adobe Substance Reclaim"), evaluate: adobeStockAddonReclaim.evaluate };
export const adobeSignAddonReview = { ...base("ADOBE_SIGN_ADDON_REVIEW","Adobe Sign Add-on Review"), evaluate: adobeStockAddonReclaim.evaluate };

export const adobeStorageGovernanceReview: BasePlaybook<C> = { ...base("ADOBE_STORAGE_GOVERNANCE_REVIEW","Adobe Storage Governance Review"), evaluate(i){ const matched=(Number(i.storageConsumption??0)>50000)||((i.inactiveDays??0)>90)||Boolean(i.contractorFlag)||!i.owner; return {matched,reason:matched?"Storage governance risk detected":"No storage risk",recommendedAction:"STORAGE_REVIEW",estimatedMonthlySaving:0,subject:{type:"USER" as const,id:i.email,email:i.email,displayName:i.displayName},evidence:{storageConsumption:i.storageConsumption,owner:i.owner,inactiveDays:i.inactiveDays,legalHold:i.legalHold},exclusions:ex(i),requiredSignals:["storageConsumption","owner"]}; }};
