import type { BasePlaybook, PlaybookEvaluationResult } from "./base-playbook";

type AdobeCandidate = { email: string; displayName: string; sku: string; cost: number; days: number; contractorFlag?: boolean; isAdmin?: boolean; isExecutive?: boolean; isCreativeLeadership?: boolean; isSharedDevice?: boolean; trustBand?: string; identityType?: string; assignedLicenses?: string[]; contractorState?: string; };

function exclusions(c: AdobeCandidate) { const x: string[] = []; if (c.isAdmin) x.push("admin account"); if (c.isExecutive) x.push("executive account"); if (c.isCreativeLeadership) x.push("creative leadership"); if (c.isSharedDevice) x.push("shared device"); if (c.identityType === "UNKNOWN_IDENTITY_TYPE") x.push("unknown identity"); if (c.trustBand === "QUARANTINED") x.push("quarantined trust"); return x; }

export const adobeInactiveLicenseReclaimPlaybook: BasePlaybook<AdobeCandidate> = {
  id: "adobe_inactive_license_reclaim_v1", name: "Adobe Inactive License Reclaim", vendor: "adobe", action: "REMOVE_LICENSE", riskClass: "B", description: "Read-only recommendation for inactive Adobe licenses.", triggerConditions: ["assigned license exists", "inactive threshold exceeded"], requiredEvidence: ["license assignment", "activity", "identity", "trust"], exclusionRules: ["admin", "executive", "creative leadership", "shared device", "unknown identity", "quarantined trust"], recommendedAction: "REMOVE_LICENSE", defaultExecutionMode: "APPROVAL_REQUIRED", expectedSavingsModel: "Assigned SKU monthly cost", verificationMethod: "Confirm inactivity and approval", rollbackConsiderations: "Reassign if needed",
  evaluate(input): PlaybookEvaluationResult { const x = exclusions(input); const matched = (input.days > 90 || input.contractorState === "INACTIVE") && (input.assignedLicenses?.length ?? 0) > 0; return { matched, reason: matched ? "Inactive and licensed" : "Not inactive or not licensed", recommendedAction: "REMOVE_LICENSE", estimatedMonthlySaving: input.cost, subject: { type: "USER", id: input.email, email: input.email, displayName: input.displayName }, evidence: { lastLoginDaysAgo: input.days, assignedLicenses: input.assignedLicenses ?? [], trustBand: input.trustBand ?? "UNKNOWN" }, exclusions: x, requiredSignals: ["assignedLicenses", "lastLoginDaysAgo", "identityType", "trustBand"] }; }
};

export const adobeContractorCleanupPlaybook: BasePlaybook<AdobeCandidate> = {
  id: "adobe_contractor_cleanup_v1", name: "Adobe Contractor Cleanup", vendor: "adobe", action: "REMOVE_LICENSE", riskClass: "B", description: "Read-only recommendation for inactive Adobe contractors.", triggerConditions: ["contractorFlag=true", "inactive threshold exceeded", "assigned license exists"], requiredEvidence: ["contractor flag", "activity", "license"], exclusionRules: ["admin", "quarantined trust"], recommendedAction: "REMOVE_LICENSE", defaultExecutionMode: "APPROVAL_REQUIRED", expectedSavingsModel: "Assigned SKU monthly cost", verificationMethod: "Confirm contractor status and offboarding", rollbackConsiderations: "Restore if contractor reactivated",
  evaluate(input): PlaybookEvaluationResult { const x = exclusions(input); const matched = Boolean(input.contractorFlag) && input.days > 45 && (input.assignedLicenses?.length ?? 0) > 0; return { matched, reason: matched ? "Inactive contractor licensed" : "Contractor criteria not met", recommendedAction: "REMOVE_LICENSE", estimatedMonthlySaving: input.cost, subject: { type: "USER", id: input.email, email: input.email, displayName: input.displayName }, evidence: { contractorFlag: Boolean(input.contractorFlag), lastLoginDaysAgo: input.days, assignedLicenses: input.assignedLicenses ?? [] }, exclusions: x, requiredSignals: ["contractorFlag", "assignedLicenses", "lastLoginDaysAgo"] }; }
};
