import type { BasePlaybook, PlaybookEvaluationResult } from './base-playbook';
type C={email:string;displayName:string;productType:string;assignedLicenses?:string[];inactiveDays?:number;cost?:number;trustBand?:string;isOrgAdmin?:boolean;isSiteAdmin?:boolean;securitySensitive?:boolean;protectedEngineering?:boolean;identityType?:string;contractorFlag?:boolean;groupAmbiguous?:boolean;siteAmbiguous?:boolean;marketplaceAssigned?:boolean;usageUnknown?:boolean;ownerUnknown?:boolean;};
const ex=(c:C)=>[c.isOrgAdmin?'org admin':null,c.isSiteAdmin?'site admin':null,c.securitySensitive?'security-sensitive role':null,c.protectedEngineering?'protected engineering role':null,c.identityType==='UNKNOWN_IDENTITY_TYPE'?'unknown identity':null,c.trustBand==='LOW'?'low trust':null,c.trustBand==='QUARANTINED'?'quarantined trust':null].filter(Boolean) as string[];
const base=(id:string,name:string)=>({id,name,vendor:'atlassian',action:'REVIEW',riskClass:'B' as const,description:name,triggerConditions:[],requiredEvidence:[],exclusionRules:[],recommendedAction:'REVIEW',defaultExecutionMode:'APPROVAL_REQUIRED' as const,expectedSavingsModel:'pricing-authority-backed only',verificationMethod:'review',rollbackConsiderations:'n/a'});

export const atlassianInactiveJiraReclaim: BasePlaybook<C> = {...base('ATLASSIAN_INACTIVE_JIRA_RECLAIM','Atlassian Inactive Jira Reclaim'),evaluate(i):PlaybookEvaluationResult{const matched=i.productType==='JIRA'&&(i.inactiveDays??0)>90&&(i.assignedLicenses??[]).length>0;return {matched,reason:matched?'Inactive Jira licensed user':'No Jira reclaim candidate',recommendedAction:'REMOVE_LICENSE_REVIEW',estimatedMonthlySaving:Number(i.cost??0),subject:{type:'USER',id:i.email,email:i.email,displayName:i.displayName},evidence:{inactiveDays:i.inactiveDays,assignedLicenses:i.assignedLicenses},exclusions:ex(i),requiredSignals:['inactiveDays','assignedLicenses','trustBand']};}};
export const atlassianInactiveConfluenceReclaim: BasePlaybook<C> = {...base('ATLASSIAN_INACTIVE_CONFLUENCE_RECLAIM','Atlassian Inactive Confluence Reclaim'),evaluate:i=>atlassianInactiveJiraReclaim.evaluate({...i,productType:'JIRA'})};
export const atlassianInactiveJsmReclaim: BasePlaybook<C> = {...base('ATLASSIAN_INACTIVE_JSM_RECLAIM','Atlassian Inactive JSM Reclaim'),evaluate:i=>atlassianInactiveJiraReclaim.evaluate({...i,productType:'JIRA'})};
export const atlassianInactiveOpsgenieReclaim: BasePlaybook<C> = {...base('ATLASSIAN_INACTIVE_OPSGENIE_RECLAIM','Atlassian Inactive Opsgenie Reclaim'),evaluate:i=>atlassianInactiveJiraReclaim.evaluate({...i,productType:'JIRA'})};

export const atlassianAdminAccessReview: BasePlaybook<C> = {...base('ATLASSIAN_ADMIN_ACCESS_REVIEW','Atlassian Admin Access Review'),evaluate(i){const matched=Boolean(i.isOrgAdmin||i.isSiteAdmin)&&(Boolean(i.contractorFlag)||Boolean(i.ownerUnknown)||(i.inactiveDays??0)>30);return {matched,reason:matched?'Admin access governance candidate':'No admin governance candidate',recommendedAction:'GOVERNANCE_REVIEW',estimatedMonthlySaving:0,subject:{type:'USER',id:i.email,email:i.email,displayName:i.displayName},evidence:{isOrgAdmin:i.isOrgAdmin,isSiteAdmin:i.isSiteAdmin,inactiveDays:i.inactiveDays},exclusions:ex(i),requiredSignals:['adminRole','inactiveDays','owner']};}};
export const atlassianGroupAssignmentReview: BasePlaybook<C> = {...base('ATLASSIAN_GROUP_ASSIGNMENT_REVIEW','Atlassian Group Assignment Review'),evaluate(i){const matched=Boolean(i.groupAmbiguous);return {matched,reason:matched?'Group assignment ambiguity':'No group ambiguity',recommendedAction:'GROUP_REVIEW',estimatedMonthlySaving:0,subject:{type:'USER',id:i.email,email:i.email,displayName:i.displayName},evidence:{groupAmbiguous:i.groupAmbiguous},exclusions:ex(i),requiredSignals:['groupMemberships']};}};
export const atlassianSiteMembershipReview: BasePlaybook<C> = {...base('ATLASSIAN_SITE_MEMBERSHIP_REVIEW','Atlassian Site Membership Review'),evaluate(i){const matched=Boolean(i.siteAmbiguous);return {matched,reason:matched?'Site membership ambiguity':'No site ambiguity',recommendedAction:'SITE_REVIEW',estimatedMonthlySaving:0,subject:{type:'USER',id:i.email,email:i.email,displayName:i.displayName},evidence:{siteAmbiguous:i.siteAmbiguous},exclusions:ex(i),requiredSignals:['siteMembership']};}};
export const atlassianMarketplaceReview: BasePlaybook<C> = {...base('ATLASSIAN_MARKETPLACE_REVIEW','Atlassian Marketplace Review'),evaluate(i){const matched=Boolean(i.marketplaceAssigned&&i.usageUnknown);return {matched,reason:matched?'Marketplace assignment usage unknown/stale':'No marketplace review candidate',recommendedAction:'MARKETPLACE_REVIEW',estimatedMonthlySaving:Number(i.cost??0),subject:{type:'USER',id:i.email,email:i.email,displayName:i.displayName},evidence:{marketplaceAssigned:i.marketplaceAssigned,usageUnknown:i.usageUnknown},exclusions:ex(i),requiredSignals:['marketplaceAssignments','usageConfidence']};}};
