import type { BasePlaybook } from "./base-playbook";

export const M365_EVIDENCE_TYPES = {
  ASSIGNED_LICENSE: "assigned license",
  LAST_SIGN_IN: "last sign-in",
  LAST_APP_OR_SERVICE_ACTIVITY: "last app/service activity",
  DESKTOP_APP_INSTALL_OR_USE: "desktop app install/use",
  MAILBOX_TYPE: "mailbox type",
  USER_ACCOUNT_STATUS: "user account status",
  DEPARTMENT_COST_CENTRE: "department/cost centre",
  MANAGER_OWNER: "manager/owner",
  SKU_COST: "SKU cost",
  COPILOT_ACTIVITY: "Copilot activity",
  ADDON_USAGE: "add-on usage",
} as const;

export type M365Candidate = {
  email: string; displayName: string; sku: string; cost: number; days: number;
  accountEnabled?: boolean; assignedLicenses?: string[]; userPrincipalName?: string; mailboxType?: string;
  isSharedMailbox?: boolean; hasDesktopActivity?: boolean; advancedFeatureUsage?: number; activityPresent?: boolean;
  isFrontlineWorker?: boolean; addonUsageDaysAgo?: number | null; department?: string; costCentre?: string;
  manager?: string; copilotActivityScore?: number; overlappingSkuDetected?: boolean; isAdmin?: boolean; isPrivileged?: boolean;
  isExecutive?: boolean; isContractor?: boolean; ownershipUnclear?: boolean; legalHold?: boolean; recentReactivation?: boolean;
  copilotRecentlyAssigned?: boolean; copilotEnablementCohort?: boolean; delegatedUsersCount?: number;
};

const commonExclusions = (c: M365Candidate): string[] => {
  const e = c.email.toLowerCase(); const x: string[] = [];
  if (e.includes("admin") || c.isAdmin) x.push("admin account");
  if (e.includes("service")) x.push("service account");
  if (c.ownershipUnclear) x.push("ownership unclear");
  return x;
};

const result = (p: BasePlaybook<M365Candidate>, matched:boolean, reason:string, saving:number, input:M365Candidate, evidence:Record<string,unknown>, exclusions:string[], requiredSignals:string[]) => ({
  matched, reason, recommendedAction: p.recommendedAction, estimatedMonthlySaving: Math.max(0, saving),
  subject: { type: "USER" as const, id: input.email, displayName: input.displayName, email: input.email }, evidence, exclusions, requiredSignals,
  verificationMethod: p.verificationMethod, executionMode: p.defaultExecutionMode, riskClass: p.riskClass, rollbackNotes: p.rollbackConsiderations,
  trustRequirements: ["Data Trust", "Governance Policy", "Approval", "Runtime Controls", "Outcome Verification", "Savings Proof"],
});

export const disabledLicensedUserReclaimPlaybook: BasePlaybook<M365Candidate> = { id: "M365_DISABLED_LICENSED_USER_RECLAIM", name: "Disabled Licensed User Reclaim", description:"Reclaim licenses for disabled users with active assignments.", vendor:"m365", action:"RECLAIM_UNUSED_LICENSE", triggerConditions:["accountEnabled=false","assigned license exists"], requiredEvidence:[M365_EVIDENCE_TYPES.USER_ACCOUNT_STATUS,M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.LAST_SIGN_IN], exclusionRules:["service account","shared mailbox candidate"], recommendedAction:"RECLAIM_UNUSED_LICENSE", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"Full assigned SKU monthly cost", verificationMethod:"Confirm user remains disabled and ownership is clear", rollbackConsiderations:"Reassign previous SKU if disabled state changed", evaluate(input){const exclusions=commonExclusions(input); const isShared=input.mailboxType==="shared"||input.isSharedMailbox===true; const matched=input.accountEnabled===false&&(input.assignedLicenses?.length??0)>0&&!isShared&&!exclusions.includes("service account"); return result(this, matched, matched?"Disabled licensed user detected":"No disabled-user reclaim opportunity", input.cost, input, {accountEnabled:input.accountEnabled,assignedLicenses:input.assignedLicenses??[],lastSignInDaysAgo:input.days,tenantScoped:true}, exclusions, ["accountEnabled","assignedLicenses","lastLoginDaysAgo"]);}};

export const inactiveUserReclaimPlaybook: BasePlaybook<M365Candidate> = { id:"M365_INACTIVE_LICENSED_USER_RECLAIM", name:"Inactive Licensed User Reclaim", description:"Reclaim paid licenses from sustained inactive users.", vendor:"m365", action:"RECLAIM_INACTIVE_LICENSE", triggerConditions:["inactivity > 90 days","license assigned","no recent sign-in"], requiredEvidence:[M365_EVIDENCE_TYPES.LAST_SIGN_IN,M365_EVIDENCE_TYPES.LAST_APP_OR_SERVICE_ACTIVITY,M365_EVIDENCE_TYPES.ASSIGNED_LICENSE], exclusionRules:["recently reactivated","high reversal risk ownership"], recommendedAction:"RECLAIM_INACTIVE_LICENSE", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"Full assigned SKU monthly cost", verificationMethod:"Verify inactivity and no recent reactivation", rollbackConsiderations:"Restore license on confirmed reactivation", evaluate(input){const exclusions=commonExclusions(input); const matched=input.days>90&&(input.assignedLicenses?.length??0)>0&&input.activityPresent===false&&!input.recentReactivation; return result(this, matched, matched?"Inactive licensed user over threshold":"No inactive reclaim opportunity", input.cost, input, {lastLoginDaysAgo:input.days,activityPresent:input.activityPresent??null,assignedLicenses:input.assignedLicenses??[]}, exclusions, ["lastLoginDaysAgo","activityPresent","assignedLicenses"]);}};

export const e3WithoutDesktopAppsRightsizePlaybook: BasePlaybook<M365Candidate> = { id:"M365_E3_DESKTOP_RIGHTSIZE", name:"E3 Desktop App Non-Usage Rightsize", description:"Rightsize E3 users with web-only behavior and no desktop usage.", vendor:"m365", action:"RIGHTSIZE_E3_TO_LIGHTER_TIER", triggerConditions:["E3 assigned","no desktop usage"], requiredEvidence:[M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.DESKTOP_APP_INSTALL_OR_USE], exclusionRules:["desktop-required departments"], recommendedAction:"RIGHTSIZE_E3_TO_LIGHTER_TIER", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"E3 to lighter tier monthly delta", verificationMethod:"Validate no desktop activation after rightsize", rollbackConsiderations:"Return to E3 if desktop dependency appears", evaluate(input){const hasE3=(input.sku==="E3")||(input.assignedLicenses??[]).includes("E3"); const matched=hasE3&&input.hasDesktopActivity===false; return result(this, matched, matched?"E3 entitlement without desktop use":"No E3 desktop rightsize opportunity", input.cost-12, input,{assignedSku:input.sku,hasDesktopActivity:input.hasDesktopActivity,usageMix:input.isFrontlineWorker?"frontline":"standard"},commonExclusions(input),["assignedLicenses","hasDesktopActivity"]);}};

export const e5UnderusedRightsizePlaybook: BasePlaybook<M365Candidate> = { id:"M365_E5_UNDERUTILISATION_RIGHTSIZE", name:"E5 Underutilisation Rightsize", description:"Rightsize E5 users with low premium capability usage.", vendor:"m365", action:"RIGHTSIZE_E5_TO_E3", triggerConditions:["E5 assigned","premium usage low"], requiredEvidence:[M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.LAST_APP_OR_SERVICE_ACTIVITY], exclusionRules:["security/admin users","unclear dependency"], recommendedAction:"RIGHTSIZE_E5_TO_E3", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"E5 to E3 monthly delta", verificationMethod:"Validate premium dependency inactivity", rollbackConsiderations:"Restore E5 where premium dependence confirmed", evaluate(input){const hasE5=(input.sku==="E5")||(input.assignedLicenses??[]).includes("E5"); const lowPremium=(input.advancedFeatureUsage??0)<=0.2; const matched=hasE5&&lowPremium&&input.activityPresent!==false; return result(this, matched, matched?"E5 assigned with low premium utilization":"No E5 rightsize opportunity", input.cost-36, input,{assignedSku:input.sku,advancedFeatureUsage:input.advancedFeatureUsage??0,securitySensitive:Boolean(input.isAdmin||input.isPrivileged)},commonExclusions(input),["assignedLicenses","advancedFeatureUsage"]);}};

export const addonLicenseReclaimPlaybook: BasePlaybook<M365Candidate> = { id:"M365_ADDON_LICENSE_RECLAIM", name:"Add-on Licence Reclaim", description:"Reclaim underused or unused add-on licenses.", vendor:"m365", action:"RECLAIM_UNUSED_ADDON", triggerConditions:["addon assigned","usage stale"], requiredEvidence:[M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.ADDON_USAGE], exclusionRules:["business critical role","ownership unclear"], recommendedAction:"RECLAIM_UNUSED_ADDON", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"Full add-on monthly cost", verificationMethod:"Confirm add-on inactivity window", rollbackConsiderations:"Reassign add-on where critical use reappears", evaluate(input){const isAddon=input.sku.startsWith("ADDON_"); const matched=isAddon&&((input.addonUsageDaysAgo??999)>90); return result(this, matched, matched?"Add-on assigned with no recent usage":"No add-on reclaim opportunity", input.cost, input,{sku:input.sku,addonUsageDaysAgo:input.addonUsageDaysAgo??null,projectLinked:false},commonExclusions(input),["assignedLicenses","addonUsageDaysAgo"]);}};

export const sharedMailboxLicenseReclaimPlaybook: BasePlaybook<M365Candidate> = { id:"M365_SHARED_MAILBOX_CONVERSION_CANDIDATE", name:"Shared Mailbox Conversion Candidate", description:"Identify users suitable for shared mailbox conversion.", vendor:"m365", action:"CONVERT_TO_SHARED_MAILBOX", triggerConditions:["mailbox-centric low activity","shared function signals"], requiredEvidence:[M365_EVIDENCE_TYPES.MAILBOX_TYPE,M365_EVIDENCE_TYPES.LAST_SIGN_IN,M365_EVIDENCE_TYPES.ASSIGNED_LICENSE], exclusionRules:["privileged/admin","legal retention conflict","executive"], recommendedAction:"CONVERT_TO_SHARED_MAILBOX", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"User mailbox license reclaimed post conversion", verificationMethod:"Validate delegations and inactive operational identity", rollbackConsiderations:"Revert to user mailbox if operational need returns", evaluate(input){const lowActivity=input.days>90; const mailboxCentric=input.mailboxType==="user" || input.mailboxType==="shared" || input.delegatedUsersCount != null; const blocked=Boolean(input.isAdmin||input.isPrivileged||input.isExecutive||input.legalHold); const matched=lowActivity&&mailboxCentric&&!blocked; return result(this, matched, matched?"Mailbox profile is a conversion candidate":"No shared mailbox conversion opportunity", input.cost, input,{mailboxType:input.mailboxType??"user",delegatedUsersCount:input.delegatedUsersCount??0,legalHold:Boolean(input.legalHold)},commonExclusions(input),["mailboxType","lastLoginDaysAgo","assignedLicenses"]);}};

export const contractorLeaverReviewPlaybook: BasePlaybook<M365Candidate> = { id:"M365_CONTRACTOR_LEAVER_LICENSE_REVIEW", name:"Contractor / Leaver Licence Review", description:"Review contractor/leaver identities for license posture.", vendor:"m365", action:"REVIEW_CONTRACTOR_LICENSE", triggerConditions:["contractor/leaver indicators","license assigned"], requiredEvidence:[M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.LAST_SIGN_IN,M365_EVIDENCE_TYPES.MANAGER_OWNER], exclusionRules:["recent sign-in","active project indicator"], recommendedAction:"REVIEW_CONTRACTOR_LICENSE", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"Potential full license reclaim", verificationMethod:"Confirm employment and ownership status", rollbackConsiderations:"Review action only; no direct mutation", evaluate(input){const candidate=Boolean(input.isContractor||input.ownershipUnclear); const stale=input.days>60; const matched=candidate&&stale&&(input.assignedLicenses?.length??0)>0; return result(this, matched, matched?"Contractor/leaver requires license review":"No contractor/leaver review opportunity", input.cost, input,{isContractor:Boolean(input.isContractor),ownershipUnclear:Boolean(input.ownershipUnclear),lastLoginDaysAgo:input.days},commonExclusions(input),["assignedLicenses","lastLoginDaysAgo","manager"]);}};

export const copilotUnderuseReallocationPlaybook: BasePlaybook<M365Candidate> = { id:"M365_COPILOT_UNDERUTILISATION_REVIEW", name:"Copilot Underutilisation Review", description:"Review Copilot assignments with low sustained usage.", vendor:"m365", action:"REVIEW_COPILOT_ASSIGNMENT", triggerConditions:["Copilot assigned","low interaction volume"], requiredEvidence:[M365_EVIDENCE_TYPES.ASSIGNED_LICENSE,M365_EVIDENCE_TYPES.COPILOT_ACTIVITY,M365_EVIDENCE_TYPES.DEPARTMENT_COST_CENTRE], exclusionRules:["new assignment","pilot/enablement cohorts"], recommendedAction:"REVIEW_COPILOT_ASSIGNMENT", riskClass:"B", defaultExecutionMode:"APPROVAL_REQUIRED", expectedSavingsModel:"Potential Copilot license redeployment", verificationMethod:"Validate low utilization outside enablement windows", rollbackConsiderations:"Retain assignment when enablement cohorts are confirmed", evaluate(input){const hasCopilot=(input.assignedLicenses??[]).some((x)=>x.includes("COPILOT")); const under=(input.copilotActivityScore??0)<0.2; const protectedCohort=Boolean(input.copilotRecentlyAssigned||input.copilotEnablementCohort); const matched=hasCopilot&&under&&!protectedCohort; return result(this, matched, matched?"Copilot low utilization candidate for review":"No Copilot underutilisation review opportunity", input.cost, input,{copilotActivityScore:input.copilotActivityScore??0,copilotRecentlyAssigned:Boolean(input.copilotRecentlyAssigned),copilotEnablementCohort:Boolean(input.copilotEnablementCohort)},commonExclusions(input),["assignedLicenses","copilotActivityScore","department"]);}};

export const overlappingSkuCleanupPlaybook = addonLicenseReclaimPlaybook;
export const serviceAccountLicenseReviewPlaybook = contractorLeaverReviewPlaybook;
export const frontlineFitRightsizePlaybook = e3WithoutDesktopAppsRightsizePlaybook;
export const storageCostExposurePlaybook = sharedMailboxLicenseReclaimPlaybook;
export const renewalReadinessPackPlaybook = inactiveUserReclaimPlaybook;
