import type { AuthType, ConnectorFamily, ConnectorManifest } from '../connector-readiness';

export type { ConnectorFamily, ConnectorManifest };
export type ConnectorAdapterMode = 'DEMO' | 'LIVE';
export type ConnectorAdapterStatus = 'PASS' | 'WARN' | 'FAIL';
export interface ConnectorAdapterConfig { tenantId: string; connectorKey: string; mode: ConnectorAdapterMode; credentialRef?: string; config: Record<string, unknown>; source: string; }
export interface ConnectorAuthRequirements { authType: AuthType; requiredScopes: string[]; optionalScopes: string[]; requiresCredentialRef: boolean; requiresTenantConsent: boolean; requiresAdminConsent: boolean; credentialFields: Array<{ key: string; label: string; sensitive: boolean; required: boolean }>; notes: string[]; }
export interface ConnectorPermissionChecklist { connectorKey: string; items: Array<{ key: string; label: string; required: boolean; status: 'REQUIRED' | 'OPTIONAL' | 'NOT_REQUIRED'; reason?: string }>; }
export interface ConnectorCapabilityDiscovery { connectorKey: string; status: 'READY' | 'PARTIAL' | 'BLOCKED'; capabilities: ConnectorManifest['capabilityManifest']; missingCapabilities: string[]; source: string; evidenceRefs: string[]; }
export interface ConnectorAdapterValidationResult { connectorKey: string; status: ConnectorAdapterStatus; errors: Array<{ code: string; message: string; path?: string }>; warnings: Array<{ code: string; message: string; path?: string }>; }
export interface ConnectorSampleFetchResult { connectorKey: string; status: ConnectorAdapterStatus; sampleRecords: Array<{ outputContract: string; payload: Record<string, unknown> }>; recordsDetected: number; source: string; evidenceRefs: string[]; }
export interface ConnectorNormalisationResult { connectorKey: string; outputContract: string; status: ConnectorAdapterStatus; normalised?: Record<string, unknown>; errors: Array<{ code: string; message: string; path?: string }>; warnings: Array<{ code: string; message: string; path?: string }>; }
export interface ConnectorAdapterEvidenceResult { connectorKey: string; outputContract: string; status: 'CREATED' | 'FAILED' | 'NOT_REQUIRED'; evidenceRef?: string; evidenceType: 'CONFIGURATION' | 'AUTHORIZATION' | 'HEALTH_CHECK' | 'DRY_RUN' | 'VALIDATION' | 'GRAPH_MAPPING' | 'INGESTION_PREVIEW' | 'CONTRACT_TEST'; source: string; }
export interface ConnectorAdapterGraphResult { connectorKey: string; outputContract: string; status: 'READY' | 'PARTIAL' | 'BLOCKED'; nodeTypes: string[]; edgeTypes: string[]; reason?: string; }
export interface ConnectorFailureClassification { category: 'AUTH' | 'PERMISSION' | 'RATE_LIMIT' | 'NETWORK' | 'SCHEMA' | 'DATA_QUALITY' | 'CONFIGURATION' | 'UNSUPPORTED_CAPABILITY' | 'UNKNOWN'; severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; retryable: boolean; recommendedAction: string; }
export interface ConnectorRateLimitPolicy { connectorKey: string; strategy: 'NONE' | 'FIXED_WINDOW' | 'TOKEN_BUCKET' | 'EXPONENTIAL_BACKOFF'; maxRequestsPerMinute?: number; maxConcurrentRequests?: number; backoffSeconds?: number; notes: string[]; }
export interface ConnectorAdapter { connectorKey: string; connectorFamily: ConnectorFamily; manifest: ConnectorManifest; getAuthRequirements(): ConnectorAuthRequirements; getPermissionChecklist(): ConnectorPermissionChecklist; discoverCapabilities(config: ConnectorAdapterConfig): Promise<ConnectorCapabilityDiscovery>; validateConfig(config: ConnectorAdapterConfig): Promise<ConnectorAdapterValidationResult>; sampleFetch(config: ConnectorAdapterConfig): Promise<ConnectorSampleFetchResult>; normalise(outputContract: string, payload: Record<string, unknown>): Promise<ConnectorNormalisationResult>; buildEvidence(outputContract: string, payload: Record<string, unknown>): Promise<ConnectorAdapterEvidenceResult>; mapToGraph(outputContract: string, normalised: Record<string, unknown>): Promise<ConnectorAdapterGraphResult>; classifyError(error: unknown): ConnectorFailureClassification; getRateLimitPolicy(): ConnectorRateLimitPolicy; }
