import { connectorContractFixtures } from '../connector-contract-testing/connector-contract-fixtures';
import type { AuthType, ConnectorFamily, ConnectorManifest } from '../connector-readiness';
import { buildAdapterEvidence } from './connector-adapter-evidence';
import { mapAdapterGraph } from './connector-adapter-graph';
import { normaliseWithContractValidator } from './connector-adapter-normalisers';
import type { ConnectorAdapter, ConnectorAdapterConfig, ConnectorAuthRequirements, ConnectorFailureClassification, ConnectorPermissionChecklist, ConnectorRateLimitPolicy } from './connector-adapter-types';

const familyDefaults: Record<ConnectorFamily, { authType?: AuthType; admin?: boolean; scopes: string[]; rate: ConnectorRateLimitPolicy['strategy'] }> = {
  M365: { authType: 'OAUTH2', admin: true, scopes: ['Microsoft Graph User.Read.All', 'Directory.Read.All', 'Reports.Read.All'], rate: 'EXPONENTIAL_BACKOFF' },
  ENTRA_ID: { authType: 'OAUTH2', admin: true, scopes: ['Directory.Read.All', 'Group.Read.All', 'User.Read.All'], rate: 'EXPONENTIAL_BACKOFF' },
  FLEXERA: { authType: 'API_KEY', scopes: ['asset read access', 'license read access', 'export access'], rate: 'FIXED_WINDOW' },
  SERVICENOW: { authType: 'API_KEY', scopes: ['CMDB read access', 'table read access'], rate: 'FIXED_WINDOW' },
  ERP: { authType: 'SERVICE_ACCOUNT', scopes: ['vendor read access', 'invoice read access', 'PO read access'], rate: 'TOKEN_BUCKET' },
  AP: { authType: 'SERVICE_ACCOUNT', scopes: ['invoice read access', 'payment read access'], rate: 'TOKEN_BUCKET' },
  PROCUREMENT: { authType: 'SERVICE_ACCOUNT', scopes: ['contract read access', 'PO read access', 'vendor read access'], rate: 'TOKEN_BUCKET' },
  HRIS: { authType: 'SERVICE_ACCOUNT', scopes: ['worker read access', 'department read access', 'manager read access'], rate: 'TOKEN_BUCKET' },
  SAAS_DISCOVERY: { authType: 'API_KEY', scopes: ['app discovery access', 'export access'], rate: 'FIXED_WINDOW' },
  AI_PROVIDER: { authType: 'API_KEY', scopes: ['usage read access', 'billing read access', 'model read access'], rate: 'FIXED_WINDOW' },
  MANUAL_UPLOAD: { authType: 'FILE_UPLOAD', scopes: ['fixture upload validation'], rate: 'NONE' },
  CUSTOM: { authType: 'CUSTOM', scopes: ['contract-test driven access'], rate: 'NONE' },
};
export class BaseConnectorAdapter implements ConnectorAdapter { connectorKey: string; connectorFamily: ConnectorFamily; constructor(public manifest: ConnectorManifest) { this.connectorKey = manifest.connectorKey; this.connectorFamily = manifest.connectorFamily; }
  private defaults() { return familyDefaults[this.connectorFamily]; }
  getAuthRequirements(): ConnectorAuthRequirements { const d = this.defaults(); const authType = d.authType ?? this.manifest.authType; const requiresCredentialRef = !['FILE_UPLOAD', 'MANUAL'].includes(authType); return { authType, requiredScopes: [...new Set([...this.manifest.requiredScopes, ...d.scopes])], optionalScopes: this.manifest.optionalScopes, requiresCredentialRef, requiresTenantConsent: authType === 'OAUTH2', requiresAdminConsent: !!d.admin, credentialFields: requiresCredentialRef ? [{ key: 'credentialRef', label: 'Credential reference', sensitive: true, required: true }] : [], notes: ['Adapter contract only: no real third-party calls, credential storage, or authority writes.'] }; }
  getPermissionChecklist(): ConnectorPermissionChecklist { const auth = this.getAuthRequirements(); return { connectorKey: this.connectorKey, items: [...auth.requiredScopes.map((s) => ({ key: s, label: s, required: true, status: 'REQUIRED' as const, reason: 'Required by connector manifest or family adapter default.' })), ...auth.optionalScopes.map((s) => ({ key: s, label: s, required: false, status: 'OPTIONAL' as const }))] }; }
  async discoverCapabilities(config: ConnectorAdapterConfig) { const validation = await this.validateConfig(config); const missing = Object.entries(this.manifest.capabilityManifest).filter(([, v]) => !v).map(([k]) => k); return { connectorKey: this.connectorKey, status: validation.status === 'FAIL' ? 'BLOCKED' as const : missing.length ? 'PARTIAL' as const : 'READY' as const, capabilities: this.manifest.capabilityManifest, missingCapabilities: missing, source: config.source, evidenceRefs: [`adapter-capability://${this.connectorKey}`] }; }
  async validateConfig(config: ConnectorAdapterConfig) { const errors: any[] = []; const warnings: any[] = []; if (config.connectorKey !== this.connectorKey) errors.push({ code: 'CONNECTOR_KEY_MISMATCH', message: 'Config connectorKey must match adapter connectorKey.', path: '/connectorKey' }); if (config.mode === 'LIVE' && config.source === 'demo-fixture') errors.push({ code: 'LIVE_DEMO_FIXTURE_REJECTED', message: 'LIVE mode must not use demo-fixture source.', path: '/source' }); if (config.mode === 'LIVE' && this.getAuthRequirements().requiresCredentialRef && !config.credentialRef) errors.push({ code: 'LIVE_CREDENTIAL_REF_REQUIRED', message: 'LIVE mode requires credentialRef for this auth type.', path: '/credentialRef' }); const required = Array.isArray((this.manifest.configSchema as any).required) ? (this.manifest.configSchema as any).required : []; for (const field of required) if (config.mode === 'LIVE' && config.config[field] == null) warnings.push({ code: 'CONFIG_FIELD_MISSING', message: `${field} is recommended by manifest config schema.`, path: `/config/${field}` }); return { connectorKey: this.connectorKey, status: errors.length ? 'FAIL' as const : warnings.length ? 'WARN' as const : 'PASS' as const, errors, warnings }; }
  async sampleFetch(config: ConnectorAdapterConfig) { const validation = await this.validateConfig(config); if (validation.status === 'FAIL') return { connectorKey: this.connectorKey, status: 'FAIL' as const, sampleRecords: [], recordsDetected: 0, source: 'connector-contract-fixtures', evidenceRefs: [] }; const sampleRecords = connectorContractFixtures.filter((f) => f.connectorKey === this.connectorKey && f.fixtureType === 'VALID').map((f) => ({ outputContract: f.outputContract, payload: { ...f.payload, connectorKey: this.connectorKey, connectorFamily: this.connectorFamily, fixtureId: f.id } })); return { connectorKey: this.connectorKey, status: sampleRecords.length ? 'PASS' as const : 'WARN' as const, sampleRecords, recordsDetected: sampleRecords.length, source: 'connector-contract-fixtures', evidenceRefs: sampleRecords.map((r) => `contract-fixture://${this.connectorKey}/${r.outputContract}`) }; }
  async normalise(outputContract: string, payload: Record<string, unknown>) { return normaliseWithContractValidator(this.connectorKey, outputContract, payload); }
  async buildEvidence(outputContract: string, payload: Record<string, unknown>) { return buildAdapterEvidence(this.connectorKey, outputContract, payload); }
  async mapToGraph(outputContract: string, _normalised: Record<string, unknown> = {}) { return mapAdapterGraph(this.connectorKey, outputContract); }
  classifyError(error: unknown): ConnectorFailureClassification { const m = error instanceof Error ? error.message : String(error); const lower = m.toLowerCase(); if (lower.includes('auth') || lower.includes('credential')) return { category: 'AUTH', severity: 'HIGH', retryable: false, recommendedAction: 'Refresh credential reference and consent.' }; if (lower.includes('permission') || lower.includes('scope')) return { category: 'PERMISSION', severity: 'HIGH', retryable: false, recommendedAction: 'Grant required read scopes.' }; if (lower.includes('rate')) return { category: 'RATE_LIMIT', severity: 'MEDIUM', retryable: true, recommendedAction: 'Retry using adapter rate limit policy.' }; if (lower.includes('network')) return { category: 'NETWORK', severity: 'MEDIUM', retryable: true, recommendedAction: 'Retry after network recovery.' }; if (lower.includes('schema')) return { category: 'SCHEMA', severity: 'HIGH', retryable: false, recommendedAction: 'Validate payload against output contract.' }; if (lower.includes('data')) return { category: 'DATA_QUALITY', severity: 'MEDIUM', retryable: false, recommendedAction: 'Fix source payload quality.' }; if (lower.includes('config')) return { category: 'CONFIGURATION', severity: 'HIGH', retryable: false, recommendedAction: 'Correct adapter configuration.' }; return { category: 'UNKNOWN', severity: 'LOW', retryable: false, recommendedAction: 'Review adapter diagnostics.' }; }
  getRateLimitPolicy(): ConnectorRateLimitPolicy { const strategy = this.defaults().rate; return { connectorKey: this.connectorKey, strategy, maxRequestsPerMinute: strategy === 'NONE' ? undefined : 60, maxConcurrentRequests: strategy === 'NONE' ? undefined : 4, backoffSeconds: strategy === 'EXPONENTIAL_BACKOFF' ? 30 : undefined, notes: ['Policy is declarative for future live integrations; sample fetch never calls external APIs.'] }; }
}
