export type CrossDomainEntityType = "USER" | "TEAM" | "DEPARTMENT" | "TOOL" | "LICENCE" | "MODEL" | "WORKFLOW";
export type CrossDomainSourceDomain = "M365" | "AI_ECONOMICS" | "CROSS_DOMAIN";
export interface CrossDomainEntityRef { tenantId:string; entityType:CrossDomainEntityType; entityId:string; displayName:string; sourceDomain:CrossDomainSourceDomain; }
export interface CrossDomainUsageSignal { tenantId:string; entityRef:CrossDomainEntityRef; domain:CrossDomainSourceDomain; usageType:string; usageVolume:number; activityRecencyDays:number; evidenceRefs:string[]; confidence:number; }
export interface CrossDomainSpendSignal { tenantId:string; entityRef:CrossDomainEntityRef; domain:CrossDomainSourceDomain; monthlyCost:number; annualizedCost:number; costCategory:string; confidence:number; evidenceRefs:string[]; }
export interface CrossDomainOutcomeSignal { tenantId:string; entityRef:CrossDomainEntityRef; outcomeType:string; projectedValue:number; realizedValue:number; confidence:number; attributionNotes:string; evidenceRefs:string[]; }
export interface CrossDomainGovernanceSignal { tenantId:string; entityRef:CrossDomainEntityRef; riskType:string; severity:"LOW"|"MODERATE"|"HIGH"|"CRITICAL"; confidence:number; evidenceRefs:string[]; }
export interface CrossDomainCorrelationResult { correlationId:string; tenantId:string; involvedEntities:CrossDomainEntityRef[]; correlationType:string; strength:"LOW"|"MODERATE"|"HIGH"; confidence:number; explanation:string; evidenceRefs:string[]; }
export interface CrossDomainDuplicationFinding { findingId:string; tenantId:string; duplicationType:string; involvedTools:string[]; involvedUsersOrTeams:string[]; monthlyCostAtRisk:number; annualizedCostAtRisk:number; confidence:number; severity:"LOW"|"MODERATE"|"HIGH"; recommendedAction:"REVIEW"|"RATIONALIZE"|"SUPPRESS_DUPLICATE_CLAIM"|"ESCALATE_APPROVAL"; evidenceRefs:string[]; }
export interface CrossDomainOutcomeAttributionResult { attributionId:string; tenantId:string; outcomeType:string; involvedDomains:CrossDomainSourceDomain[]; projectedValue:number; realizedValue:number; confidence:number; doubleCountRisk:number; attributionStrength:"WEAK"|"MODERATE"|"STRONG"; explanation:string; evidenceRefs:string[]; }
export interface CrossDomainGovernanceRiskResult { riskId:string; tenantId:string; riskType:string; severity:"LOW"|"MODERATE"|"HIGH"|"CRITICAL"; involvedDomains:CrossDomainSourceDomain[]; involvedEntities:CrossDomainEntityRef[]; governanceImpact:string; recommendedAction:"REVIEW"|"ESCALATE_APPROVAL"|"DEFER"|"BLOCK_RECOMMENDATION"; confidence:number; evidenceRefs:string[]; }
export interface CrossDomainEconomicRecommendation { recommendationId:string; tenantId:string; sourceDomains:CrossDomainSourceDomain[]; decision:"PROMOTED"|"PROMOTED_WITH_APPROVAL"|"SUPPRESSED_DUPLICATE"|"SUPPRESSED_CONFLICT"|"DEFERRED"|"BLOCKED"; priorityBand:"CRITICAL_REVIEW"|"HIGH_VALUE"|"STANDARD"|"WATCHLIST"|"SUPPRESSED"; confidenceScore:number; annualizedSavings:number; productivityOpportunity:number; doubleCountRisk:number; arbitrationReasons:string[]; evidenceRefs:string[]; replayCorrelationId:string; lineageCorrelationId:string; }
export interface CrossDomainEconomicReport { tenantId:string; generatedAt:string; correlationSummary:CrossDomainCorrelationResult[]; duplicationFindings:CrossDomainDuplicationFinding[]; outcomeAttribution:CrossDomainOutcomeAttributionResult[]; governanceRisks:CrossDomainGovernanceRiskResult[]; recommendations:CrossDomainEconomicRecommendation[]; estimatedAnnualSavings:number; estimatedProductivityOpportunity:number; doubleCountRisk:number; readinessStatus:"READY_FOR_CROSS_DOMAIN_PLAYBOOKS"|"READY_WITH_LIMITS"|"HARDENING_REQUIRED"; }
