import { and, eq } from "drizzle-orm";
import { assetOwnersTable, assetsTable, assetSourceMappingsTable, db, evidenceLinksTable, m365EvidenceRecordsTable, m365UsersTable, operationalEntitiesTable, servicenowAssetsTable } from "@workspace/db";
import { PrincipalAuthorityService } from "../principal-authority-service";

export type AssetType = "USER"|"LICENSE"|"APPLICATION"|"SAAS_PRODUCT"|"CLOUD_RESOURCE"|"DATABASE_RESOURCE"|"AI_ASSET"|"CONTRACT"|"VENDOR"|"SERVICE"|"BUSINESS_CAPABILITY"|"UNKNOWN";
export type MappingMethod = "DIRECT_ID"|"EMAIL"|"NAME"|"NORMALIZED_NAME"|"EXTERNAL_REFERENCE"|"HEURISTIC"|"MANUAL"|"UNKNOWN";
export type OwnershipType = "BUSINESS_OWNER"|"TECHNICAL_OWNER"|"FINANCIAL_OWNER"|"APPLICATION_OWNER"|"SERVICE_OWNER"|"DATA_OWNER"|"SYSTEM_OWNER"|"UNKNOWN";

type BackfillResult = { scanned: number; created: number; updated: number; mapped: number; skipped: number; errors: string[] };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const envAllowsMemory = () => ["test", "development"].includes(String(process.env.RUNTIME_ENV ?? process.env.NODE_ENV ?? "development").toLowerCase());
const asDate = (value: unknown) => value instanceof Date ? value : value ? new Date(String(value)) : new Date();
const metadataOf = (value: unknown) => value && typeof value === "object" ? value as Record<string, unknown> : {};

export class AssetRegistryService {
  private static memAssets = new Map<string, any>();
  private static memMappings = new Map<string, any>();
  private static memOwners = new Map<string, any>();

  constructor(private readonly principals = new PrincipalAuthorityService(), private readonly store = db) {}

  normalizeAssetName(input: unknown) {
    return String(input ?? "").trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9@._-]+/g, "-").replace(/^-+|-+$/g, "").replace(/-{2,}/g, "-") || "unknown";
  }

  private memList<T>(map: Map<string, T>, tenantId: string) { return Array.from(map.values()).filter((x: any) => x.tenantId === tenantId); }
  private mappingKey(input: { tenantId: string; sourceSystem: string; sourceEntityType: string; sourceEntityId: string }) { return `${input.tenantId}:${input.sourceSystem}:${input.sourceEntityType}:${input.sourceEntityId}`; }
  private ownerKey(input: { tenantId: string; assetId: string; principalId: string; ownershipType: string }) { return `${input.tenantId}:${input.assetId}:${input.principalId}:${input.ownershipType}`; }

  private async findAsset(input: { tenantId: string; primarySourceSystem?: string | null; primaryExternalId?: string | null; assetType?: string; normalizedName?: string }) {
    if (input.primarySourceSystem && input.primaryExternalId) {
      try { const rows = await this.store.select().from(assetsTable).where(and(eq(assetsTable.tenantId, input.tenantId), eq(assetsTable.primarySourceSystem, input.primarySourceSystem), eq(assetsTable.primaryExternalId, input.primaryExternalId))).limit(1); if (rows[0]) return rows[0]; }
      catch (e) { if (!envAllowsMemory()) throw e; return this.memList(AssetRegistryService.memAssets, input.tenantId).find((a: any) => a.primarySourceSystem === input.primarySourceSystem && a.primaryExternalId === input.primaryExternalId) ?? null; }
    }
    if (input.assetType && input.normalizedName) {
      try { const rows = await this.store.select().from(assetsTable).where(and(eq(assetsTable.tenantId, input.tenantId), eq(assetsTable.assetType, input.assetType), eq(assetsTable.normalizedName, input.normalizedName))).limit(1); return rows[0] ?? null; }
      catch (e) { if (!envAllowsMemory()) throw e; return this.memList(AssetRegistryService.memAssets, input.tenantId).find((a: any) => a.assetType === input.assetType && a.normalizedName === input.normalizedName) ?? null; }
    }
    return null;
  }

  async createOrUpdateAsset(input: { tenantId: string; assetType?: AssetType; displayName?: string; normalizedName?: string; description?: string | null; status?: string; lifecycleState?: string; businessCriticality?: string; sourceOfRecord?: string | null; primarySourceSystem?: string | null; primaryExternalId?: string | null; metadata?: Record<string, unknown>; lastSeenAt?: Date; allowLowerConfidenceOverwrite?: boolean }) {
    const assetType = input.assetType ?? "UNKNOWN";
    const displayName = input.displayName ?? input.primaryExternalId ?? "Unknown asset";
    const normalizedName = input.normalizedName ?? this.normalizeAssetName(displayName);
    const existing = await this.findAsset({ tenantId: input.tenantId, primarySourceSystem: input.primarySourceSystem, primaryExternalId: input.primaryExternalId, assetType, normalizedName });
    const now = new Date();
    if (existing) {
      const row = { ...existing, displayName: existing.lifecycleState === "TRUSTED" && !input.allowLowerConfidenceOverwrite ? existing.displayName : displayName, description: input.description ?? existing.description, status: input.status ?? existing.status, lifecycleState: existing.lifecycleState === "TRUSTED" && !input.allowLowerConfidenceOverwrite ? existing.lifecycleState : (input.lifecycleState ?? existing.lifecycleState), businessCriticality: input.businessCriticality ?? existing.businessCriticality, sourceOfRecord: input.sourceOfRecord ?? existing.sourceOfRecord, primarySourceSystem: input.primarySourceSystem ?? existing.primarySourceSystem, primaryExternalId: input.primaryExternalId ?? existing.primaryExternalId, lastSeenAt: input.lastSeenAt ?? now, updatedAt: now, metadata: { ...metadataOf(existing.metadata), ...metadataOf(input.metadata) } };
      try { const [saved] = await this.store.update(assetsTable).set(row as any).where(eq(assetsTable.id, existing.id)).returning(); return { asset: saved, created: false }; }
      catch (e) { if (!envAllowsMemory()) throw e; AssetRegistryService.memAssets.set(existing.id, row); return { asset: row, created: false }; }
    }
    const row = { id: id("asset"), tenantId: input.tenantId, assetType, displayName, normalizedName, description: input.description ?? null, status: input.status ?? "UNKNOWN", lifecycleState: input.lifecycleState ?? "DISCOVERED", businessCriticality: input.businessCriticality ?? "UNKNOWN", sourceOfRecord: input.sourceOfRecord ?? input.primarySourceSystem ?? null, primarySourceSystem: input.primarySourceSystem ?? null, primaryExternalId: input.primaryExternalId ?? null, createdAt: now, updatedAt: now, lastSeenAt: input.lastSeenAt ?? now, metadata: input.metadata ?? {} };
    try { const [saved] = await this.store.insert(assetsTable).values(row as any).returning(); return { asset: saved, created: true }; }
    catch (e) { if (!envAllowsMemory()) throw e; AssetRegistryService.memAssets.set(row.id, row); return { asset: row, created: true }; }
  }

  async createOrUpdateSourceMapping(input: { tenantId: string; assetId: string; sourceSystem: string; sourceEntityType: string; sourceEntityId: string; externalId?: string | null; sourceUrl?: string | null; confidence?: string | number | null; mappingMethod?: MappingMethod; metadata?: Record<string, unknown>; lastSeenAt?: Date }) {
    const key = this.mappingKey(input); const now = new Date();
    try { const rows = await this.store.select().from(assetSourceMappingsTable).where(and(eq(assetSourceMappingsTable.tenantId, input.tenantId), eq(assetSourceMappingsTable.sourceSystem, input.sourceSystem), eq(assetSourceMappingsTable.sourceEntityType, input.sourceEntityType), eq(assetSourceMappingsTable.sourceEntityId, input.sourceEntityId))).limit(1); const existing = rows[0]; if (existing) { const [saved] = await this.store.update(assetSourceMappingsTable).set({ assetId: input.assetId, externalId: input.externalId ?? existing.externalId, sourceUrl: input.sourceUrl ?? existing.sourceUrl, confidence: input.confidence == null ? existing.confidence : String(input.confidence), mappingMethod: input.mappingMethod ?? existing.mappingMethod, lastSeenAt: input.lastSeenAt ?? now, metadata: { ...metadataOf(existing.metadata), ...metadataOf(input.metadata) } } as any).where(eq(assetSourceMappingsTable.id, existing.id)).returning(); return { mapping: saved, created: false }; } }
    catch (e) { if (!envAllowsMemory()) throw e; const existing = AssetRegistryService.memMappings.get(key); if (existing) { const row = { ...existing, assetId: input.assetId, externalId: input.externalId ?? existing.externalId, confidence: input.confidence == null ? existing.confidence : String(input.confidence), mappingMethod: input.mappingMethod ?? existing.mappingMethod, lastSeenAt: input.lastSeenAt ?? now, metadata: { ...metadataOf(existing.metadata), ...metadataOf(input.metadata) } }; AssetRegistryService.memMappings.set(key, row); return { mapping: row, created: false }; } }
    const row = { id: id("asset-map"), tenantId: input.tenantId, assetId: input.assetId, sourceSystem: input.sourceSystem, sourceEntityType: input.sourceEntityType, sourceEntityId: input.sourceEntityId, externalId: input.externalId ?? null, sourceUrl: input.sourceUrl ?? null, confidence: input.confidence == null ? null : String(input.confidence), mappingMethod: input.mappingMethod ?? "UNKNOWN", firstSeenAt: now, lastSeenAt: input.lastSeenAt ?? now, metadata: input.metadata ?? {} };
    try { const [saved] = await this.store.insert(assetSourceMappingsTable).values(row as any).returning(); return { mapping: saved, created: true }; }
    catch (e) { if (!envAllowsMemory()) throw e; AssetRegistryService.memMappings.set(key, row); return { mapping: row, created: true }; }
  }

  async resolveAsset(input: { tenantId: string; sourceSystem?: string; sourceEntityType?: string; sourceEntityId?: string; externalId?: string; assetType?: AssetType; displayName?: string; email?: string; metadata?: Record<string, unknown> }) {
    if (input.sourceSystem && input.sourceEntityType && input.sourceEntityId) { const found = await this.getAssetBySource(input.tenantId, input.sourceSystem, input.sourceEntityType, input.sourceEntityId); if (found) return found; }
    const displayName = input.displayName ?? input.email ?? input.externalId ?? input.sourceEntityId ?? "Unknown asset";
    const primaryExternalId = input.externalId ?? input.sourceEntityId ?? input.email ?? null;
    const result = await this.createOrUpdateAsset({ tenantId: input.tenantId, assetType: input.assetType ?? (input.email ? "USER" : "UNKNOWN"), displayName, primarySourceSystem: input.sourceSystem ?? null, primaryExternalId, metadata: { ...(input.metadata ?? {}), email: input.email }, lifecycleState: "NORMALIZED" });
    let mapping = null;
    if (input.sourceSystem && input.sourceEntityType && input.sourceEntityId) mapping = (await this.createOrUpdateSourceMapping({ tenantId: input.tenantId, assetId: result.asset.id, sourceSystem: input.sourceSystem, sourceEntityType: input.sourceEntityType, sourceEntityId: input.sourceEntityId, externalId: primaryExternalId, mappingMethod: input.email ? "EMAIL" : "DIRECT_ID", confidence: "0.90", metadata: input.metadata })).mapping;
    return { asset: result.asset, mapping };
  }

  async getAssetById(tenantId: string, assetId: string) { try { const rows = await this.store.select().from(assetsTable).where(and(eq(assetsTable.tenantId, tenantId), eq(assetsTable.id, assetId))).limit(1); return rows[0] ?? null; } catch (e) { if (!envAllowsMemory()) throw e; return AssetRegistryService.memAssets.get(assetId) ?? null; } }
  async getAssetBySource(tenantId: string, sourceSystem: string, sourceEntityType: string, sourceEntityId: string) { try { const rows = await this.store.select().from(assetSourceMappingsTable).where(and(eq(assetSourceMappingsTable.tenantId, tenantId), eq(assetSourceMappingsTable.sourceSystem, sourceSystem), eq(assetSourceMappingsTable.sourceEntityType, sourceEntityType), eq(assetSourceMappingsTable.sourceEntityId, sourceEntityId))).limit(1); const mapping = rows[0]; return mapping ? { asset: await this.getAssetById(tenantId, mapping.assetId), mapping } : null; } catch (e) { if (!envAllowsMemory()) throw e; const mapping = AssetRegistryService.memMappings.get(this.mappingKey({ tenantId, sourceSystem, sourceEntityType, sourceEntityId })); return mapping ? { asset: await this.getAssetById(tenantId, mapping.assetId), mapping } : null; } }
  async listAssets(tenantId: string, filters: { assetType?: string; status?: string } = {}) { try { const rows = await this.store.select().from(assetsTable).where(eq(assetsTable.tenantId, tenantId)); return rows.filter((r: any) => (!filters.assetType || r.assetType === filters.assetType) && (!filters.status || r.status === filters.status)); } catch (e) { if (!envAllowsMemory()) throw e; return this.memList(AssetRegistryService.memAssets, tenantId).filter((r: any) => (!filters.assetType || r.assetType === filters.assetType) && (!filters.status || r.status === filters.status)); } }

  async linkAssetToPrincipalOwner(input: { tenantId: string; assetId: string; ownershipType?: OwnershipType; sourceSystem?: string | null; sourceReference?: string | null; confidence?: string | number | null; status?: string; rawOwner?: Record<string, unknown>; principalId?: string; email?: string | null; externalId?: string | null; displayName?: string | null }) {
    const principal = input.principalId ? await this.principals.getPrincipal(input.tenantId, input.principalId) : await this.principals.resolvePrincipal({ tenantId: input.tenantId, email: input.email ?? (input.rawOwner?.email as string | undefined), externalId: input.externalId ?? (input.rawOwner?.externalId as string | undefined), displayName: input.displayName ?? (input.rawOwner?.displayName as string | undefined) ?? (input.rawOwner?.name as string | undefined), sourceSystem: input.sourceSystem ?? undefined });
    if (!principal) return null;
    const ownershipType = input.ownershipType ?? "UNKNOWN"; const key = this.ownerKey({ tenantId: input.tenantId, assetId: input.assetId, principalId: principal.id, ownershipType }); const now = new Date();
    try { const existingRows = await this.store.select().from(assetOwnersTable).where(and(eq(assetOwnersTable.tenantId, input.tenantId), eq(assetOwnersTable.assetId, input.assetId), eq(assetOwnersTable.principalId, principal.id), eq(assetOwnersTable.ownershipType, ownershipType))).limit(1); if (existingRows[0]) { const [saved] = await this.store.update(assetOwnersTable).set({ sourceSystem: input.sourceSystem ?? existingRows[0].sourceSystem, sourceReference: input.sourceReference ?? existingRows[0].sourceReference, confidence: input.confidence == null ? existingRows[0].confidence : String(input.confidence), status: input.status ?? existingRows[0].status, lastVerifiedAt: now, metadata: { ...metadataOf(existingRows[0].metadata), rawOwner: input.rawOwner ?? {} } } as any).where(eq(assetOwnersTable.id, existingRows[0].id)).returning(); return { owner: saved, principal, created: false }; } }
    catch (e) { if (!envAllowsMemory()) throw e; const existing = AssetRegistryService.memOwners.get(key); if (existing) { const row = { ...existing, lastVerifiedAt: now, metadata: { ...metadataOf(existing.metadata), rawOwner: input.rawOwner ?? {} } }; AssetRegistryService.memOwners.set(key, row); return { owner: row, principal, created: false }; } }
    const row = { id: id("asset-owner"), tenantId: input.tenantId, assetId: input.assetId, principalId: principal.id, ownershipType, sourceSystem: input.sourceSystem ?? null, sourceReference: input.sourceReference ?? null, confidence: input.confidence == null ? null : String(input.confidence), status: input.status ?? "UNVERIFIED", assignedAt: now, lastVerifiedAt: now, metadata: { rawOwner: input.rawOwner ?? {} } };
    try { const [saved] = await this.store.insert(assetOwnersTable).values(row as any).returning(); await this.principals.recordActionEvent({ tenantId: input.tenantId, principalId: principal.id, actionContextType: "ASSET_OWNER", actionContextId: saved.id, role: ownershipType, metadata: { assetId: input.assetId, sourceSystem: input.sourceSystem, rawOwner: input.rawOwner ?? {} } }); return { owner: saved, principal, created: true }; }
    catch (e) { if (!envAllowsMemory()) throw e; AssetRegistryService.memOwners.set(key, row); await this.principals.recordActionEvent({ tenantId: input.tenantId, principalId: principal.id, actionContextType: "ASSET_OWNER", actionContextId: row.id, role: ownershipType, metadata: { assetId: input.assetId, sourceSystem: input.sourceSystem, rawOwner: input.rawOwner ?? {} } }); return { owner: row, principal, created: true }; }
  }

  async getOwnersForAsset(tenantId: string, assetId: string) { try { return await this.store.select().from(assetOwnersTable).where(and(eq(assetOwnersTable.tenantId, tenantId), eq(assetOwnersTable.assetId, assetId))); } catch (e) { if (!envAllowsMemory()) throw e; return this.memList(AssetRegistryService.memOwners, tenantId).filter((o: any) => o.assetId === assetId); } }
  async getAssetsForPrincipal(tenantId: string, principalId: string) { const owners = await this.getAssetOwners(tenantId); const linked = owners.filter((o: any) => o.principalId === principalId); return Promise.all(linked.map((o: any) => this.getAssetById(tenantId, o.assetId))); }
  async getAssetOwners(tenantId: string) { try { return await this.store.select().from(assetOwnersTable).where(eq(assetOwnersTable.tenantId, tenantId)); } catch (e) { if (!envAllowsMemory()) throw e; return this.memList(AssetRegistryService.memOwners, tenantId); } }
  async recordAssetSeen(input: { tenantId: string; assetId: string; seenAt?: Date; metadata?: Record<string, unknown> }) { const asset = await this.getAssetById(input.tenantId, input.assetId); if (!asset) return null; return (await this.createOrUpdateAsset({ ...asset, tenantId: input.tenantId, assetType: asset.assetType, displayName: asset.displayName, primarySourceSystem: asset.primarySourceSystem, primaryExternalId: asset.primaryExternalId, lastSeenAt: input.seenAt ?? new Date(), metadata: { ...metadataOf(asset.metadata), ...metadataOf(input.metadata) } })).asset; }

  async linkEvidenceToAsset(input: { tenantId: string; evidenceItemId: string; assetId: string; relationshipType?: string }) { try { const [row] = await this.store.insert(evidenceLinksTable).values({ id: id("evlink"), tenantId: input.tenantId, evidenceItemId: input.evidenceItemId, linkedEntityType: "ASSET", linkedEntityId: input.assetId, relationshipType: input.relationshipType ?? "RELATES_TO" }).returning(); return row; } catch (e) { if (!envAllowsMemory()) throw e; return { id: id("evlink"), ...input, linkedEntityType: "ASSET", linkedEntityId: input.assetId, relationshipType: input.relationshipType ?? "RELATES_TO" }; } }

  async backfillM365(tenantId: string): Promise<BackfillResult> {
    const result: BackfillResult = { scanned: 0, created: 0, updated: 0, mapped: 0, skipped: 0, errors: [] };
    const users = await this.readRows(m365UsersTable, tenantId); const evidence = await this.readRows(m365EvidenceRecordsTable, tenantId);
    for (const user of users as any[]) {
      result.scanned++;
      try { const r = await this.createOrUpdateAsset({ tenantId, assetType: "USER", displayName: user.displayName ?? user.userPrincipalName, status: String(user.accountEnabled) === "true" ? "ACTIVE" : "INACTIVE", lifecycleState: "NORMALIZED", primarySourceSystem: "M365", primaryExternalId: String(user.sourceObjectId), metadata: { source: "m365_users", userPrincipalName: user.userPrincipalName, raw: user } }); r.created ? result.created++ : result.updated++; const m = await this.createOrUpdateSourceMapping({ tenantId, assetId: r.asset.id, sourceSystem: "M365", sourceEntityType: "m365_users", sourceEntityId: String(user.id ?? user.sourceObjectId), externalId: String(user.sourceObjectId), mappingMethod: "DIRECT_ID", confidence: "0.95", metadata: { userPrincipalName: user.userPrincipalName } }); if (m.created) result.mapped++; for (const sku of Array.isArray(user.assignedLicenses) ? user.assignedLicenses : []) { const lr = await this.createOrUpdateAsset({ tenantId, assetType: "LICENSE", displayName: String(sku), lifecycleState: "NORMALIZED", primarySourceSystem: "M365", primaryExternalId: String(sku), metadata: { assignedTo: user.userPrincipalName } }); lr.created ? result.created++ : result.updated++; const lm = await this.createOrUpdateSourceMapping({ tenantId, assetId: lr.asset.id, sourceSystem: "M365", sourceEntityType: "assigned_license", sourceEntityId: `${user.sourceObjectId}:${sku}`, externalId: String(sku), mappingMethod: "DIRECT_ID", confidence: "0.85", metadata: { userPrincipalName: user.userPrincipalName } }); if (lm.created) result.mapped++; } }
      catch (e) { result.errors.push(String((e as Error).message ?? e)); }
    }
    for (const row of evidence as any[]) {
      result.scanned++;
      try { const r = await this.createOrUpdateAsset({ tenantId, assetType: "USER", displayName: row.displayName ?? row.userId, status: row.accountStatus === "ACTIVE" ? "ACTIVE" : "UNKNOWN", lifecycleState: "NORMALIZED", primarySourceSystem: "M365", primaryExternalId: String(row.userId), metadata: { source: "m365_evidence_records", department: row.department, costCentre: row.costCentre, rawEvidence: row.rawEvidence } }); r.created ? result.created++ : result.updated++; const m = await this.createOrUpdateSourceMapping({ tenantId, assetId: r.asset.id, sourceSystem: "M365", sourceEntityType: "m365_evidence_records", sourceEntityId: String(row.id ?? row.sourceRecordId), externalId: String(row.userId), mappingMethod: "DIRECT_ID", confidence: "0.90", metadata: { sourceRecordId: row.sourceRecordId } }); if (m.created) result.mapped++; for (const sku of Array.isArray(row.assignedLicences) ? row.assignedLicences : []) { const lr = await this.createOrUpdateAsset({ tenantId, assetType: "LICENSE", displayName: String(sku), lifecycleState: "NORMALIZED", primarySourceSystem: "M365", primaryExternalId: String(sku), metadata: { source: "m365_evidence_records" } }); lr.created ? result.created++ : result.updated++; } }
      catch (e) { result.errors.push(String((e as Error).message ?? e)); }
    }
    return result;
  }

  async backfillServiceNow(tenantId: string): Promise<BackfillResult> { const result: BackfillResult = { scanned: 0, created: 0, updated: 0, mapped: 0, skipped: 0, errors: [] }; const rows = await this.readRows(servicenowAssetsTable, tenantId); for (const row of rows as any[]) { result.scanned++; try { const r = await this.createOrUpdateAsset({ tenantId, assetType: row.contractId ? "CONTRACT" : "UNKNOWN", displayName: row.assetTag ?? row.sourceObjectId, primarySourceSystem: "SERVICENOW", primaryExternalId: String(row.sourceObjectId), metadata: { raw: row }, lifecycleState: "NORMALIZED" }); r.created ? result.created++ : result.updated++; const m = await this.createOrUpdateSourceMapping({ tenantId, assetId: r.asset.id, sourceSystem: "SERVICENOW", sourceEntityType: "servicenow_assets", sourceEntityId: String(row.id ?? row.sourceObjectId), externalId: String(row.sourceObjectId), mappingMethod: "DIRECT_ID", confidence: "0.80", metadata: row.sourceMetadata }); if (m.created) result.mapped++; if (row.owner || row.userPrincipalName || row.assignedTo) await this.linkAssetToPrincipalOwner({ tenantId, assetId: r.asset.id, ownershipType: "BUSINESS_OWNER", sourceSystem: "SERVICENOW", sourceReference: String(row.sourceObjectId), email: row.userPrincipalName, displayName: row.owner ?? row.assignedTo, rawOwner: { owner: row.owner, assignedTo: row.assignedTo, userPrincipalName: row.userPrincipalName } }); } catch (e) { result.errors.push(String((e as Error).message ?? e)); } } return result; }
  async backfillOperational(tenantId: string): Promise<BackfillResult> { const result: BackfillResult = { scanned: 0, created: 0, updated: 0, mapped: 0, skipped: 0, errors: [] }; const rows = await this.readRows(operationalEntitiesTable, tenantId); for (const row of rows as any[]) { result.scanned++; try { const r = await this.createOrUpdateAsset({ tenantId, assetType: this.assetTypeFromOperational(row.entityType), displayName: row.canonicalName, primarySourceSystem: row.sourceSystem, primaryExternalId: row.canonicalKey, metadata: { raw: row, sourceReferences: row.sourceReferences }, lifecycleState: "MATCHED" }); r.created ? result.created++ : result.updated++; const m = await this.createOrUpdateSourceMapping({ tenantId, assetId: r.asset.id, sourceSystem: row.sourceSystem, sourceEntityType: "operational_entities", sourceEntityId: String(row.id ?? row.canonicalKey), externalId: row.canonicalKey, mappingMethod: "NORMALIZED_NAME", confidence: String(row.entityConfidenceScore ?? 0), metadata: row.metadata }); if (m.created) result.mapped++; } catch (e) { result.errors.push(String((e as Error).message ?? e)); } } return result; }

  private assetTypeFromOperational(entityType: string): AssetType { const v = String(entityType).toUpperCase(); if (v.includes("USER")) return "USER"; if (v.includes("APP")) return "APPLICATION"; if (v.includes("SERVICE")) return "SERVICE"; return "UNKNOWN"; }
  private async readRows(table: any, tenantId: string) { try { return await this.store.select().from(table).where(eq(table.tenantId, tenantId)); } catch (e) { if (!envAllowsMemory()) throw e; return []; } }
}
