import { FileText } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { WorkspaceModeBanner, EvidenceBadge, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, RiskBadge, StatusBadge } from '../components/executive'
import { useAIGovernanceExposureData } from '../hooks/useAIGovernanceExposureData'
const money=(value?:number)=>typeof value==='number'?`$${Math.round(value).toLocaleString()}`:'—'
const label=(value:string)=>value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,(char)=>char.toUpperCase())
const actionCopy = ['Assign owner', 'Review approval status', 'Apply AI policy', 'Consolidate AI tooling', 'Review code-upload controls', 'Review data-sharing controls']
export default function AIGovernanceExposure(){const{data}=useAIGovernanceExposureData();const dataRisks=data.findings.filter((f)=>f.findingType==='DATA_EXPOSURE_RISK');const codeRisks=data.findings.filter((f)=>f.findingType==='SOURCE_CODE_EXPOSURE_RISK');const duplicate=data.findings.filter((f)=>f.findingType==='DUPLICATE_AI_TOOLING');return <Shell><ExecutivePageShell title='AI Governance' subtitle='Discover AI applications, policy gaps, data exposure risks, source code exposure risks, duplicate AI tooling, and AI spend governance.' badgeLabel='Read-only intelligence' badgeTone='info'>
<div aria-label='Workspace Mode'><WorkspaceModeBanner dataSourceOverride='Sample governance dataset' executionOverride='Execution disabled' /></div>
<div data-testid='ai-governance-kpis' style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><ExecutiveKpiCard label='AI Applications Detected' value={data.summary.aiApplicationsDetected} tone='info'/><ExecutiveKpiCard label='Unapproved AI Apps' value={data.summary.unapprovedAIApps} tone='danger'/><ExecutiveKpiCard label='Policy Gaps' value={data.summary.policyGaps} tone='warning'/><ExecutiveKpiCard label='Governance Exposure Score' value={data.summary.governanceExposureScore} tone='danger'/><ExecutiveKpiCard label='Potential Annual Savings' value={money(data.summary.potentialAnnualSavings)} tone='good'/><ExecutiveKpiCard label='High-Risk Findings' value={data.summary.highRiskFindings} tone='danger'/></div>
<ExecutiveSection testId='ai-inventory' title='AI Application Inventory'><div style={{display:'grid',gridTemplateColumns:'1fr .5fr .7fr 1fr .6fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Application</span><span>Users</span><span>Approved</span><span>Owner</span><span>Risk</span></div>{data.inventory.map((app)=><div key={app.applicationName} style={{display:'grid',gridTemplateColumns:'1fr .5fr .7fr 1fr .6fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><strong>{app.applicationName}</strong><span>{app.usersDetected}</span><StatusBadge status={app.approved?'Approved':'Unapproved'} tone={app.approved?'good':'danger'}/><span>{app.owner??'Owner required'}</span><RiskBadge level={app.riskLevel}/></div>)}</ExecutiveSection>
<ExecutiveSection testId='ai-findings' title='AI Governance Findings'><div style={{display:'grid',gridTemplateColumns:'1.1fr 1fr .6fr .5fr 1.4fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Finding</span><span>Application</span><span>Risk</span><span>Trust</span><span>Recommended Action</span></div>{data.findings.map((f)=><div key={f.id} style={{display:'grid',gridTemplateColumns:'1.1fr 1fr .6fr .5fr 1.4fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><span>{label(f.findingType)}</span><strong>{f.applicationName}</strong><RiskBadge level={f.riskLevel}/><span>{f.trustScore}</span><span>{f.recommendedAction}</span></div>)}</ExecutiveSection>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><ExecutiveSection testId='ai-exposure-risks' title='Data & Code Exposure Risks'><h3>Data Exposure</h3>{dataRisks.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · potential corporate data disclosure.</p>)}<h3>Source Code Exposure</h3>{codeRisks.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · potential code upload or model interaction.</p>)}</ExecutiveSection><ExecutiveSection testId='ai-duplicate' title='Duplicate AI Tooling'>{duplicate.map((f)=><p key={f.id}>ChatGPT · Claude · Copilot · Gemini · {f.recommendedAction}</p>)}</ExecutiveSection><ExecutiveSection testId='ai-policy' title='Policy Coverage'><p>Covered: {data.inventory.filter((app)=>app.policyCoverage).length}</p><p>Missing: {data.inventory.filter((app)=>app.policyCoverage===false).length}</p><p>Needs Review: {data.inventory.filter((app)=>app.policyCoverage===undefined).length}</p></ExecutiveSection><ExecutiveSection testId='ai-actions' title='Governance Actions'>{Array.from(new Set([...actionCopy, ...data.opportunity.recommendedActions])).map((a)=><p key={a}><StatusBadge status={a} tone='info'/></p>)}</ExecutiveSection><ExecutiveSection testId='ai-evidence' title='Evidence Panel' rightSlot={<EvidenceBadge confidence='HIGH'/>}>{data.evidenceRefs.map((ref)=><p key={ref}><FileText size={13}/> {ref}</p>)}</ExecutiveSection></div>
</ExecutivePageShell></Shell>}
