import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useContractIntelligenceData } from '../hooks/useContractIntelligenceData'

function money(value: number) { return value >= 1000000 ? `$${(value / 1000000).toFixed(1)}M` : `$${Math.round(value / 1000)}k` }
function riskStatus(value: string) { return value === 'HIGH' ? 'blocked' : value === 'MEDIUM' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div> }

export default function ContractIntelligenceView() {
  const { data, error, isEmptyLive, refresh } = useContractIntelligenceData()
  return <Shell><div style={{padding:'16px 20px'}}><h1>Contract Intelligence</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>Detect auto-renewal risk, unused commitments, price increase exposure, and renewal leverage in enterprise contracts.</p>{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Contract intelligence not available yet' description='Load contracts, order forms, invoices, and commitments to calculate contract risk.' /> : <>
    <section data-testid='contract-summary' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12}}><Card label='Contracts' value={String(data.summary.contracts)} detail='Contracts evaluated.' /><Card label='At Risk' value={String(data.summary.atRisk)} detail='Contracts requiring review.' /><Card label='Unused Value' value={money(data.summary.unusedValue)} detail='Unused commitment and entitlement value.' /><Card label='Generated Opportunities' value={String(data.summary.generatedOpportunities)} detail='Factory-ready contract opportunities.' /></section>
    <section data-testid='contract-table' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Contract Risk</SectionLabel><div style={{display:'grid',gridTemplateColumns:'1.2fr .8fr .8fr .8fr .7fr .7fr .8fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Contract</span><span>Vendor</span><span>Annual Value</span><span>Unused Value</span><span>Auto Renew</span><span>Risk</span><span>Opportunities</span></div>{data.contracts.map((contract:any)=><div key={contract.id} style={{display:'grid',gridTemplateColumns:'1.2fr .8fr .8fr .8fr .7fr .7fr .8fr',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><span>{contract.contractName}</span><span>{contract.vendor}</span><span>{money(contract.annualValue)}</span><span>{money(contract.unusedValue)}</span><span>{contract.autoRenew ? 'Yes' : 'No'}</span><span><StatusPill status={riskStatus(contract.riskLevel) as any} /> {contract.riskLevel}</span><span>{contract.intelligence?.commitmentExposure ? 'Generate opportunity' : 'Review'}</span></div>)}</section>
  </>}</div></Shell>
}
