import { useState } from 'react'
import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useDataTrustData } from '../hooks/useDataTrustData'
import { useTrustAccountabilityData } from '../hooks/useTrustAccountabilityData'
import { useTrustResolutionTasks } from '../hooks/useTrustResolutionTasks'
import { useWorkspace } from '../lib/workspaceContext'
import { RecommendationExplainabilityDrawer } from '../components/RecommendationExplainabilityDrawer'

function money(value: number) { return `$${Math.round(value).toLocaleString()}` }
function bandStatus(band: string) { return band === 'BLOCKED' ? 'blocked' : band === 'LOW_CONFIDENCE' || band === 'INVESTIGATE' ? 'degraded' : 'ready' }
function slaStatus(status: string) { return status === 'OVERDUE' ? 'blocked' : status === 'AT_RISK' ? 'degraded' : 'ready' }
function bar(score: number) { return <div aria-label={`trust visual indicator ${score}`} style={{height:8,background:'var(--surface-2)',borderRadius:999,overflow:'hidden'}}><div style={{width:`${Math.max(0, Math.min(100, score))}%`,height:'100%',background: score >= 90 ? 'var(--green)' : score >= 75 ? 'var(--teal)' : score >= 60 ? 'var(--amber)' : 'var(--red)'}} /></div> }
function relativeDue(dueAt: string) { const hours = Math.round((new Date(dueAt).getTime() - Date.now()) / 3_600_000); return hours < 0 ? `${Math.abs(hours)}h overdue` : `Due in ${hours}h` }

function TrustCard({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div>
}

export default function DataTrustView() {
  const workspace = useWorkspace()
  const { data, error, isEmptyLive, refresh } = useDataTrustData()
  const tasksState = useTrustResolutionTasks()
  const accountabilityState = useTrustAccountabilityData()
  const [findingId, setFindingId] = useState<string | null>(null)
  const [recommendationId, setRecommendationId] = useState<string | null>(null)
  const totalPotential = data.summary.executionEligibleValue + data.summary.approvalRequiredValue + data.summary.blockedByTrustValue + data.summary.blockedByPolicyValue + data.summary.manualOnlyValue
  const lostOpportunity = data.summary.manualOnlyValue
  const accountability = accountabilityState.accountability
  const rollup = accountability?.rollup ?? { openTasks:0, overdueTasks:0, atRiskTasks:0, resolvedThisMonth:0, blockedValueOverdue:0, highestEscalationLevel:'NONE' }
  const accountableTasks = accountability?.tasks ?? tasksState.tasks

  return <Shell><div style={{padding:'16px 20px'}}><h1>Data Trust</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>Operational trust surface for recommendations, execution readiness, and trapped value.</p><p data-testid='m365-investigate-warning' style={{color:'var(--amber)',fontSize:12}}>Investigate trust is not sufficient for live M365 execution.</p>
    {workspace.mode === 'live' && error && <LiveDataError error={error} onRetry={() => void refresh()} />}
    {workspace.mode === 'live' && isEmptyLive ? <EmptyState title='Data trust not available yet' description='Connect and sync your first data source to calculate trust, readiness, and blocked value.' /> : <>
      <section data-testid='trust-summary-cards' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12}}>
        <div style={{border:'var(--border-teal)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>Global Trust</SectionLabel><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{fontSize:32}}>{data.summary.globalTrustScore}</span><span><StatusPill status={bandStatus(data.summary.globalTrustBand)} /> {data.summary.globalTrustBand}</span></div>{bar(data.summary.globalTrustScore)}<p style={{fontSize:12,color:'var(--text-secondary)'}}>{data.summary.globalTrustReasons?.join('; ') ?? data.summary.globalTrustLabel}</p></div>
        <TrustCard label='Execution Eligible' value={money(data.summary.executionEligibleValue)} detail='Value safe for operator-triggered execution.' />
        <TrustCard label='Blocked By Trust' value={money(data.summary.blockedByTrustValue)} detail='Value waiting on evidence, identity, ownership, or freshness.' />
        <TrustCard label='Trust Issues' value={String(data.summary.trustIssueCount)} detail={`${data.summary.identityConflictCount} identity · ${data.summary.missingOwnerCount} owner · ${data.summary.staleSourceCount} stale`} />
      </section>

      <section data-testid='execution-readiness-breakdown' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Execution Readiness Breakdown</SectionLabel><div style={{display:'grid',gridTemplateColumns:'repeat(5, minmax(0, 1fr))',gap:10,marginTop:10}}>{data.readiness.breakdown.map((b:any)=><TrustCard key={b.category} label={String(b.category).replaceAll('_',' ')} value={money(b.value)} detail={`${b.count} recommendations`} />)}</div></section>

      <section data-testid='connector-trust-grid' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12,marginTop:14}}>{data.connectors.map((c:any)=><div key={c.connectorId} style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{c.connectorName}</SectionLabel><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span><StatusPill status={bandStatus(c.trustBand)} /> {c.trustBand}</span><strong>{c.trustScore}</strong></div>{bar(c.trustScore)}<p style={{fontSize:12,color:'var(--text-secondary)'}}>Last sync {c.lastSyncAt ?? 'unknown'} · {c.freshnessStatus}</p><p style={{fontSize:12}}>Identity issues {c.identityIssues} · Missing ownership {c.missingOwnership} · Stale {c.staleRecords}</p><p style={{fontSize:12}}>Affected value {money(c.affectedValue)}</p></div>)}</section>

      <section data-testid='trust-findings-queue' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Trust Findings Queue</SectionLabel><div style={{display:'grid',gridTemplateColumns:'1.2fr .7fr .7fr .9fr .7fr 1.5fr 160px',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Type</span><span>Severity</span><span>Source</span><span>Affected Value</span><span>Status</span><span>Remediation Hint</span><span>Resolution</span></div>{data.findings.map((f:any)=>{const task=tasksState.tasks.find((t:any)=>t.findingId===f.findingId);return <div key={f.findingId} style={{display:'grid',gridTemplateColumns:'1.2fr .7fr .7fr .9fr .7fr 1.5fr 160px',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><button onClick={()=>{setFindingId(f.findingId); setRecommendationId(null)}} style={{background:'transparent',color:'inherit',textAlign:'left',border:0,padding:0}}>{String(f.findingType).replaceAll('_',' ')}</button><span>{f.severity}</span><span>{f.sourceSystem}</span><span>{money(f.affectedValue)}</span><span>{f.status}</span><span>{f.remediationHint}</span><span>{task ? `${task.status} · ${task.ownerName ?? task.owner}` : <button onClick={()=>void tasksState.createTask(f)}>Create resolution task</button>}</span></div>})}</section>

      <section data-testid='trust-accountability' style={{border:'var(--border-teal)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Trust Accountability</SectionLabel>{accountabilityState.error && workspace.mode==='live' && <LiveDataError error={accountabilityState.error} onRetry={() => void accountabilityState.refresh()} />}<div style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:10,marginTop:10}}><TrustCard label='Open Tasks' value={String(rollup.openTasks)} detail={`${money(rollup.blockedValueOpen ?? 0)} blocked value open.`} /><TrustCard label='Overdue' value={String(rollup.overdueTasks)} detail={`${money(rollup.blockedValueOverdue ?? 0)} blocked value overdue.`} /><TrustCard label='At Risk' value={String(rollup.atRiskTasks)} detail='Tasks inside final SLA window.' /><TrustCard label='Resolved This Month' value={String(rollup.resolvedThisMonth)} detail={`Highest escalation ${rollup.highestEscalationLevel}.`} /></div>
        <div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr .7fr .8fr .8fr .8fr 260px',gap:8,fontSize:12,fontWeight:600,marginTop:14}}><span>Finding</span><span>Owner</span><span>SLA Status</span><span>Due</span><span>Unlock Value</span><span>Escalation</span><span>Actions</span></div>{accountableTasks.map((task:any)=><div key={task.taskId} style={{display:'grid',gridTemplateColumns:'1.2fr 1fr .7fr .8fr .8fr .8fr 260px',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><span>{task.title}</span><span><StatusPill status={task.ownerName || task.owner ? 'ready' : 'degraded'} /> {task.ownerName ?? task.owner ?? 'Unassigned'}</span><span><StatusPill status={slaStatus(task.slaStatus)} /> {task.slaStatus}</span><span>{relativeDue(task.dueAt)}</span><span>{money(task.unlockValue)}</span><span>{task.escalationLevel}</span><span style={{display:'flex',gap:4,flexWrap:'wrap'}}><button onClick={()=>void accountabilityState.assignTask(task.taskId,{ ownerId:'iam-team', ownerName:'IAM Team', ownerType:'TEAM' })}>Assign owner</button><button onClick={()=>void accountabilityState.escalateTask(task.taskId,'Operator escalation')}>Escalate</button><button onClick={()=>void tasksState.setStatus(task.taskId,'IN_PROGRESS')}>Mark in progress</button><button onClick={()=>void tasksState.setStatus(task.taskId,'RESOLVED')}>Mark resolved</button></span></div>)}</section>

      <section data-testid='resolution-tasks-panel' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Resolution Tasks</SectionLabel>{tasksState.error && workspace.mode==='live' && <LiveDataError error={tasksState.error} onRetry={() => void tasksState.refresh()} />}{tasksState.tasks.length===0?<p style={{fontSize:12,color:'var(--text-secondary)'}}>No resolution tasks yet.</p>:tasksState.tasks.map((task:any)=><div key={task.taskId} style={{display:'grid',gridTemplateColumns:'1.4fr .8fr .7fr .8fr .9fr 170px',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><span>{task.title}</span><span>{task.ownerName ?? task.owner}</span><span>{task.priority}</span><span>{task.status}</span><span>{money(task.unlockValue)}</span><span style={{display:'flex',gap:4}}><button onClick={()=>void tasksState.setStatus(task.taskId,'IN_PROGRESS')}>Mark in progress</button><button onClick={()=>void tasksState.setStatus(task.taskId,'RESOLVED')}>Mark resolved</button></span></div>)}</section>

      <section data-testid='trust-impact-panel' style={{border:'var(--border-teal)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Trust Impact</SectionLabel><div style={{display:'grid',gridTemplateColumns:'repeat(5, minmax(0, 1fr))',gap:10,marginTop:10}}><TrustCard label='Potential Savings' value={money(totalPotential)} detail='Total value observed.' /><TrustCard label='Execution Eligible' value={money(data.summary.executionEligibleValue)} detail='Ready now.' /><TrustCard label='Blocked By Trust' value={money(data.summary.blockedByTrustValue)} detail='Resolve evidence gaps.' /><TrustCard label='Blocked By Policy' value={money(data.summary.blockedByPolicyValue)} detail='Governance exception or policy change.' /><TrustCard label='Lost / Deferred Opportunity' value={money(lostOpportunity)} detail='Manual-only value.' /></div></section>
    </>}
  <RecommendationExplainabilityDrawer findingId={findingId} recommendationId={recommendationId} onSelectRecommendation={(id)=>setRecommendationId(id)} onClose={()=>{setFindingId(null); setRecommendationId(null)}} />
  </div></Shell>
}
