import { useState } from 'react'
import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useExecutivePrioritiesData } from '../hooks/useExecutivePrioritiesData'
import { DataStateBanner } from '../components/shared/DataStateBanner'

function money(value: number) { return value >= 1000000 ? `$${(value / 1000000).toFixed(1)}M` : `$${Math.round(value / 1000)}k` }
function pill(value: string) { return value === 'CRITICAL' || value === 'BLOCKED' ? 'blocked' : value === 'HIGH' || value === 'APPROVAL_REQUIRED' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div> }

export default function ExecutivePrioritiesView() {
  const { summary, topPriorities, priorities, error, isEmptyLive, dataState, refresh } = useExecutivePrioritiesData()
  const [expanded, setExpanded] = useState<string | null>(null)
  return <Shell><div style={{padding:'16px 20px'}}><h1>Executive Priorities</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>If you only do 5 things this month, prioritize the opportunities with the best value, trust, readiness, effort, and strategic fit.</p>{dataState !== 'LIVE' && <DataStateBanner state={dataState} ctaLabel={dataState === 'NOT_CONNECTED' ? 'Connect Tenant' : undefined} ctaHref={dataState === 'NOT_CONNECTED' ? '/connectors' : undefined} />}{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Executive priorities not available yet' description='Generate opportunities before calculating executive priorities.' /> : <>
    <section data-testid='executive-summary-cards' style={{display:'grid',gridTemplateColumns:'repeat(5, minmax(0, 1fr))',gap:12}}><Card label='Top 5 Monthly Savings' value={money(summary.topFiveMonthlySavings)} detail='Estimated monthly impact.' /><Card label='Top 5 Annual Savings' value={money(summary.topFiveAnnualSavings)} detail='Annualized executive value.' /><Card label='Ready Now' value={String(summary.readyNowCount)} detail='No approval blocker.' /><Card label='Approval Required' value={String(summary.approvalRequiredCount)} detail='Governance action needed.' /><Card label='Blocked' value={String(summary.blockedCount)} detail='Resolve blockers first.' /></section>
    <section data-testid='executive-brief-card' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Executive Brief</SectionLabel><h3>If you only execute the top 5 opportunities this month…</h3><p>{summary.summaryNarrative}</p><div style={{display:'flex',gap:12,fontSize:12}}><span>Confidence <StatusPill status={pill(summary.confidenceBand) as any} /> {summary.confidenceBand}</span><span>Execution readiness {summary.executionReadinessPercent}%</span><span>Top opportunity {summary.topOpportunityTitle}</span></div></section>
    <section data-testid='executive-priorities-table' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Top Priorities</SectionLabel><div style={{display:'grid',gridTemplateColumns:'50px 1.3fr .7fr .7fr .7fr .6fr .8fr .9fr .7fr 1fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Rank</span><span>Opportunity</span><span>Source</span><span>Domain</span><span>Monthly Value</span><span>Trust</span><span>Confidence</span><span>Readiness</span><span>Priority</span><span>Next Action</span></div>{topPriorities.map((priority:any)=><div key={priority.priorityId}><button onClick={()=>setExpanded(expanded===priority.priorityId?null:priority.priorityId)} style={{display:'grid',gridTemplateColumns:'50px 1.3fr .7fr .7fr .7fr .6fr .8fr .9fr .7fr 1fr',gap:8,width:'100%',padding:'8px 0',border:0,borderTop:'var(--border-default)',background:'transparent',color:'inherit',textAlign:'left',fontSize:12,alignItems:'center'}}><strong>#{priority.priorityRank}</strong><span>{priority.title}</span><span>{priority.source}</span><span>{priority.domain}</span><span>{money(priority.projectedMonthlySavings)}</span><span>{priority.trustScore}</span><span><StatusPill status={pill(priority.confidenceScore >= 80 ? 'HIGH' : 'MEDIUM') as any} /> {priority.confidenceScore >= 80 ? 'HIGH' : 'MEDIUM'}</span><span><StatusPill status={pill(priority.readiness) as any} /> {priority.readiness}</span><span><StatusPill status={pill(priority.priorityBand) as any} /> {priority.priorityBand}</span><span>{priority.recommendedNextAction}</span></button>{expanded===priority.priorityId && <div data-testid='priority-rationale' style={{padding:10,borderTop:'var(--border-subtle)',fontSize:12,color:'var(--text-secondary)'}}><div>Rationale: {priority.rationale.join(' · ')}</div><div>Execution ease: {priority.executionEase} · Time to realize: {priority.timeToRealize} · Strategic importance: {priority.strategicImportance}</div><div>Recommended next action: {priority.recommendedNextAction}</div></div>}</div>)}</section>
    <p style={{fontSize:12,color:'var(--text-tertiary)'}}>{priorities.length} total opportunities scored. No execute or approve actions are available on this read-only surface.</p>
  </>}</div></Shell>
}
