import { Shell } from '../components/layout/Shell'
import { LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useM365OnboardingData } from '../hooks/useM365OnboardingData'
import { useWorkspace } from '../lib/workspaceContext'

function statusFor(state: string) { return state === 'PASSED' || state === 'READY_FOR_PILOT' || state === 'COMPLETE' ? 'ready' : state === 'WARNING' ? 'degraded' : state === 'BLOCKED' ? 'blocked' : 'pending' }
function money(value: number) { return `$${Math.round(Number(value ?? 0)).toLocaleString()}` }
function List({ items }: { items?: string[] }) { return <>{(items ?? []).map((item) => <div key={item} style={{ fontSize: 12, color: 'var(--text-secondary)' }}>• {item}</div>)}</> }

export default function M365OnboardingView() {
  const workspace = useWorkspace()
  const { onboarding, checklist, summary, loading, error, start, runReadiness, runDiscovery, runTrust, runOpportunities, setPilotMode, refresh } = useM365OnboardingData()
  if (error) return <Shell><LiveDataError error={error} onRetry={refresh} /></Shell>
  const trust = onboarding.trust ?? {}
  const readiness = onboarding.readiness ?? {}
  const discovery = onboarding.discovery ?? {}
  const opp = onboarding.opportunityAssessment ?? {}
  const controlledReady = checklist?.summary?.readiness === 'CONTROLLED_EXECUTION_READY'
  return <Shell><div style={{ padding: 20, display: 'grid', gap: 16 }}>
    <header><SectionLabel>Tenant onboarding</SectionLabel><h1>Microsoft 365 Onboarding</h1><div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><StatusPill status={statusFor(onboarding.status)} /> <span>{onboarding.status}</span><span> Pilot mode: {onboarding.pilotMode}</span><span>Tenant: {workspace.tenantName}</span></div></header>
    <section data-testid='m365-onboarding-stepper' style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10 }}>{(onboarding.steps ?? []).map((step: any) => <div key={step.stepId} style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><strong>{step.label}</strong><div><StatusPill status={statusFor(step.state)} /> {step.state}</div><p style={{ fontSize: 12 }}>{step.summary}</p><List items={step.blockers} /><List items={step.warnings} />{step.stepId === 'READINESS_CHECK' && <button disabled={loading} onClick={() => void runReadiness()}>Check readiness</button>}{step.stepId === 'DISCOVERY' && <button disabled={loading} onClick={() => void runDiscovery()}>Run discovery</button>}{step.stepId === 'TRUST_ASSESSMENT' && <button disabled={loading} onClick={() => void runTrust()}>Run trust assessment</button>}{step.stepId === 'OPPORTUNITY_ASSESSMENT' && <button disabled={loading} onClick={() => void runOpportunities()}>Run opportunity assessment</button>}</div>)}</section>
    <div style={{ display: 'flex', gap: 8 }}><button disabled={loading} onClick={() => void start()}>Start onboarding</button><a href='/evidence-packs'>Generate Tenant Evidence Pack</a><a href='/evidence-packs'>Generate Pilot Evidence Pack</a><a href='/overview'>Executive Value Dashboard</a><button disabled={loading} onClick={() => void runReadiness()}>Check readiness</button><button disabled={loading} onClick={() => void runDiscovery()}>Run discovery</button><button disabled={loading} onClick={() => void runTrust()}>Run trust assessment</button><button disabled={loading} onClick={() => void runOpportunities()}>Run opportunity assessment</button></div>
    <section data-testid='m365-readiness-panel' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Readiness Panel</SectionLabel><div>Read Ready: {String(readiness.readReady)}</div><div>Write Ready: {String(readiness.writeReady)}</div><div>Graph Reachable: {String(readiness.graphReachable)}</div><div>Permissions: {(readiness.permissions ?? readiness.requiredReadPermissions ?? []).length}</div><List items={readiness.blockers} /><List items={readiness.warnings} /></section>
    <section data-testid='m365-discovery-panel' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Discovery Panel</SectionLabel><div>users {discovery.counts?.users ?? 0}</div><div>licenses {discovery.counts?.skus ?? discovery.counts?.licenses ?? 0}</div><div>usage records {discovery.counts?.usageRecords ?? 0}</div><div>mailboxes {discovery.counts?.mailboxes ?? 0}</div><div>groups {discovery.counts?.groups ?? 0}</div><div>last snapshot {discovery.snapshotId ?? 'none'}</div></section>
    <section data-testid='m365-trust-panel' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Trust Panel</SectionLabel>{['identityTrust','licenseTrust','usageTrust','activityTrust','mailboxTrust','executionSafetyTrust'].map((key) => <div key={key}>{key}: {trust[key]?.band ?? 'UNKNOWN'}</div>)}</section>
    <section data-testid='m365-opportunity-panel' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Opportunity Panel</SectionLabel><div>candidates found {opp.candidates ?? 0}</div><div>opportunities generated {opp.opportunitiesGenerated ?? 0}</div><div>ready for approval {opp.readyForApproval ?? 0}</div><div>review required {opp.reviewRequired ?? 0}</div><div>blocked {opp.blocked ?? 0}</div><div>projected savings {money(opp.projectedMonthlySavings ?? 0)}</div></section>
    <section data-testid='m365-pilot-selector' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Pilot Mode Selector</SectionLabel>{(['READ_ONLY','DRY_RUN','CONTROLLED_EXECUTION'] as const).map((mode) => <button key={mode} disabled={loading || (mode === 'CONTROLLED_EXECUTION' && !controlledReady)} onClick={() => void setPilotMode(mode)}>{mode}</button>)}{!controlledReady && <div>Controlled execution blocked until checklist supports it.</div>}</section>
    <section data-testid='m365-go-live-checklist' style={{ border: 'var(--border-default)', borderRadius: 10, padding: 12 }}><SectionLabel>Go-Live Checklist</SectionLabel><div>Readiness summary: {checklist?.summary?.readiness ?? summary?.checklist?.readiness}</div><div>Blockers: {checklist?.summary?.blocked ?? 0}</div><div>Warnings: {checklist?.summary?.warning ?? 0}</div>{(checklist?.items ?? []).map((item: any) => <div key={item.id} style={{ display: 'grid', gridTemplateColumns: '1fr 120px 2fr', gap: 8, padding: '6px 0', borderTop: 'var(--border-subtle)' }}><span>{item.label}</span><span>{item.status}</span><span>{item.reason}</span></div>)}</section>
  </div></Shell>
}
