import { useState } from 'react'
import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useOpportunitiesData } from '../hooks/useOpportunitiesData'

function money(value: number) { return `$${Math.round(value).toLocaleString()}` }
function statusFor(value: string) { return value === 'CRITICAL' || value === 'BLOCKED' ? 'blocked' : value === 'HIGH' || value === 'APPROVAL_REQUIRED' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div> }

export default function OpportunitiesView() {
  const { data, error, isEmptyLive, refresh } = useOpportunitiesData()
  const [expanded, setExpanded] = useState<string | null>(null)
  return <Shell><div style={{padding:'16px 20px'}}><h1>Opportunities</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>Canonical Opportunity Factory output across trust, vendor change, drift, utilization, renewals, benchmarks and contracts.</p>{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Opportunities not available yet' description='Connect and sync sources to calculate canonical opportunities.' /> : <>
    <section data-testid='opportunity-summary' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12}}><Card label='Open Opportunities' value={String(data.summary.openOpportunities)} detail='Canonical opportunities available.' /><Card label='Projected Savings' value={money(data.summary.projectedSavings)} detail='Monthly savings potential.' /><Card label='Critical' value={String(data.summary.critical)} detail='Highest urgency or priority.' /><Card label='Eligible' value={String(data.summary.eligible)} detail='Ready for governed recommendation.' /></section>
    <section data-testid='opportunities-table' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Ranked Opportunity List</SectionLabel><div style={{display:'grid',gridTemplateColumns:'1.5fr .8fr .8fr 1fr .6fr .7fr .7fr .9fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Title</span><span>Source</span><span>Domain</span><span>Projected Savings</span><span>Trust</span><span>Confidence</span><span>Priority</span><span>Readiness</span></div>{data.opportunities.map((opp:any)=><div key={opp.id}><button onClick={()=>setExpanded(expanded===opp.id?null:opp.id)} style={{display:'grid',gridTemplateColumns:'1.5fr .8fr .8fr 1fr .6fr .7fr .7fr .9fr',gap:8,width:'100%',padding:'8px 0',border:0,borderTop:'var(--border-default)',background:'transparent',color:'inherit',fontSize:12,textAlign:'left',alignItems:'center'}}><span>#{opp.rank} {opp.title}</span><span><StatusPill status={statusFor(opp.source) as any} /> {opp.source}</span><span>{opp.domain}</span><span>{money(opp.projectedMonthlySavings)}</span><span>{opp.trustScore}</span><span>{opp.confidenceScore}</span><span><StatusPill status={statusFor(opp.priorityBand) as any} /> {opp.priorityBand}</span><span>{opp.readiness}</span></button>{expanded===opp.id && <div data-testid='opportunity-detail' style={{padding:10,borderTop:'var(--border-subtle)',fontSize:12,color:'var(--text-secondary)'}}>{opp.description}<br/>Source reference: {opp.sourceReferenceId} · Score {opp.score}</div>}</div>)}</section>
  </>}</div></Shell>
}
