import { useMemo, useState } from 'react'
import { Link } from 'wouter'
import { Shell } from '../components/layout/Shell'
import { EmptyState, MetricCard, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { DataStateBanner } from '../components/shared/DataStateBanner'
import { demoRemediations, useOutcomeProtectionData, type ProtectedOutcome, type ProtectedOutcomeDetail } from '../hooks/useOutcomeProtectionData'
import { DecisionContext } from '../components/shared/DecisionContext'
import { WorkflowContext } from '../components/shared/WorkflowContext'
import { AIValueAttributionContext } from '../components/shared/AIValueAttributionContext'
import { AIEconomicsContext } from '../components/shared/AIEconomicsContext'
import { AIInitiativeContext } from '../components/shared/AIInitiativeContext'
import { AICapitalAllocationContext } from '../components/shared/AICapitalAllocationContext'
import { ValueRealisationContext } from '../components/shared/ValueRealisationContext'

function money(value?: number) { const amount = value ?? 0; return amount >= 1000 ? `$${Math.round(amount / 1000)}k` : `$${amount.toLocaleString()}` }
function pill(value: string) { const raw = value.toLowerCase().replace(/_/g, '-'); if (raw === 'protected' || raw === 'resolved') return 'verified'; if (raw === 'at-risk') return 'approval-required'; if (raw === 'drifted' || raw === 'remediation-open') return 'blocked'; return 'pending' }
function Field({ label, value }: { label: string; value?: string | number }) { return <div><div style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-label)', letterSpacing: '.05em' }}>{label}</div><div style={{ fontSize: 12, marginTop: 3 }}>{value ?? '—'}</div></div> }
function narrative(d: ReturnType<typeof useOutcomeProtectionData>['dashboard']) { return `Certen is currently protecting ${money(d.protectedAnnualValue)} of annualized verified value. ${d.retentionRate}% of protected value remains retained. ${money(d.driftedAnnualValue)} has drifted and requires remediation. ${d.remediationOpen} remediation actions are currently open. ${d.upcomingChecks.length} retention checks are scheduled this week.` }
function recoveredValue(outcomes: ProtectedOutcome[]) { return outcomes.filter((o) => o.status === 'RESOLVED').reduce((sum, outcome) => sum + (outcome.protectedAnnualValue ?? 0), 0) }
function openFindings(detailMap: Record<string, ProtectedOutcomeDetail>, dashboard: ReturnType<typeof useOutcomeProtectionData>['dashboard']) { const detailed = Object.values(detailMap).flatMap((detail) => detail.findings); return (detailed.length ? detailed : dashboard.openDriftFindings).filter((f) => ['OPEN', 'ACKNOWLEDGED', 'REMEDIATION_CREATED'].includes(f.status)).slice(0, 10) }
function remediations(detailMap: Record<string, ProtectedOutcomeDetail>) { const detailed = Object.values(detailMap).flatMap((detail) => detail.remediations); return detailed.length ? detailed : demoRemediations }

function DetailDrawer({ detail }: { detail: ProtectedOutcomeDetail }) { const o = detail.outcome; const rate = Math.round(((o.retainedAnnualValue ?? 0) / Math.max(o.protectedAnnualValue ?? 1, 1)) * 100); return <section data-testid='outcome-protection-detail' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14, display: 'grid', gap: 14 }}><SectionLabel>Protected Outcome Detail Drawer</SectionLabel>{detail.dataState !== 'LIVE' && detail.dataState !== 'DEMO' && <div role='status' data-testid='outcome-detail-data-state'>{detail.dataState === 'NOT_CONNECTED' ? 'Connector not configured for this outcome detail.' : 'No detail data found.'}{detail.error ? ` (${detail.error})` : ''}</div>}<div><SectionLabel>Value Realisation</SectionLabel><ValueRealisationContext sourceSystem='RECOMMENDATION_APPROVAL' sourceReference={o.actionId} /></div><div><SectionLabel>Decision</SectionLabel><DecisionContext sourceSystem='RECOMMENDATION_APPROVAL' sourceReference={o.actionId} /></div><div><SectionLabel>Workflow</SectionLabel><WorkflowContext sourceSystem='RECOMMENDATION_APPROVAL' sourceReference={o.actionId} /></div><div><SectionLabel>AI Value Attribution</SectionLabel><AIValueAttributionContext sourceSystem='RECOMMENDATION_APPROVAL' sourceReference={o.actionId} /></div><div><SectionLabel>AI Economics</SectionLabel><AIEconomicsContext workflowId={o.actionId} /></div><div><SectionLabel>AI Initiative Portfolio</SectionLabel><AIInitiativeContext workflowId={o.actionId} /><AICapitalAllocationContext workflowId={o.actionId} /></div><SectionLabel>Outcome Summary</SectionLabel><div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12 }}><Field label='Protected Value' value={money(o.protectedAnnualValue)} /><Field label='Retained Value' value={money(o.retainedAnnualValue)} /><Field label='Drifted Value' value={money(o.driftedAnnualValue)} /><Field label='Retention Rate' value={`${rate}%`} /><Field label='Status' value={o.status} /></div><div><SectionLabel>Policies</SectionLabel>{detail.policies.length === 0 ? <p>No policies linked.</p> : detail.policies.map((p) => <p key={p.id}>{p.name} · {p.policyType} · {p.checkFrequency} · Enabled: {String(p.enabled)}</p>)}</div><div><SectionLabel>Drift Findings</SectionLabel>{detail.findings.length === 0 ? <p>No drift findings.</p> : detail.findings.map((f) => <p key={f.id}>{f.severity} · {f.driftType} · Leakage {money(f.estimatedAnnualLeakage)} · {f.reason} · Resolution: {f.status}</p>)}</div><div><SectionLabel>Retention History</SectionLabel>{detail.retentionChecks.map((c) => <p key={c.id}>{c.checkedAt} · {c.result} · Retained {money(c.retainedAnnualValue)} · Drifted {money(c.driftedAnnualValue)}</p>)}</div><div><SectionLabel>Evidence</SectionLabel><Field label='Evidence Count' value={o.evidenceIds.length} /><Field label='Evidence IDs' value={o.evidenceIds.join(', ') || '—'} /></div></section> }

export default function OutcomeProtectionView() { const { dashboard, outcomes, isDemo, dataState, error, loading, fetchOutcomeDetail } = useOutcomeProtectionData(); const [expandedId, setExpandedId] = useState<string | null>(null); const [details, setDetails] = useState<Record<string, ProtectedOutcomeDetail>>({}); const findings = useMemo(() => openFindings(details, dashboard), [details, dashboard]); const queue = useMemo(() => remediations(details), [details])
  const expand = async (outcome: ProtectedOutcome) => { const next = expandedId === outcome.id ? null : outcome.id; setExpandedId(next); if (next && !details[outcome.id]) { const detail = await fetchOutcomeDetail(outcome.id); setDetails((current) => ({ ...current, [outcome.id]: detail })) } }
  return <Shell><div style={{ padding: 24, display: 'grid', gap: 18 }}><header><h1 style={{ margin: 0 }}>Outcome Protection</h1><p style={{ color: 'var(--text-secondary)', marginTop: 6 }}>Protect verified outcomes, detect drift, track retained value, and manage remediation actions.</p></header>{dataState !== 'LIVE' && <DataStateBanner state={dataState} ctaLabel={dataState === 'NOT_CONNECTED' ? 'Connect Tenant' : undefined} ctaHref={dataState === 'NOT_CONNECTED' ? '/connectors' : undefined} />}{error && dataState !== 'NOT_CONNECTED' && <div role='alert'>Outcome protection data is unavailable: {error}</div>}{loading && <div role='status'>Loading outcome protection data…</div>}
    <section data-testid='outcome-protection-summary' style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 10 }}><MetricCard label='Protected Outcomes' value={String(dashboard.protectedOutcomes)} /><MetricCard label='Retained Outcomes' value={String(dashboard.retainedOutcomes)} /><MetricCard label='At-Risk Outcomes' value={String(dashboard.atRiskOutcomes)} /><MetricCard label='Drifted Outcomes' value={String(dashboard.driftedOutcomes)} /><MetricCard label='Open Remediations' value={String(dashboard.remediationOpen)} /><MetricCard label='Retention Rate' value={`${dashboard.retentionRate}%`} /></section>
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10 }}><MetricCard label='Protected Annual Value' value={money(dashboard.protectedAnnualValue)} hero /><MetricCard label='Retained Annual Value' value={money(dashboard.retainedAnnualValue)} hero /><MetricCard label='Drifted Annual Value' value={money(dashboard.driftedAnnualValue)} hero /></section>
    <section data-testid='protected-value-funnel' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14 }}><SectionLabel>Protected Value Funnel</SectionLabel><div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 10 }}><Field label='Verified Value' value={money(dashboard.protectedAnnualValue)} /><Field label='Protected Value' value={money(dashboard.protectedAnnualValue)} /><Field label='Retained Value' value={money(dashboard.retainedAnnualValue)} /><Field label='Drifted Value' value={money(dashboard.driftedAnnualValue)} /><Field label='Recovered Value' value={money(recoveredValue(outcomes))} /></div></section>
    <section style={{ border: 'var(--border-default)', borderRadius: 12, padding: 14 }}><SectionLabel>Executive Narrative</SectionLabel><p>{narrative(dashboard)}</p></section>
    <section><SectionLabel>Protected Outcomes</SectionLabel><div style={{ display: 'grid', gridTemplateColumns: '1.8fr .8fr .8fr repeat(6, 1fr)', gap: 8, fontSize: 11, color: 'var(--text-secondary)', padding: 8 }}><span>Name</span><span>Domain</span><span>Status</span><span>Protected Value</span><span>Retained Value</span><span>Drifted Value</span><span>Protection Start</span><span>Last Check</span><span>Next Check · Open Findings</span></div><div data-testid='protected-outcomes-table' style={{ display: 'grid', gap: 8 }}>{outcomes.length === 0 ? <EmptyState title='No protected outcomes yet.' description='Verified outcomes will appear here once protection starts.' /> : outcomes.map((o) => <button key={o.id} onClick={() => void expand(o)} style={{ display: 'grid', gridTemplateColumns: '1.8fr .8fr .8fr repeat(6, 1fr)', gap: 8, textAlign: 'left', border: 'var(--border-default)', borderRadius: 10, padding: 10, background: 'var(--bg-card)', color: 'inherit' }}><span>{o.name}</span><span>{o.assetType ?? o.valueType}</span><StatusPill status={pill(o.status) as any} /><span>{money(o.protectedAnnualValue)}</span><span>{money(o.retainedAnnualValue)}</span><span>{money(o.driftedAnnualValue)}</span><span>{o.protectionStart}</span><span>{o.lastCheckedAt ?? '—'}</span><span>{o.nextCheckAt ?? '—'} · Open Findings {o.driftFindingIds.length}</span></button>)}</div></section>
    {expandedId && details[expandedId] && <DetailDrawer detail={details[expandedId]} />}
    <section data-testid='open-drift-findings'><SectionLabel>Open Drift Findings</SectionLabel>{findings.map((f) => <div key={f.id} style={{ display: 'grid', gridTemplateColumns: '.7fr 1fr 1fr 2fr 2fr .8fr', gap: 8, padding: 8, borderBottom: 'var(--border-subtle)' }}><span>{f.severity}</span><span>{f.driftType}</span><span>{money(f.estimatedMonthlyLeakage)}/month</span><span>{f.reason}</span><span>{f.recommendedAction}</span><span>{f.status}</span></div>)}</section>
    <section data-testid='remediation-queue'><SectionLabel>Remediation Queue</SectionLabel>{queue.map((r) => <div key={r.id} style={{ display: 'grid', gridTemplateColumns: '2fr 1.4fr .8fr 1fr .8fr 1fr', gap: 8, padding: 8, borderBottom: 'var(--border-subtle)' }}><span>{r.description}</span><span>{r.actionType}</span><span>{r.status}</span><span>{r.governedActionId ? <Link href={`/actions`}>Open Governed Action</Link> : '—'}</span><span>{r.actionType === 'CREATE_NEW_GOVERNED_ACTION' ? 'HIGH' : 'MEDIUM'}</span><span>{r.createdAt}</span></div>)}</section>
    <section data-testid='upcoming-retention-checks'><SectionLabel>Upcoming Retention Checks</SectionLabel>{dashboard.upcomingChecks.map((o) => <div key={o.id} style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', gap: 8, padding: 8, borderBottom: 'var(--border-subtle)' }}><span>{o.name}</span><span>{o.nextCheckAt}</span><span>{money(o.protectedAnnualValue)}</span><span>{o.status}</span></div>)}</section>
    <footer style={{ display: 'flex', gap: 12 }}><Link href='/actions'>Open Action Center</Link><Link href='/executive-value'>Open Executive Value</Link><Link href='/evidence'>Open Evidence</Link><Link href='/outcomes'>Open Outcome</Link><Link href='/actions'>Open Governed Action</Link></footer>
  </div></Shell> }
