import React, { useState } from 'react'
import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useOutcomesData } from '../hooks/useOutcomesData'

function money(value: number | null | undefined) { return value == null ? '—' : `$${Math.round(value).toLocaleString()}` }
function statusPill(status: string) { const s = String(status).toUpperCase(); return s.includes('FAILED') || s.includes('DISPUTED') ? 'blocked' : s.includes('VERIFIED') ? 'verified' : s.includes('PROGRESS') ? 'testing' : 'pending' }

export default function OutcomeLedgerView(){
 const {data,isEmptyLive,error,refresh}=useOutcomesData(); const [evidenceId,setEvidenceId]=useState<string|null>(null); if(error) return <Shell><LiveDataError error={error} onRetry={refresh} /></Shell>
 if(isEmptyLive) return <Shell><EmptyState title='No verified savings yet' description='Outcomes will appear here as actions are executed and savings are evidence-verified.' /></Shell>
 const [projected,verified,variance,pending,failed,drift]=data.stats; const selected=data.ledger.find((item:any)=>item.id===evidenceId)
 return <Shell><div style={{padding:20}}><h1>Outcomes</h1><div>{money(projected)} projected | {money(verified)} verified | {money(variance)} variance <span title='Difference between projected and evidence-verified savings. This gap closes as actions complete verification cycles. Normal for early-stage execution.'>ⓘ</span></div><div>{pending} pending verification | {failed} failed | {drift} drift detected</div>
  <section style={{border:'var(--border-default)',borderRadius:10,padding:12,marginTop:14}}><SectionLabel>Outcome Ledger</SectionLabel><div style={{display:'grid',gridTemplateColumns:'1.3fr .7fr .7fr .7fr .7fr .7fr .7fr .7fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Outcome</span><span>Projected</span><span>Verified</span><span>Variance</span><span>Confidence</span><span>Evidence</span><span>Status</span><span>Verification Age</span></div>{data.ledger.map((l:any)=><div key={l.id} style={{display:'grid',gridTemplateColumns:'1.3fr .7fr .7fr .7fr .7fr .7fr .7fr .7fr',gap:8,borderTop:'var(--border-default)',padding:'8px 0',fontSize:12,alignItems:'center'}}><span>{l.action}</span><span>{money(l.projected)}</span><span>{money(l.verified)}</span><span>{money(l.variance ?? ((l.verified ?? 0) - (l.projected ?? 0)))}</span><span>{l.confidence ?? 'LOW'}</span><button onClick={()=>setEvidenceId(l.id)}>{l.evidence === 'Available' ? 'View Evidence' : 'Unavailable'}</button><span><StatusPill status={statusPill(l.verificationStatus ?? l.state) as any} /> {l.verificationStatus ?? l.state}</span><span>{l.verificationAge || 'Pending'}</span></div>)}</section>
  {selected && <section data-testid='outcome-evidence-pack' style={{border:'var(--border-teal)',borderRadius:10,padding:12,marginTop:14}}><SectionLabel>Verification Pack · {selected.action}</SectionLabel><button onClick={()=>setEvidenceId(null)} style={{float:'right'}}>Close</button><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:10}}><div><h3>Before snapshot</h3><pre style={{fontSize:12,whiteSpace:'pre-wrap'}}>{JSON.stringify(selected.evidencePack?.beforeState ?? {}, null, 2)}</pre></div><div><h3>After snapshot</h3><pre style={{fontSize:12,whiteSpace:'pre-wrap'}}>{JSON.stringify(selected.evidencePack?.afterState ?? {}, null, 2)}</pre></div></div><h3>Execution Timeline</h3><div>{(selected.evidencePack?.executionTimeline ?? ['Discovery','Recommendation','Approval','Execution','Verification','Outcome']).map((event:any,idx:number)=><div key={idx}>✓ {typeof event === 'string' ? event : `${event.stage} · ${event.timestamp ?? 'pending'} · ${event.description}`}</div>)}</div><h3>Supporting evidence</h3><pre style={{fontSize:12,whiteSpace:'pre-wrap'}}>{JSON.stringify(selected.evidencePack?.supportingEvidence ?? selected.evidencePack ?? {}, null, 2)}</pre></section>}
 </div></Shell>}
