import { FileText } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { WorkspaceModeBanner, EvidenceBadge, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, RiskBadge, StatusBadge } from '../components/executive'
import { useOwnershipIntelligenceData } from '../hooks/useOwnershipIntelligenceData'
const money=(value?:number)=>typeof value==='number'?`$${Math.round(value).toLocaleString()}`:'—'
const label=(value:string)=>value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,(char)=>char.toUpperCase())
export default function OwnershipIntelligence(){const{data}=useOwnershipIntelligenceData();const statuses=['OWNED','PARTIALLY_OWNED','OWNERLESS','STALE','CONFLICTED'];const statusCopy=['Owned','Partially Owned','Ownerless','Stale','Conflicted'];const spend=data.findings.filter((f)=>f.annualCost&&['NO_BUSINESS_OWNER','NO_BUDGET_OWNER','NO_EXECUTIVE_SPONSOR'].includes(f.gapType));const renewals=data.findings.filter((f)=>f.renewalDate&&f.gapType==='NO_RENEWAL_OWNER');const ai=data.findings.filter((f)=>f.sourceContext.includes('AI_GOVERNANCE')&&f.gapType==='NO_BUSINESS_OWNER');const staleConflict=data.findings.filter((f)=>f.ownershipStatus==='STALE'||f.ownershipStatus==='CONFLICTED');const actions=data.opportunity.recommendedActions.length?data.opportunity.recommendedActions:['Assign business owner','Assign technical owner','Assign budget owner','Assign renewal owner','Confirm stale owner','Resolve owner conflict','Escalate high-spend ownerless app'];return <Shell><ExecutivePageShell title='Vendor & Application Ownership Intelligence' subtitle='Identify applications, vendors, renewals, AI tools, and high-spend services without clear accountability.' badgeLabel='Read-only intelligence' badgeTone='info'>
<div aria-label='Workspace Mode'><WorkspaceModeBanner dataSourceOverride='Sample governance dataset' executionOverride='Execution disabled' /></div>
<div data-testid='ownership-kpis' style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><ExecutiveKpiCard label='Applications Reviewed' value={data.summary.applicationsReviewed} tone='info'/><ExecutiveKpiCard label='Ownerless Applications' value={data.summary.ownerlessApplications} tone='danger'/><ExecutiveKpiCard label='Annual Spend Without Owner' value={money(data.summary.annualSpendWithoutOwner)} tone='warning'/><ExecutiveKpiCard label='Renewals Without Owner' value={data.summary.renewalsWithoutOwner} tone='danger'/><ExecutiveKpiCard label='AI Apps Without Owner' value={data.summary.aiApplicationsWithoutOwner} tone='danger'/><ExecutiveKpiCard label='High-Risk Ownership Findings' value={data.summary.highRiskOwnershipFindings} tone='danger'/></div>
<ExecutiveSection testId='ownership-map' title='Ownership Accountability Map'>{statusCopy.map((copy)=><span key={copy} style={{display:'none'}}>{copy}</span>)}{statuses.map((status)=><div key={status} style={{display:'inline-flex',margin:'0 8px 8px 0'}}><StatusBadge status={`${label(status)}: ${data.ownershipStatusBreakdown[status]??0}`} tone={status==='OWNERLESS'||status==='CONFLICTED'?'danger':status==='STALE'?'warning':'info'}/></div>)}</ExecutiveSection>
<ExecutiveSection testId='ownership-findings-table' title='Ownership Findings Table'><div style={{overflowX:'auto'}}><div style={{minWidth:980}}><div style={{display:'grid',gridTemplateColumns:'.8fr .8fr .8fr 1fr .55fr .75fr .85fr 1fr 1.2fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Vendor</span><span>App</span><span>Status</span><span>Gap</span><span>Risk</span><span>Annual Cost</span><span>Renewal Date</span><span>Source Context</span><span>Recommended Action</span></div>{data.findings.map((f)=><div key={f.id} style={{display:'grid',gridTemplateColumns:'.8fr .8fr .8fr 1fr .55fr .75fr .85fr 1fr 1.2fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><strong>{f.vendorName}</strong><span>{f.applicationName}</span><span>{label(f.ownershipStatus)}</span><span>{label(f.gapType)}</span><RiskBadge level={f.riskLevel}/><span>{money(f.annualCost)}</span><span>{f.renewalDate??'—'}</span><span>{f.sourceContext.join(', ')}</span><span>{f.recommendedAction}</span></div>)}</div></div></ExecutiveSection>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><ExecutiveSection testId='ownership-spend' title='Spend Without Accountability'>{spend.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · exposed spend {money(f.annualCost)} · {label(f.gapType)}</p>)}</ExecutiveSection><ExecutiveSection testId='ownership-renewals' title='Renewals Without Owner'>{renewals.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {f.renewalDate} · {f.recommendedAction}</p>)}</ExecutiveSection><ExecutiveSection testId='ownership-ai' title='AI Applications Without Owner'>{ai.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {f.recommendedAction}</p>)}</ExecutiveSection><ExecutiveSection testId='ownership-stale-conflicted' title='Owner Conflicts / Stale Ownership'>{staleConflict.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {label(f.ownershipStatus)} · {f.recommendedAction}</p>)}</ExecutiveSection><ExecutiveSection testId='ownership-actions' title='Recommended Actions'>{actions.map((a)=><p key={a}><StatusBadge status={a} tone='info'/></p>)}</ExecutiveSection><ExecutiveSection testId='ownership-evidence' title='Evidence Panel' rightSlot={<EvidenceBadge confidence='HIGH'/>}>{data.evidenceRefs.map((ref)=><p key={ref}><FileText size={13}/> {ref}</p>)}</ExecutiveSection></div>
</ExecutivePageShell></Shell>}
