import { Link } from 'wouter'
import { CheckCircle2, CircleAlert, CircleDollarSign, ClipboardList, FileText, ShieldCheck } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { WorkspaceModeBanner, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, StatusBadge } from '../components/executive'
import { demoStory } from '../lib/demoStory'
import { usePilotWorkspaceData } from '../hooks/usePilotWorkspaceData'

const money = (value: number) => `$${Math.round(Number(value ?? 0)).toLocaleString()}`
const date = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value || 'Just now' : parsed.toLocaleString(undefined, { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }) }
const toneFor = (status: string) => /Blocked|Review|required/i.test(status) ? 'danger' : /attention|Needs/i.test(status) ? 'warning' : /Value|Evidence/i.test(status) ? 'info' : 'good'

export default function PilotWorkspace() {
  const data = usePilotWorkspaceData()
  return <Shell><ExecutivePageShell title='Workspace Control Center' subtitle='Track readiness, trust, value, governed execution status, evidence and open actions across demo, pilot and production workspace modes.' badgeLabel='Workspace operating center' badgeTone='info' narrative={demoStory.pilotWorkspaceNarrative} rightSlot={<div style={{ display:'flex', gap:8, flexWrap:'wrap', justifyContent:'flex-end' }}><StatusBadge status={data.tenant.name} tone='neutral' /><StatusBadge status={data.tenant.environment} tone={data.tenant.environment === 'LIVE' ? 'warning' : 'info'} /><StatusBadge status={data.overallReadiness} tone={toneFor(data.overallReadiness)} /><StatusBadge status={`Updated ${date(data.tenant.lastUpdated)}`} tone='neutral' /></div>}>
    <div aria-label='Workspace Mode'><WorkspaceModeBanner dataSourceOverride='Sample governance dataset' executionOverride='Execution disabled' /></div>
    {data.sourceWarnings.length > 0 && <div style={{ border:'1px solid rgba(245,158,11,.35)', background:'rgba(245,158,11,.08)', borderRadius:14, padding:12, color:'var(--text-secondary)' }}>Some live sources need attention. The workspace is showing the best available operational data.</div>}
    <section data-testid='pilot-workspace-kpis' style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(170px, 1fr))', gap:12 }}>
      <ExecutiveKpiCard label='Tenant Status' value={data.kpis.tenantStatus} tone={toneFor(data.kpis.tenantStatus)} sublabel='Pilot operating status' trend={<ClipboardList size={14} />} />
      <ExecutiveKpiCard label='Trust Status' value={data.kpis.trustStatus} tone={toneFor(data.kpis.trustStatus)} sublabel='Trust posture for review' trend={<ShieldCheck size={14} />} />
      <ExecutiveKpiCard label='Projected Annual Value' value={money(data.kpis.projectedAnnualValue)} tone='info' sublabel='Value identified' trend={<CircleDollarSign size={14} />} />
      <ExecutiveKpiCard label='Verified Annual Value' value={money(data.kpis.verifiedAnnualValue)} tone={data.kpis.verifiedAnnualValue ? 'good' : 'warning'} sublabel={data.kpis.verifiedAnnualValue ? 'Value verified' : 'Review required'} trend={<CheckCircle2 size={14} />} />
      <ExecutiveKpiCard label='Open Actions' value={data.kpis.openActions} tone={data.kpis.openActions ? 'warning' : 'good'} sublabel='Next operational action' trend={<CircleAlert size={14} />} />
      <ExecutiveKpiCard label='Evidence Packs' value={data.kpis.evidencePacks} tone={data.kpis.evidencePacks ? 'good' : 'warning'} sublabel={data.kpis.evidencePacks ? 'Evidence ready' : 'Review required'} trend={<FileText size={14} />} />
    </section>

    <div style={{ display:'grid', gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)', gap:16 }}>
      <ExecutiveSection testId='pilot-readiness' title='Pilot Readiness' description='Onboarding, connector, trust, evidence and executive review readiness.'>{data.pilotReadiness.map((item) => <Link key={item.label} href={item.href}><div style={{ display:'grid', gridTemplateColumns:'1fr auto', gap:12, padding:'13px 0', borderTop:'var(--border-default)', color:'inherit' }}><div><strong>{item.label}</strong><p style={{ margin:'4px 0 0', color:'var(--text-secondary)' }}>{item.detail}</p></div><StatusBadge status={item.status} tone={toneFor(item.status)} /></div></Link>)}</ExecutiveSection>
      <ExecutiveSection testId='value-summary' title='Value Summary' description='Value identified, value verified, savings confidence and pilot value narrative.'><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}><ExecutiveKpiCard label='Value identified' value={money(data.valueSummary.projectedAnnualValue)} tone='info' /><ExecutiveKpiCard label='Value verified' value={money(data.valueSummary.verifiedAnnualValue)} tone='good' /></div><p style={{ color:'var(--text-secondary)', lineHeight:1.6 }}>{data.valueSummary.narrative}</p><StatusBadge status={`Savings confidence: ${data.valueSummary.confidence}`} tone='info' /></ExecutiveSection>
    </div>

    <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(280px, 1fr))', gap:16 }}>
      <ExecutiveSection testId='execution-control' title='Execution Control' description='Approval-gated, controlled and verification-focused pilot operations.'><p>Pending approvals: <strong>{data.executionControl.pendingApprovals}</strong></p><p>Dry-run status: <StatusBadge status={data.executionControl.dryRunStatus} tone={toneFor(data.executionControl.dryRunStatus)} /></p><p>Controlled execution: <StatusBadge status={data.executionControl.controlledExecutionStatus} tone={toneFor(data.executionControl.controlledExecutionStatus)} /></p><p>Blocked actions: <strong>{data.executionControl.blockedActions}</strong></p><p>Verification status: <StatusBadge status={data.executionControl.verificationStatus} tone={toneFor(data.executionControl.verificationStatus)} /></p></ExecutiveSection>
      <ExecutiveSection testId='evidence-proof' title='Evidence & Proof' description='Evidence, proof, export availability and executive review readiness grouped for customer review.'><p>Proof status: <StatusBadge status={data.evidenceProof.proofStatus} tone={toneFor(data.evidenceProof.proofStatus)} /></p><p>Export availability: <strong>{data.evidenceProof.exportAvailability}</strong></p><p>Executive review: <StatusBadge status={data.evidenceProof.executiveReviewReadiness} tone={toneFor(data.evidenceProof.executiveReviewReadiness)} /></p><p><Link href='/executive-value'>Open Executive Value Dashboard</Link> · <Link href='/evidence-packs'>Open Evidence Packs</Link></p><div style={{ display:'grid', gap:8 }}>{data.evidenceProof.packs.map((pack: any) => <Link key={pack.id ?? pack.name ?? pack.title} href='/evidence-packs'><div style={{ border:'var(--border-default)', borderRadius:12, padding:10 }}><strong>{pack.name ?? pack.title ?? 'Evidence pack'}</strong><p style={{ margin:'4px 0 0', color:'var(--text-secondary)' }}>{pack.status ?? 'Evidence ready'}</p></div></Link>)}</div></ExecutiveSection>
      <ExecutiveSection testId='open-actions' title='Open Actions' description='Prioritised customer-success checklist for the next operational action.'>{data.openActions.map((action, index) => <Link key={action.id} href={action.href}><div style={{ display:'grid', gridTemplateColumns:'auto 1fr auto', gap:12, alignItems:'center', border:'var(--border-default)', borderRadius:14, padding:12, marginBottom:10, color:'inherit' }}><strong style={{ color:'var(--teal)' }}>{index + 1}</strong><div><strong>{action.label}</strong><p style={{ margin:'4px 0 0', color:'var(--text-secondary)' }}>{action.reason}</p></div><StatusBadge status={action.status} tone={toneFor(action.status)} /></div></Link>)}</ExecutiveSection>
    </div>
  </ExecutivePageShell></Shell>
}
