import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useRenewalsData } from '../hooks/useRenewalsData'

function money(value: number) { return value >= 1000000 ? `$${(value / 1000000).toFixed(1)}M` : `$${Math.round(value / 1000)}k` }
function riskStatus(value: string) { return value === 'HIGH' ? 'blocked' : value === 'MEDIUM' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div> }

export default function RenewalsView() {
  const { data, error, isEmptyLive, refresh } = useRenewalsData()
  return <Shell><div style={{padding:'16px 20px'}}><h1>Renewals</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>Renewal Intelligence turns upcoming contract dates into board-level recoverable spend and negotiation leverage.</p>{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Renewal intelligence not available yet' description='Connect contract, spend, and usage sources to calculate renewal readiness.' /> : <>
    <section data-testid='renewal-summary' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12}}><Card label='Upcoming Renewals' value={String(data.summary.upcomingRenewals)} detail='Renewals in the action window.' /><Card label='Renewal Spend' value={money(data.summary.renewalSpend)} detail='Annual spend under renewal review.' /><Card label='Recoverable' value={money(data.summary.recoverable)} detail='Negotiation-ready recoverable value.' /><Card label='High Risk' value={String(data.summary.highRisk)} detail='Needs executive attention.' /></section>
    <section data-testid='renewals-table' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Renewal Readiness</SectionLabel><div style={{display:'grid',gridTemplateColumns:'1fr 1fr .8fr .8fr .8fr .8fr .8fr .7fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Vendor</span><span>Renewal Date</span><span>Spend</span><span>Days Remaining</span><span>Readiness</span><span>Recoverable</span><span>Leverage</span><span>Actions</span></div>{data.renewals.map((renewal:any)=><div key={renewal.id} style={{display:'grid',gridTemplateColumns:'1fr 1fr .8fr .8fr .8fr .8fr .8fr .7fr',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><span><strong>{renewal.vendor}</strong><div style={{color:'var(--text-secondary)'}}>{renewal.contractName}</div></span><span>{renewal.renewalDate}</span><span>{money(renewal.annualSpend)}</span><span>{renewal.daysRemaining} days</span><span>{renewal.readiness.readinessScore}</span><span>{money(renewal.readiness.recoverableSpend)}</span><span><StatusPill status={riskStatus(renewal.readiness.negotiationLeverage) as any} /> {renewal.readiness.negotiationLeverage}</span><span>{renewal.readiness.recommendedActions}</span></div>)}</section>
  </>}</div></Shell>
}
