import { FileText } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { EmptyState, EvidenceBadge, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, RiskBadge, StatusBadge } from '../components/executive'
import { program2LiveUnconnectedCopy } from '../lib/program2Completion'
import { useRenewalContractData } from '../hooks/useRenewalContractData'
const money=(value?:number)=>typeof value==='number'?`$${Math.round(value).toLocaleString()}`:'—'
const pct=(value?:number)=>typeof value==='number'?`${Math.round(value*100)}%`:'—'
const calendarWindows = ['0–30 days', '31–60 days', '61–90 days', '91–120 days', '121–180 days']
const actionCopy = ['Renegotiate before renewal', 'Reduce seats before renewal', 'Consolidate duplicate vendors', 'Retire low-use tools', 'Assign contract owner', 'Validate missing usage/cost data', 'Prepare executive renewal review']
export default function RenewalContractIntelligence(){const{data,isEmptyLive}=useRenewalContractData();const negotiation=data.findings.filter((f)=>['RENEGOTIATE','REDUCE'].includes(f.recommendation));const consolidation=data.findings.filter((f)=>f.recommendation==='CONSOLIDATE');const gaps=data.findings.filter((f)=>['OWNER_GAP','MISSING_USAGE_DATA','MISSING_COST_DATA'].includes(f.findingType));return <Shell><ExecutivePageShell title='Technology Management — Renewal Risk' subtitle='Which contracts and renewals require RENEW, OPTIMISE, CONSOLIDATE, RETIRE, REVIEW or BLOCKED management decisions?' badgeLabel='Read-only intelligence' badgeTone='info'>
{isEmptyLive && <EmptyState title='Renewal Risk unavailable.' description={program2LiveUnconnectedCopy('Renewal Risk')} />}
<div data-testid='renewal-contract-kpis' style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><ExecutiveKpiCard label='Upcoming Renewals' value={data.summary.upcomingRenewals} tone='warning'/><ExecutiveKpiCard label='Annual Spend Reviewed' value={money(data.summary.annualSpendReviewed)} tone='info'/><ExecutiveKpiCard label='Potential Annual Savings' value={money(data.summary.potentialAnnualSavings)} tone='good'/><ExecutiveKpiCard label='High-Risk Renewals' value={data.summary.highRiskRenewals} tone='danger'/><ExecutiveKpiCard label='Contracts Missing Owner' value={data.summary.contractsMissingOwner} tone='danger'/><ExecutiveKpiCard label='Negotiation Opportunities' value={data.summary.negotiationOpportunities} tone='warning'/></div>
<ExecutiveSection testId='renewal-calendar' title='Renewal Calendar'>{(data.renewalCalendar.length ? data.renewalCalendar : calendarWindows.map((label)=>({ label, findings: [] }))).map((window)=><div key={window.label} style={{border:'var(--border-default)',borderRadius:14,padding:12,marginBottom:10}}><strong>{window.label}</strong><p>{window.findings.map((f)=>f.vendorName).join(', ')||'No renewals in this window'}</p></div>)}</ExecutiveSection>
<ExecutiveSection testId='renewal-risk-table' title='Renewal Risk Table'><div style={{overflowX:'auto'}}><div style={{minWidth:920}}><div style={{display:'grid',gridTemplateColumns:'.8fr .8fr .85fr .45fr .8fr .6fr .55fr .8fr .8fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Vendor</span><span>App</span><span>Renewal Date</span><span>Days</span><span>Annual Cost</span><span>Utilisation</span><span>Risk</span><span>Recommendation</span><span>Potential Savings</span></div>{data.findings.map((f)=><div key={f.id} style={{display:'grid',gridTemplateColumns:'.8fr .8fr .85fr .45fr .8fr .6fr .55fr .8fr .8fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><strong>{f.vendorName}</strong><span>{f.applicationName}</span><span>{f.renewalDate??'—'}</span><span>{f.daysToRenewal??'—'}</span><span>{money(f.annualCost)}</span><span>{pct(f.utilisationRate)}</span><RiskBadge level={f.riskLevel}/><span>{f.recommendation}</span><span>{money(f.potentialAnnualSavings)}</span></div>)}</div></div></ExecutiveSection>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><ExecutiveSection testId='renewal-negotiation' title='Negotiation Opportunities'>{negotiation.map((f)=><p key={f.id}><strong>{f.vendorName}</strong> · {f.recommendation} · {money(f.potentialAnnualSavings)}</p>)}</ExecutiveSection><ExecutiveSection testId='renewal-consolidation' title='Consolidation Before Renewal'>{consolidation.map((f)=><p key={f.id}><strong>{f.vendorName}</strong> · duplicates {f.duplicateWith?.join(', ')}</p>)}</ExecutiveSection><ExecutiveSection testId='renewal-gaps' title='Owner / Data Gaps'>{gaps.map((f)=><p key={f.id}><strong>{f.vendorName}</strong> · {f.findingType}</p>)}</ExecutiveSection><ExecutiveSection testId='renewal-actions' title='Recommended Actions'>{Array.from(new Set([...actionCopy, ...data.opportunity.topRenewalActions])).map((a)=><p key={a}><StatusBadge status={a} tone='info'/></p>)}</ExecutiveSection><ExecutiveSection testId='renewal-evidence' title='Evidence Panel' rightSlot={<EvidenceBadge confidence={data.opportunity.savingsConfidence}/>} >{data.evidenceRefs.map((ref)=><p key={ref}><FileText size={13}/> {ref}</p>)}</ExecutiveSection></div>
</ExecutivePageShell></Shell>}
