import { useEffect, useState } from 'react';
import { Layout } from '@/components/layout';

export default function RuntimeHealthView() {
  const [health, setHealth] = useState<any>(null);
  const [recovery, setRecovery] = useState<any>(null);
  useEffect(()=>{ fetch('/api/runtime/health').then((r)=>r.json()).then(setHealth).catch(()=>setHealth(null)); fetch('/api/runtime/recovery').then((r)=>r.json()).then(setRecovery).catch(()=>setRecovery(null)); },[]);
  return <Layout><div className='space-y-3'><h1 className='text-2xl font-semibold'>Runtime Health</h1>{health ? <div className='border rounded p-3 text-sm'><div>{health.wording?.runtime}</div><div>{health.wording?.evidencePipeline}</div><div>{health.wording?.policy}</div><div>Runtime status: {health.runtimeStatus}</div><div>Scheduler health: {String(health.schedulerHealth)}</div><div>Connector health matrix: {(health.connectors??[]).map((c:any)=>`${c.name}:${c.health}`).join(', ')}</div><div>Governance activity counters: policy {health.metrics?.policyEvaluationActivity}, events {health.metrics?.governanceEventThroughput}</div><div>Verification/drift stats: failed {health.metrics?.failedVerificationCount}, drift {health.metrics?.driftDetectionCount}</div><div>Audit export stats: {health.metrics?.auditPackGenerationActivity}</div><div>Failed policy checks: {health.metrics?.staleApprovalCount}</div><div>Stale governance objects: rec {health.metrics?.staleRecommendationCount}, approvals {health.metrics?.staleApprovalCount}</div></div> : <div>Loading...</div>}<div className='border rounded p-3 text-sm'><h2 className='font-semibold'>Runtime Recovery</h2>{recovery ? <><div>{recovery.recoveryState}</div><div>Reconciliation backlog: {recovery.reconciliationBacklog}</div><div>Stale workflow count: {recovery.staleWorkflowCount}</div><div>Recovery-required markers: {(recovery.recoveryRequiredMarkers??[]).join(', ') || '-'}</div><div>Last successful cycles: {JSON.stringify(recovery.lastSuccessfulCycles ?? {})}</div><div>{recovery.runtimeCheckpointStatus}</div></> : <div>Loading recovery...</div>}</div></div></Layout>;
}
