import { FileText } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { WorkspaceModeBanner, EvidenceBadge, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, RiskBadge, StatusBadge } from '../components/executive'
import { useSaaSRationalisationData } from '../hooks/useSaaSRationalisationData'
const money=(value?:number)=>typeof value==='number'?`$${Math.round(value).toLocaleString()}`:'—'
const label=(value:string)=>value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,(char)=>char.toUpperCase())
const actionCopy = ['Consolidate duplicate tools', 'Retire dormant vendors', 'Assign missing owners', 'Review renewal-risk vendors', 'Validate underused high-cost apps', 'Decide preferred tool per capability category']
export default function SaaSRationalisation(){const{data}=useSaaSRationalisationData();const savings=data.opportunity.findingsWithSavings;const governance=data.opportunity.governanceOnlyFindings;return <Shell><ExecutivePageShell title='SaaS Rationalisation' subtitle='Identify overlapping vendors, underused SaaS, owner gaps, renewal risk, and consolidation opportunities.' badgeLabel='Read-only intelligence' badgeTone='info'>
<div aria-label='Workspace Mode'><WorkspaceModeBanner dataSourceOverride='Sample governance dataset' executionOverride='Execution disabled' /></div>
<div data-testid='saas-rationalisation-kpis' style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><ExecutiveKpiCard label='Applications Reviewed' value={data.summary.applicationsReviewed} tone='info'/><ExecutiveKpiCard label='Overlap Groups' value={data.summary.overlapGroups} tone='warning'/><ExecutiveKpiCard label='Duplicate Capability Findings' value={data.summary.duplicateCapabilityFindings} tone='warning'/><ExecutiveKpiCard label='Potential Annual Savings' value={money(data.summary.potentialAnnualSavings)} tone='good'/><ExecutiveKpiCard label='Governance Findings' value={data.summary.governanceFindings} tone='danger'/><ExecutiveKpiCard label='Renewal Risks' value={data.summary.renewalRisks} tone='warning'/></div>
<ExecutiveSection testId='saas-overlap-map' title='Vendor Overlap Map' description='Capability groups showing approved, active, underused and unmanaged apps.'>{data.overlapGroups.map((group)=><div key={group.id} style={{border:'var(--border-default)',borderRadius:14,padding:12,marginBottom:10}}><strong>{group.displayName}</strong><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:8}}>{group.applications.map((app)=><StatusBadge key={`${group.id}-${app.applicationName}`} status={`${app.applicationName} · ${app.status}`} tone={app.status==='unmanaged'?'danger':app.status==='underused'||app.status==='dormant'?'warning':'info'}/>)}</div></div>)}</ExecutiveSection>
<ExecutiveSection testId='saas-findings-table' title='Rationalisation Findings Table'><div style={{overflowX:'auto'}}><div style={{minWidth:960}}><div style={{display:'grid',gridTemplateColumns:'.8fr .8fr .9fr 1fr .55fr .6fr .6fr .6fr .8fr 1.3fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Vendor</span><span>App</span><span>Category</span><span>Finding</span><span>Risk</span><span>Assigned</span><span>Active</span><span>Utilisation</span><span>Potential Savings</span><span>Recommended Action</span></div>{data.findings.map((f)=><div key={f.id} style={{display:'grid',gridTemplateColumns:'.8fr .8fr .9fr 1fr .55fr .6fr .6fr .6fr .8fr 1.3fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><strong>{f.vendorName}</strong><span>{f.applicationName}</span><span>{label(f.capabilityCategory)}</span><span>{label(f.findingType)}</span><RiskBadge level={f.riskLevel}/><span>{f.usersAssigned??'—'}</span><span>{f.activeUsers??'—'}</span><span>{typeof f.utilisationRate==='number'?`${Math.round(f.utilisationRate*100)}%`:'—'}</span><span>{money(f.potentialAnnualSavings)}</span><span>{f.recommendedAction}</span></div>)}</div></div></ExecutiveSection>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><ExecutiveSection testId='saas-savings' title='Savings Opportunities' description='Only supported savings are shown.'>{savings.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {money(f.potentialAnnualSavings)} · {f.recommendedAction}</p>)}</ExecutiveSection><ExecutiveSection testId='saas-governance' title='Governance Exposure'>{governance.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {label(f.findingType)} · <RiskBadge level={f.riskLevel}/></p>)}</ExecutiveSection><ExecutiveSection testId='saas-actions' title='Recommended Actions'>{Array.from(new Set([...actionCopy, ...data.opportunity.topRationalisationActions])).map((a)=><p key={a}><StatusBadge status={a} tone='info'/></p>)}</ExecutiveSection><ExecutiveSection testId='saas-evidence' title='Evidence Panel' rightSlot={<EvidenceBadge confidence={data.opportunity.savingsConfidence}/>} >{data.evidenceRefs.map((ref)=><p key={ref}><FileText size={13}/> {ref}</p>)}</ExecutiveSection></div>
</ExecutivePageShell></Shell>}
