import { FileText } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { WorkspaceModeBanner, EvidenceBadge, ExecutiveKpiCard, ExecutivePageShell, ExecutiveSection, RiskBadge, StatusBadge } from '../components/executive'
import { useShadowITExposureData } from '../hooks/useShadowITExposureData'
const money=(value?:number)=>typeof value==='number'?`$${Math.round(value).toLocaleString()}`:'Governance exposure'
const label=(value:string)=>value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,(char)=>char.toUpperCase())
export default function ShadowITExposure(){const{data}=useShadowITExposureData();const ai=data.findings.filter((f)=>f.findingType.includes('AI'));const duplicate=data.findings.filter((f)=>f.findingType.includes('DUPLICATE'));const dormant=data.findings.filter((f)=>f.findingType.includes('DORMANT'));const evidenceRefs=Array.from(new Set(data.findings.flatMap((f)=>f.evidenceRefs)));return <Shell><ExecutivePageShell title='Shadow IT Exposure' subtitle='Discover unapproved SaaS, AI tools, duplicate applications, dormant apps, and governance exposure.' badgeLabel='Read-only intelligence' badgeTone='info'>
<div aria-label='Workspace Mode'><WorkspaceModeBanner dataSourceOverride='Sample governance dataset' executionOverride='Execution disabled' /></div>
<div data-testid='shadow-it-kpis' style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><ExecutiveKpiCard label='Applications Discovered' value={data.summary.applicationsDiscovered} tone='info'/><ExecutiveKpiCard label='Unknown / Unapproved Apps' value={data.summary.unknownApplications} tone='warning'/><ExecutiveKpiCard label='AI Applications' value={data.summary.aiApplications} tone='danger'/><ExecutiveKpiCard label='Duplicate Capability Findings' value={data.summary.duplicateCapabilityFindings} tone='warning'/><ExecutiveKpiCard label='Potential Annual Savings' value={money(data.summary.potentialAnnualSavings)} tone='good'/><ExecutiveKpiCard label='Governance Exposure Score' value={data.governanceExposureScore} tone='danger'/></div>
<ExecutiveSection testId='shadow-it-findings' title='Exposure Findings Table' description='Evidence-backed findings across unapproved, AI, dormant and unmanaged applications.'><div style={{overflowX:'auto'}}><div style={{minWidth:860}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr .6fr .5fr .6fr .8fr 1.5fr',gap:8,fontWeight:700,borderBottom:'var(--border-default)',paddingBottom:8}}><span>Application</span><span>Finding Type</span><span>Risk</span><span>Users</span><span>Trust Score</span><span>Estimated Savings</span><span>Recommended Action</span></div>{data.findings.map((f)=><div key={f.id} style={{display:'grid',gridTemplateColumns:'1fr 1fr .6fr .5fr .6fr .8fr 1.5fr',gap:8,borderBottom:'var(--border-default)',padding:'10px 0',alignItems:'center'}}><strong>{f.applicationName}</strong><span>{label(f.findingType)}</span><RiskBadge level={f.riskLevel}/><span>{f.userCount}</span><span>{f.trustScore}</span><span>{f.findingType.includes('DORMANT')||f.findingType.includes('DUPLICATE')?money(f.annualCostEstimate):'Governance exposure'}</span><span>{f.recommendedAction}</span></div>)}</div></div></ExecutiveSection>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><ExecutiveSection testId='shadow-it-ai-exposure' title='AI Application Exposure' description='AI apps are high-governance-exposure findings because they can create AI governance exposure, data disclosure and policy coverage risk.'>{ai.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · {f.userCount} users · <RiskBadge level={f.riskLevel}/></p>)}</ExecutiveSection><ExecutiveSection testId='shadow-it-duplicate' title='Duplicate Capability' description='Overlapping tools that should be reviewed for consolidation.'>{duplicate.length?duplicate.map((f)=><p key={f.id}>{f.applicationName}</p>):<p>Dropbox vs OneDrive · Miro vs Lucid · Slack vs Teams · Zoom vs Teams</p>}</ExecutiveSection><ExecutiveSection testId='shadow-it-dormant' title='Dormant / Rationalisation Opportunities'>{dormant.map((f)=><p key={f.id}><strong>{f.applicationName}</strong> · supported savings {money(f.annualCostEstimate)}</p>)}</ExecutiveSection><ExecutiveSection testId='shadow-it-evidence' title='Evidence Panel' rightSlot={<EvidenceBadge confidence='HIGH'/>}><p>Enterprise App ID · OAuth App ID · Sign-in record ID</p>{evidenceRefs.map((ref)=><p key={ref}><FileText size={13}/> {ref}</p>)}</ExecutiveSection><ExecutiveSection testId='shadow-it-governance-actions' title='Recommended Governance Actions'>{['Assign application owner','Review approval status','Validate usage','Consolidate duplicate tools','Review AI policy coverage','Create exception or remediation plan'].map((action)=><p key={action}><StatusBadge status={action} tone='info'/></p>)}</ExecutiveSection></div>
</ExecutivePageShell></Shell>}
