import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { useUtilizationIntelligenceData } from '../hooks/useUtilizationIntelligenceData'

function money(value: number) { return value >= 1000000 ? `$${(value / 1000000).toFixed(1)}M` : `$${Math.round(value / 1000)}k` }
function bandStatus(value: string) { return value === 'UNUSED' ? 'blocked' : value === 'LOW' || value === 'MEDIUM' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14}}><SectionLabel>{label}</SectionLabel><div style={{fontSize:28,marginTop:6}}>{value}</div><p style={{fontSize:12,color:'var(--text-secondary)',margin:'6px 0 0'}}>{detail}</p></div> }

export default function UtilizationIntelligenceView() {
  const { data, error, isEmptyLive, refresh } = useUtilizationIntelligenceData()
  return <Shell><div style={{padding:'16px 20px'}}><h1>Utilization Intelligence</h1><p style={{color:'var(--text-secondary)',fontSize:13}}>Detect shelfware, underutilization, feature waste, license waste, adoption gaps, and unused commitments.</p>{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Utilization intelligence not available yet' description='Sync usage and assignment data to calculate waste and utilization opportunities.' /> : <>
    <section data-testid='utilization-summary' style={{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:12}}><Card label='Assets Analysed' value={String(data.summary.assetsAnalysed)} detail='Assigned assets evaluated.' /><Card label='Unused Value' value={money(data.summary.unusedValue)} detail='Waste from unused or underused resources.' /><Card label='Low Utilization' value={String(data.summary.lowUtilization)} detail='Low or unused records.' /><Card label='Generated Opportunities' value={String(data.summary.generatedOpportunities)} detail='Factory-ready opportunities.' /></section>
    <section data-testid='utilization-table' style={{border:'var(--border-default)',background:'var(--bg-card)',borderRadius:12,padding:14,marginTop:14}}><SectionLabel>Utilization Waste</SectionLabel><div style={{display:'grid',gridTemplateColumns:'.8fr 1.2fr .6fr .6fr .8fr .8fr .8fr 1fr',gap:8,fontSize:12,fontWeight:600,marginTop:10}}><span>Platform</span><span>Resource</span><span>Assigned</span><span>Active</span><span>Utilization %</span><span>Monthly Cost</span><span>Waste Estimate</span><span>Opportunity</span></div>{data.records.map((record:any)=><div key={record.id} style={{display:'grid',gridTemplateColumns:'.8fr 1.2fr .6fr .6fr .8fr .8fr .8fr 1fr',gap:8,padding:'8px 0',borderTop:'var(--border-default)',fontSize:12,alignItems:'center'}}><span>{record.platform}</span><span>{record.resourceName}</span><span>{record.assignedCount}</span><span>{record.activeCount}</span><span><StatusPill status={bandStatus(record.utilizationBand) as any} /> {record.utilizationPercent}%</span><span>{money(record.monthlyCost)}</span><span>{money(record.wasteEstimate)}</span><span>{record.opportunity ?? 'Generate Campaign'}</span></div>)}</section>
  </>}</div></Shell>
}
