import { Shell } from '../components/layout/Shell'
import { EmptyState, LiveDataError, SectionLabel, StatusPill } from '../components/shared/Foundation'
import { program2LiveUnconnectedCopy } from '../lib/program2Completion'
import { useVendorIntelligenceData } from '../hooks/useVendorIntelligenceData'

function money(value: number) { return `$${Math.round(Number(value ?? 0)).toLocaleString()}` }
function severityStatus(severity: string) { return severity === 'CRITICAL' || severity === 'HIGH' ? 'blocked' : severity === 'MEDIUM' ? 'degraded' : 'ready' }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14 }}><SectionLabel>{label}</SectionLabel><div style={{ fontSize: 28, marginTop: 6 }}>{value}</div><p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: '6px 0 0' }}>{detail}</p></div> }

export default function VendorIntelligenceView() {
  const { data, error, isEmptyLive, refresh, ingestSignal, classifyChange, assessChange, promoteToOpportunity } = useVendorIntelligenceData()
  const summary = data.summary
  return <Shell><div style={{ padding: '16px 20px' }}><h1>Technology Management — Vendor Intelligence</h1><p style={{ color: 'var(--text-secondary)', fontSize: 13 }}>Which vendor changes create renewal, spend, risk or management-decision exposure across the technology portfolio?</p>{error && <LiveDataError error={error} onRetry={() => void refresh()} />}{isEmptyLive ? <EmptyState title='Vendor Intelligence unavailable.' description={program2LiveUnconnectedCopy('Vendor Intelligence')} /> : <>
    <section data-testid='vendor-intelligence-summary' style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12 }}><Card label='Vendor Changes Detected' value={String(summary.vendorChangesDetected)} detail='Changes found across vendor feeds.' /><Card label='High Impact' value={String(summary.highImpact)} detail='Requires operator review.' /><Card label='Affected Spend' value={money(summary.affectedSpend)} detail='Potential spend exposure.' /><Card label='Generated Opportunities' value={String(summary.generatedOpportunities)} detail='Candidate governed actions.' /></section>
    <section data-testid='vendor-signal-feed' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14, marginTop: 14 }}><SectionLabel>Signal Feed</SectionLabel><button onClick={() => void ingestSignal()}>Ingest signal</button><div style={{ display: 'grid', gridTemplateColumns: '.8fr .8fr 1.5fr .8fr .8fr .7fr', gap: 8, fontSize: 12, fontWeight: 600, marginTop: 10 }}><span>Source</span><span>Vendor</span><span>Title</span><span>Detected</span><span>State</span><span>Duplicate</span></div>{(data.signals ?? []).map((signal: any) => <div key={signal.signalId} style={{ display: 'grid', gridTemplateColumns: '.8fr .8fr 1.5fr .8fr .8fr .7fr', gap: 8, padding: '8px 0', borderTop: 'var(--border-default)', fontSize: 12 }}><span>{signal.sourceType}</span><span>{signal.vendor}</span><span>{signal.title}</span><span>{signal.detectedAt}</span><span>{signal.signalState}</span><span>{signal.duplicateOfSignalId ? 'Yes' : 'No'}</span></div>)}</section>
    <section data-testid='vendor-change-feed' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14, marginTop: 14 }}><SectionLabel>Change Feed / Change Classification</SectionLabel><div style={{ display: 'grid', gridTemplateColumns: '110px 1.4fr .7fr .8fr .8fr 1fr 260px', gap: 8, fontSize: 12, fontWeight: 600, marginTop: 10 }}><span>Vendor</span><span>Change</span><span>Category</span><span>Severity</span><span>Confidence</span><span>Reasons</span><span>Actions</span></div>{data.changes.map((change: any) => <div key={change.id} style={{ display: 'grid', gridTemplateColumns: '110px 1.4fr .7fr .8fr .8fr 1fr 260px', gap: 8, padding: '8px 0', borderTop: 'var(--border-default)', fontSize: 12, alignItems: 'center' }}><span>{change.vendor}</span><span><strong>{change.title}</strong><div style={{ color: 'var(--text-secondary)' }}>{change.description}</div></span><span>{change.category}</span><span><StatusPill status={severityStatus(change.impactSeverity) as any} /> {change.impactSeverity}</span><span>{change.classifierConfidence ?? 'SEEDED'}</span><span>{(change.classificationReasons ?? []).join(', ') || 'Seeded VCDE change'}</span><span style={{ display: 'flex', gap: 6 }}><button onClick={() => void classifyChange(change.sourceSignalId ?? change.id)}>Classify</button><button onClick={() => void assessChange(change.id)}>Assess impact</button><button onClick={() => void promoteToOpportunity(change.id)}>Promote to Opportunity Factory</button></span></div>)}</section>
    <section data-testid='vendor-impact-assessment' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14, marginTop: 14 }}><SectionLabel>Impact Assessment</SectionLabel>{data.changes.map((change: any) => <div key={`${change.id}-impact`} style={{ display: 'grid', gridTemplateColumns: '1fr .8fr .8fr 1.2fr', gap: 8, padding: '8px 0', borderTop: 'var(--border-default)', fontSize: 12 }}><span>{change.title}</span><span>{money(change.potentialImpact ?? change.affectedSpend ?? 0)} affected spend</span><span>{change.impactConfidence ?? 'Pending confidence'}</span><span>{(change.impactReasons ?? ['Assess impact to calculate affected platforms']).join(', ')}</span></div>)}</section>
    <section data-testid='vendor-opportunity-pipeline' style={{ border: 'var(--border-default)', background: 'var(--bg-card)', borderRadius: 12, padding: 14, marginTop: 14 }}><SectionLabel>Opportunity Pipeline</SectionLabel>{data.changes.map((change: any) => <div key={`${change.id}-pipeline`} style={{ display: 'grid', gridTemplateColumns: '1fr .7fr 1fr .7fr', gap: 8, padding: '8px 0', borderTop: 'var(--border-default)', fontSize: 12 }}><span>{change.title}</span><span>{(change.generatedOpportunityCount ?? 0) > 0 ? 'Promoted' : 'Not promoted'}</span><span>{change.linkedOpportunityId ?? `sourceReferenceId: ${change.id}`}</span><span>{change.priorityRank ?? 'Pending'}</span></div>)}</section>
  </>}</div></Shell>
}
