export type ExecutivePostureState='STABLE'|'OPTIMIZING'|'DRIFTING'|'FRAGMENTED'|'AT_RISK'|'CRITICAL';
export type GovernanceReadinessState='EXECUTIVE_GOVERNANCE_READY'|'READY_WITH_LIMITS'|'OPERATIONAL_HARDENING_REQUIRED';
export interface EnterpriseEconomicHealth { overallEconomicHealth:number; economicDriftRisk:number; governanceMaturity:number; realizationMaturity:number; forecastReliability:number; operationalEfficiency:number; optimizationPersistence:number; aiEconomicHealth:number; cloudEconomicHealth:number; confidence:number; assumptions?:string[]; evidenceRefs?:string[]; uncertainty?:string[]; calibrationLimitations?:string[]; operationalDependencies?:string[]; }
export interface EconomicPostureAssessment { posture:ExecutivePostureState; postureReasons:string[]; confidence:number; topWeaknesses:string[]; topStrengths:string[]; assumptions?:string[]; evidenceRefs?:string[]; uncertainty?:string[]; calibrationLimitations?:string[]; operationalDependencies?:string[]; }
export interface ExecutiveEconomicRisk { riskType:'AI_SPRAWL_RISK'|'GPU_SPEND_EXPLOSION'|'CLOUD_DRIFT_RISK'|'GOVERNANCE_COLLAPSE_RISK'|'REALIZATION_FAILURE_RISK'|'DUPLICATE_TOOL_RISK'|'FORECAST_UNRELIABILITY_RISK'|'SHADOW_AI_RISK'|'OWNERLESS_INFRASTRUCTURE_RISK'|'APPROVAL_BOTTLENECK_RISK'; severity:number; trajectory:'IMPROVING'|'STABLE'|'WORSENING'; confidence:number; mitigationGuidance:string[]; forecastWindow:'30D'|'90D'|'180D'|'365D'; }
export interface ExecutiveTransformationAssessment { transformationType:'AI_TRANSFORMATION'|'FINOPS_TRANSFORMATION'|'TOOL_CONSOLIDATION'|'CLOUD_GOVERNANCE_TRANSFORMATION'|'SAVINGS_REALIZATION_TRANSFORMATION'; projectedSuccessProbability:number; projectedFailureRisk:number; governanceReadiness:number; organizationalFriction:number; forecastConfidence:number; topDependencies:string[]; topRisks:string[]; }
export interface ExecutiveScenarioGovernanceResult { preferredScenario:string; highestRiskScenario:string; highestROIProjection:string; strongestGovernanceScenario:string; lowestConfidenceScenario:string; executiveTradeoffs:string[]; }
export interface ExecutiveGovernanceScorecard { domainScores:{domain:'AI_GOVERNANCE'|'FINOPS_GOVERNANCE'|'REALIZATION_GOVERNANCE'|'FORECASTING_GOVERNANCE'|'OPERATIONALIZATION_GOVERNANCE'|'OWNERSHIP_GOVERNANCE'|'RECURRENCE_PREVENTION';score:number}[]; overallScore:number; strongestDomains:string[]; weakestDomains:string[]; governanceMaturity:number; confidence:number; }
export interface ExecutiveStrategyComparison { bestProjectedROI:string; bestProjectedGovernance:string; bestProjectedEfficiency:string; highestProjectedRisk:string; highestProjectedDrift:string; recommendedStrategy:'OPTIMIZATION_FIRST'|'AI_ACCELERATION_FIRST'|'GOVERNANCE_FIRST'|'BALANCED_EXECUTION'|'COST_CONTAINMENT_FIRST'; confidence:number; }
export interface EconomicGovernanceStressTest { stressSeverity:number; recoveryLikelihood:number; governanceResilience:number; forecastReliabilityImpact:number; realizationImpact:number; criticalFailureAreas:string[]; }
export interface ExecutiveGovernanceReadiness { readinessStatus:GovernanceReadinessState; readinessReasons:string[]; criticalGaps:string[]; governanceStrengths:string[]; forecastingMaturity:number; simulationMaturity:number; operationalizationMaturity:number; calibrationMaturity:number; memoryMaturity:number; }
export interface ExecutiveEconomicGovernanceReport { tenantId:string; economicHealth:EnterpriseEconomicHealth; economicPosture:EconomicPostureAssessment; topExecutiveRisks:ExecutiveEconomicRisk[]; topTransformationRisks:ExecutiveTransformationAssessment[]; topTransformationOpportunities:ExecutiveTransformationAssessment[]; executiveScenarioAssessment:ExecutiveScenarioGovernanceResult; executiveStrategyAssessment:ExecutiveStrategyComparison; governanceStressResults:EconomicGovernanceStressTest; governanceReadiness:ExecutiveGovernanceReadiness; executiveConfidence:number; recommendedGovernanceFocus:string[]; }
