export type CommitmentProvider='AWS'|'AZURE'|'GCP'|'MULTI_CLOUD';
export type CommitmentType='RESERVED_INSTANCE'|'SAVINGS_PLAN'|'COMMITTED_USE_DISCOUNT'|'CAPACITY_RESERVATION'|'GPU_COMMITMENT';
export type CommitmentRecommendationCategory='COMMITMENT_REVIEW'|'UNDERUTILIZATION_REVIEW'|'OVERCOMMITMENT_REVIEW'|'EXPIRATION_REVIEW'|'COVERAGE_GAP_REVIEW'|'ELASTICITY_RISK_REVIEW'|'GPU_COMMITMENT_REVIEW';
export type GovernanceMode='READ_ONLY'|'RECOMMEND_ONLY'|'APPROVAL_REQUIRED';
export interface CommitmentEconomicSignal { tenantId:string; provider?:CommitmentProvider; accountId?:string; commitmentId:string; commitmentType?:CommitmentType; serviceName?:string; region?:string; instanceFamily?:string; startDate?:string; endDate?:string; commitmentTermMonths?:number; committedSpendMonthly:number; actualCoveredSpendMonthly:number; utilizationPercentage?:number; coveragePercentage?:number; environmentScope?:string; ownerId?:string; costCenter?:string; tags?:Record<string,string>; evidenceRefs?:string[]; sourceSystem?:string; replayCorrelationId?:string; lineageCorrelationId?:string; forecastConfidence?:number; }
export interface CommitmentUtilizationResult { utilizationScore:number; wasteEstimateMonthly:number; wasteEstimateAnnual:number; efficiencyBand:'OPTIMAL'|'HEALTHY'|'UNDERUTILIZED'|'SEVERELY_UNDERUTILIZED'; confidence:number; reasons:string[]; }
export interface CommitmentCoverageResult { coverageScore:number; coverageGapRisk:number; coverageFragmentationRisk:number; coverageRecommendations:string[]; confidence:number; }
export interface CommitmentDecayResult { decayRiskScore:number; daysUntilExpiration:number; expectedDecayTrajectory:'STABLE'|'RISING'|'HIGH'; renewalReviewRecommended:boolean; confidence:number; }
export interface CommitmentElasticityRiskResult { elasticityRiskScore:number; lockInRisk:number; forecastVolatility:number; commitmentRigidityRisk:number; confidence:number; }
export interface CommitmentExpirationForecast { expirationRiskScore:number; projectedPostExpirationSpend:number; renewalPriority:'LOW'|'MEDIUM'|'HIGH'; forecastConfidence:number; reasons:string[]; }
export interface CommitmentSavingsSimulation { scenario:'RENEW_CURRENT'|'REDUCE_COMMITMENTS'|'EXPAND_COMMITMENTS'|'GPU_EXPANSION'|'AI_ACCELERATION'|'WORKLOAD_CONSOLIDATION'|'MULTI_CLOUD_SHIFT'; projectedSavings:number; projectedWaste:number; coverageImpact:number; governanceRisk:number; elasticityRisk:number; confidence:number; tradeoffs:string[]; }
export interface CommitmentRiskResult { riskType:'OVERCOMMITMENT'|'UNDERUTILIZATION'|'COVERAGE_GAPS'|'EXPIRATION_CONCENTRATION'|'GPU_LOCKIN'|'ELASTICITY_MISMATCH'|'COMMITMENT_FRAGMENTATION'; severity:'LOW'|'MEDIUM'|'HIGH'; trajectory:'IMPROVING'|'STABLE'|'WORSENING'; confidence:number; recommendedReview:string; }
export interface CommitmentRecommendation { recommendationId:string; tenantId:string; commitmentId:string; recommendationCategory:CommitmentRecommendationCategory; recommendationSummary:string; estimatedMonthlyImpact:number; estimatedAnnualImpact:number; confidence:number; recommendedMode:GovernanceMode; operationalRisk:number; evidenceRefs:string[]; }
export interface CommitmentEconomicsReport { tenantId:string; commitmentCount:number; totalCommittedSpendMonthly:number; totalCoveredSpendMonthly:number; estimatedMonthlyWaste:number; estimatedAnnualWaste:number; averageCoverage:number; averageUtilization:number; underutilizedCommitmentCount:number; expirationRiskCount:number; elasticityRiskCount:number; gpuCommitmentRiskCount:number; commitmentEconomicHealth:number; topCommitmentRisks:string[]; topOptimizationAreas:string[]; recommendedNextActions:string[]; readinessStatus:'READY_FOR_COMMITMENT_GOVERNANCE'|'READY_WITH_LIMITS'|'HARDENING_REQUIRED'; }
