export type M365AuthState = 'READY' | 'MISSING_CONFIG' | 'TOKEN_FAILED' | 'GRAPH_UNREACHABLE' | 'INSUFFICIENT_PERMISSIONS'
export type M365HealthState = 'HEALTHY' | 'DEGRADED' | 'PARTIAL' | 'FAILED' | 'NOT_CONFIGURED'
export type TrustBand = 'TRUSTED' | 'HIGH' | 'INVESTIGATE' | 'LOW_CONFIDENCE' | 'BLOCKED'

export interface PermissionCheck { permission: string; required: boolean; granted: boolean; category: 'READ' | 'WRITE'; reason: string }
export interface M365ReadinessReport { tenantId: string; authState: M365AuthState; readReady: boolean; writeReady: boolean; requiredReadPermissions: PermissionCheck[]; requiredWritePermissions: PermissionCheck[]; graphReachable: boolean; tokenAcquired: boolean; blockers: string[]; warnings: string[]; checkedAt: string }
export interface M365TenantSnapshot { snapshotId: string; tenantId: string; organizationId?: string; displayName?: string; capturedAt: string; source: 'MICROSOFT_GRAPH' }
export interface M365User { id: string; tenantId: string; userPrincipalName: string; displayName?: string; accountEnabled: boolean; userType: string; department?: string; jobTitle?: string; usageLocation?: string; createdDateTime?: string; signInActivity?: { lastSignInDateTime?: string; lastNonInteractiveSignInDateTime?: string }; assignedLicenses: string[]; assignedPlans?: string[]; isAdminCandidate?: boolean; isServiceAccountCandidate?: boolean; isSharedMailboxCandidate?: boolean; isNoReplyCandidate?: boolean; sourceSnapshotId: string }
export interface M365LicenseAssignment { id: string; tenantId: string; userId: string; skuId: string; skuPartNumber?: string; assignmentType: 'DIRECT' | 'GROUP' | 'UNKNOWN'; disabledPlans?: string[]; sourceSnapshotId: string }
export interface M365SubscribedSku { skuId: string; skuPartNumber: string; prepaidEnabled: number; consumedUnits: number; capabilityStatus?: string; appliesTo?: string }
export interface M365UsageRecord { id: string; tenantId: string; userPrincipalName: string; reportType: 'OFFICE365_ACTIVE_USER' | 'MAILBOX_USAGE' | 'OFFICE_ACTIVATION'; lastActivityDate?: string; exchangeActive?: boolean; oneDriveActive?: boolean; sharePointActive?: boolean; teamsActive?: boolean; outlookActive?: boolean; rawFields: Record<string, unknown>; sourceSnapshotId: string }
export interface M365Mailbox { id: string; tenantId: string; userPrincipalName: string; recipientType?: 'USER' | 'SHARED' | 'ROOM' | 'EQUIPMENT' | 'UNKNOWN'; mailboxStorageUsed?: number; itemCount?: number; lastActivityDate?: string; sourceSnapshotId: string }
export interface M365DiscoveryResult { tenantId: string; snapshotId: string; status: 'COMPLETED' | 'PARTIAL' | 'FAILED'; counts: { users: number; enabledUsers: number; disabledUsers: number; licensedUsers: number; skus: number; usageRecords: number; mailboxes: number; groups: number }; warnings: string[]; blockers: string[]; startedAt: string; completedAt: string }
export interface M365ConnectorHealth { tenantId: string; state: M365HealthState; dimensions: Record<'auth' | 'permissions' | 'usersRead' | 'licensesRead' | 'usageReportsRead' | 'mailboxReportsRead' | 'freshness' | 'rateLimitRisk', string>; lastSuccessfulSyncAt?: string; lastFailedSyncAt?: string; lastError?: string; freshnessAgeHours?: number; warnings: string[]; blockers: string[]; checkedAt: string }
export interface TrustDimension { score: number; band: TrustBand; reasons: string[]; affectedValue?: number }
export interface M365TrustReport { tenantId: string; globalTrustScore: number; globalTrustBand: TrustBand; identityTrust: TrustDimension; licenseTrust: TrustDimension; usageTrust: TrustDimension; activityTrust: TrustDimension; mailboxTrust: TrustDimension; executionSafetyTrust: TrustDimension; blockers: string[]; warnings: string[]; recommendations: string[]; generatedAt: string }
