export type EconomicForecastWindow = '30D'|'90D'|'180D'|'365D';
export interface SpendForecast { tenantId:string; forecastWindow:EconomicForecastWindow; projectedMonthlySpend:number; projectedAnnualizedSpend:number; spendGrowthRate:number; confidence:number; evidenceRefs:string[]; assumptions:string[]; projectedSpendTrajectory:number[]; spendAccelerationRisk:number; duplicateSpendRisk:number; aiSpendGrowthRisk:number; costConcentrationRisk:number; }
export interface SavingsRealizationForecast { tenantId:string; recommendationId:string; projectedSavings:number; realizationProbability:number; reversalProbability:number; confidence:number; evidenceRefs:string[]; assumptions:string[]; projectedSavingsRealizationRate:number; projectedReversalRate:number; projectedFalsePositiveRisk:number; projectedGovernanceFriction:number; }
export interface GovernanceDriftForecast { tenantId:string; projectedRiskLevel:'LOW'|'MODERATE'|'HIGH'|'CRITICAL'; projectedDriftAreas:string[]; driftAccelerationRisk:number; confidence:number; evidenceRefs:string[]; projectedDriftRisk:number; projectedCriticalAreas:string[]; governanceHealthTrend:'IMPROVING'|'STABLE'|'DECLINING'; }
export interface AIAdoptionForecast { tenantId:string; departmentId:string; projectedAdoptionRate:number; projectedToolSprawlRisk:number; projectedGovernanceRisk:number; projectedProductivityGain:number; confidence:number; projectedAIEfficiency:number; projectedWasteRisk:number; }
export interface ProductivityOutcomeForecast { tenantId:string; departmentId:string; projectedProductivityGain:number; projectedContractorReduction:number; projectedEfficiencyGain:number; projectedOutcomeConfidence:number; projectedFailureRisk:number; evidenceRefs:string[]; assumptions:string[]; }
export interface RecommendationRealizationForecast { tenantId:string; recommendationId:string; approvalLikelihood:number; deferralLikelihood:number; reversalLikelihood:number; projectedOperationalFriction:number; projectedSavingsRealization:number; projectedGovernanceFriction:number; confidence:number; evidenceRefs:string[]; assumptions:string[]; }
export interface EconomicRiskForecast { tenantId:string; riskType:string; projectedSeverity:'LOW'|'MODERATE'|'HIGH'|'CRITICAL'; projectedImpact:number; confidence:number; mitigationRecommendation:string; evidenceRefs:string[]; }
export interface CrossDomainEfficiencyForecast { tenantId:string; forecastWindow:EconomicForecastWindow; projectedEfficiencyScore:number; projectedSavingsOpportunity:number; projectedConsolidationOpportunity:number; projectedGovernanceEfficiency:number; confidence:number; evidenceRefs:string[]; assumptions:string[]; }
export interface ForecastConfidenceResult { confidenceScore:number; confidenceBand:'VERY_HIGH'|'HIGH'|'MODERATE'|'LOW'|'SPECULATIVE'; confidenceReasons:string[]; uncertaintyFactors:string[]; }
export interface EconomicIntelligenceReport { tenantId:string; forecastWindow:EconomicForecastWindow; projectedSpendGrowth:number; projectedSavingsRealization:number; projectedGovernanceDrift:number; projectedAIAdoption:number; projectedProductivityGain:number; projectedEconomicRisk:number; projectedToolSprawlRisk:number; projectedDuplicateSavingsRisk:number; projectedConsolidationOpportunity:number; governanceHealthTrend:'IMPROVING'|'STABLE'|'DECLINING'; economicEfficiencyTrend:'IMPROVING'|'STABLE'|'DECLINING'; forecastConfidenceScore:number; readinessStatus:'READY_FOR_FORECAST_DRIVEN_GOVERNANCE'|'READY_WITH_LIMITS'|'HARDENING_REQUIRED'; topForecastRisks:string[]; topForecastOpportunities:string[]; evidenceRefs:string[]; assumptions:string[]; }
