import { db, executionApprovalsTable } from "@workspace/db";
import { and, desc, eq } from "drizzle-orm";
import { emitPlatformEvent } from "../observability/platform-events";
import { PrincipalAuthorityService } from "../principal-authority-service";
import { EvidenceRegistryV2Service } from "../evidence-registry-v2-service";

export class ExecutionApprovalService {
  private principals = new PrincipalAuthorityService();
  private evidenceRegistry = new EvidenceRegistryV2Service();
  requestApproval(input:any){ return db.insert(executionApprovalsTable).values({ ...input, approvalStatus: "PENDING" }).returning().then(async ([r])=>{ const requester = await this.principals.resolvePrincipal({ tenantId: r.tenantId, email: r.requestedBy, displayName: r.requestedBy }); if (requester) await this.principals.recordActionEvent({ tenantId: r.tenantId, principalId: requester.id, actionContextType: "APPROVAL", actionContextId: String(r.id), role: "REQUESTED", metadata: { rawIdentity: r.requestedBy } }); const ev = await this.evidenceRegistry.createEvidenceItem({ tenantId: r.tenantId, evidenceType: "APPROVAL", sourceSystem: "CERTEN", sourceEntityType: "execution_approvals", sourceEntityId: String(r.id), collectedByPrincipalId: requester?.id, payload: r }); await this.evidenceRegistry.linkEvidenceToEntity({ tenantId: r.tenantId, evidenceItemId: ev.id, linkedEntityType: "APPROVAL", linkedEntityId: String(r.id), relationshipType: "AUDIT_TRAIL" }); await emitPlatformEvent({ tenantId:r.tenantId,eventType:"EXECUTION_APPROVAL_REQUESTED",severity:"INFO",source:"governance-approval",correlationId:`approval:${r.id}`,entityType:r.entityType,entityId:r.entityId,message:"Approval requested",evidence:r }); return r; }); }
  async approve(id:number, actorId:string, evidence:any={}){ const [r]=await db.select().from(executionApprovalsTable).where(eq(executionApprovalsTable.id,id)).limit(1); if(!r) throw new Error("APPROVAL_NOT_FOUND");
    const approver = await this.principals.resolvePrincipal({ tenantId: r.tenantId, email: actorId, displayName: actorId });
    const approvedBy=[...(r.approvedBy as any[]),actorId]; const current=approvedBy.length; const status=current>=r.requiredApprovals?"APPROVED":"PENDING";
    const [u]=await db.update(executionApprovalsTable).set({ approvedBy, currentApprovals:current, approvalStatus:status, approvalEvidence:{...(r.approvalEvidence as any),...evidence}}).where(eq(executionApprovalsTable.id,id)).returning();
    if (approver) await this.principals.recordActionEvent({ tenantId: u.tenantId, principalId: approver.id, actionContextType: "APPROVAL", actionContextId: String(u.id), role: "APPROVED", metadata: { rawIdentity: actorId } }); const ev = await this.evidenceRegistry.createEvidenceItem({ tenantId: u.tenantId, evidenceType: "APPROVAL", sourceSystem: "CERTEN", sourceEntityType: "execution_approvals", sourceEntityId: String(u.id), collectedByPrincipalId: approver?.id, payload: { approval: u, evidence } }); await this.evidenceRegistry.linkEvidenceToEntity({ tenantId: u.tenantId, evidenceItemId: ev.id, linkedEntityType: "APPROVAL", linkedEntityId: String(u.id), relationshipType: "PROVES" });
    await emitPlatformEvent({ tenantId:u.tenantId,eventType:"EXECUTION_APPROVAL_UPDATED",severity:"INFO",source:"governance-approval",correlationId:`approval:${u.id}`,entityType:u.entityType,entityId:u.entityId,message:"Approval updated",evidence:u }); return u; }
  async reject(id:number, actorId:string, reason?:string){ const [r]=await db.select().from(executionApprovalsTable).where(eq(executionApprovalsTable.id,id)).limit(1); if(!r) throw new Error("APPROVAL_NOT_FOUND");
    const [u]=await db.update(executionApprovalsTable).set({ rejectedBy:[...(r.rejectedBy as any[]),actorId], approvalStatus:"REJECTED", approvalEvidence:{...(r.approvalEvidence as any),reason}}).where(eq(executionApprovalsTable.id,id)).returning();
    await emitPlatformEvent({ tenantId:u.tenantId,eventType:"EXECUTION_APPROVAL_REJECTED",severity:"WARNING",source:"governance-approval",correlationId:`approval:${u.id}`,entityType:u.entityType,entityId:u.entityId,message:"Approval rejected",evidence:u }); return u; }
  async expire(id:number){ const [u]=await db.update(executionApprovalsTable).set({ approvalStatus:"EXPIRED" }).where(and(eq(executionApprovalsTable.id,id),eq(executionApprovalsTable.approvalStatus,"PENDING"))).returning(); return u; }
  getApprovalStatus(id:number){ return db.select().from(executionApprovalsTable).where(eq(executionApprovalsTable.id,id)).orderBy(desc(executionApprovalsTable.updatedAt)).limit(1).then((r)=>r[0] ?? null); }
}
