import type { CommandViewRuntimeOptions } from './commandViewData'
import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'
import type { M365ConnectorReadinessStatus, M365SyncStatus } from './m365BetaTypes'

export interface ConnectorHubState { metadata: ControlPlaneRuntimeMetadata; summary:{healthy:number;degraded:number;blocked:number;liveConnectors:number;syntheticConnectors:number}; m365?: { readinessStatus: M365ConnectorReadinessStatus; syncStatus: M365SyncStatus; lastCheckedAt?: string; lastSyncAt?: string; checks: Array<{ id: string; status: 'PASSED'|'WARNING'|'FAILED'; detail: string }>; canSync: boolean; canSmokeTest: boolean; canExecute: boolean; smokeTest?: any; syncResult?: any; productionReadinessCounts?: { readyForApproval: number; needsHardening: number; notReady: number } }; connectors:Array<{id:string;name:string;domain:string;mode:'SYNTHETIC'|'LIVE'|'HYBRID';capability:'READ_ONLY'|'GOVERNED_EXECUTION'|'NONE';health:'HEALTHY'|'DEGRADED'|'BLOCKED'|'UNKNOWN';statusDetail:string;lastSyncAt?:string;freshness?:string;actions:{canConnect:boolean;canSmokeTest:boolean;canSync:boolean;canExecute:boolean}}> }

export async function loadConnectorHubState(runtime: CommandViewRuntimeOptions): Promise<ConnectorHubState> {
 if (runtime.environment === 'DEMO') { const connectors=[{id:'m365',name:'M365',domain:'saas',mode:'SYNTHETIC' as const,capability:'NONE' as const,health:'DEGRADED' as const,statusDetail:'Synthetic sandbox connector',actions:{canConnect:false,canSmokeTest:false,canSync:false,canExecute:false}}]; return { metadata:{environment:'DEMO',tenantId:runtime.tenantId,dataSource:'DEMO_SEED'}, summary:{healthy:0,degraded:1,blocked:0,liveConnectors:0,syntheticConnectors:connectors.length}, connectors, m365: { readinessStatus:'DEGRADED', syncStatus:'NEVER_SYNCED', checks:[{id:'DEMO_ONLY',status:'WARNING',detail:'Synthetic evidence only.'}], canSync:false, canSmokeTest:false, canExecute:false, productionReadinessCounts:{readyForApproval:0,needsHardening:0,notReady:0} } } }
 try {
  const [rows, readiness, status] = await Promise.all([
    fetch('/api/connectors').then(r=>r.json()),
    fetch('/api/connectors/m365/readiness').then(r=>r.ok?r.json():{ status: 'NOT_CONFIGURED', checks: [] }),
    fetch('/api/connectors/m365/status').then(r=>r.ok?r.json():null),
  ])
  const connectors=(rows??[]).map((c:any)=>({id:String(c.id),name:String(c.name),domain:String(c.type ?? 'saas'),mode:'LIVE' as const,capability:runtime.executionCapabilities.liveExecutionEnabled?'GOVERNED_EXECUTION' as const:'READ_ONLY' as const,health:String(c.status)==='connected'?'HEALTHY' as const:String(c.status)==='syncing'?'DEGRADED' as const:'BLOCKED' as const,statusDetail:`${c.status}`,lastSyncAt:c.lastSync,freshness:c.lastSync,actions:{canConnect:false,canSmokeTest:String(c.name).toLowerCase().includes('m365'),canSync:String(c.name).toLowerCase().includes('m365'),canExecute:false}}))
  const ds=connectors.length?'LIVE_API':'LIVE_EMPTY'
  const m365 = { readinessStatus: (readiness?.status ?? 'NOT_CONFIGURED') as M365ConnectorReadinessStatus, syncStatus: (status?.syncStatus ?? 'NEVER_SYNCED') as M365SyncStatus, lastCheckedAt: readiness?.lastCheckedAt, lastSyncAt: status?.lastSyncTime, checks: Array.isArray(readiness?.checks) ? readiness.checks : [], canSync: Boolean(readiness?.canSync), canSmokeTest: Boolean(readiness?.canSmokeTest), canExecute: false, productionReadinessCounts: status?.productionReadinessCounts ?? { readyForApproval: 0, needsHardening: 0, notReady: 0 } }
  return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:ds}, summary:{healthy:connectors.filter((c:any)=>c.health==='HEALTHY').length,degraded:connectors.filter((c:any)=>c.health==='DEGRADED').length,blocked:connectors.filter((c:any)=>c.health==='BLOCKED').length,liveConnectors:connectors.length,syntheticConnectors:0}, connectors, m365 }
 } catch { return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:'LIVE_ERROR',error:'Failed to load connectors API.'}, summary:{healthy:0,degraded:0,blocked:0,liveConnectors:0,syntheticConnectors:0}, connectors:[], m365: { readinessStatus:'NOT_CONFIGURED', syncStatus:'FAILED', checks:[{id:'CONNECTOR_API',status:'FAILED',detail:'Failed to load m365 readiness.'}], canSync:false, canSmokeTest:false, canExecute:false, productionReadinessCounts:{readyForApproval:0,needsHardening:0,notReady:0} } } }
}
