import type { CommandViewRuntimeOptions } from './commandViewData'
import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'

export interface DriftMonitorState { metadata: ControlPlaneRuntimeMetadata; summary:{activeDriftEvents:number;valueAtRisk:number;recurrencePrevented:number;monitoredOutcomes:number}; events:Array<{id:string;title:string;domain:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';status:'ACTIVE'|'MONITORING'|'RESOLVED'|'BLOCKED';valueAtRisk?:number;linkedOutcomeId?:string;detectedAt?:string;evidenceSummary?:string;recommendedAction:string}> }

export async function loadDriftMonitorState(runtime: CommandViewRuntimeOptions): Promise<DriftMonitorState> {
 if (runtime.environment==='DEMO') return { metadata:{environment:'DEMO',tenantId:runtime.tenantId,dataSource:'DEMO_SEED'}, summary:{activeDriftEvents:1,valueAtRisk:900,recurrencePrevented:2,monitoredOutcomes:3}, events:[{id:'d1',title:'License reclaim recurrence watch',domain:'saas',severity:'MEDIUM',status:'ACTIVE',valueAtRisk:900,linkedOutcomeId:'o1',detectedAt:'2026-05-01T09:00:00.000Z',evidenceSummary:'Synthetic drift scenario',recommendedAction:'Review synthetic recurrence evidence'}] }
 try { const rows=await fetch('/api/drift/events').then(r=>r.json()); const events=(rows??[]).map((e:any)=>({id:String(e.id),title:e.driftReason??e.reversalReason??'Drift event',domain:'saas',severity:'MEDIUM' as const,status:String(e.status??'ACTIVE').toUpperCase()==='OPEN'?'ACTIVE' as const:'MONITORING' as const,valueAtRisk:Number(e.realizationDelta??0),linkedOutcomeId:e.outcomeLedgerId?String(e.outcomeLedgerId):undefined,detectedAt:e.createdAt,evidenceSummary:'Live drift signal',recommendedAction:'Investigate drift recurrence and validate outcome integrity'})); const ds=events.length?'LIVE_API':'LIVE_EMPTY'; return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:ds}, summary:{activeDriftEvents:events.filter((e:any)=>e.status==='ACTIVE').length,valueAtRisk:events.reduce((a:number,e:any)=>a+Number(e.valueAtRisk??0),0),recurrencePrevented:0,monitoredOutcomes:events.length}, events }
 } catch { return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:'LIVE_ERROR',error:'Failed to load drift APIs.'}, summary:{activeDriftEvents:0,valueAtRisk:0,recurrencePrevented:0,monitoredOutcomes:0}, events:[] } }
}
