import type { CommandViewRuntimeOptions } from './commandViewData'
import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'

export interface ExecutionState { metadata: ControlPlaneRuntimeMetadata; summary: { queued:number; dryRunReady:number; approvalPending:number; executing:number; verified:number; failed:number; rollbackAvailable:number }; records: Array<{ id:string; title:string; domain:string; status:'QUEUED'|'DRY_RUN_READY'|'APPROVAL_PENDING'|'EXECUTING'|'EXECUTED'|'VERIFIED'|'FAILED'|'BLOCKED'|'ROLLED_BACK'; environment:'DEMO'|'LIVE'; executionMode:string; actor?:string; requestedAt?:string; completedAt?:string; projectedMonthlySavings?:number; verifiedMonthlySavings?:number; rollbackStatus?:string; evidenceSummary?:string; nextStep:string }> }

export async function loadExecutionState(runtime: CommandViewRuntimeOptions): Promise<ExecutionState> {
 if (runtime.environment === 'DEMO') return { metadata:{environment:'DEMO',tenantId:runtime.tenantId,dataSource:'DEMO_SEED'}, summary:{queued:1,dryRunReady:1,approvalPending:1,executing:0,verified:1,failed:0,rollbackAvailable:2}, records:[{id:'ex1',title:'OpenAI route policy update',domain:'ai',status:'DRY_RUN_READY',environment:'DEMO',executionMode:'SIMULATED',requestedAt:'2026-05-01T09:00:00.000Z',projectedMonthlySavings:11200,rollbackStatus:'AVAILABLE',evidenceSummary:'Synthetic execution record.',nextStep:'Simulate execution'}] }
 try { const [verifications, obs] = await Promise.all([fetch('/api/execution-orchestration/verifications').then(r=>r.json()), fetch('/api/execution-orchestration/observability/summary').then(r=>r.json())]); const records=(verifications??[]).map((v:any)=>({id:String(v.id),title:v.recommendationId?`Recommendation ${v.recommendationId}`:'Execution item',domain:'saas',status:String(v.verificationStatus??'QUEUED').includes('VERIFIED')?'VERIFIED':'QUEUED',environment:'LIVE' as const,executionMode:'READ_ONLY_BETA',actor:v.verifiedBy,requestedAt:v.createdAt,completedAt:v.verifiedAt,projectedMonthlySavings:Number(v.expectedMonthlySaving??0),verifiedMonthlySavings:Number(v.actualMonthlySaving??0),rollbackStatus:v.rollbackStatus??'UNKNOWN',evidenceSummary:'Live verification record.',nextStep:'Governed execution is disabled in this beta workspace. Dry-run and approval workflows remain available.'})); const ds=records.length?'LIVE_API':'LIVE_EMPTY'; return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:ds}, summary:{queued:Number(obs?.readyItems??0),dryRunReady:Number(obs?.readyItems??0),approvalPending:0,executing:Number(obs?.runningItems??0),verified:Number(obs?.verifiedOutcomes??0),failed:Number(obs?.failedVerifications??0),rollbackAvailable:Number(obs?.rollbackReviewsNeeded??0)}, records }
 } catch { return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:'LIVE_ERROR',error:'Failed to load execution APIs.'}, summary:{queued:0,dryRunReady:0,approvalPending:0,executing:0,verified:0,failed:0,rollbackAvailable:0}, records:[] } }
}
