import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'
import type { CommandViewRuntimeOptions } from './commandViewData'

export interface GovernanceState { metadata: ControlPlaneRuntimeMetadata; summary: { approvalsRequired: number; blockedActions: number; policyWarnings: number; highRiskActions: number; averageTrustScore?: number }; approvalQueue: Array<{ id: string; title: string; domain: string; approvalState: 'PENDING'|'APPROVED'|'REJECTED'|'NOT_REQUIRED'; requestedBy?: string; requestedAt?: string; riskClass?: string; trustScore?: number; projectedMonthlySavings?: number; reason: string; nextStep: string }>; blockedActions: Array<{ id: string; title: string; domain: string; blocker: string; trustScore?: number; policyOutcome?: string; remediationStep: string }>; policyGates: Array<{ id: string; label: string; status: 'PASSED'|'WARNING'|'FAILED'|'BLOCKED'|'NOT_AVAILABLE'; detail: string }> }

export async function loadGovernanceState(runtime: CommandViewRuntimeOptions): Promise<GovernanceState> {
  if (runtime.environment === 'DEMO') return { metadata: { environment: 'DEMO', tenantId: runtime.tenantId, dataSource: 'DEMO_SEED' }, summary: { approvalsRequired: 2, blockedActions: 1, policyWarnings: 2, highRiskActions: 1, averageTrustScore: 79 }, approvalQueue: [{ id: 'd-a1', title: 'AWS rightsize batch', domain: 'cloud', approvalState: 'PENDING', requestedBy: 'demo.operator', requestedAt: '2026-05-01T09:00:00.000Z', riskClass: 'B', trustScore: 81, projectedMonthlySavings: 6800, reason: 'Synthetic approval gate.', nextStep: 'Simulated approval flow' }], blockedActions: [{ id: 'd-b1', title: 'M365 reclaim cohort', domain: 'saas', blocker: 'Synthetic trust freshness blocker', trustScore: 61, policyOutcome: 'BLOCKED', remediationStep: 'Refresh synthetic evidence feed' }], policyGates: [{ id: 'g1', label: 'Policy fit', status: 'PASSED', detail: 'Synthetic policy checks passed' }, { id: 'g2', label: 'Approval requirement', status: 'WARNING', detail: 'Approval required in synthetic flow' }] }
  try {
    const [approvals, recs] = await Promise.all([fetch('/api/approvals?tenantId=default').then((r)=>r.json()), fetch('/api/recommendations').then((r)=>r.json())])
    const approvalQueue = (approvals ?? []).map((a:any)=>({ id:String(a.id), title:`Recommendation ${a.recommendationId}`, domain:'saas', approvalState:String(a.status ?? 'PENDING').includes('APPROV')?'APPROVED':'PENDING', requestedBy:a.requestedBy, requestedAt:a.createdAt, riskClass:a.riskClass, trustScore:undefined, projectedMonthlySavings:undefined, reason:'Live approval record.', nextStep:'Approval action endpoint not enabled in this beta build.' }))
    const blockedActions = (recs ?? []).filter((r:any)=>String(r.executionStatus).includes('BLOCK')).map((r:any)=>({ id:String(r.id), title:r.displayName ?? r.userEmail, domain:r.connector ?? 'saas', blocker:'Execution status blocked', trustScore:Math.round((Number(r.trustScore ?? 0))*100), policyOutcome:'BLOCKED', remediationStep:'Resolve trust/policy blockers.' }))
    const avg = (recs ?? []).length ? Math.round((recs.reduce((a:number,r:any)=>a+Number(r.trustScore ?? 0),0)/(recs.length))*100) : undefined
    const dataSource = (approvalQueue.length || blockedActions.length) ? 'LIVE_API' : 'LIVE_EMPTY'
    return { metadata: { environment: 'LIVE', tenantId: runtime.tenantId, dataSource }, summary: { approvalsRequired: approvalQueue.filter((a:any)=>a.approvalState==='PENDING').length, blockedActions: blockedActions.length, policyWarnings: approvalQueue.length, highRiskActions: approvalQueue.filter((a:any)=>a.riskClass==='A').length, averageTrustScore: avg }, approvalQueue, blockedActions, policyGates: [{ id:'lg1', label:'Policy fit', status:'NOT_AVAILABLE', detail:'Detailed live policy gate endpoint not available.' }] }
  } catch { return { metadata: { environment: 'LIVE', tenantId: runtime.tenantId, dataSource: 'LIVE_ERROR', error: 'Failed to load governance APIs.' }, summary: { approvalsRequired:0, blockedActions:0, policyWarnings:0, highRiskActions:0 }, approvalQueue: [], blockedActions: [], policyGates: [] } }
}
