import type { ConnectorConfig } from '../types/connector'
import type { GovernanceAction, AuditEntry, ExecutionRecord } from '../types/governance'

export const CONNECTORS: ConnectorConfig[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    domain: 'ai',
    description: 'AI runtime economics · token spend · model usage',
    iconType: 'ai',
    readiness: 'READY',
    enabled: true,
    lastSyncAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    evidenceSources: [
      { id: 'openai-usage', name: 'Usage API v2', iconType: 'api', trustScore: 99, lastSyncAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'openai-billing', name: 'Billing export', iconType: 'billing', trustScore: 96, lastSyncAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'openai-audit', name: 'Org audit log', iconType: 'audit', trustScore: 74, lastSyncAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), status: 'LAGGING' },
    ],
  },
  {
    id: 'aws',
    name: 'AWS',
    domain: 'cloud',
    description: 'Cloud spend · EC2 · S3 · RDS · Cost Explorer',
    iconType: 'cloud-aws',
    readiness: 'DEGRADED',
    enabled: true,
    lastSyncAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    evidenceSources: [
      { id: 'aws-cost-explorer', name: 'Cost Explorer API', iconType: 'api', trustScore: 82, lastSyncAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), status: 'LAGGING' },
      { id: 'aws-billing', name: 'CUR export', iconType: 'export', trustScore: 88, lastSyncAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), status: 'LAGGING' },
      { id: 'aws-cloudtrail', name: 'CloudTrail', iconType: 'audit', trustScore: 91, lastSyncAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), status: 'LAGGING' },
    ],
  },
  {
    id: 'azure',
    name: 'Azure',
    domain: 'cloud',
    description: 'Cloud spend · Cost Management · Advisor',
    iconType: 'cloud-az',
    readiness: 'READY',
    enabled: true,
    lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    evidenceSources: [
      { id: 'azure-cost', name: 'Cost Management API', iconType: 'api', trustScore: 97, lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'azure-billing', name: 'Billing export', iconType: 'billing', trustScore: 95, lastSyncAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'azure-advisor', name: 'Advisor API', iconType: 'api', trustScore: 88, lastSyncAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(), status: 'ACTIVE' },
    ],
  },
  {
    id: 'm365',
    name: 'M365 / Entra ID',
    domain: 'saas',
    description: 'License audit · seat activity · SaaS spend',
    iconType: 'saas',
    readiness: 'READY',
    enabled: true,
    lastSyncAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    evidenceSources: [
      { id: 'm365-graph', name: 'Graph API', iconType: 'api', trustScore: 98, lastSyncAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'm365-billing', name: 'Billing API', iconType: 'billing', trustScore: 99, lastSyncAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'm365-audit', name: 'Audit log', iconType: 'audit', trustScore: 93, lastSyncAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), status: 'ACTIVE' },
    ],
  },
  {
    id: 'servicenow',
    name: 'ServiceNow ITAM',
    domain: 'itam',
    description: 'Asset inventory · hardware lifecycle · CMDB feed',
    iconType: 'itam',
    readiness: 'UNAVAILABLE',
    enabled: false,
    lastSyncAt: null,
    evidenceSources: [],
  },
  {
    id: 'flexera',
    name: 'Flexera Authority',
    domain: 'saas',
    description: 'Authority source · entitlement validation · license position evidence',
    iconType: 'saas',
    readiness: 'UNAVAILABLE',
    enabled: false,
    lastSyncAt: null,
    evidenceSources: [],
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    domain: 'data',
    description: 'Warehouse economics · query spend · credit burn',
    iconType: 'data',
    readiness: 'READY',
    enabled: true,
    lastSyncAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    evidenceSources: [
      { id: 'sf-account', name: 'Account usage', iconType: 'api', trustScore: 99, lastSyncAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'sf-query', name: 'Query history', iconType: 'audit', trustScore: 97, lastSyncAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(), status: 'ACTIVE' },
      { id: 'sf-billing', name: 'Credit billing', iconType: 'billing', trustScore: 100, lastSyncAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(), status: 'ACTIVE' },
    ],
  },
]

export const GOVERNANCE_ACTIONS: GovernanceAction[] = [
  {
    id: 'ga-001',
    name: 'Downgrade GPT-4 → GPT-3.5-turbo for simple tasks',
    description: 'AI runtime: 847 requests/day with avg 52 input tokens — eligible for model routing',
    domain: 'ai',
    savingAmount: 1240,
    verdict: 'GOVERNED_EXECUTION_ELIGIBLE',
    blastRadius: 'LOW',
    rollback: 'FULL',
    certId: 'GEC-2026-05-22-AI-0001',
    proofChain: [
      { id: 'p1', label: 'Telemetry validated', detail: 'OpenAI Usage API v2 · 30-day baseline · 99% trust', status: 'PASS', proofHash: 'a3f7c2e1b8d94' },
      { id: 'p2', label: 'Cost model applied', detail: 'GPT-4 $0.00003/tok → GPT-3.5-turbo $0.0000005/tok · 60× cheaper', status: 'PASS', proofHash: 'b9e2a4f1c6d83' },
      { id: 'p3', label: 'Blast radius assessed', detail: 'Affected workflows: 2 · No downstream dependencies · Rollback: full routing revert', status: 'PASS', proofHash: 'c4d1b7e9a2f56' },
      { id: 'p4', label: 'Policy gate cleared', detail: 'Risk class C · Single approval sufficient · No dual-approval required', status: 'PASS', proofHash: null },
    ],
  },
  {
    id: 'ga-002',
    name: 'Right-size EC2 c5.2xlarge → c5.xlarge (us-east-1)',
    description: 'Cloud: 14 instances averaging 18% CPU over 60 days — 3× over-provisioned',
    domain: 'cloud',
    savingAmount: 3840,
    verdict: 'APPROVAL_REQUIRED',
    blastRadius: 'MEDIUM',
    rollback: 'FULL',
    certId: 'GEC-2026-05-22-CLD-0002',
    proofChain: [
      { id: 'p1', label: 'Utilisation data confirmed', detail: 'AWS Cost Explorer · 60-day P95 CPU: 18% · Memory: 22%', status: 'PASS', proofHash: 'd7e3c9b1a4f28' },
      { id: 'p2', label: 'Degraded connector caveat', detail: 'AWS connector refreshed 3h ago — data may be stale by up to 3 hours', status: 'WARN', proofHash: null },
      { id: 'p3', label: 'Risk class B — dual approval required', detail: 'Production workloads affected · Requires FinOps Manager + Engineering Lead', status: 'WARN', proofHash: null },
    ],
  },
  {
    id: 'ga-003',
    name: 'Reclaim 94 inactive M365 E3 licences',
    description: 'SaaS: 94 seats with zero sign-in for 90+ days · £37.80/seat/month',
    domain: 'saas',
    savingAmount: 42840,
    verdict: 'GOVERNED_EXECUTION_ELIGIBLE',
    blastRadius: 'LOW',
    rollback: 'FULL',
    certId: 'GEC-2026-05-22-M365-0042',
    proofChain: [
      { id: 'p1', label: 'Seat activity verified', detail: 'Graph API · 90-day last sign-in audit · 94 confirmed inactive', status: 'PASS', proofHash: 'e2f8a3c7b1d94' },
      { id: 'p2', label: 'Billing confirmed', detail: 'M365 Billing API · E3 £37.80/seat · Annual contract · Monthly reclaim window open', status: 'PASS', proofHash: 'f1a9b4d2c8e37' },
      { id: 'p3', label: 'Rollback plan verified', detail: 'Licences held in pool for 30 days · Reinstatement < 4h · No data loss', status: 'PASS', proofHash: null },
    ],
  },
  {
    id: 'ga-004',
    name: 'Snowflake warehouse auto-suspend (XL → auto-suspend 60s)',
    description: 'Data: ANALYTICS_WH running 24/7 with 8% query coverage — 2,640 idle credit-hours/month',
    domain: 'data',
    savingAmount: 9240,
    verdict: 'GOVERNED_EXECUTION_ELIGIBLE',
    blastRadius: 'LOW',
    rollback: 'FULL',
    certId: 'GEC-2026-05-22-DATA-0003',
    proofChain: [
      { id: 'p1', label: 'Credit burn quantified', detail: 'Snowflake account usage · 2,640 idle credits · $3.50/credit · $9,240/month', status: 'PASS', proofHash: 'a8c2e7f4b1d63' },
      { id: 'p2', label: 'Query pattern analysed', detail: 'P99 query duration: 42s · Auto-suspend 60s covers 100% of workload', status: 'PASS', proofHash: 'b3d9a1f7c4e28' },
      { id: 'p3', label: 'No SLA impact', detail: 'Resume latency: 2-4s · All dashboards operate on cached results · No user impact', status: 'PASS', proofHash: null },
    ],
  },
  {
    id: 'ga-005',
    name: 'Decommission legacy ServiceNow CMDB sync job',
    description: 'ITAM: ServiceNow connector unconfigured — sync job consuming $240/month in compute with no output',
    domain: 'itam',
    savingAmount: 240,
    verdict: 'MANUAL_ONLY',
    blastRadius: 'LOW',
    rollback: 'FULL',
    certId: null,
    proofChain: [
      { id: 'p1', label: 'Connector unavailable', detail: 'ServiceNow ITAM not configured — cannot validate CMDB dependencies', status: 'WARN', proofHash: null },
      { id: 'p2', label: 'Manual review required', detail: 'Configure ServiceNow connector first to enable automated governance', status: 'WARN', proofHash: null },
    ],
  },
  {
    id: 'ga-006',
    name: 'Reserved Instance coverage: RDS PostgreSQL (1yr No-Upfront)',
    description: 'Cloud: 3 on-demand db.r6g.2xlarge instances running continuously for 180 days',
    domain: 'cloud',
    savingAmount: 18600,
    verdict: 'APPROVAL_REQUIRED',
    blastRadius: 'HIGH',
    rollback: 'NONE',
    certId: 'GEC-2026-05-22-CLD-0006',
    proofChain: [
      { id: 'p1', label: 'Utilisation validated', detail: 'AWS Cost Explorer · 180 days on-demand · 98% uptime · Committed workload', status: 'PASS', proofHash: 'c9e4b2f8a7d15' },
      { id: 'p2', label: 'Commitment risk flagged', detail: '1-year commitment · No rollback after purchase · CFO sign-off required', status: 'WARN', proofHash: null },
      { id: 'p3', label: 'AWS connector degraded caveat', detail: 'Stale data risk: last sync 3h ago · Verify pricing before committing', status: 'WARN', proofHash: null },
    ],
  },
]

export const AUDIT_ENTRIES: AuditEntry[] = [
  { id: 'ae-001', timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(), action: 'Model downgrade GPT-4 → GPT-3.5-turbo approved', verdict: 'GOVERNED_EXECUTION_ELIGIBLE', domain: 'ai', certId: 'GEC-2026-05-22-AI-0001', actorId: 'j.doe@acme.com' },
  { id: 'ae-002', timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(), action: 'M365 licence reclaim: 94 seats queued for execution', verdict: 'GOVERNED_EXECUTION_ELIGIBLE', domain: 'saas', certId: 'GEC-2026-05-22-M365-0042', actorId: 'j.doe@acme.com' },
  { id: 'ae-003', timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), action: 'EC2 right-size: first approval recorded (FinOps Manager)', verdict: 'APPROVAL_REQUIRED', domain: 'cloud', certId: 'GEC-2026-05-22-CLD-0002', actorId: 'j.doe@acme.com' },
  { id: 'ae-004', timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), action: 'Snowflake auto-suspend executed — ANALYTICS_WH configured', verdict: 'GOVERNED_EXECUTION_ELIGIBLE', domain: 'data', certId: 'GEC-2026-05-22-DATA-0003', actorId: 'system' },
  { id: 'ae-005', timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), action: 'RDS Reserved Instance: NEVER_ELIGIBLE — no rollback possible on commitment', verdict: 'NEVER_ELIGIBLE', domain: 'cloud', certId: null, actorId: 'system' },
]

export const EXECUTION_RECORDS: ExecutionRecord[] = [
  {
    id: 'er-001',
    name: 'Snowflake ANALYTICS_WH auto-suspend',
    domain: 'data',
    approvedBy: 'j.doe@acme.com',
    approvedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    executedAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    blastRadius: 'LOW',
    rollback: 'FULL',
    savingRealised: 9240,
    certId: 'GEC-2026-05-22-DATA-0003',
    status: 'COMPLETED',
  },
  {
    id: 'er-002',
    name: 'M365 licence reclaim (94 seats)',
    domain: 'saas',
    approvedBy: 'j.doe@acme.com',
    approvedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    executedAt: null,
    blastRadius: 'LOW',
    rollback: 'FULL',
    savingRealised: null,
    certId: 'GEC-2026-05-22-M365-0042',
    status: 'QUEUED',
  },
  {
    id: 'er-003',
    name: 'Model downgrade GPT-4 → GPT-3.5-turbo',
    domain: 'ai',
    approvedBy: 'j.doe@acme.com',
    approvedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    executedAt: null,
    blastRadius: 'LOW',
    rollback: 'FULL',
    savingRealised: null,
    certId: 'GEC-2026-05-22-AI-0001',
    status: 'QUEUED',
  },
]
