import type { CommandViewRuntimeOptions } from './commandViewData'
import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'

export interface OutcomeLedgerState { metadata: ControlPlaneRuntimeMetadata; summary:{projectedMonthlySavings:number;verifiedMonthlySavings:number;projectedAnnualSavings:number;verifiedAnnualSavings:number;outcomesRecorded:number;verificationPending:number;savingsConfidence?:string}; outcomes:Array<{id:string;title:string;domain:string;environment:'DEMO'|'LIVE';status:'PROJECTED'|'APPROVED'|'EXECUTED'|'VERIFIED'|'DRIFTED'|'BLOCKED';projectedMonthlySavings?:number;verifiedMonthlySavings?:number;confidence?:string;evidenceSummary?:string;approvedBy?:string;executedBy?:string;verifiedAt?:string;driftStatus?:string}> }

export async function loadOutcomeLedgerState(runtime: CommandViewRuntimeOptions): Promise<OutcomeLedgerState> {
 if (runtime.environment==='DEMO') return { metadata:{environment:'DEMO',tenantId:runtime.tenantId,dataSource:'DEMO_SEED'}, summary:{projectedMonthlySavings:24800,verifiedMonthlySavings:4200,projectedAnnualSavings:297600,verifiedAnnualSavings:50400,outcomesRecorded:3,verificationPending:2,savingsConfidence:'SYNTHETIC_MEDIUM'}, outcomes:[{id:'o1',title:'OpenAI route policy update',domain:'ai',environment:'DEMO',status:'VERIFIED',projectedMonthlySavings:11200,verifiedMonthlySavings:4200,confidence:'SYNTHETIC',evidenceSummary:'Synthetic ledger record',driftStatus:'MONITORING'}] }
 try { const [rows,summary]=await Promise.all([fetch('/api/outcomes').then(r=>r.json()),fetch('/api/outcomes/summary').then(r=>r.json())]); const outcomes=(rows??[]).map((o:any)=>({id:String(o.id),title:o.displayName??o.userEmail??'Outcome',domain:'saas',environment:'LIVE' as const,status:o.executedAt?'EXECUTED':'APPROVED',projectedMonthlySavings:Number(o.monthlySaving??0),verifiedMonthlySavings:undefined,confidence:'NOT_YET_VERIFIED',evidenceSummary:'Live outcome ledger record',verifiedAt:o.executedAt})); const ds=outcomes.length?'LIVE_API':'LIVE_EMPTY'; return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:ds}, summary:{projectedMonthlySavings:Number(summary?.totalMonthlySaving??0),verifiedMonthlySavings:0,projectedAnnualSavings:Number(summary?.totalAnnualisedSaving??0),verifiedAnnualSavings:0,outcomesRecorded:outcomes.length,verificationPending:outcomes.length,savingsConfidence:'LOW'}, outcomes }
 } catch { return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:'LIVE_ERROR',error:'Failed to load outcome ledger APIs.'}, summary:{projectedMonthlySavings:0,verifiedMonthlySavings:0,projectedAnnualSavings:0,verifiedAnnualSavings:0,outcomesRecorded:0,verificationPending:0}, outcomes:[] } }
}
