import type { CommandViewRuntimeOptions } from './commandViewData'
import type { ControlPlaneRuntimeMetadata } from './controlPlaneTypes'

export interface OutcomeLedgerState { metadata: ControlPlaneRuntimeMetadata; summary:{projectedMonthlySavings:number;verifiedMonthlySavings:number;projectedAnnualSavings:number;verifiedAnnualSavings:number;savingsVariance:number;outcomesRecorded:number;verificationPending:number;failedVerification:number;driftDetected:number;driftPrevented:number;savingsConfidence?:string}; outcomes:Array<{id:string;title:string;domain:string;environment:'DEMO'|'LIVE';status:'PROJECTED'|'APPROVED'|'EXECUTED'|'VERIFIED'|'DRIFTED'|'BLOCKED';projectedMonthlySavings?:number;verifiedMonthlySavings?:number;confidence?:string;evidenceSummary?:string;approvedBy?:string;executedBy?:string;verifiedAt?:string;driftStatus?:string;badge?:string}>; byPlaybook:Array<{playbook:string;outcomes:number;projectedMonthlySavings:number;verifiedMonthlySavings:number}> }

export async function loadOutcomeLedgerState(runtime: CommandViewRuntimeOptions): Promise<OutcomeLedgerState> {
 if (runtime.environment==='DEMO') return { metadata:{environment:'DEMO',tenantId:runtime.tenantId,dataSource:'DEMO_SEED'}, summary:{projectedMonthlySavings:24800,verifiedMonthlySavings:4200,projectedAnnualSavings:297600,verifiedAnnualSavings:50400,savingsVariance:-20600,outcomesRecorded:3,verificationPending:2,failedVerification:0,driftDetected:1,driftPrevented:1,savingsConfidence:'SYNTHETIC_MEDIUM'}, outcomes:[{id:'o1',title:'OpenAI route policy update',domain:'ai',environment:'DEMO',status:'VERIFIED',projectedMonthlySavings:11200,verifiedMonthlySavings:4200,confidence:'SYNTHETIC',evidenceSummary:'Governance-controlled outcome · Evidence-backed',driftStatus:'MONITORING',badge:'Evidence-backed'}], byPlaybook:[{playbook:'OPENAI_ROUTE_POLICY',outcomes:1,projectedMonthlySavings:11200,verifiedMonthlySavings:4200}] }
 try {
   const tenantId = encodeURIComponent(runtime.tenantId ?? 'default')
   const [rows,summary,byPlaybook]=await Promise.all([
    fetch(`/api/outcomes/ledger?tenantId=${tenantId}`).then(r=>r.json()),
    fetch(`/api/outcomes/ledger/summary?tenantId=${tenantId}`).then(r=>r.json()),
    fetch(`/api/outcomes/ledger/by-playbook?tenantId=${tenantId}`).then(r=>r.json()),
   ])
   const outcomes=(rows??[]).map((o:any)=>{ const ev=o.evidence??{}; const st=String(ev.verificationState??'PENDING_VERIFICATION'); return ({id:String(o.id),title:o.displayName??o.userEmail??'Outcome',domain:'saas',environment:'LIVE' as const,status:st==='VERIFIED'?'VERIFIED':st.includes('FAILED')?'BLOCKED':'EXECUTED',projectedMonthlySavings:Number(o.monthlySaving??0),verifiedMonthlySavings:Number(ev.verifiedSaving??0)||undefined,confidence:'Evidence-backed',evidenceSummary:'Governance-controlled outcome · Evidence-backed',verifiedAt:ev.verifiedAt??o.executedAt,driftStatus:String(ev.driftStatus??'NO_DRIFT_DETECTED'),badge:'Evidence-backed'}) })
   const ds=outcomes.length?'LIVE_API':'LIVE_EMPTY'; return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:ds}, summary:{projectedMonthlySavings:Number(summary?.projectedMonthlySavings??0),verifiedMonthlySavings:Number(summary?.verifiedMonthlySavings??0),projectedAnnualSavings:Number(summary?.projectedAnnualSavings??0),verifiedAnnualSavings:Number(summary?.verifiedAnnualSavings??0),savingsVariance:Number(summary?.savingsVariance??0),outcomesRecorded:outcomes.length,verificationPending:Number(summary?.pendingVerificationCount??0),failedVerification:Number(summary?.failedVerificationCount??0),driftDetected:Number(summary?.driftDetectedCount??0),driftPrevented:Number(summary?.driftPreventedCount??0),savingsConfidence:'Evidence-backed'}, outcomes, byPlaybook:Array.isArray(byPlaybook)?byPlaybook:[] }
 } catch { return { metadata:{environment:'LIVE',tenantId:runtime.tenantId,dataSource:'LIVE_ERROR',error:'Failed to load outcome ledger APIs.'}, summary:{projectedMonthlySavings:0,verifiedMonthlySavings:0,projectedAnnualSavings:0,verifiedAnnualSavings:0,savingsVariance:0,outcomesRecorded:0,verificationPending:0,failedVerification:0,driftDetected:0,driftPrevented:0}, outcomes:[], byPlaybook:[] } }
}
