import { platformEventService } from "../../events/platform-event-service";
import { governedActionService, type GovernedAction } from "../../actions/governed-actions";
import { governedExecutionService, type ExecutionConnector, type ExecutionEvidence, type GovernedExecution, type GovernedExecutionStatus, type GovernedExecutionType } from "../../execution/governed-execution";
import { getTenantExecutionPolicy } from "../../runtime/live-tenant-safety";
import { economicOutcomeAttributionService } from "../../economic-outcomes/economic-outcome-attribution";
import { outcomeProtectionService } from "../../outcome-protection/outcome-protection";
import { upsertDataPlatformArtifact, getDataPlatformArtifactByExecution, listDataPlatformArtifacts, type DataPlatformArtifact } from "../data-platform/data-platform-artifacts";

type State = { warehouseId: string; name: string; size: string; autoSuspend: number; status: "ACTIVE" | "SUSPENDED"; owner?: string; monthlySpend: number; spendReviewOpen?: boolean };
type RollbackPayload = { provider: "SNOWFLAKE"; executionId: string; actionId: string; warehouseId: string; priorState: State; targetState: Partial<State>; partialReason?: string };
type OperationInput = { tenantId: string; action: GovernedAction; execution: GovernedExecution; executionType: GovernedExecutionType; dryRun: boolean; approvalPresent: boolean; readinessVerdict: string; connector: ExecutionConnector; ownerId?: string };
const states = new Map<string, State>();
const rollbacks = new Map<string, RollbackPayload>();
const key = (tenantId: string, warehouseId: string) => `${tenantId}:${warehouseId}`;
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
function defaultState(tenantId: string, warehouseId: string): State { return states.get(key(tenantId, warehouseId)) ?? { warehouseId, name: warehouseId, size: "LARGE", autoSuspend: 0, status: "ACTIVE", owner: "unassigned", monthlySpend: 1200 }; }
function evidence(executionId: string, evidenceType: ExecutionEvidence["evidenceType"], summary: string, payload: Record<string, unknown>): ExecutionEvidence { return { id: id("exevidence"), executionId, evidenceType, summary, payload, createdAt: now() }; }
function targetFor(type: GovernedExecutionType, input: OperationInput, before: State): Partial<State> {
  if (type === "SNOWFLAKE_SET_AUTO_SUSPEND") return { autoSuspend: 300 };
  if (type === "SNOWFLAKE_RESIZE_WAREHOUSE") return { size: "MEDIUM" };
  if (type === "SNOWFLAKE_SUSPEND_WAREHOUSE") return { status: "SUSPENDED" };
  if (type === "SNOWFLAKE_TAG_COST_OWNER") return { owner: input.ownerId ?? input.action.ownerId ?? "cost-owner" };
  if (type === "SNOWFLAKE_CREATE_SPEND_REVIEW") return { spendReviewOpen: true };
  return before;
}
function artifactType(type: GovernedExecutionType): DataPlatformArtifact["artifactType"] { return type === "SNOWFLAKE_CREATE_SPEND_REVIEW" ? "SPEND_REVIEW" : type === "SNOWFLAKE_TAG_COST_OWNER" ? "COST_OWNER_TAG" : "WAREHOUSE"; }
function artifactState(type: GovernedExecutionType): DataPlatformArtifact["state"] { return type === "SNOWFLAKE_SET_AUTO_SUSPEND" ? "AUTO_SUSPEND_SET" : type === "SNOWFLAKE_RESIZE_WAREHOUSE" ? "RESIZED" : type === "SNOWFLAKE_SUSPEND_WAREHOUSE" ? "SUSPENDED" : type === "SNOWFLAKE_TAG_COST_OWNER" ? "TAGGED" : type === "SNOWFLAKE_CREATE_SPEND_REVIEW" ? "REVIEW_OPEN" : "UNKNOWN"; }
function assertCanWrite(input: OperationInput) { if (getTenantExecutionPolicy(input.tenantId).mode === "DEMO" && !input.dryRun) throw new Error("SNOWFLAKE_DEMO_MODE_BLOCKS_WRITES"); if (input.connector.status !== "CONNECTED") throw new Error("SNOWFLAKE_CONNECTOR_CREDENTIALS_REQUIRED"); if (!["ELIGIBLE", "APPROVAL_REQUIRED"].includes(input.readinessVerdict)) throw new Error("SNOWFLAKE_TRUST_AUTHORITY_DENIED"); if (input.action.readiness === "APPROVAL_REQUIRED" && !input.approvalPresent) throw new Error("SNOWFLAKE_APPROVAL_REQUIRED"); }
export function readSnowflakeWarehouseState(input: { tenantId: string; warehouseId: string }) { return defaultState(input.tenantId, input.warehouseId); }
export async function executeSnowflakeOperation(input: OperationInput): Promise<{ status: GovernedExecutionStatus; evidence: ExecutionEvidence[]; rollbackPayload?: RollbackPayload; artifact?: DataPlatformArtifact }> {
  assertCanWrite(input); const before = defaultState(input.tenantId, input.action.sourceId); const target = targetFor(input.executionType, input, before); const after = input.dryRun ? before : { ...before, ...target }; if (!input.dryRun) states.set(key(input.tenantId, before.warehouseId), after);
  const rb: RollbackPayload = { provider: "SNOWFLAKE", executionId: input.execution.id, actionId: input.action.id, warehouseId: before.warehouseId, priorState: before, targetState: target, partialReason: input.executionType === "SNOWFLAKE_SUSPEND_WAREHOUSE" ? "Warehouse resume requires explicit provider approval." : undefined }; rollbacks.set(input.execution.id, rb);
  const ev = [evidence(input.execution.id, "PRE_STATE", "Snowflake pre-state evidence captured.", { provider: "SNOWFLAKE", state: before }), evidence(input.execution.id, "EXECUTION_RESULT", input.dryRun ? "Dry run available for controlled Snowflake execution." : `Controlled Snowflake execution completed for ${input.executionType}.`, { provider: "SNOWFLAKE", executionMode: "CONTROLLED_EXECUTION", autonomous: false, target }), evidence(input.execution.id, "POST_STATE", "Snowflake post-state evidence captured.", { provider: "SNOWFLAKE", state: after }), evidence(input.execution.id, "ROLLBACK_PAYLOAD", "Snowflake rollback payload created.", rb as unknown as Record<string, unknown>)];
  const ts = now(); const artifact = upsertDataPlatformArtifact({ id: `sf-artifact-${input.execution.id}`, tenantId: input.tenantId, executionId: input.execution.id, actionId: input.action.id, provider: "SNOWFLAKE", artifactType: artifactType(input.executionType), providerId: before.warehouseId, name: before.name, state: artifactState(input.executionType), sizeBefore: before.size, sizeAfter: after.size, autoSuspendBefore: before.autoSuspend, autoSuspendAfter: after.autoSuspend, monthlySpendBefore: before.monthlySpend, monthlySpendAfter: Math.max(after.monthlySpend * 0.75, 0), ownerBefore: before.owner, ownerAfter: after.owner, createdAt: ts, updatedAt: ts });
  await platformEventService.recordEvent({ tenantId: input.tenantId, category: "EXECUTION", type: "SNOWFLAKE_CONTROLLED_EXECUTION", entityType: "GovernedExecution", entityId: input.execution.id, sourceSystem: "snowflake-execution-adapter", metadata: { actionId: input.action.id, autonomous: false } });
  return { status: "COMPLETED", evidence: ev, rollbackPayload: rb, artifact };
}
export const setSnowflakeAutoSuspend = executeSnowflakeOperation; export const resizeSnowflakeWarehouse = executeSnowflakeOperation; export const suspendSnowflakeWarehouse = executeSnowflakeOperation; export const tagSnowflakeCostOwner = executeSnowflakeOperation; export const createSnowflakeSpendReview = executeSnowflakeOperation;
export async function verifySnowflakeWarehouseState(input: { tenantId: string; executionId: string }) { return verifySnowflakeExecution(input.tenantId, input.executionId); }
export async function verifySnowflakeExecution(tenantId: string, executionId: string) { const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const artifact = getDataPlatformArtifactByExecution(tenantId, executionId); if (!artifact) throw new Error("SNOWFLAKE_ARTIFACT_NOT_FOUND"); const ev = governedExecutionService.appendEvidence(execution, evidence(executionId, "VERIFICATION_RESULT", "Snowflake provider post-state verification passed.", { provider: "SNOWFLAKE", artifactId: artifact.id, lifecycle: ["Projected", "Approved", "Executed", "Verified", "Protected"] })); const outcome = economicOutcomeAttributionService.createEconomicOutcome({ tenantId, assetId: artifact.id, assetType: "OTHER", name: `Snowflake ${artifact.name} cost optimisation`, outcomeType: "COST_REDUCTION", status: "MEASURED", measurementConfidence: "HIGH", measuredValue: artifact.monthlySpendBefore && artifact.monthlySpendAfter ? artifact.monthlySpendBefore - artifact.monthlySpendAfter : 100, source: "CONNECTOR", metadata: { provider: "SNOWFLAKE", executionId } }); await governedActionService.updateExecutionMetadata(tenantId, execution.actionId, { status: "VERIFIED", outcomeIds: [outcome.id], evidenceIds: [ev.id], actualMonthlyValue: outcome.measuredValue, actualAnnualValue: (outcome.measuredValue ?? 0) * 12 }); const policy = outcomeProtectionService.createDriftPolicy({ tenantId, name: "SNOWFLAKE_AUTO_SUSPEND_REMOVED", domain: "DATA", policyType: "CONFIG_REVERTED" }); const protectedOutcome = await outcomeProtectionService.protectOutcome({ tenantId, outcomeId: outcome.id, actionId: execution.actionId, executionId, assetId: artifact.id, assetType: "OTHER", policyIds: [policy.id], evidenceIds: [ev.id] }); await platformEventService.recordEvent({ tenantId, category: "OUTCOME", type: "SNOWFLAKE_OUTCOME_VERIFIED", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "snowflake-execution-adapter", metadata: { outcomeId: outcome.id, protectedOutcomeId: protectedOutcome.id, autonomous: false } }); return { verified: true, artifact, evidence: ev, outcome, protectedOutcome }; }
export async function rollbackSnowflakeWarehouseConfig(tenantIdOrExecutionId: string, maybeExecutionId?: string) { const tenantId = maybeExecutionId ? tenantIdOrExecutionId : "default"; const executionId = maybeExecutionId ?? tenantIdOrExecutionId; const execution = governedExecutionService.getExecution(tenantId, executionId); if (!execution) throw new Error("EXECUTION_NOT_FOUND"); const rb = rollbacks.get(executionId); if (!rb) throw new Error("ROLLBACK_PAYLOAD_MISSING"); const partial = Boolean(rb.partialReason); if (!partial) states.set(key(tenantId, rb.warehouseId), rb.priorState); const ev = governedExecutionService.appendEvidence(execution, evidence(executionId, "ROLLBACK_RESULT", partial ? "Snowflake rollback recorded as PARTIAL with destructive limitation evidence." : "Snowflake rollback restored prior warehouse configuration.", { ...rb, status: partial ? "PARTIAL" : "COMPLETE" } as unknown as Record<string, unknown>)); governedExecutionService.updateExecution({ ...execution, status: "ROLLED_BACK", updatedAt: now() }); await platformEventService.recordEvent({ tenantId, category: "EXECUTION", type: "EXECUTION_ROLLED_BACK", entityType: "GovernedExecution", entityId: executionId, sourceSystem: "snowflake-execution-adapter", metadata: { evidenceId: ev.id, partial, autonomous: false } }); return { rolledBack: !partial, partial, evidence: ev }; }
export { listDataPlatformArtifacts as listSnowflakeArtifacts };
export function clearSnowflakeExecutionState() { states.clear(); rollbacks.clear(); }
