export type KubernetesProvider='EKS'|'AKS'|'GKE'|'SELF_MANAGED'|'UNKNOWN';
export type KubernetesWorkloadType='DEPLOYMENT'|'STATEFULSET'|'DAEMONSET'|'JOB'|'CRONJOB'|'POD'|'SERVICE'|'INGRESS'|'OTHER';
export type KubernetesRecommendationCategory='CLUSTER_EFFICIENCY_REVIEW'|'NAMESPACE_COST_REVIEW'|'WORKLOAD_RIGHTSIZE_REVIEW'|'POD_WASTE_REVIEW'|'NODE_POOL_REVIEW'|'AUTOSCALING_REVIEW'|'EPHEMERAL_WORKLOAD_REVIEW'|'GPU_WORKLOAD_REVIEW'|'OWNERSHIP_REMEDIATION';
export type GovernanceMode='READ_ONLY'|'RECOMMEND_ONLY'|'APPROVAL_REQUIRED';
export interface KubernetesClusterSignal { clusterId?:string; clusterName?:string; provider?:KubernetesProvider; }
export interface KubernetesNamespaceSignal { namespace?:string; environmentType?:'PRODUCTION'|'STAGING'|'DEV'|'TEST'|'SANDBOX'|'UNKNOWN'; ownerId?:string; ownerConfidence?:number; }
export interface KubernetesWorkloadSignal { workloadId?:string; workloadName?:string; workloadType?:KubernetesWorkloadType; nodePoolId?:string; podCount?:number; requestedCpu?:number; usedCpu?:number; requestedMemory?:number; usedMemory?:number; monthlyCost:number; }
export interface KubernetesPodSignal { crashLoopPods?:number; orphanedPods?:number; idlePods?:number; staleReplicas?:number; lowRequestPods?:number; completedJobsNotCleaned?:number; }
export interface KubernetesNodePoolSignal { binPackingRisk?:number; capacityWasteRisk?:number; purchaseOptionRisk?:number; gpuNodePoolWaste?:number; }
export interface KubernetesAutoscalingSignal { hpaVpaMisalignment?:number; scaleOutWithoutScaleIn?:number; minReplicaOverprovisioning?:number; cronMismatch?:number; batchInefficiency?:number; }
export interface KubernetesGPUSignal { gpuRequested?:number; gpuUsed?:number; gpuNodeIdle?:number; aiBurstiness?:number; inferenceEfficiency?:number; trainingUtilization?:number; commitmentAlignmentRisk?:number; }
export interface KubernetesNormalizedSignal extends KubernetesClusterSignal, KubernetesNamespaceSignal, KubernetesWorkloadSignal, KubernetesPodSignal, KubernetesNodePoolSignal, KubernetesAutoscalingSignal, KubernetesGPUSignal { tenantId:string; provider:KubernetesProvider; clusterId:string; clusterName:string; namespace:string; workloadId:string; workloadName:string; workloadType:KubernetesWorkloadType; nodePoolId:string; podCount:number; requestedCpu:number; usedCpu:number; requestedMemory:number; usedMemory:number; gpuRequested:number; gpuUsed:number; monthlyCost:number; annualizedCost:number; ownerId:string; ownerConfidence:number; environmentType:'PRODUCTION'|'STAGING'|'DEV'|'TEST'|'SANDBOX'|'UNKNOWN'; labels:Record<string,string>; annotations:Record<string,string>; evidenceRefs:string[]; sourceSystem:string; sourceUpdatedAt:string; replayCorrelationId:string; lineageCorrelationId:string; ownershipQuality:'HIGH'|'MEDIUM'|'LOW'; resourceRequestQuality:'HIGH'|'MEDIUM'|'LOW'; usageSignalQuality:'HIGH'|'MEDIUM'|'LOW'; costSignalQuality:'HIGH'|'MEDIUM'|'LOW'; environmentSignalQuality:'HIGH'|'MEDIUM'|'LOW'; }
export interface ClusterEfficiencyResult { clusterEfficiencyScore:number; estimatedMonthlyWaste:number; estimatedAnnualWaste:number; topWasteDrivers:string[]; clusterRisk:number; confidence:number; }
export interface NamespaceEconomicsResult { namespace:string; monthlyCost:number; annualizedCost:number; ownerConfidence:number; wasteScore:number; allocationRisk:number; recommendedReview:string; confidence:number; }
export interface WorkloadRightsizingEconomicsResult { rightsizingScore:number; overRequestWasteMonthly:number; underRequestRisk:number; recommendedReviewMode:GovernanceMode; confidence:number; reasons:string[]; }
export interface PodWasteResult { podWasteScore:number; estimatedMonthlyWaste:number; wasteDrivers:string[]; cleanupReviewRecommended:boolean; confidence:number; }
export interface NodePoolEconomicsResult { nodePoolEfficiencyScore:number; estimatedMonthlyWaste:number; binPackingRisk:number; capacityWasteRisk:number; purchaseOptionRisk:number; recommendedReview:string; confidence:number; }
export interface AutoscalingEfficiencyResult { autoscalingEfficiencyScore:number; autoscalingWasteMonthly:number; misalignmentRisk:number; recommendedReview:string; confidence:number; }
export interface EphemeralWorkloadEconomicsResult { ephemeralWasteScore:number; estimatedMonthlyWaste:number; ttlPolicyRecommended:boolean; cleanupReviewRecommended:boolean; confidence:number; }
export interface KubernetesGPUEconomicsResult { gpuEfficiencyScore:number; gpuWasteMonthly:number; gpuUtilizationRisk:number; commitmentAlignmentRisk:number; recommendedReview:string; confidence:number; }
export interface KubernetesEconomicRecommendation { recommendationId:string; tenantId:string; clusterId:string; namespace:string; workloadId:string; recommendationCategory:KubernetesRecommendationCategory; recommendationSummary:string; estimatedMonthlySavings:number; estimatedAnnualSavings:number; confidence:number; recommendedMode:GovernanceMode; operationalRisk:number; evidenceRefs:string[]; replayCorrelationId:string; lineageCorrelationId:string; }
export interface KubernetesEconomicReport { tenantId:string; clusterCount:number; namespaceCount:number; workloadCount:number; totalMonthlyCost:number; totalAnnualizedCost:number; estimatedMonthlyWaste:number; estimatedAnnualWaste:number; clusterEfficiencyAverage:number; namespaceAllocationRisk:number; workloadRightsizeOpportunity:number; podWasteOpportunity:number; nodePoolWasteOpportunity:number; autoscalingWasteOpportunity:number; ephemeralWasteOpportunity:number; gpuWasteOpportunity:number; ownershipRemediationCount:number; topWasteDrivers:string[]; topOperationalRisks:string[]; recommendedNextActions:string[]; readinessStatus:'READY_FOR_KUBERNETES_GOVERNANCE'|'READY_WITH_LIMITS'|'HARDENING_REQUIRED'; }
