export type ExecutiveProofPackType='BOARD'|'CFO'|'CIO'|'PROCUREMENT'|'AUDIT'|'OPERATOR';
export type PackStatus='DRAFT'|'READY'|'BLOCKED'|'EXPORTED'|'ARCHIVED';
export type SectionKey='EXECUTIVE_SUMMARY'|'VALUE_SUMMARY'|'FINANCE_VERIFICATION'|'PORTFOLIO_POSITION'|'COMMERCIAL_EXPOSURE'|'RENEWAL_RISK'|'OWNERSHIP_ACCOUNTABILITY'|'EVIDENCE_COVERAGE'|'GOVERNED_ACTIONS'|'OUTCOME_VERIFICATION'|'RISK_REGISTER'|'RECOMMENDATIONS'|'AUDIT_TRAIL'|'OPERATING_NEXT_STEPS';
export type EvidenceSourceType='TECHNOLOGY_PORTFOLIO'|'EVIDENCE_REGISTRY'|'OUTCOME_FINANCE'|'FINANCIAL_TRUTH'|'COMMERCIAL_AUTHORITY'|'OWNERSHIP_INTELLIGENCE'|'ECONOMIC_GRAPH'|'LIVE_TENANT_READINESS'|'CONNECTOR_READINESS'|'AUDIT';
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(t:string,id:string):Promise<T|undefined>;list(t:string,f?:Record<string,unknown>):Promise<T[]>;deleteTenant(t:string):Promise<void>;size():Promise<number>}
export const EXECUTIVE_PROOF_PACK_COLLECTIONS=['EXECUTIVE_PROOF_PACKS','EXECUTIVE_PROOF_PACK_SECTIONS','EXECUTIVE_PROOF_PACK_EVIDENCE_BINDINGS','EXECUTIVE_PROOF_PACK_EXPORTS','EXECUTIVE_PROOF_PACK_AUDIENCE_SUMMARIES','EXECUTIVE_PROOF_PACK_READINESS_CHECKS','EXECUTIVE_PROOF_PACK_SNAPSHOTS'] as const; export type ExecutiveProofPackCollection=typeof EXECUTIVE_PROOF_PACK_COLLECTIONS[number];
export interface ExecutiveProofPack{ id:string;tenantId:string;packType:ExecutiveProofPackType;title:string;reportingPeriod?:string;status:PackStatus;readinessScore:number;generatedAt:string;generatedBy?:string;sourceSystems:string[];portfolioSnapshotId?:string;evidenceSnapshotId?:string;outcomeFinanceSnapshotId?:string;economicControlChainAuditId?:string;executiveSummary:string;keyFindings:string[];metrics:{totalAnnualSpend?:number;projectedSavings?:number;approvedSavings?:number;executedSavings?:number;financeVerifiedSavings?:number;varianceAmount?:number;variancePercent?:number;commercialExposure?:number;renewalRiskCount?:number;criticalRiskCount?:number;evidenceCoverageScore?:number;ownershipCompletenessScore?:number;portfolioCompletenessScore?:number;confidenceScore?:number;currency?:string;[k:string]:unknown};audienceNarrativeId?:string;sectionIds:string[];evidenceBindingIds:string[];exportIds:string[];blockers:Array<{blockerType:'MISSING_PORTFOLIO'|'MISSING_EVIDENCE'|'MISSING_FINANCIAL_TRUTH'|'MISSING_OUTCOME_FINANCE'|'MISSING_OWNERSHIP'|'MISSING_GRAPH'|'UNVERIFIED_VALUE'|'LOW_CONFIDENCE'|'EXPORT_NOT_READY';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';description:string;nextStep:string}>;demo:boolean;createdAt:string;updatedAt:string}
export interface ExecutiveProofPackSection{ id:string;tenantId:string;packId:string;sectionKey:SectionKey;title:string;order:number;status:'READY'|'PARTIAL'|'MISSING'|'BLOCKED';narrative:string;metrics:Record<string,unknown>;sourceRefs:Array<{sourceType:EvidenceSourceType;sourceId?:string;evidenceRefs:string[]}>;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ExecutiveProofPackEvidenceBinding{ id:string;tenantId:string;packId:string;sectionId?:string;evidenceRef:string;bindingType:'SUPPORTS_METRIC'|'PROVES_VALUE'|'PROVES_ACTION'|'PROVES_OUTCOME'|'PROVES_OWNERSHIP'|'PROVES_RISK'|'PROVES_AUDIT'|'EXPORT_INCLUDED';pillar?:'AUTO_EXECUTION'|'VALUE_REALISATION'|'PROTECTED_GOVERNANCE'|'SHARED_PLATFORM';targetMetric?:string;targetId?:string;trustLevel:'LOW'|'MEDIUM'|'HIGH'|'CERTIFIED';integrityStatus:'PASS'|'WARN'|'FAIL'|'UNKNOWN';redactionStatus:'NOT_REQUIRED'|'PENDING'|'REDACTED'|'FAILED';exportSafe:boolean;createdAt:string;updatedAt:string}
export interface ExecutiveProofPackAudienceSummary{ id:string;tenantId:string;packId:string;packType:ExecutiveProofPackType;headline:string;narrative:string;audienceFocus:Array<'VALUE'|'RISK'|'FINANCE'|'TECHNOLOGY'|'PROCUREMENT'|'AUDITABILITY'|'OPERATIONS'|'GOVERNANCE'>;topQuestionsAnswered:string[];recommendedDecisions:Array<{decision:string;rationale:string;evidenceRefs:string[];valueImpact?:number;riskImpact?:string}>;createdAt:string;updatedAt:string}
export type ExecutiveProofPackExportType='JSON'|'MARKDOWN'|'HTML'|'PDF_READY'|'DOCX_READY';
export interface ExecutiveProofPackExport{ id:string;tenantId:string;packId:string;exportType:ExecutiveProofPackExportType;status:'READY'|'BLOCKED'|'EXPORTED'|'FAILED';exportPayloadRef?:string;contentHash?:string;hashAlgorithm?:'SHA256'|'SHA512'|'NONE';exportSafe:boolean;blockers:string[];generatedAt:string;generatedBy?:string;evidenceRefs:string[];metadata:Record<string,unknown>}
export interface ExecutiveProofPackReadinessCheck{ id:string;tenantId:string;packId:string;checkKey:'PORTFOLIO_AVAILABLE'|'EVIDENCE_AVAILABLE'|'FINANCIAL_TRUTH_AVAILABLE'|'OUTCOME_FINANCE_AVAILABLE'|'OWNERSHIP_AVAILABLE'|'GRAPH_AVAILABLE'|'VALUE_VERIFIED'|'EVIDENCE_EXPORT_SAFE'|'REDACTION_COMPLETE'|'AUDIT_CHAIN_AVAILABLE'|'DEMO_LIVE_GUARD';status:'PASS'|'WARN'|'FAIL'|'NOT_APPLICABLE';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';reason?:string;nextStep?:string;createdAt:string;updatedAt:string}
export interface ExecutiveProofPackSnapshot{ id:string;tenantId:string;generatedAt:string;packCount:number;readyCount:number;blockedCount:number;exportedCount:number;packTypesAvailable:ExecutiveProofPackType[];averageReadinessScore:number;exportReadyCount:number;evidenceBoundCount:number;exportBlockedCount:number;latestPackIds:string[];readiness:'READY'|'PARTIAL'|'MISSING_DATA'|'BLOCKED'|'DEMO';createdAt:string}
export const PACK_TYPES:ExecutiveProofPackType[]=['BOARD','CFO','CIO','PROCUREMENT','AUDIT','OPERATOR'];
