import type { OracleJavaSignal } from './oracle-java-types';
const clamp=(n:number)=>Math.max(0,Math.min(1,Number(n.toFixed(4))));
export const normalizeOracleJavaSignal=(signal:OracleJavaSignal):OracleJavaSignal=>({
...signal,
entitlement:{entitlementEvidenceQuality:clamp(signal.entitlement.entitlementEvidenceQuality),contractEvidenceConfidence:clamp(signal.entitlement.contractEvidenceConfidence),entitlementCoverageRatio:clamp(signal.entitlement.entitlementCoverageRatio),productMetricAlignment:clamp(signal.entitlement.productMetricAlignment),processorMetricExposure:clamp(signal.entitlement.processorMetricExposure),namedUserPlusExposure:clamp(signal.entitlement.namedUserPlusExposure),supportStatusConfidence:clamp(signal.entitlement.supportStatusConfidence),auditEvidenceCompleteness:clamp(signal.entitlement.auditEvidenceCompleteness)},
infrastructure:{physicalCoreAttributionConfidence:clamp(signal.infrastructure.physicalCoreAttributionConfidence),virtualizationBoundaryConfidence:clamp(signal.infrastructure.virtualizationBoundaryConfidence),hardPartitionEvidenceConfidence:clamp(signal.infrastructure.hardPartitionEvidenceConfidence),softPartitionRisk:clamp(signal.infrastructure.softPartitionRisk),vmwareAffinityAmbiguity:clamp(signal.infrastructure.vmwareAffinityAmbiguity),cloudBYOLAmbiguity:clamp(signal.infrastructure.cloudBYOLAmbiguity),DRRoleAmbiguity:clamp(signal.infrastructure.DRRoleAmbiguity),clusterMobilityRisk:clamp(signal.infrastructure.clusterMobilityRisk),hostOwnershipConfidence:clamp(signal.infrastructure.hostOwnershipConfidence)},
java:{oracleJdkDetectionConfidence:clamp(signal.java.oracleJdkDetectionConfidence),openJdkAlternativeConfidence:clamp(signal.java.openJdkAlternativeConfidence),javaSeSubscriptionExposure:clamp(signal.java.javaSeSubscriptionExposure),employeeMetricExposure:clamp(signal.java.employeeMetricExposure),runtimeVersionRisk:clamp(signal.java.runtimeVersionRisk),unsupportedRuntimeRisk:clamp(signal.java.unsupportedRuntimeRisk),commercialFeatureExposure:clamp(signal.java.commercialFeatureExposure),containerizedRuntimeExposure:clamp(signal.java.containerizedRuntimeExposure),kubernetesJvmDensity:clamp(signal.java.kubernetesJvmDensity),inactiveRuntimeWaste:clamp(signal.java.inactiveRuntimeWaste),runtimeOwnershipConfidence:clamp(signal.java.runtimeOwnershipConfidence)},
exposure:{...signal.exposure,estimatedAnnualExposure:Number((signal.exposure.estimatedMonthlyExposure*12).toFixed(2)),auditBackExposureRisk:clamp(signal.exposure.auditBackExposureRisk),renewalNegotiationRisk:clamp(signal.exposure.renewalNegotiationRisk),recurrenceRisk:clamp(signal.exposure.recurrenceRisk),executiveMateriality:clamp(signal.exposure.executiveMateriality)}
});
