import type { ProductionConnectorContext, RawFetchResult, RawProductionRecord } from "../production-connector-types";
import { MicrosoftGraphHttpClient } from "../../microsoft-auth";
import { m365Fixtures } from "./m365-tests-fixtures";
export class M365GraphClient {
  private graph?: MicrosoftGraphHttpClient;
  constructor(private readonly options: { credentialRef?: string; tokenProvider?: ProductionConnectorContext["tokenProvider"]; graphClient?: MicrosoftGraphHttpClient; enableCopilotUsage?: boolean } = {}) { this.graph = options.graphClient; }
  private async live(context: ProductionConnectorContext) { if (!context.credentialRef) throw Object.assign(new Error("missing credentialRef"), { code: "MICROSOFT_AUTH_FAILED" }); if (!context.tokenProvider) throw Object.assign(new Error("missing token provider"), { code: "MICROSOFT_AUTH_FAILED" }); return this.graph ?? new MicrosoftGraphHttpClient({ tokenProvider: () => context.tokenProvider!({ tenantId: context.tenantId, connectorKey: context.connectorKey, credentialRef: context.credentialRef!, scopes: [] }) }); }
  async fetchUsers(context: ProductionConnectorContext) { return (await this.live(context)).getAllPages("/users?$select=id,userPrincipalName,displayName,department,assignedLicenses,accountEnabled"); }
  async fetchGroups(context: ProductionConnectorContext) { return (await this.live(context)).getAllPages("/groups?$select=id,displayName,mail,owners"); }
  async fetchSubscribedSkus(context: ProductionConnectorContext) { return (await this.live(context)).getAllPages("/subscribedSkus"); }
  async fetchUserLicenseDetails(context: ProductionConnectorContext, userId: string) { return (await this.live(context)).getAllPages(`/users/${encodeURIComponent(userId)}/licenseDetails`); }
  async fetchOffice365ActiveUserDetail(context: ProductionConnectorContext, period = "D30") { return (await this.live(context)).getReport(`/reports/getOffice365ActiveUserDetail(period='${period}')`); }
  async fetchOffice365ActiveUserCounts(context: ProductionConnectorContext, period = "D30") { return (await this.live(context)).getReport(`/reports/getOffice365ActiveUserCounts(period='${period}')`); }
  async fetchOffice365GroupsActivityDetail(context: ProductionConnectorContext, period = "D30") { return (await this.live(context)).getReport(`/reports/getOffice365GroupsActivityDetail(period='${period}')`); }
  async fetchM365AppUserDetail(context: ProductionConnectorContext, period = "D30") { return (await this.live(context)).getReport(`/reports/getM365AppUserDetail(period='${period}')`); }
  async fetchCopilotUsage(context: ProductionConnectorContext, period = "D30") { if (!this.options.enableCopilotUsage && !context.config?.enableCopilotUsage) return { status: "NOT_AVAILABLE" as const, reason: "MICROSOFT_COPILOT_NOT_AVAILABLE", rows: [] }; return (await this.live(context)).getReport(`/reports/getMicrosoft365CopilotUsageUserDetail(period='${period}')`); }
  async fetchRecords(context: ProductionConnectorContext): Promise<RawFetchResult> {
    if (context.mode === "SYNC" && !context.tokenProvider) return { status: "BLOCKED", reason: "TOKEN_PROVIDER_NOT_CONFIGURED", records: [] };
    if (!context.credentialRef || !context.tokenProvider || context.config?.useFixtures) return { status: "READY", records: m365Fixtures };
    const records: RawProductionRecord[] = []; const endpointStatus: NonNullable<RawFetchResult["endpointStatus"]> = [];
    const collect = async (endpoint: string, kind: string, fn: () => Promise<any[]>) => { try { const rows = await fn(); endpointStatus.push({ endpoint, status: "AVAILABLE" }); rows.forEach((payload: any, i: number) => records.push({ id: String(payload.id ?? payload.skuId ?? `${kind}_${i}`), kind, payload, sourceEndpoint: endpoint })); } catch (e: any) { endpointStatus.push({ endpoint, status: "UNAVAILABLE", reason: e.code ?? e.message }); if (["users", "subscribedSkus"].includes(endpoint)) throw e; } };
    try { await collect("users", "user", () => this.fetchUsers(context)); await collect("groups", "group", () => this.fetchGroups(context)); await collect("subscribedSkus", "sku", () => this.fetchSubscribedSkus(context)); const usage = await this.fetchOffice365ActiveUserDetail(context); usage.rows.forEach((payload: any, i: number) => records.push({ id: `usage_${i}`, kind: "usage", payload, sourceEndpoint: "reports/activeUserDetail" })); const copilot = await this.fetchCopilotUsage(context); if ("status" in copilot) records.push({ id: "copilot_not_available", kind: "copilotUsage", payload: { reason: copilot.reason }, sourceEndpoint: "reports/copilot" }); else copilot.rows.forEach((payload: any, i: number) => records.push({ id: `copilot_${i}`, kind: "usage", payload, sourceEndpoint: "reports/copilot" })); return { status: "READY", records, endpointStatus }; } catch (e: any) { return { status: "BLOCKED", reason: e.code ?? e.message, records, endpointStatus }; }
  }
}
