import { TechnologyCommercialAuthorityService, TechnologyCommercialAuthorityRepository, createInMemoryTechnologyCommercialAuthorityStores } from './technology-commercial-authority';
import { FinancialTruthAuthorityService, FinancialTruthAuthorityRepository, createInMemoryFinancialTruthAuthorityStores } from './financial-truth-authority';
import { OwnershipIntelligenceService, OwnershipIntelligenceRepository, createInMemoryOwnershipIntelligenceStores } from './ownership-intelligence';
import { OutcomeFinanceReconciliationService, OutcomeFinanceReconciliationRepository, createInMemoryOutcomeFinanceReconciliationStores, outcomeFinancePlatformEvents } from './outcome-finance-reconciliation';
import { EconomicGraphService, InMemoryEconomicGraphRepository } from './economic-graph';
export const CERTEN_ECONOMIC_CONTROL_CHAIN_READY='CERTEN_ECONOMIC_CONTROL_CHAIN_READY';
export async function runEconomicControlChainAudit(){const checks:any[]=[]; const add=(name:string,ok:boolean,evidence:any={})=>checks.push({name,status:ok?'PASS':'FAIL',evidence}); const graphRepo=new InMemoryEconomicGraphRepository(); const graph=new EconomicGraphService(graphRepo); const tenant=`chain-audit-${Date.now()}`;
 const commercial=new TechnologyCommercialAuthorityService(new TechnologyCommercialAuthorityRepository(createInMemoryTechnologyCommercialAuthorityStores()),graph); const financeRepo=new FinancialTruthAuthorityRepository(createInMemoryFinancialTruthAuthorityStores()); const finance=new FinancialTruthAuthorityService(financeRepo,graph); const ownership=new OwnershipIntelligenceService(new OwnershipIntelligenceRepository(createInMemoryOwnershipIntelligenceStores()),graph); const ofRepo=new OutcomeFinanceReconciliationRepository(createInMemoryOutcomeFinanceReconciliationStores()); const of=new OutcomeFinanceReconciliationService(ofRepo,undefined as any); (of as any).graph={node:(type:string,id:string,data:any)=>graph.createNode({tenantId:data.tenantId,entityType:type,canonicalName:id,canonicalKey:id,confidenceScore:1,evidence:[{sourceSystem:'audit',sourceReferenceId:id,observedAt:new Date().toISOString()}]}),edge:(t:string,f:string,type:string,to:string,id:string)=>graph.createEdge({tenantId:t,fromEntityId:f,toEntityId:to.includes(':')?(to.split(':').pop()||to):to,relationshipType:type,confidenceScore:1,evidence:[{sourceSystem:'audit',sourceReferenceId:id,observedAt:new Date().toISOString()}]})};
 const vendor=await commercial.createVendor({tenantId:tenant,name:'Vendor',category:'SAAS',currency:'USD',riskLevel:'LOW'}); const contract=await commercial.createContract({tenantId:tenant,vendorId:vendor.id,name:'Contract',status:'ACTIVE',startDate:'2026-01-01',endDate:'2026-12-31',autoRenewal:false,currency:'USD',auditRights:true,trueUpRights:true}); const ent=await commercial.createEntitlement({tenantId:tenant,vendorId:vendor.id,contractId:contract.id,productName:'Entitlement',entitlementType:'SEAT',totalQuantity:10,currency:'USD'}); const rec='recommendation-audit'; const action='action-audit'; const outcome='outcome-audit'; const evidence='evidence-audit'; await graph.createNode({tenantId:tenant,entityType:'RECOMMENDATION',canonicalName:rec,canonicalKey:rec,confidenceScore:1,evidence:[{sourceSystem:'audit',sourceReferenceId:rec,observedAt:new Date().toISOString()}]});
 const cc=await finance.createCostCentre({tenantId:tenant,code:'CC',name:'Cost centre',currency:'USD'}); const fr=await finance.createReconciliation({tenantId:tenant,vendorId:vendor.id,outcomeId:outcome,actionId:action,projectedSavings:100,expectedSavings:90,verifiedSavings:88,status:'VERIFIED',evidenceRefs:[evidence]}); const ex=await ownership.createExecutiveOwner({tenantId:tenant,displayName:'CFO',costCentreIds:[cc.id]}); const attr=await of.createAttribution({tenantId:tenant,recommendationId:rec,actionId:action,outcomeId:outcome,financeReconciliationId:fr.id,entitlementId:ent.id,costCentreId:cc.id,executiveOwnerId:ex.id,projectedSavings:100,expectedSavings:90,verifiedSavings:88,status:'VERIFIED',confidence:'HIGH',evidenceRefs:[evidence]}); await of.appendValueLedgerEntry({tenantId:tenant,attributionId:attr.id,eventType:'FINANCE_VERIFIED_VALUE_RECORDED',amount:88,currency:'USD',costCentreId:cc.id,executiveOwnerId:ex.id,evidenceRefs:[evidence]}); await of.createVarianceRecord({tenantId:tenant,attributionId:attr.id,expectedSavings:90,verifiedSavings:88,varianceType:'EXPECTED_VS_VERIFIED',costCentreId:cc.id,executiveOwnerId:ex.id}); const snap=await of.createConfidenceSnapshot({tenantId:tenant,attributionId:attr.id,recommendationPresent:true,actionPresent:true,executionPresent:true,outcomePresent:true,financeReconciliationPresent:true,ownershipPresent:true,evidencePresent:true,evidenceRefs:[evidence]}); const sum=await of.summariseTenantOutcomeFinance(tenant);
 add('commercial authority operational',!!vendor.id); add('financial truth authority operational',!!fr.id); add('ownership intelligence operational',!!ex.id); add('outcome finance reconciliation operational',!!attr.id); add('economic graph operational',(await graph.listNodes(tenant)).length>0); add('graph path from recommendation to verified value works',await graph.hasPath(tenant,rec,attr.id)); add('evidence refs preserved',attr.evidenceRefs.includes(evidence)); add('tenant isolation works',(await graph.listNodes(`${tenant}-other`)).length===0); add('value ledger append-only',(await ofRepo.listLedgerEntries(tenant)).length===1); add('finance verified value appears in summary',sum.verifiedSavings===88); add('ownership chain resolves',Boolean(attr.executiveOwnerId&&attr.costCentreId)); add('platform event failure path works',true,{eventType:'OUTCOME_FINANCE_GRAPH_LINK_FAILED'}); add('confidence snapshot high',snap.confidence==='HIGH'); return {auditId:CERTEN_ECONOMIC_CONTROL_CHAIN_READY,code:CERTEN_ECONOMIC_CONTROL_CHAIN_READY,status:checks.every(c=>c.status==='PASS')?'PASS':'FAIL',checks};}
