export type OperationalState = 'PROPOSED'|'SIMULATED'|'APPROVAL_REQUIRED'|'APPROVED'|'GOVERNED_EXECUTION_ELIGIBLE'|'MANUAL_ONLY'|'DATA_TRUST_INSUFFICIENT'|'EXECUTION_READY_NOT_LIVE_ENABLED'|'EXECUTED'|'VERIFIED'|'ROLLED_BACK'|'DRIFT_DETECTED'|'BLOCKED';
export type ExecutionIntentType = 'SIMULATE'|'REQUEST_APPROVAL'|'APPROVE'|'REJECT'|'REQUEST_MORE_EVIDENCE'|'MARK_MANUAL_ONLY'|'EXECUTE'|'VERIFY'|'ROLLBACK'|'ACKNOWLEDGE_DRIFT'|'BLOCK';
export type SourceSurface = 'UI'|'API'|'MCP';
export type IntentResultState = 'INTENT_ACCEPTED'|'INTENT_REJECTED'|'INTENT_DUPLICATE'|'INTENT_BLOCKED_BY_POLICY'|'INTENT_BLOCKED_BY_APPROVAL'|'INTENT_BLOCKED_BY_CONNECTOR'|'INTENT_BLOCKED_BY_DATA_TRUST'|'INTENT_BLOCKED_BY_SIMULATION'|'INTENT_BLOCKED_BY_ROLLBACK'|'INTENT_BLOCKED_BY_TENANT_MODE'|'EXECUTION_READY_NOT_LIVE_ENABLED';

export type TenantOperationalMode = 'DEMO'|'PILOT_READ_ONLY'|'PILOT_APPROVAL_REQUIRED'|'PRODUCTION_RECOMMEND_ONLY'|'PRODUCTION_APPROVAL_REQUIRED'|'PRODUCTION_GOVERNED_EXECUTION'|'PRODUCTION_LOCKED';
export type LedgerEnvironment = 'DEMO'|'PILOT'|'PRODUCTION';
export type EvidenceSourceOfTruth = 'FIXTURE'|'CONNECTOR'|'LEDGER'|'SIMULATION';
export type TenantOperationalModeRule = { mode: TenantOperationalMode; allowedIntentTypes: ExecutionIntentType[]; blockedIntentTypes: ExecutionIntentType[]; requiresApproval: boolean; allowsLiveExecution: boolean; auditLabel: string; uiBanner: string; };
export const TENANT_OPERATIONAL_MODE_REGISTRY: Record<TenantOperationalMode,TenantOperationalModeRule> = {
DEMO:{mode:'DEMO',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','EXECUTE','VERIFY','ROLLBACK','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:[],requiresApproval:true,allowsLiveExecution:false,auditLabel:'DEMO_SANDBOX',uiBanner:'DEMO MODE — fixture-backed, no live execution'},
PILOT_READ_ONLY:{mode:'PILOT_READ_ONLY',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','VERIFY','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:['EXECUTE','ROLLBACK'],requiresApproval:true,allowsLiveExecution:false,auditLabel:'PILOT_READ_ONLY',uiBanner:'PILOT READ-ONLY — real evidence, no live mutation'},
PILOT_APPROVAL_REQUIRED:{mode:'PILOT_APPROVAL_REQUIRED',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','EXECUTE','VERIFY','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:['ROLLBACK'],requiresApproval:true,allowsLiveExecution:true,auditLabel:'PILOT_APPROVAL',uiBanner:'PILOT APPROVAL REQUIRED — controlled execution'},
PRODUCTION_RECOMMEND_ONLY:{mode:'PRODUCTION_RECOMMEND_ONLY',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:['APPROVE','EXECUTE','VERIFY','ROLLBACK'],requiresApproval:true,allowsLiveExecution:false,auditLabel:'PRODUCTION_RECOMMEND_ONLY',uiBanner:'PRODUCTION RECOMMEND-ONLY — no execution permitted'},
PRODUCTION_APPROVAL_REQUIRED:{mode:'PRODUCTION_APPROVAL_REQUIRED',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','EXECUTE','VERIFY','ROLLBACK','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:[],requiresApproval:true,allowsLiveExecution:true,auditLabel:'PRODUCTION_APPROVAL',uiBanner:'PRODUCTION APPROVAL REQUIRED — live execution gated by approval'},
PRODUCTION_GOVERNED_EXECUTION:{mode:'PRODUCTION_GOVERNED_EXECUTION',allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','EXECUTE','VERIFY','ROLLBACK','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:[],requiresApproval:false,allowsLiveExecution:true,auditLabel:'PRODUCTION_GOVERNED',uiBanner:'PRODUCTION GOVERNED EXECUTION — live governed execution'},
PRODUCTION_LOCKED:{mode:'PRODUCTION_LOCKED',allowedIntentTypes:['SIMULATE','ACKNOWLEDGE_DRIFT','BLOCK'],blockedIntentTypes:['REQUEST_APPROVAL','APPROVE','REJECT','REQUEST_MORE_EVIDENCE','MARK_MANUAL_ONLY','EXECUTE','VERIFY','ROLLBACK'],requiresApproval:false,allowsLiveExecution:false,auditLabel:'PRODUCTION_LOCKED',uiBanner:'PRODUCTION LOCKED — no execution permitted'},
};
export type ExecutionIntentDto={tenantId:string;executionId:string;actorId:string;actorRole:string;intentType:ExecutionIntentType;sourceSurface:SourceSurface;timestamp:string;reason:string;requiredProofIds:string[];expectedStateTransition:{from:OperationalState;to:OperationalState};idempotencyKey:string};
export type ExecutionIntentResultDto={accepted:boolean;rejected:boolean;reason:IntentResultState;previousState:OperationalState;nextState:OperationalState;proofIds:string[];ledgerEntryId:string;idempotencyKey:string;timestamp:string};
export type ProofNode={proofId:string;proofType:string;title:string;summary:string;source:string;timestamp:string;confidence:number;upstreamProofIds:string[];downstreamProofIds:string[];evidenceHash:string;displayPriority:number;expandableDetails:Record<string,unknown>;environment:LedgerEnvironment;isFixtureBacked:boolean;sourceOfTruth:EvidenceSourceOfTruth};
type ExecutionRecord={executionId:string;tenantId:string;state:OperationalState;approvalGranted:boolean;simulationReady:boolean;connectorReady:boolean;dataTrustReady:boolean;rollbackEligible:boolean;tenantExecutionMode:'ENFORCED'|'READ_ONLY';tenantMode:TenantOperationalMode;proofIds:string[];ledgerEntryId:string;fixtureBacked?:boolean;};
export type ActionHistoryEntry={action:ExecutionIntentType;actor:string;actorRole:string;sourceSurface:SourceSurface;reason:string;result:IntentResultState;previousState:OperationalState;nextState:OperationalState;timestamp:string;proofIds:string[];ledgerEntryId:string;idempotencyKey:string};
import { db, economicOperationsActionHistoryTable, economicOperationsExecutionStateTable, economicOperationsIdempotencyTable } from '@workspace/db';
import { and, eq } from 'drizzle-orm';
type IdempotencyStore={get:(k:string)=>ExecutionIntentResultDto|undefined;set:(k:string,v:ExecutionIntentResultDto)=>void}; class InMemoryIdempotencyStore implements IdempotencyStore{private m=new Map<string,ExecutionIntentResultDto>();get(k:string){return this.m.get(k);}set(k:string,v:ExecutionIntentResultDto){this.m.set(k,v);}}
export class EconomicOperationsIntentService { private executions=new Map<string,ExecutionRecord>(); private actions=new Map<string,ActionHistoryEntry[]>(); private proofs=new Map<string,ProofNode[]>(); constructor(private idempotencyStore:IdempotencyStore=new InMemoryIdempotencyStore()){} seedExecution(input:ExecutionRecord){this.executions.set(`${input.tenantId}:${input.executionId}`,input);} getActions(tenantId:string,executionId:string){return this.actions.get(`${tenantId}:${executionId}`)??[];} 
getOutcome(tenantId:string,executionId:string){ const e=this.executions.get(`${tenantId}:${executionId}`); if(!e) return null; const simulatedOnly=e.tenantMode==='DEMO'; const env:LedgerEnvironment=e.tenantMode==='DEMO'?'DEMO':e.tenantMode.startsWith('PILOT')?'PILOT':'PRODUCTION'; return { executionId, projectedMonthlySavings:1200, projectedAnnualSavings:14400, verifiedMonthlySavings:0, verifiedAnnualSavings:0, savingConfidence:e.dataTrustReady?0.92:0.4, executionStatus:e.state, approvalProvenance:e.approvalGranted?'APPROVED':'NOT_APPROVED', verificationStatus:simulatedOnly?'SIMULATED_ONLY':'PENDING_VERIFICATION', rollbackStatus:e.rollbackEligible?'ELIGIBLE':'BLOCKED', ledgerEnvironment:env, isFixtureBacked:Boolean(e.fixtureBacked), isVerifiedSaving:false, sourceOfTruth:e.fixtureBacked?'FIXTURE':'SIMULATION' }; }
getProofGraph(tenantId:string,executionId:string){const n=this.proofs.get(`${tenantId}:${executionId}`)??[];return {executionId,status:n.length<3?'PROOF_INCOMPLETE':'PROOF_COMPLETE',nodes:n};}
async submitIntent(intent:ExecutionIntentDto, _env:'development'|'production'='development'):Promise<ExecutionIntentResultDto>{const reject=(reason:IntentResultState,prev:OperationalState,next:OperationalState):ExecutionIntentResultDto=>({accepted:false,rejected:true,reason,previousState:prev,nextState:next,proofIds:[],ledgerEntryId:`ledger-${intent.executionId}`,idempotencyKey:intent.idempotencyKey,timestamp:new Date().toISOString()}); const key=`${intent.tenantId}:${intent.executionId}:${intent.intentType}:${intent.idempotencyKey}`; const dup=this.idempotencyStore.get(key); if(dup) return {...dup,accepted:false,rejected:true,reason:'INTENT_DUPLICATE'};
const [persistedDup]=await db.select().from(economicOperationsIdempotencyTable).where(and(eq(economicOperationsIdempotencyTable.tenantId, intent.tenantId), eq(economicOperationsIdempotencyTable.executionId, intent.executionId), eq(economicOperationsIdempotencyTable.intentType, intent.intentType), eq(economicOperationsIdempotencyTable.idempotencyKey, intent.idempotencyKey))).limit(1);
if(persistedDup){ return {accepted:false,rejected:true,reason:'INTENT_DUPLICATE',previousState:intent.expectedStateTransition.from,nextState:intent.expectedStateTransition.from,proofIds:[],ledgerEntryId:`ledger-${intent.executionId}`,idempotencyKey:intent.idempotencyKey,timestamp:new Date().toISOString()}; } const execution=this.executions.get(`${intent.tenantId}:${intent.executionId}`); if(!execution) return reject('INTENT_REJECTED',intent.expectedStateTransition.from,intent.expectedStateTransition.from); const mode=TENANT_OPERATIONAL_MODE_REGISTRY[execution.tenantMode]; if(!mode.allowedIntentTypes.includes(intent.intentType)||mode.blockedIntentTypes.includes(intent.intentType)) return reject('INTENT_BLOCKED_BY_TENANT_MODE',execution.state,execution.state); if(intent.intentType==='EXECUTE' && mode.requiresApproval && !execution.approvalGranted) return reject('INTENT_BLOCKED_BY_APPROVAL',execution.state,execution.state); let next=intent.expectedStateTransition.to; let reason:IntentResultState='INTENT_ACCEPTED'; if(intent.intentType==='APPROVE'){execution.approvalGranted=true; next='APPROVED';} if(intent.intentType==='REJECT'||intent.intentType==='MARK_MANUAL_ONLY'){next='MANUAL_ONLY';} if(intent.intentType==='REQUEST_MORE_EVIDENCE'){next='DATA_TRUST_INSUFFICIENT';} if(intent.intentType==='REQUEST_APPROVAL'){next='APPROVAL_REQUIRED';} if(intent.intentType==='ACKNOWLEDGE_DRIFT'){next='DRIFT_DETECTED';} if(intent.intentType==='EXECUTE'){ const live=String(process.env.M365_LIVE_LICENSE_MUTATION_ENABLED??'false')==='true'; if(execution.tenantMode==='DEMO'){next='EXECUTED';} else if(execution.tenantMode==='PILOT_READ_ONLY'||execution.tenantMode==='PRODUCTION_RECOMMEND_ONLY'){ return reject('INTENT_BLOCKED_BY_TENANT_MODE',execution.state,execution.state);} else if(!live){next='EXECUTION_READY_NOT_LIVE_ENABLED'; reason='EXECUTION_READY_NOT_LIVE_ENABLED';} }
const prev=execution.state; execution.state=next; const result:ExecutionIntentResultDto={accepted:true,rejected:false,reason,previousState:prev,nextState:next,proofIds:intent.requiredProofIds,ledgerEntryId:execution.ledgerEntryId,idempotencyKey:intent.idempotencyKey,timestamp:new Date().toISOString()}; this.idempotencyStore.set(key,result);
await db.insert(economicOperationsIdempotencyTable).values({tenantId:intent.tenantId,executionId:intent.executionId,intentType:intent.intentType,idempotencyKey:intent.idempotencyKey,resultState:result.reason,resultHash:Buffer.from(JSON.stringify(result)).toString('base64').slice(0,64),metadataJson:{accepted:result.accepted}}).onConflictDoNothing(); const hist=this.getActions(intent.tenantId,intent.executionId); hist.push({action:intent.intentType,actor:intent.actorId,actorRole:intent.actorRole,sourceSurface:intent.sourceSurface,reason:intent.reason,result:result.reason,previousState:result.previousState,nextState:result.nextState,timestamp:result.timestamp,proofIds:result.proofIds,ledgerEntryId:result.ledgerEntryId,idempotencyKey:result.idempotencyKey}); this.actions.set(`${intent.tenantId}:${intent.executionId}`,hist);
await db.insert(economicOperationsActionHistoryTable).values({tenantId:intent.tenantId,executionId:intent.executionId,recommendationId:intent.executionId.replace('m365-exec-',''),intentType:intent.intentType,actorId:intent.actorId,actorRole:intent.actorRole,sourceSurface:intent.sourceSurface,resultState:result.reason,previousState:result.previousState,nextState:result.nextState,reason:intent.reason,idempotencyKey:intent.idempotencyKey,proofIds:result.proofIds as any,ledgerEntryId:result.ledgerEntryId,metadataJson:{duplicate:false}});
await db.insert(economicOperationsExecutionStateTable).values({tenantId:intent.tenantId,executionId:intent.executionId,recommendationId:intent.executionId.replace('m365-exec-',''),provider:'m365',playbookId:'m365-disabled-licensed-user-reclaim',currentState:result.nextState,previousState:result.previousState,approvalStatus:execution.approvalGranted?'APPROVED':'PENDING',simulationStatus:execution.simulationReady?'READY':'PENDING',executionStatus:result.nextState==='EXECUTED'?'EXECUTED':'PENDING',verificationStatus:result.nextState==='VERIFIED'?'VERIFIED':'PENDING_VERIFICATION',rollbackStatus:execution.rollbackEligible?'ELIGIBLE':'BLOCKED',driftStatus:result.nextState==='DRIFT_DETECTED'?'DRIFT_DETECTED':'NO_DRIFT_DETECTED',lastIntentType:intent.intentType,metadataJson:{source:'intent-service'}}).onConflictDoUpdate({target:[economicOperationsExecutionStateTable.tenantId,economicOperationsExecutionStateTable.executionId],set:{previousState:result.previousState,currentState:result.nextState,approvalStatus:execution.approvalGranted?'APPROVED':'PENDING',lastIntentType:intent.intentType,lastStateTransitionAt:new Date(),updatedAt:new Date()}});
this.proofs.set(`${intent.tenantId}:${intent.executionId}`,[{proofId:'simulation-proof',proofType:'SIMULATION_PROOF',title:'Simulation proof',summary:'deterministic simulation',source:'m365',timestamp:result.timestamp,confidence:0.9,upstreamProofIds:[],downstreamProofIds:['approval-proof'],evidenceHash:'h1',displayPriority:1,expandableDetails:{},environment:'PILOT',isFixtureBacked:false,sourceOfTruth:'SIMULATION'},{proofId:'approval-proof',proofType:'APPROVAL_PROOF',title:'Approval proof',summary:execution.approvalGranted?'approved':'pending',source:'intent',timestamp:result.timestamp,confidence:0.9,upstreamProofIds:['simulation-proof'],downstreamProofIds:['execution-readiness-proof'],evidenceHash:'h2',displayPriority:2,expandableDetails:{},environment:'PILOT',isFixtureBacked:false,sourceOfTruth:'LEDGER'},{proofId:'execution-readiness-proof',proofType:'EXECUTION_READINESS_PROOF',title:'Execution readiness proof',summary:next,source:'intent',timestamp:result.timestamp,confidence:0.9,upstreamProofIds:['approval-proof'],downstreamProofIds:[],evidenceHash:'h3',displayPriority:3,expandableDetails:{},environment:'PILOT',isFixtureBacked:false,sourceOfTruth:'LEDGER'}]); return result; }
}
