export type OperationalState = 'PROPOSED'|'SIMULATED'|'APPROVAL_REQUIRED'|'APPROVED'|'EXECUTED'|'VERIFIED'|'ROLLBACK_READY'|'ROLLED_BACK'|'BLOCKED';
export type ExecutionIntentType = 'SIMULATE'|'REQUEST_APPROVAL'|'APPROVE'|'EXECUTE'|'VERIFY'|'ROLLBACK'|'BLOCK';
export type SourceSurface = 'UI'|'API'|'MCP';
export type IntentResultState = 'INTENT_ACCEPTED'|'INTENT_REJECTED'|'INTENT_DUPLICATE'|'INTENT_BLOCKED_BY_POLICY'|'INTENT_BLOCKED_BY_APPROVAL'|'INTENT_BLOCKED_BY_CONNECTOR'|'INTENT_BLOCKED_BY_DATA_TRUST'|'INTENT_BLOCKED_BY_SIMULATION'|'INTENT_BLOCKED_BY_ROLLBACK'|'INTENT_BLOCKED_BY_TENANT_MODE';

export type TenantOperationalMode = 'DEMO'|'PILOT_READ_ONLY'|'PILOT_APPROVAL_REQUIRED'|'PRODUCTION_RECOMMEND_ONLY'|'PRODUCTION_APPROVAL_REQUIRED'|'PRODUCTION_GOVERNED_EXECUTION'|'PRODUCTION_LOCKED';
export type LedgerEnvironment = 'DEMO'|'PILOT'|'PRODUCTION';
export type EvidenceSourceOfTruth = 'FIXTURE'|'CONNECTOR'|'LEDGER'|'SIMULATION';

export type TenantOperationalModeRule = { mode: TenantOperationalMode; label: string; description: string; allowedDataSources: EvidenceSourceOfTruth[]; allowedConnectorCapabilities: Array<'NONE'|'READ_ONLY'|'WRITE'>; allowedIntentTypes: ExecutionIntentType[]; blockedIntentTypes: ExecutionIntentType[]; requiresApproval: boolean; allowsSimulation: boolean; allowsLiveExecution: boolean; allowsFixtureFallback: boolean; ledgerPolicy: string; rollbackPolicy: string; driftPolicy: string; auditLabel: string; uiBanner: string; };

export const TENANT_OPERATIONAL_MODE_REGISTRY: Record<TenantOperationalMode,TenantOperationalModeRule> = {
  DEMO: { mode:'DEMO', label:'Demo Mode', description:'Fixture-backed demo, no live execution.', allowedDataSources:['FIXTURE','SIMULATION'], allowedConnectorCapabilities:['NONE'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','EXECUTE','VERIFY','BLOCK'], blockedIntentTypes:['ROLLBACK'], requiresApproval:true, allowsSimulation:true, allowsLiveExecution:false, allowsFixtureFallback:true, ledgerPolicy:'SIMULATED_ONLY', rollbackPolicy:'SIMULATED_ONLY', driftPolicy:'SIMULATED', auditLabel:'DEMO_SANDBOX', uiBanner:'DEMO MODE — fixture-backed, no live execution' },
  PILOT_READ_ONLY: { mode:'PILOT_READ_ONLY', label:'Pilot Read-Only', description:'Read-only pilot with real evidence.', allowedDataSources:['CONNECTOR','SIMULATION'], allowedConnectorCapabilities:['READ_ONLY'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','VERIFY','BLOCK'], blockedIntentTypes:['EXECUTE','ROLLBACK'], requiresApproval:true, allowsSimulation:true, allowsLiveExecution:false, allowsFixtureFallback:false, ledgerPolicy:'PROJECTED_ONLY', rollbackPolicy:'NOT_ALLOWED', driftPolicy:'ACTIVE', auditLabel:'PILOT_READ_ONLY', uiBanner:'PILOT READ-ONLY — real evidence, no live mutation' },
  PILOT_APPROVAL_REQUIRED: { mode:'PILOT_APPROVAL_REQUIRED', label:'Pilot Approval Required', description:'Pilot requiring explicit approvals before execution.', allowedDataSources:['CONNECTOR','SIMULATION'], allowedConnectorCapabilities:['READ_ONLY','WRITE'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','EXECUTE','VERIFY','BLOCK'], blockedIntentTypes:['ROLLBACK'], requiresApproval:true, allowsSimulation:true, allowsLiveExecution:true, allowsFixtureFallback:false, ledgerPolicy:'PILOT_LEDGER', rollbackPolicy:'CONTROLLED', driftPolicy:'ACTIVE', auditLabel:'PILOT_APPROVAL', uiBanner:'PILOT APPROVAL REQUIRED — controlled execution' },
  PRODUCTION_RECOMMEND_ONLY: { mode:'PRODUCTION_RECOMMEND_ONLY', label:'Production Recommend-Only', description:'Recommendations and proofs only.', allowedDataSources:['CONNECTOR','LEDGER'], allowedConnectorCapabilities:['READ_ONLY'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','BLOCK'], blockedIntentTypes:['APPROVE','EXECUTE','VERIFY','ROLLBACK'], requiresApproval:true, allowsSimulation:true, allowsLiveExecution:false, allowsFixtureFallback:false, ledgerPolicy:'READ_ONLY', rollbackPolicy:'NOT_ALLOWED', driftPolicy:'ACTIVE', auditLabel:'PRODUCTION_RECOMMEND_ONLY', uiBanner:'PRODUCTION RECOMMEND-ONLY — no execution permitted' },
  PRODUCTION_APPROVAL_REQUIRED: { mode:'PRODUCTION_APPROVAL_REQUIRED', label:'Production Approval Required', description:'Live execution gated by approval.', allowedDataSources:['CONNECTOR','LEDGER'], allowedConnectorCapabilities:['READ_ONLY','WRITE'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','EXECUTE','VERIFY','ROLLBACK','BLOCK'], blockedIntentTypes:[], requiresApproval:true, allowsSimulation:true, allowsLiveExecution:true, allowsFixtureFallback:false, ledgerPolicy:'AUTHORITATIVE', rollbackPolicy:'CONTROLLED', driftPolicy:'ACTIVE', auditLabel:'PRODUCTION_APPROVAL', uiBanner:'PRODUCTION APPROVAL REQUIRED — live execution gated by approval' },
  PRODUCTION_GOVERNED_EXECUTION: { mode:'PRODUCTION_GOVERNED_EXECUTION', label:'Production Governed Execution', description:'Live governed execution.', allowedDataSources:['CONNECTOR','LEDGER'], allowedConnectorCapabilities:['READ_ONLY','WRITE'], allowedIntentTypes:['SIMULATE','REQUEST_APPROVAL','APPROVE','EXECUTE','VERIFY','ROLLBACK','BLOCK'], blockedIntentTypes:[], requiresApproval:false, allowsSimulation:true, allowsLiveExecution:true, allowsFixtureFallback:false, ledgerPolicy:'AUTHORITATIVE', rollbackPolicy:'CONTROLLED', driftPolicy:'ACTIVE', auditLabel:'PRODUCTION_GOVERNED', uiBanner:'PRODUCTION GOVERNED EXECUTION — live governed execution' },
  PRODUCTION_LOCKED: { mode:'PRODUCTION_LOCKED', label:'Production Locked', description:'Execution locked for safety.', allowedDataSources:['CONNECTOR','LEDGER'], allowedConnectorCapabilities:['READ_ONLY'], allowedIntentTypes:['SIMULATE','BLOCK'], blockedIntentTypes:['REQUEST_APPROVAL','APPROVE','EXECUTE','VERIFY','ROLLBACK'], requiresApproval:false, allowsSimulation:true, allowsLiveExecution:false, allowsFixtureFallback:false, ledgerPolicy:'READ_ONLY', rollbackPolicy:'NOT_ALLOWED', driftPolicy:'ACTIVE', auditLabel:'PRODUCTION_LOCKED', uiBanner:'PRODUCTION LOCKED — no execution permitted' },
};

export type ExecutionIntentDto = { tenantId:string; executionId:string; actorId:string; actorRole:string; intentType:ExecutionIntentType; sourceSurface:SourceSurface; timestamp:string; reason:string; requiredProofIds:string[]; expectedStateTransition:{from:OperationalState;to:OperationalState}; idempotencyKey:string };
export type ExecutionIntentResultDto = { accepted:boolean; rejected:boolean; reason:IntentResultState; previousState:OperationalState; nextState:OperationalState; proofIds:string[]; ledgerEntryId:string; idempotencyKey:string; timestamp:string };
export type ProofNode = { proofId:string; proofType:string; title:string; summary:string; source:string; timestamp:string; confidence:number; upstreamProofIds:string[]; downstreamProofIds:string[]; evidenceHash:string; displayPriority:number; expandableDetails:Record<string,unknown>; environment: LedgerEnvironment; isFixtureBacked: boolean; sourceOfTruth: EvidenceSourceOfTruth };

export const OPERATIONAL_STATE_REGISTRY = { PROPOSED:{allowedNextActions:['SIMULATE','BLOCK']}, SIMULATED:{allowedNextActions:['REQUEST_APPROVAL','EXECUTE','BLOCK']}, APPROVAL_REQUIRED:{allowedNextActions:['APPROVE','BLOCK']}, APPROVED:{allowedNextActions:['EXECUTE','BLOCK']}, EXECUTED:{allowedNextActions:['VERIFY','ROLLBACK','BLOCK']}, VERIFIED:{allowedNextActions:['ROLLBACK','BLOCK']}, ROLLBACK_READY:{allowedNextActions:['ROLLBACK','BLOCK']}, ROLLED_BACK:{allowedNextActions:['BLOCK']}, BLOCKED:{allowedNextActions:[]} } as const;

type ExecutionRecord = {executionId:string;tenantId:string;state:OperationalState;approvalGranted:boolean;simulationReady:boolean;connectorReady:boolean;dataTrustReady:boolean;rollbackEligible:boolean;tenantExecutionMode:'ENFORCED'|'READ_ONLY';tenantMode: TenantOperationalMode;proofIds:string[];ledgerEntryId:string;fixtureBacked?:boolean;};
export type ActionHistoryEntry = {action:ExecutionIntentType;actor:string;actorRole:string;sourceSurface:SourceSurface;reason:string;result:IntentResultState;previousState:OperationalState;nextState:OperationalState;timestamp:string;proofIds:string[];ledgerEntryId:string;idempotencyKey:string};

type IdempotencyStore = {get:(k:string)=>ExecutionIntentResultDto|undefined;set:(k:string,v:ExecutionIntentResultDto)=>void};
class InMemoryIdempotencyStore implements IdempotencyStore { private m=new Map<string,ExecutionIntentResultDto>(); get(k:string){return this.m.get(k);} set(k:string,v:ExecutionIntentResultDto){this.m.set(k,v);} }

export class EconomicOperationsIntentService {
  private executions = new Map<string,ExecutionRecord>();
  private actions = new Map<string,ActionHistoryEntry[]>();
  private proofs = new Map<string,ProofNode[]>();
  constructor(private idempotencyStore:IdempotencyStore = new InMemoryIdempotencyStore()){}
  seedExecution(input:ExecutionRecord){ this.executions.set(`${input.tenantId}:${input.executionId}`, input); }
  getActions(tenantId:string, executionId:string){ return this.actions.get(`${tenantId}:${executionId}`) ?? []; }
  getOutcome(tenantId:string,executionId:string){ const e=this.executions.get(`${tenantId}:${executionId}`); if(!e) return null; const env:LedgerEnvironment=e.tenantMode==='DEMO'?'DEMO':e.tenantMode.startsWith('PILOT')?'PILOT':'PRODUCTION'; const fixture=Boolean(e.fixtureBacked); const verified=e.state==='VERIFIED' && !fixture && env==='PRODUCTION'; return { executionId, projectedMonthlySavings:1200, projectedAnnualSavings:14400, verifiedMonthlySavings:verified?1100:0, verifiedAnnualSavings:verified?13200:0, savingConfidence:e.dataTrustReady?0.92:0.41, executionStatus:e.state, approvalProvenance:e.approvalGranted?'APPROVED_BY_POLICY':'NOT_APPROVED', verificationStatus:verified?'VERIFIED':'PENDING', rollbackStatus:e.rollbackEligible?'ELIGIBLE':'BLOCKED', driftRecurrence:'LOW', evidenceCompleteness:e.proofIds.length>0?'COMPLETE':'PROOF_INCOMPLETE', timestamps:{updatedAt:new Date().toISOString()}, ledgerEnvironment:env, isFixtureBacked:fixture, isVerifiedSaving:verified, sourceOfTruth: fixture?'FIXTURE':env==='PRODUCTION'?'LEDGER':'SIMULATION' as EvidenceSourceOfTruth }; }
  getProofGraph(tenantId:string,executionId:string){ const e=this.executions.get(`${tenantId}:${executionId}`); if(!e) return null; const nodes = this.proofs.get(`${tenantId}:${executionId}`) ?? []; const mixed = nodes.some((n)=>n.isFixtureBacked) && nodes.some((n)=>!n.isFixtureBacked); return {executionId,status:nodes.length===0||mixed?'PROOF_INCOMPLETE':'PROOF_COMPLETE',nodes}; }
  submitIntent(intent:ExecutionIntentDto, env:'development'|'production'='development'):ExecutionIntentResultDto {
    const reject=(reason:IntentResultState,prev:OperationalState,next:OperationalState):ExecutionIntentResultDto=>({accepted:false,rejected:true,reason,previousState:prev,nextState:next,proofIds:[],ledgerEntryId:`ledger-${intent.executionId}`,idempotencyKey:intent.idempotencyKey,timestamp:new Date().toISOString()});
    if(env==='production' && !intent.tenantId) return reject('INTENT_REJECTED','BLOCKED','BLOCKED');
    if(!intent.actorId||!intent.actorRole||!intent.sourceSurface||!intent.idempotencyKey) return reject('INTENT_REJECTED',intent.expectedStateTransition.from,intent.expectedStateTransition.from);
    const key = `${intent.tenantId}:${intent.executionId}:${intent.intentType}:${intent.idempotencyKey}`;
    const dup = this.idempotencyStore.get(key); if(dup) return {...dup,reason:'INTENT_DUPLICATE',accepted:false,rejected:true};
    const execution = this.executions.get(`${intent.tenantId}:${intent.executionId}`); if(!execution) return reject('INTENT_REJECTED',intent.expectedStateTransition.from,intent.expectedStateTransition.from);
    const modeRule = TENANT_OPERATIONAL_MODE_REGISTRY[execution.tenantMode];
    if (execution.fixtureBacked && execution.tenantMode !== 'DEMO') return reject('INTENT_BLOCKED_BY_TENANT_MODE', execution.state, execution.state);
    if (!modeRule.allowedIntentTypes.includes(intent.intentType) || modeRule.blockedIntentTypes.includes(intent.intentType)) return reject('INTENT_BLOCKED_BY_TENANT_MODE', execution.state, execution.state);
    if (intent.intentType === 'EXECUTE' && !modeRule.allowsLiveExecution) return reject('INTENT_BLOCKED_BY_TENANT_MODE', execution.state, execution.state);
    if(execution.state!==intent.expectedStateTransition.from) return reject('INTENT_REJECTED',execution.state,execution.state);
    const allowed = OPERATIONAL_STATE_REGISTRY[execution.state].allowedNextActions as readonly ExecutionIntentType[];
    if(!allowed.includes(intent.intentType)) return reject('INTENT_BLOCKED_BY_POLICY',execution.state,execution.state);
    if(intent.intentType==='EXECUTE' && !execution.connectorReady) return reject('INTENT_BLOCKED_BY_CONNECTOR',execution.state,execution.state);
    if(intent.intentType==='EXECUTE' && !execution.dataTrustReady) return reject('INTENT_BLOCKED_BY_DATA_TRUST',execution.state,execution.state);
    if((execution.state==='APPROVAL_REQUIRED'||intent.intentType==='EXECUTE') && modeRule.requiresApproval && !execution.approvalGranted) return reject('INTENT_BLOCKED_BY_APPROVAL',execution.state,execution.state);
    if(intent.intentType==='ROLLBACK' && !execution.rollbackEligible) return reject('INTENT_BLOCKED_BY_ROLLBACK',execution.state,execution.state);
    execution.state = intent.expectedStateTransition.to;
    const result:ExecutionIntentResultDto={accepted:true,rejected:false,reason:'INTENT_ACCEPTED',previousState:intent.expectedStateTransition.from,nextState:intent.expectedStateTransition.to,proofIds:intent.requiredProofIds,ledgerEntryId:execution.ledgerEntryId,idempotencyKey:intent.idempotencyKey,timestamp:new Date().toISOString()};
    this.idempotencyStore.set(key,result);
    const hist = this.getActions(intent.tenantId,intent.executionId); hist.push({action:intent.intentType,actor:intent.actorId,actorRole:intent.actorRole,sourceSurface:intent.sourceSurface,reason:intent.reason,result:result.reason,previousState:result.previousState,nextState:result.nextState,timestamp:result.timestamp,proofIds:result.proofIds,ledgerEntryId:result.ledgerEntryId,idempotencyKey:result.idempotencyKey}); this.actions.set(`${intent.tenantId}:${intent.executionId}`,hist);
    const environment: LedgerEnvironment=execution.tenantMode==='DEMO'?'DEMO':execution.tenantMode.startsWith('PILOT')?'PILOT':'PRODUCTION'; const fixture=Boolean(execution.fixtureBacked);
    this.proofs.set(`${intent.tenantId}:${intent.executionId}`,[{proofId:'source-evidence',proofType:'SOURCE_EVIDENCE',title:'Source evidence',summary:'Evidence linked to execution',source:'connectors',timestamp:result.timestamp,confidence:0.92,upstreamProofIds:[],downstreamProofIds:['execution-decision'],evidenceHash:'hash-1',displayPriority:1,expandableDetails:{intent:intent.intentType},environment,isFixtureBacked:fixture,sourceOfTruth:fixture?'FIXTURE':'CONNECTOR'},{proofId:'execution-decision',proofType:'EXECUTION_DECISION',title:'Execution decision',summary:result.reason,source:'intent-service',timestamp:result.timestamp,confidence:0.95,upstreamProofIds:['source-evidence'],downstreamProofIds:['outcome-ledger-entry'],evidenceHash:'hash-2',displayPriority:2,expandableDetails:{state:result.nextState,auditLabel:modeRule.auditLabel},environment,isFixtureBacked:fixture,sourceOfTruth:'SIMULATION'},{proofId:'outcome-ledger-entry',proofType:'OUTCOME_LEDGER_ENTRY',title:'Outcome ledger entry',summary:execution.ledgerEntryId,source:'ledger',timestamp:result.timestamp,confidence:0.9,upstreamProofIds:['execution-decision'],downstreamProofIds:[],evidenceHash:'hash-3',displayPriority:3,expandableDetails:{ledgerEntryId:execution.ledgerEntryId,ledgerPolicy:modeRule.ledgerPolicy},environment,isFixtureBacked:fixture,sourceOfTruth:fixture?'SIMULATION':'LEDGER'}]);
    return result;
  }
}
