export const TECHNOLOGY_PORTFOLIO_AUTHORITY_READY='TECHNOLOGY_PORTFOLIO_AUTHORITY_READY';
export const TECHNOLOGY_PORTFOLIO_COLLECTIONS=['TECHNOLOGY_PORTFOLIO_ASSETS','TECHNOLOGY_PORTFOLIO_PRODUCTS','TECHNOLOGY_PORTFOLIO_APPLICATIONS','TECHNOLOGY_PORTFOLIO_VENDORS','TECHNOLOGY_PORTFOLIO_RELATIONSHIPS','TECHNOLOGY_PORTFOLIO_RISK_RECORDS','TECHNOLOGY_PORTFOLIO_VALUE_RECORDS','TECHNOLOGY_PORTFOLIO_SNAPSHOTS','TECHNOLOGY_PORTFOLIO_RECOMMENDATIONS'] as const;
export type Score='LOW'|'MEDIUM'|'HIGH'|'CRITICAL'|'UNKNOWN'; export type TargetType='ASSET'|'VENDOR'|'PRODUCT'|'APPLICATION';
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(t:string,id:string):Promise<T|undefined>;list(t:string,f?:Record<string,unknown>):Promise<T[]>;deleteTenant(t:string):Promise<void>;size():Promise<number>}
export interface TechnologyPortfolioAsset{ id:string;tenantId:string;assetType:'APPLICATION'|'SAAS'|'AI_MODEL'|'AI_AGENT'|'AI_WORKFLOW'|'MCP_SERVER'|'CLOUD_SERVICE'|'DATA_PLATFORM'|'INFRASTRUCTURE'|'SECURITY_TOOL'|'BUSINESS_SERVICE'|'UNKNOWN';name:string;description?:string;vendorId?:string;productId?:string;applicationId?:string;lifecycleStatus:'DISCOVERED'|'ACTIVE'|'UNDER_REVIEW'|'DUPLICATE'|'RETIRE_CANDIDATE'|'RENEWAL_RISK'|'NON_COMPLIANT'|'RETIRED'|'UNKNOWN';criticality:Score;businessCapability?:string;environment?:'PRODUCTION'|'NON_PRODUCTION'|'DEVELOPMENT'|'TEST'|'UNKNOWN';ownerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;contractIds:string[];entitlementIds:string[];renewalIds:string[];invoiceIds:string[];purchaseOrderIds:string[];usageSignalIds:string[];recommendationIds:string[];outcomeIds:string[];evidenceRefs:string[];annualSpend?:number;verifiedSavings?:number;projectedSavings?:number;commercialExposure?:number;currency?:string;sourceSystems:string[];graphNodeId?:string;confidenceScore:number;completenessScore:number;createdAt:string;updatedAt:string}
export interface TechnologyPortfolioVendor{ id:string;tenantId:string;name:string;category:'SAAS'|'CLOUD'|'AI'|'DATA'|'INFRASTRUCTURE'|'SECURITY'|'PROFESSIONAL_SERVICES'|'OTHER';assetIds:string[];productIds:string[];contractIds:string[];renewalIds:string[];entitlementIds:string[];annualSpend?:number;verifiedSavings?:number;projectedSavings?:number;exposureValue?:number;currency?:string;ownerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;riskLevel:Score;renewalRisk:Score;evidenceRefs:string[];sourceSystems:string[];confidenceScore:number;completenessScore:number;createdAt:string;updatedAt:string}
export interface TechnologyPortfolioProduct{ id:string;tenantId:string;vendorId?:string;name:string;productFamily?:string;productType:'APPLICATION'|'LICENSED_SOFTWARE'|'AI_SERVICE'|'AI_MODEL'|'CLOUD_SERVICE'|'DATA_PLATFORM'|'SECURITY_TOOL'|'INFRASTRUCTURE'|'SERVICE'|'UNKNOWN';assetIds:string[];entitlementIds:string[];usageSignalIds:string[];contractIds:string[];renewalIds:string[];annualSpend?:number;utilisationPercent?:number;verifiedSavings?:number;projectedSavings?:number;currency?:string;ownerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;evidenceRefs:string[];sourceSystems:string[];confidenceScore:number;completenessScore:number;createdAt:string;updatedAt:string}
export interface TechnologyPortfolioApplication{ id:string;tenantId:string;name:string;applicationType:'BUSINESS_APPLICATION'|'TECHNICAL_APPLICATION'|'SAAS_APPLICATION'|'AI_APPLICATION'|'INTEGRATION'|'SERVICE'|'UNKNOWN';businessCapability?:string;lifecycleStatus:'DISCOVERED'|'ACTIVE'|'UNDER_REVIEW'|'DUPLICATE'|'RETIRE_CANDIDATE'|'RETIRED'|'UNKNOWN';vendorId?:string;productIds:string[];assetIds:string[];ownerUserId?:string;technicalOwnerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;cmdbId?:string;serviceNowId?:string;contractIds:string[];entitlementIds:string[];evidenceRefs:string[];sourceSystems:string[];riskLevel:Score;criticality:Score;confidenceScore:number;completenessScore:number;createdAt:string;updatedAt:string}
export interface TechnologyPortfolioRelationship{ id:string;tenantId:string;fromType:'ASSET'|'VENDOR'|'PRODUCT'|'APPLICATION'|'CONTRACT'|'ENTITLEMENT'|'OWNER'|'COST_CENTRE'|'OUTCOME'|'EVIDENCE';fromId:string;toType:TechnologyPortfolioRelationship['fromType'];toId:string;relationshipType:'OWNS'|'FUNDS'|'USES'|'DEPENDS_ON'|'GOVERNED_BY'|'PAID_BY'|'VERIFIED_BY'|'SUPPORTED_BY_EVIDENCE'|'DUPLICATES'|'REPLACES'|'PART_OF'|'DERIVED_FROM';confidence:number;evidenceRefs:string[];sourceSystems:string[];createdAt:string;updatedAt:string}
export interface TechnologyPortfolioRiskRecord{ id:string;tenantId:string;targetType:TargetType;targetId:string;riskType:'MISSING_OWNER'|'MISSING_COST_CENTRE'|'MISSING_CONTRACT'|'MISSING_ENTITLEMENT'|'MISSING_USAGE'|'MISSING_FINANCIAL_TRUTH'|'RENEWAL_RISK'|'COMMERCIAL_EXPOSURE'|'DUPLICATE_CAPABILITY'|'UNDER_UTILISATION'|'UNVERIFIED_SAVINGS'|'EVIDENCE_GAP'|'GRAPH_DISCONNECTED';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';valueAtRisk?:number;currency?:string;description:string;recommendedAction:string;evidenceRefs:string[];sourceSystems:string[];status:'OPEN'|'ACKNOWLEDGED'|'RESOLVED'|'WAIVED';createdAt:string;updatedAt:string}
export interface TechnologyPortfolioValueRecord{ id:string;tenantId:string;targetType:TargetType;targetId:string;projectedValue?:number;approvedValue?:number;executedValue?:number;financeVerifiedValue?:number;varianceAmount?:number;variancePercent?:number;currency:string;confidence:'LOW'|'MEDIUM'|'HIGH'|'UNAVAILABLE';evidenceRefs:string[];sourceSystems:string[];createdAt:string;updatedAt:string}
export interface TechnologyPortfolioSnapshot{ id:string;tenantId:string;generatedAt:string;assetCount:number;vendorCount:number;productCount:number;applicationCount:number;totalAnnualSpend?:number;totalProjectedSavings?:number;totalFinanceVerifiedSavings?:number;totalCommercialExposure?:number;currency?:string;missingOwnerCount:number;missingCostCentreCount:number;missingContractCount:number;missingUsageCount:number;missingFinancialTruthCount:number;renewalRiskCount:number;duplicateCapabilityCount:number;underUtilisedCount:number;unverifiedSavingsCount:number;averageCompletenessScore:number;averageConfidenceScore:number;riskBreakdown:Record<string,number>;sourceCoverage:Record<string,number>;evidenceRefs:string[];evidenceCoverageScore?:number;evidenceGapCount?:number;restrictedEvidenceCount?:number;readiness:'READY'|'PARTIAL'|'MISSING_DATA'|'BLOCKED'|'DEMO';createdAt:string}
export interface TechnologyPortfolioRecommendation{ id:string;tenantId:string;targetType:TargetType;targetId:string;recommendationType:'ASSIGN_OWNER'|'ADD_COST_CENTRE'|'LINK_CONTRACT'|'LINK_ENTITLEMENT'|'IMPORT_USAGE'|'IMPORT_FINANCIAL_TRUTH'|'REVIEW_RENEWAL'|'INVESTIGATE_DUPLICATE'|'VERIFY_SAVINGS'|'COLLECT_EVIDENCE'|'RETIRE_CANDIDATE'|'OPTIMISE_SPEND';priority:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';title:string;description:string;recommendedAction:string;projectedValue?:number;currency?:string;evidenceRefs:string[];sourceSystems:string[];status:'OPEN'|'IN_PROGRESS'|'COMPLETED'|'DISMISSED';createdAt:string;updatedAt:string}
export interface PortfolioValueSummary{totalAnnualSpend?:number;totalProjectedSavings?:number;totalApprovedSavings?:number;totalExecutedSavings?:number;totalFinanceVerifiedSavings?:number;totalVariance?:number;commercialExposure?:number;renewalLeverageValue?:number;unverifiedSavings?:number}
