import { db, executionBatchItemsTable, executionBatchesTable, executionDependenciesTable, executionEscalationsTable, executionOrchestrationEventsTable, executionOrchestrationPlansTable, executionQueueItemsTable } from "@workspace/db";
import { and, eq, isNull, lt, or, inArray } from "drizzle-orm";

export class ExecutionOrchestrationRepository {
  async createPlan(input: any) { const [plan] = await db.insert(executionOrchestrationPlansTable).values(input).returning(); return plan; }
  async updatePlan(tenantId: string, id: number, patch: any) { const [plan] = await db.update(executionOrchestrationPlansTable).set({ ...patch, updatedAt: new Date() }).where(and(eq(executionOrchestrationPlansTable.tenantId, tenantId), eq(executionOrchestrationPlansTable.id, id))).returning(); return plan; }
  async getPlan(tenantId: string, planId: number) { const [plan] = await db.select().from(executionOrchestrationPlansTable).where(and(eq(executionOrchestrationPlansTable.tenantId, tenantId), eq(executionOrchestrationPlansTable.id, planId))).limit(1); return plan; }
  async listPlans(tenantId: string) { return db.select().from(executionOrchestrationPlansTable).where(eq(executionOrchestrationPlansTable.tenantId, tenantId)); }
  async enqueueQueueItems(items: any[]) { return db.insert(executionQueueItemsTable).values(items).returning(); }
  async getPlanItems(tenantId: string, planId: number) { return db.select().from(executionQueueItemsTable).where(and(eq(executionQueueItemsTable.tenantId, tenantId), eq(executionQueueItemsTable.planId, planId))); }
  async cancelPendingItems(tenantId: string, planId: number) { return db.update(executionQueueItemsTable).set({ status: "CANCELLED", updatedAt: new Date() }).where(and(eq(executionQueueItemsTable.tenantId, tenantId), eq(executionQueueItemsTable.planId, planId), inArray(executionQueueItemsTable.status, ["PENDING", "READY", "WAITING_APPROVAL", "WAITING_DEPENDENCIES", "PAUSED", "RETRY_SCHEDULED"]))).returning(); }
  async listActiveQueueItems(tenantId:string){ return db.select().from(executionQueueItemsTable).where(and(eq(executionQueueItemsTable.tenantId, tenantId), inArray(executionQueueItemsTable.status, ["QUEUED","WAITING_APPROVAL","WAITING_DEPENDENCIES","READY","RUNNING","PAUSED","ESCALATED"]))); }
  async getPlanEvents(tenantId: string, planId: number) { return db.select().from(executionOrchestrationEventsTable).where(and(eq(executionOrchestrationEventsTable.tenantId, tenantId), eq(executionOrchestrationEventsTable.planId, planId))); }
  async getReadyQueueItems(tenantId: string, limit = 10) { return db.select().from(executionQueueItemsTable).where(and(eq(executionQueueItemsTable.tenantId, tenantId), eq(executionQueueItemsTable.status, "READY"), or(isNull(executionQueueItemsTable.lockedAt), lt(executionQueueItemsTable.lockedAt, new Date(Date.now()-60_000))))).limit(limit); }
  async lockQueueItem(tenantId: string, id: number, workerId: string) { const [row]=await db.update(executionQueueItemsTable).set({ lockedAt: new Date(), lockedBy: workerId }).where(and(eq(executionQueueItemsTable.id,id),eq(executionQueueItemsTable.tenantId,tenantId),eq(executionQueueItemsTable.status,"READY"),or(isNull(executionQueueItemsTable.lockedAt),lt(executionQueueItemsTable.lockedAt,new Date(Date.now()-60_000))))).returning(); return row; }
  async updateItem(tenantId:string,id:number,patch:any){ const [row]=await db.update(executionQueueItemsTable).set({...patch,updatedAt:new Date()}).where(and(eq(executionQueueItemsTable.id,id),eq(executionQueueItemsTable.tenantId,tenantId))).returning(); return row; }
  async releaseExpiredLocks() { return db.update(executionQueueItemsTable).set({ lockedAt: null, lockedBy: null }).where(lt(executionQueueItemsTable.lockedAt, new Date(Date.now()-60_000))).returning(); }
  async evaluateDependencies(tenantId:string){ return db.select().from(executionQueueItemsTable).where(and(eq(executionQueueItemsTable.tenantId, tenantId), eq(executionQueueItemsTable.status, "WAITING_DEPENDENCIES"))); }
  async createDependency(input:any){ const [d] = await db.insert(executionDependenciesTable).values(input).returning(); return d; }
  async listDependenciesForItem(tenantId:string,queueItemId:number){ return db.select().from(executionDependenciesTable).where(and(eq(executionDependenciesTable.tenantId, tenantId), eq(executionDependenciesTable.queueItemId, queueItemId))); }
  async resolveDependency(tenantId:string,id:number){ const [d] = await db.update(executionDependenciesTable).set({status:"RESOLVED",resolvedAt:new Date()}).where(and(eq(executionDependenciesTable.tenantId, tenantId), eq(executionDependenciesTable.id, id))).returning(); return d; }
  async failDependency(tenantId:string,id:number,reason:string){ const [d] = await db.update(executionDependenciesTable).set({status:"FAILED",resolvedAt:new Date()}).where(and(eq(executionDependenciesTable.tenantId, tenantId), eq(executionDependenciesTable.id, id))).returning(); return { ...d, reason }; }
  async getBlockedItemsReadyForRecheck(tenantId:string){ return db.select().from(executionQueueItemsTable).where(and(eq(executionQueueItemsTable.tenantId, tenantId), eq(executionQueueItemsTable.status, "WAITING_DEPENDENCIES"))); }
  async createEscalation(input:any){ const [e] = await db.insert(executionEscalationsTable).values(input).returning(); return e; }
  async acknowledgeEscalation(tenantId:string,id:number,actorId?:string){ const [e] = await db.update(executionEscalationsTable).set({status:"ACKNOWLEDGED",assignedActorId:actorId,acknowledgedAt:new Date()}).where(and(eq(executionEscalationsTable.tenantId, tenantId), eq(executionEscalationsTable.id,id))).returning(); return e; }
  async resolveEscalation(tenantId:string,id:number,resolutionNotes?:string){ const [e] = await db.update(executionEscalationsTable).set({status:"RESOLVED",resolutionNotes,resolvedAt:new Date()}).where(and(eq(executionEscalationsTable.tenantId, tenantId), eq(executionEscalationsTable.id,id))).returning(); return e; }
  async listOpenEscalations(tenantId:string,planId?:number){ return db.select().from(executionEscalationsTable).where(planId ? and(eq(executionEscalationsTable.tenantId, tenantId), eq(executionEscalationsTable.planId, planId), eq(executionEscalationsTable.status, "OPEN")) : and(eq(executionEscalationsTable.tenantId, tenantId), eq(executionEscalationsTable.status, "OPEN"))); }
  async appendEvent(input:any){ const [e]=await db.insert(executionOrchestrationEventsTable).values(input).returning(); return e; }
  async createBatch(input:any){ const [b]=await db.insert(executionBatchesTable).values(input).returning(); return b; }
  async assignBatchItems(items:any[]){ return db.insert(executionBatchItemsTable).values(items).returning(); }
  async updateBatch(tenantId:string,id:number,patch:any){ const [b]=await db.update(executionBatchesTable).set({...patch, updatedAt:new Date()}).where(and(eq(executionBatchesTable.tenantId,tenantId),eq(executionBatchesTable.id,id))).returning(); return b; }
  async getBatch(tenantId:string,id:number){ const [b]=await db.select().from(executionBatchesTable).where(and(eq(executionBatchesTable.tenantId,tenantId),eq(executionBatchesTable.id,id))).limit(1); return b; }
  async listBatches(tenantId:string){ return db.select().from(executionBatchesTable).where(eq(executionBatchesTable.tenantId, tenantId)); }
  async getBatchItems(tenantId:string,batchId:number){ return db.select().from(executionBatchItemsTable).where(and(eq(executionBatchItemsTable.tenantId,tenantId),eq(executionBatchItemsTable.batchId,batchId))); }
}
