import { useCallback, useEffect, useMemo, useState } from 'react'
import { liveFetch, normalizeApiError } from '../lib/liveApi'
import { useWorkspace } from '../lib/workspaceContext'

export type ApprovalRequestStatus = 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED' | 'CANCELLED'
export type ApprovalType = 'STANDARD' | 'CAB' | 'EXECUTIVE' | 'EMERGENCY'
export type ApprovalRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type ApprovalRequest = { id: string; tenantId: string; actionId: string; status: ApprovalRequestStatus; approvalType: ApprovalType; riskLevel: ApprovalRiskLevel; requestedBy?: string; submittedAt?: string; approvedAt?: string; rejectedAt?: string; expiresAt?: string; reason: string; evidenceIds: string[]; approverIds: string[]; approvalRuleId?: string; createdAt: string; updatedAt: string; actionTitle?: string; actionDomain?: string; projectedMonthlyValue?: number; projectedAnnualValue?: number; blastRadius?: string; rollbackCapability?: string }
export type ApprovalDecision = { id: string; approvalRequestId: string; approverId: string; decision: 'APPROVE' | 'REJECT'; comment?: string; createdAt: string }
export type ApprovalAuthorityReport = { verdict: 'APPROVAL_NOT_REQUIRED' | 'APPROVAL_REQUIRED' | 'PENDING' | 'APPROVED' | 'REJECTED'; reason: string; approvalType: ApprovalType; riskLevel: ApprovalRiskLevel; requiredApprovers: number; approvedCount: number; evidenceCount: number; generatedAt: string }
export type ApprovalDashboard = { pending: number; approved: number; rejected: number; expired: number; awaitingExecutive: number; awaitingCab: number; monthlyValueAwaitingApproval: number; annualValueAwaitingApproval: number; requests: ApprovalRequest[] }
export type ApprovalRequestDetail = { request: ApprovalRequest; decisions: ApprovalDecision[]; report?: ApprovalAuthorityReport | null; action?: { title: string; domain: string; projectedMonthlyValue?: number; projectedAnnualValue?: number; blastRadius?: string; rollbackCapability?: string }; trustAuthority?: { verdict: string; confidence: string; blockers: unknown[]; missingEvidence: unknown[] }; executionReadiness?: { verdict: string; reasons: string[] } }
export type ApprovalCenterData = { dashboard: ApprovalDashboard; requests: ApprovalRequest[]; isDemo: boolean; error?: string }

export const approvalCenterApiPaths = ['/api/approval-authority/dashboard', '/api/approval-authority/requests/:id']
const iso = (day: number) => `2026-06-${String(day).padStart(2, '0')}T10:00:00.000Z`
export const demoApprovalRequests: ApprovalRequest[] = [
  { id: 'appr-standard', tenantId: 'demo', actionId: 'ga-ready', status: 'PENDING', approvalType: 'STANDARD', riskLevel: 'MEDIUM', requestedBy: 'finops@certen.io', submittedAt: iso(7), reason: 'Approval required for governed savings action.', evidenceIds: ['readiness-report', 'execution-readiness', 'evidence-summary'], approverIds: ['app-owner'], createdAt: iso(7), updatedAt: iso(7), actionTitle: 'Snowflake auto suspend', actionDomain: 'DATA', projectedMonthlyValue: 1200, projectedAnnualValue: 14400, blastRadius: 'MEDIUM', rollbackCapability: 'FULL' },
  { id: 'appr-cab', tenantId: 'demo', actionId: 'ga-cab', status: 'PENDING', approvalType: 'CAB', riskLevel: 'HIGH', requestedBy: 'ops@certen.io', submittedAt: iso(7), reason: 'CAB approval required for high blast-radius workflow disablement.', evidenceIds: ['cab-evidence', 'rollback-plan'], approverIds: ['cab-1', 'cab-2'], createdAt: iso(7), updatedAt: iso(7), actionTitle: 'Disable duplicate SaaS workflow', actionDomain: 'SAAS', projectedMonthlyValue: 18000, projectedAnnualValue: 216000, blastRadius: 'HIGH', rollbackCapability: 'PARTIAL' },
  { id: 'appr-exec', tenantId: 'demo', actionId: 'ga-exec', status: 'PENDING', approvalType: 'EXECUTIVE', riskLevel: 'CRITICAL', requestedBy: 'cio-office@certen.io', submittedAt: iso(6), reason: 'Executive approval required for critical protected value remediation.', evidenceIds: ['exec-readiness', 'outcome-ledger'], approverIds: ['cfo', 'cio'], createdAt: iso(6), updatedAt: iso(6), actionTitle: 'Reapply cloud spend guardrail', actionDomain: 'CLOUD', projectedMonthlyValue: 42000, projectedAnnualValue: 504000, blastRadius: 'HIGH', rollbackCapability: 'NONE' },
  { id: 'appr-approved', tenantId: 'demo', actionId: 'ga-approved', status: 'APPROVED', approvalType: 'STANDARD', riskLevel: 'MEDIUM', requestedBy: 'itam@certen.io', submittedAt: iso(5), approvedAt: iso(6), reason: 'Approved for execution.', evidenceIds: ['approval-pack'], approverIds: ['it-owner'], createdAt: iso(5), updatedAt: iso(6), actionTitle: 'Inactive Copilot reclaim', actionDomain: 'M365', projectedMonthlyValue: 9000, projectedAnnualValue: 108000, blastRadius: 'LOW', rollbackCapability: 'FULL' },
  { id: 'appr-rejected', tenantId: 'demo', actionId: 'ga-rejected', status: 'REJECTED', approvalType: 'STANDARD', riskLevel: 'MEDIUM', requestedBy: 'operator@certen.io', submittedAt: iso(4), rejectedAt: iso(5), reason: 'Rejected pending owner evidence.', evidenceIds: ['partial-evidence'], approverIds: ['app-owner'], createdAt: iso(4), updatedAt: iso(5), actionTitle: 'Retire stale AI asset', actionDomain: 'AI', projectedMonthlyValue: 7000, projectedAnnualValue: 84000, blastRadius: 'MEDIUM', rollbackCapability: 'PARTIAL' },
]
const emptyDashboard: ApprovalDashboard = { pending: 0, approved: 0, rejected: 0, expired: 0, awaitingExecutive: 0, awaitingCab: 0, monthlyValueAwaitingApproval: 0, annualValueAwaitingApproval: 0, requests: [] }
export function summarizeApprovals(requests: ApprovalRequest[]): ApprovalDashboard { const pending = requests.filter((r) => r.status === 'PENDING'); return { pending: pending.length, approved: requests.filter((r) => r.status === 'APPROVED').length, rejected: requests.filter((r) => r.status === 'REJECTED').length, expired: requests.filter((r) => r.status === 'EXPIRED').length, awaitingExecutive: pending.filter((r) => r.approvalType === 'EXECUTIVE').length, awaitingCab: pending.filter((r) => r.approvalType === 'CAB').length, monthlyValueAwaitingApproval: pending.reduce((sum, r) => sum + (r.projectedMonthlyValue ?? 0), 0), annualValueAwaitingApproval: pending.reduce((sum, r) => sum + (r.projectedAnnualValue ?? 0), 0), requests } }
export const demoApprovalCenterData: ApprovalCenterData = { dashboard: summarizeApprovals(demoApprovalRequests), requests: demoApprovalRequests, isDemo: true }
export function buildDemoApprovalDetail(id: string): ApprovalRequestDetail { const request = demoApprovalRequests.find((r) => r.id === id) ?? demoApprovalRequests[0]; const approvals = request.status === 'APPROVED' ? request.approverIds.map((approverId, index) => ({ id: `${request.id}-decision-${index}`, approvalRequestId: request.id, approverId, decision: 'APPROVE' as const, comment: 'Approved with evidence.', createdAt: request.approvedAt ?? request.updatedAt })) : request.status === 'REJECTED' ? [{ id: `${request.id}-reject`, approvalRequestId: request.id, approverId: request.approverIds[0] ?? 'approver', decision: 'REJECT' as const, comment: 'Missing required owner evidence.', createdAt: request.rejectedAt ?? request.updatedAt }] : []; return { request, decisions: approvals, report: { verdict: request.status === 'APPROVED' ? 'APPROVED' : request.status === 'REJECTED' ? 'REJECTED' : 'PENDING', reason: request.reason, approvalType: request.approvalType, riskLevel: request.riskLevel, requiredApprovers: request.approverIds.length, approvedCount: approvals.filter((d) => d.decision === 'APPROVE').length, evidenceCount: request.evidenceIds.length, generatedAt: request.updatedAt }, action: { title: request.actionTitle ?? request.actionId, domain: request.actionDomain ?? 'OTHER', projectedMonthlyValue: request.projectedMonthlyValue, projectedAnnualValue: request.projectedAnnualValue, blastRadius: request.blastRadius, rollbackCapability: request.rollbackCapability }, trustAuthority: { verdict: request.riskLevel === 'CRITICAL' ? 'APPROVAL_REQUIRED' : 'ELIGIBLE', confidence: request.riskLevel === 'CRITICAL' ? 'MEDIUM' : 'HIGH', blockers: request.riskLevel === 'CRITICAL' ? ['Rollback requires executive approval'] : [], missingEvidence: request.status === 'REJECTED' ? ['OWNER'] : [] }, executionReadiness: { verdict: request.status === 'APPROVED' ? 'ELIGIBLE' : 'APPROVAL_REQUIRED', reasons: ['Approval Authority must be approved before governed execution.'] } } }

export function useApprovalCenterData() { const workspace = useWorkspace(); const [data, setData] = useState<ApprovalCenterData>(() => workspace.mode === 'demo' ? demoApprovalCenterData : { dashboard: emptyDashboard, requests: [], isDemo: false }); const [loading, setLoading] = useState(false)
  const refresh = useCallback(async () => { if (workspace.mode === 'demo') { setData(demoApprovalCenterData); return demoApprovalCenterData }
    if (!workspace.dataReady) { const empty = { dashboard: emptyDashboard, requests: [], isDemo: false }; setData(empty); return empty } setLoading(true); try { const dashboard = await liveFetch<ApprovalDashboard>('/api/approval-authority/dashboard'); const next = { dashboard: { ...emptyDashboard, ...(dashboard ?? {}) }, requests: dashboard.requests ?? [], isDemo: false }; setData(next); return next } catch (error) { const err = normalizeApiError(error); const fallback = { dashboard: emptyDashboard, requests: [], isDemo: false, error: err.message }; setData(fallback); return fallback } finally { setLoading(false) } }, [workspace.mode, workspace.dataReady])
  useEffect(() => { void refresh() }, [refresh])
  const fetchApprovalDetail = useCallback(async (id: string) => { if (data.isDemo || workspace.mode === 'demo') return buildDemoApprovalDetail(id); return await liveFetch<ApprovalRequestDetail>(`/api/approval-authority/requests/${id}`) }, [data.isDemo, workspace.mode])
  const decideApproval = useCallback(async (id: string, decision: 'approve' | 'reject' | 'cancel') => { if (data.isDemo || workspace.mode === 'demo') return buildDemoApprovalDetail(id); await liveFetch(`/api/approval-authority/requests/${id}/${decision}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ approverId: 'control-plane-operator' }) }); await refresh(); return fetchApprovalDetail(id) }, [data.isDemo, workspace.mode, refresh, fetchApprovalDetail])
  return useMemo(() => ({ ...data, loading, refresh, fetchApprovalDetail, decideApproval }), [data, loading, refresh, fetchApprovalDetail, decideApproval])
}
