import { useMemo } from 'react'
import { useWorkspace } from '../lib/workspaceContext'
import { useLiveResource } from './useLiveResource'
export type ExecutiveRiskItem={id:string;title:string;riskLevel:string;riskScore:number;domain:string;vendorName?:string;applicationName?:string;annualCostExposure?:number;potentialAnnualSavings?:number;daysToRenewal?:number;ownerMissing?:boolean;affectedUsers?:number;rationale:string;recommendedAction:string;evidenceRefs:string[]}
export type ExecutiveRiskDataState='LIVE'|'DEMO'|'NOT_CONNECTED'|'NO_DATA'
export type ExecutiveRiskData={summary:{portfolioRiskScore:number;criticalIssues:number;highRiskIssues:number;ownerlessSpend:number;renewalsAtRisk:number;aiGovernanceGaps:number;shadowITFindings:number;potentialAnnualSavings:number;evidenceConfidence:string};topRisks:ExecutiveRiskItem[];leadershipActions:{actionType:string;label:string;count:number;priority:string;rationale:string}[];domainBreakdown:{domain:string;issueCount:number;criticalCount:number;highCount:number;exposedSpend:number;potentialSavings:number}[];executiveNarrative:string;evidenceRefs:string[];generatedAt:string;dataState:ExecutiveRiskDataState;error?:string}
const risks:ExecutiveRiskItem[]=[{id:'ownerless-dropbox',title:'Dropbox has exposed spend without an owner',riskLevel:'HIGH',riskScore:95,domain:'SHADOW_IT',vendorName:'Dropbox',applicationName:'Dropbox',annualCostExposure:52000,ownerMissing:true,rationale:'Ownerless storage exposure appears across Shadow IT, SaaS Rationalisation, and Ownership.',recommendedAction:'ASSIGN_OWNER',evidenceRefs:['duplicate-dropbox-onedrive']},{id:'ai-chatgpt',title:'ChatGPT is part of an AI governance risk cluster',riskLevel:'HIGH',riskScore:100,domain:'AI_GOVERNANCE',vendorName:'OpenAI',applicationName:'ChatGPT',annualCostExposure:36000,potentialAnnualSavings:10200,ownerMissing:true,affectedUsers:34,rationale:'ChatGPT has AI policy and ownership exposure with active usage evidence.',recommendedAction:'REVIEW_AI_POLICY',evidenceRefs:['oauth-app-chatgpt','signin-chatgpt-34-users']},{id:'renewal-slack',title:'Slack has renewal-linked risk',riskLevel:'HIGH',riskScore:100,domain:'RENEWALS',vendorName:'Slack Technologies',applicationName:'Slack',annualCostExposure:180000,potentialAnnualSavings:54000,daysToRenewal:45,rationale:'Slack has a near-term renewal and duplicate collaboration exposure.',recommendedAction:'RENEGOTIATE_RENEWAL',evidenceRefs:['renewal-slack-45-days']},{id:'duplicate-dropbox',title:'Dropbox is part of a duplicate capability cluster',riskLevel:'MEDIUM',riskScore:60,domain:'SAAS_RATIONALISATION',vendorName:'Dropbox',applicationName:'Dropbox',annualCostExposure:52000,potentialAnnualSavings:20800,ownerMissing:true,rationale:'Dropbox overlaps with OneDrive.',recommendedAction:'CONSOLIDATE_VENDOR',evidenceRefs:['duplicate-dropbox-onedrive']},{id:'tableau-value',title:'Tableau high-cost low-usage opportunity',riskLevel:'HIGH',riskScore:85,domain:'RENEWALS',vendorName:'Tableau',applicationName:'Tableau',annualCostExposure:140000,potentialAnnualSavings:35000,daysToRenewal:87,rationale:'Tableau has high cost and low utilisation before renewal.',recommendedAction:'EXECUTIVE_REVIEW',evidenceRefs:['usage-tableau-29pct']}]
const actions=['Assign Owners','Review AI Policy','Renegotiate Renewals','Consolidate Vendors','Retire Unused Tools','Validate Data','Generate Evidence']
const emptyExecutiveRiskData:Omit<ExecutiveRiskData,'dataState'|'error'>={summary:{portfolioRiskScore:0,criticalIssues:0,highRiskIssues:0,ownerlessSpend:0,renewalsAtRisk:0,aiGovernanceGaps:0,shadowITFindings:0,potentialAnnualSavings:0,evidenceConfidence:'UNKNOWN'},topRisks:[],leadershipActions:[],domainBreakdown:[],executiveNarrative:'',evidenceRefs:[],generatedAt:''}
export const demoExecutiveRiskData:ExecutiveRiskData={summary:{portfolioRiskScore:88,criticalIssues:0,highRiskIssues:4,ownerlessSpend:140000,renewalsAtRisk:2,aiGovernanceGaps:1,shadowITFindings:1,potentialAnnualSavings:120000,evidenceConfidence:'HIGH'},topRisks:risks,leadershipActions:actions.map((label,i)=>({actionType:label.toUpperCase().replace(/ /g,'_'),label,count:i<4?1:0,priority:i<4?'HIGH':'MEDIUM',rationale:'Read-only leadership focus area.'})),domainBreakdown:[{domain:'RENEWALS',issueCount:2,criticalCount:0,highCount:2,exposedSpend:320000,potentialSavings:89000},{domain:'OWNERSHIP',issueCount:2,criticalCount:0,highCount:2,exposedSpend:140000,potentialSavings:0},{domain:'SHADOW_IT',issueCount:1,criticalCount:0,highCount:1,exposedSpend:52000,potentialSavings:0},{domain:'SAAS_RATIONALISATION',issueCount:1,criticalCount:0,highCount:0,exposedSpend:52000,potentialSavings:20800},{domain:'AI_GOVERNANCE',issueCount:1,criticalCount:0,highCount:1,exposedSpend:36000,potentialSavings:10200},{domain:'M365',issueCount:0,criticalCount:0,highCount:0,exposedSpend:0,potentialSavings:0}],executiveNarrative:'The highest-priority governance issues are concentrated in ownerless applications, near-term renewals, AI governance exposure, and duplicate SaaS capability. Immediate attention should focus on ownership assignment, AI policy review, renewal rationalisation, and evidence-backed executive review.',evidenceRefs:Array.from(new Set(risks.flatMap((r)=>r.evidenceRefs))),generatedAt:'2026-06-03T00:00:00.000Z',dataState:'DEMO'}
const notConnectedExecutiveRiskData:ExecutiveRiskData={...emptyExecutiveRiskData,dataState:'NOT_CONNECTED'}
export function normalizeExecutiveRiskPayload(payload:any):ExecutiveRiskData{const topRisks=Array.isArray(payload?.topRisks)?payload.topRisks:[];return{summary:{...emptyExecutiveRiskData.summary,...(payload?.summary??{})},topRisks,leadershipActions:Array.isArray(payload?.leadershipActions)?payload.leadershipActions:[],domainBreakdown:Array.isArray(payload?.domainBreakdown)?payload.domainBreakdown:[],executiveNarrative:String(payload?.executiveNarrative??''),evidenceRefs:Array.isArray(payload?.evidenceRefs)?payload.evidenceRefs:[],generatedAt:String(payload?.generatedAt??''),dataState:topRisks.length===0?'NO_DATA':'LIVE'}}
export function useExecutiveRiskData(){
  const workspace=useWorkspace()
  const live=useLiveResource<ExecutiveRiskData>({path:'/api/executive-risk',enabled:workspace.mode==='live',requireDataReady:false,initialData:{...emptyExecutiveRiskData,dataState:'NO_DATA'},normalizer:normalizeExecutiveRiskPayload,isEmpty:(data)=>data.topRisks.length===0})
  return useMemo(()=>{
    if(workspace.mode==='demo')return{data:demoExecutiveRiskData,loading:false,error:null,isEmptyLive:false,refresh:()=>Promise.resolve(demoExecutiveRiskData)}
    if(!workspace.dataReady)return{data:notConnectedExecutiveRiskData,loading:false,error:null,isEmptyLive:false,refresh:()=>Promise.resolve(notConnectedExecutiveRiskData)}
    const data:ExecutiveRiskData=live.error?{...emptyExecutiveRiskData,dataState:'NO_DATA',error:live.error.message}:live.data
    return{data,loading:live.loading,error:live.error,isEmptyLive:live.isEmpty,refresh:live.refresh}
  },[workspace.mode,workspace.dataReady,live.data,live.loading,live.error,live.isEmpty,live.refresh])
}
