import { useMemo } from 'react'
import { useWorkspace } from '../lib/workspaceContext'
import { useLiveResource } from './useLiveResource'

type Node = { id:string; type:string; label:string; domain?:string; riskLevel?:string; annualCost?:number; potentialAnnualSavings?:number; metadata?:Record<string, unknown> }
type Edge = { id:string; sourceId:string; targetId:string; type:string; label:string; metadata?:Record<string, unknown> }
type Insight = { id:string; type:string; title:string; severity:string; relatedNodeIds:string[]; rationale:string; recommendedAction:string; evidenceRefs:string[] }
export type GovernanceGraphData = { nodes:Node[]; edges:Edge[]; summary:{ vendors:number; applications:number; owners:number; findings:number; risks:number; opportunities:number; evidenceItems:number; ownerlessApplications:number; highRiskApplications:number; annualCostMapped:number; potentialAnnualSavingsMapped:number; domainsRepresented:string[] }; insights:Insight[]; generatedAt:string }
const app = (id:string,label:string,vendor:string,owner:string|undefined,cost:number,domains:string[],risk='HIGH'): Node => ({ id:`app:${id}`, type:'APPLICATION', label, riskLevel:risk, annualCost:cost, metadata:{ vendor, owner, domains, renewalDate: id==='slack'?'2026-07-18':undefined } })
const finding = (id:string,label:string,domain:string,risk='HIGH',savings?:number): Node => ({ id:`finding:${id}`, type:'FINDING', label, domain, riskLevel:risk, potentialAnnualSavings:savings })
const evidence = ['oauth-app-chatgpt','signin-chatgpt-34-users','renewal-slack-45-days','usage-tableau-29pct','owner-gap-claude','duplicate-dropbox-onedrive','duplicate-zoom-teams'].map((label) => ({ id:`evidence:${label}`, type:'EVIDENCE', label }))
const apps = [app('slack','Slack','Slack Technologies','engineering@example.com',180000,['RENEWALS','SAAS_RATIONALISATION']), app('zoom','Zoom','Zoom','it@example.com',95000,['RENEWALS','SAAS_RATIONALISATION']), app('tableau','Tableau','Tableau','data@example.com',140000,['RENEWALS','SAAS_RATIONALISATION']), app('dropbox','Dropbox','Dropbox',undefined,52000,['SHADOW_IT','SAAS_RATIONALISATION','OWNERSHIP']), app('chatgpt','ChatGPT','OpenAI',undefined,36000,['AI_GOVERNANCE','SHADOW_IT','OWNERSHIP']), app('claude','Claude','Anthropic',undefined,24000,['AI_GOVERNANCE','OWNERSHIP']), app('microsoft-copilot','Microsoft Copilot','Microsoft','ai-governance@example.com',15120,['AI_GOVERNANCE']), app('github-copilot','GitHub Copilot','GitHub','engineering@example.com',2280,['AI_GOVERNANCE']), app('box','Box','Box','legal@example.com',60000,['RENEWALS','SAAS_RATIONALISATION'],'MEDIUM'), app('miro','Miro','Miro','product@example.com',38000,['SAAS_RATIONALISATION','OWNERSHIP'],'MEDIUM'), app('salesforce','Salesforce','Salesforce','revenue@example.com',240000,['RENEWALS','EXECUTIVE_VALUE'],'LOW'), app('hubspot','HubSpot','HubSpot','marketing@example.com',120000,['OWNERSHIP','SAAS_RATIONALISATION','RENEWALS']), app('onedrive','OneDrive','Microsoft','it@example.com',0,['M365_OPTIMISATION','SAAS_RATIONALISATION'],'LOW'), app('teams','Teams','Microsoft','collaboration@example.com',0,['M365_OPTIMISATION','SAAS_RATIONALISATION'],'LOW'), app('power-bi','Power BI','Microsoft','data@example.com',0,['M365_OPTIMISATION','SAAS_RATIONALISATION'],'LOW')]
const findings = [finding('chatgpt-ai-policy-gap','ChatGPT AI policy gap','AI_GOVERNANCE', 'HIGH', 10200), finding('claude-ownerless-ai-app','Claude ownerless AI app','AI_GOVERNANCE'), finding('dropbox-duplicate-storage','Dropbox duplicate storage','SAAS_RATIONALISATION','HIGH',20800), finding('slack-renewal-risk','Slack renewal risk','RENEWALS','HIGH',54000), finding('tableau-high-cost-low-usage','Tableau high-cost low-usage','RENEWALS','HIGH',35000), finding('hubspot-ownership-conflict','HubSpot ownership conflict','OWNERSHIP'), finding('zoom-duplicate-communications','Zoom duplicate communications','SAAS_RATIONALISATION','HIGH',28500), finding('box-missing-usage-data','Box missing usage data','RENEWALS','MEDIUM')]
const vendors = Array.from(new Set(apps.map((node) => String(node.metadata?.vendor)))).map((label) => ({ id:`vendor:${label.toLowerCase().replace(/\s+/g,'-')}`, type:'VENDOR', label }))
const owners = Array.from(new Set(apps.map((node) => String(node.metadata?.owner ?? '')).filter(Boolean))).map((label) => ({ id:`owner:${label}`, type:'OWNER', label }))
const domains = Array.from(new Set(apps.flatMap((node) => node.metadata?.domains as string[]))).map((label) => ({ id:`domain:${label}`, type:'DOMAIN', label, domain:label }))
const edges: Edge[] = apps.flatMap((node) => [{ id:`vendor-edge:${node.id}`, sourceId:`vendor:${String(node.metadata?.vendor).toLowerCase().replace(/\s+/g,'-')}`, targetId:node.id, type:'OWNS_APPLICATION', label:'owns application' }, ...(node.metadata?.owner ? [{ id:`owner-edge:${node.id}`, sourceId:node.id, targetId:`owner:${node.metadata.owner}`, type:'HAS_OWNER', label:'has owner' }] : [])])
export const demoGovernanceGraphData: GovernanceGraphData = { nodes:[...vendors,...apps,...owners,...findings,...evidence,...domains], edges, summary:{ vendors:vendors.length, applications:apps.length, owners:owners.length, findings:findings.length, risks:8, opportunities:5, evidenceItems:evidence.length, ownerlessApplications:3, highRiskApplications:8, annualCostMapped:1105400, potentialAnnualSavingsMapped:148500, domainsRepresented:domains.map((d)=>d.label) }, insights:[{ id:'ownerless-dropbox', type:'OWNERLESS_HIGH_SPEND', title:'Dropbox has exposed spend without an owner', severity:'HIGH', relatedNodeIds:['app:dropbox'], rationale:'Dropbox maps annual cost without an owner relationship.', recommendedAction:'Assign accountable business and budget owners.', evidenceRefs:['duplicate-dropbox-onedrive'] }, { id:'multidomain-chatgpt', type:'MULTI_DOMAIN_RISK', title:'ChatGPT appears across multiple governance domains', severity:'HIGH', relatedNodeIds:['app:chatgpt'], rationale:'ChatGPT is present in AI Governance, Shadow IT, and Ownership contexts.', recommendedAction:'Review the shared governance issue across contributing domains.', evidenceRefs:['oauth-app-chatgpt','signin-chatgpt-34-users'] }, { id:'duplicate-dropbox', type:'DUPLICATE_CAPABILITY_CLUSTER', title:'Dropbox is part of a duplicate capability cluster', severity:'MEDIUM', relatedNodeIds:['app:dropbox','app:onedrive'], rationale:'Dropbox overlaps with OneDrive.', recommendedAction:'Assess preferred tool and consolidation opportunity.', evidenceRefs:['duplicate-dropbox-onedrive'] }, { id:'ai-chatgpt', type:'AI_GOVERNANCE_CLUSTER', title:'ChatGPT is part of an AI governance risk cluster', severity:'HIGH', relatedNodeIds:['app:chatgpt'], rationale:'ChatGPT has high-risk AI governance findings.', recommendedAction:'Review AI ownership, policy coverage, and evidence.', evidenceRefs:['oauth-app-chatgpt'] }, { id:'renewal-slack', type:'RENEWAL_RISK_CLUSTER', title:'Slack has renewal-linked risk', severity:'HIGH', relatedNodeIds:['app:slack'], rationale:'Slack has a near-term renewal connected to high-risk findings.', recommendedAction:'Prepare renewal review with risk, owner, cost, and evidence context.', evidenceRefs:['renewal-slack-45-days'] }, { id:'value-slack', type:'HIGH_VALUE_OPPORTUNITY', title:'Slack maps a high-value opportunity', severity:'HIGH', relatedNodeIds:['finding:slack-renewal-risk'], rationale:'Potential savings mapped exceed $25,000.', recommendedAction:'Prioritize executive value review and supporting evidence.', evidenceRefs:['renewal-slack-45-days'] }], generatedAt:'2026-06-03T00:00:00.000Z' }
export function normalizeGovernanceGraphPayload(payload:any): GovernanceGraphData { return { nodes:Array.isArray(payload?.nodes)?payload.nodes:[], edges:Array.isArray(payload?.edges)?payload.edges:[], summary:{...demoGovernanceGraphData.summary, ...(payload?.summary ?? {})}, insights:Array.isArray(payload?.insights)?payload.insights:[], generatedAt:String(payload?.generatedAt ?? demoGovernanceGraphData.generatedAt) } }
export type GovernanceGraphDataState = 'LIVE' | 'DEMO' | 'NOT_CONNECTED' | 'NO_DATA'
const notConnectedGovernanceGraphData: GovernanceGraphData = { nodes:[], edges:[], summary:{ vendors:0, applications:0, owners:0, findings:0, risks:0, opportunities:0, evidenceItems:0, ownerlessApplications:0, highRiskApplications:0, annualCostMapped:0, potentialAnnualSavingsMapped:0, domainsRepresented:[] }, insights:[], generatedAt:'' }
export function useGovernanceGraphData() {
  const workspace = useWorkspace()
  const live = useLiveResource<GovernanceGraphData>({ path:'/api/governance-graph', enabled: workspace.mode === 'live', requireDataReady:false, initialData:demoGovernanceGraphData, normalizer:normalizeGovernanceGraphPayload, isEmpty:(data)=>data.nodes.length===0 })
  return useMemo(() => {
    if (workspace.mode === 'demo') return { data:demoGovernanceGraphData, loading:false, error:null, isEmptyLive:false, dataState:'DEMO' as GovernanceGraphDataState, refresh:()=>Promise.resolve(demoGovernanceGraphData) }
    if (!workspace.dataReady) return { data:notConnectedGovernanceGraphData, loading:false, error:null, isEmptyLive:true, dataState:'NOT_CONNECTED' as GovernanceGraphDataState, refresh:live.refresh }
    const dataState: GovernanceGraphDataState = live.error ? 'NO_DATA' : live.data.nodes.length === 0 ? 'NO_DATA' : 'LIVE'
    return { data:live.data, loading:live.loading, error:live.error, isEmptyLive:live.isEmpty, dataState, refresh:live.refresh }
  }, [workspace.mode, workspace.dataReady, live.data, live.loading, live.error, live.isEmpty, live.refresh])
}
