import { useCallback, useEffect, useMemo, useState } from 'react'
import { liveFetch, normalizeApiError } from '../lib/liveApi'
import { useWorkspace } from '../lib/workspaceContext'

export type ProtectedOutcomeStatus = 'PROTECTED' | 'AT_RISK' | 'DRIFTED' | 'REMEDIATION_OPEN' | 'RESOLVED' | 'ARCHIVED'
export type DriftFinding = { id: string; tenantId: string; protectedOutcomeId: string; signalIds: string[]; status: 'OPEN' | 'ACKNOWLEDGED' | 'REMEDIATION_CREATED' | 'RESOLVED' | 'DISMISSED'; severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; driftType: 'VALUE_LEAKAGE' | 'CONTROL_BREAKDOWN' | 'RECURRING_WASTE' | 'OWNERSHIP_DRIFT' | 'POLICY_DRIFT' | 'UNKNOWN'; estimatedMonthlyLeakage?: number; estimatedAnnualLeakage?: number; reason: string; recommendedAction: string; createdAt: string; updatedAt: string }
export type DriftPolicy = { id: string; name: string; policyType: string; checkFrequency: 'DAILY' | 'WEEKLY' | 'MONTHLY'; enabled: boolean }
export type RetentionCheck = { id: string; result: 'PASSED' | 'FAILED' | 'AT_RISK' | 'UNKNOWN'; retainedMonthlyValue?: number; retainedAnnualValue?: number; driftedMonthlyValue?: number; driftedAnnualValue?: number; evidenceIds: string[]; checkedAt: string }
export type DriftRemediationAction = { id: string; protectedOutcomeId: string; driftFindingId: string; governedActionId?: string; status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CANCELLED'; actionType: 'REOPEN_GOVERNED_ACTION' | 'CREATE_NEW_GOVERNED_ACTION' | 'REQUEST_OWNER_REVIEW' | 'REAPPLY_EXECUTION' | 'CREATE_TICKET' | 'MANUAL_REVIEW'; description: string; createdAt: string; updatedAt: string }
export type ProtectedOutcome = { id: string; tenantId: string; outcomeId: string; actionId?: string; executionId?: string; assetId?: string; assetType?: 'AI_ASSET' | 'M365' | 'SAAS' | 'CLOUD' | 'APPLICATION' | 'OTHER'; name: string; description?: string; status: ProtectedOutcomeStatus; valueType: 'SAVINGS' | 'COST_AVOIDANCE' | 'PRODUCTIVITY' | 'RISK_REDUCTION' | 'REVENUE_ENABLEMENT' | 'OTHER'; protectedMonthlyValue?: number; protectedAnnualValue?: number; retainedMonthlyValue?: number; retainedAnnualValue?: number; driftedMonthlyValue?: number; driftedAnnualValue?: number; currency?: string; protectionStart: string; lastCheckedAt?: string; nextCheckAt?: string; policyIds: string[]; driftFindingIds: string[]; evidenceIds: string[]; createdAt: string; updatedAt: string }
export type OutcomeProtectionDashboard = { protectedOutcomes: number; retainedOutcomes: number; atRiskOutcomes: number; driftedOutcomes: number; remediationOpen: number; protectedMonthlyValue: number; protectedAnnualValue: number; retainedMonthlyValue: number; retainedAnnualValue: number; driftedMonthlyValue: number; driftedAnnualValue: number; retentionRate: number | null; openDriftFindings: DriftFinding[]; upcomingChecks: ProtectedOutcome[] }
export type OutcomeProtectionDataState = 'LIVE' | 'DEMO' | 'NOT_CONNECTED' | 'NO_DATA'
export type ProtectedOutcomeDetail = { outcome: ProtectedOutcome; policies: DriftPolicy[]; findings: DriftFinding[]; retentionChecks: RetentionCheck[]; remediations: DriftRemediationAction[]; signals?: unknown[]; dataState: OutcomeProtectionDataState; error?: string }
export type OutcomeProtectionData = { dashboard: OutcomeProtectionDashboard; outcomes: ProtectedOutcome[]; isDemo: boolean; dataState: OutcomeProtectionDataState; error?: string }

export const outcomeProtectionApiPaths = ['/api/outcome-protection/dashboard', '/api/outcome-protection/outcomes']
const emptyDashboard: OutcomeProtectionDashboard = { protectedOutcomes: 0, retainedOutcomes: 0, atRiskOutcomes: 0, driftedOutcomes: 0, remediationOpen: 0, protectedMonthlyValue: 0, protectedAnnualValue: 0, retainedMonthlyValue: 0, retainedAnnualValue: 0, driftedMonthlyValue: 0, driftedAnnualValue: 0, retentionRate: null, openDriftFindings: [], upcomingChecks: [] }
const iso = (day: number) => `2026-06-${String(day).padStart(2, '0')}T09:00:00.000Z`

export const demoProtectedOutcomes: ProtectedOutcome[] = [
  { id: 'po-protected', tenantId: 'demo', outcomeId: 'outcome-copilot', actionId: 'ga-retained', assetType: 'M365', name: 'Copilot licence reclaim retained', status: 'PROTECTED', valueType: 'SAVINGS', protectedMonthlyValue: 18000, protectedAnnualValue: 216000, retainedMonthlyValue: 18000, retainedAnnualValue: 216000, driftedMonthlyValue: 0, driftedAnnualValue: 0, currency: 'USD', protectionStart: iso(1), lastCheckedAt: iso(7), nextCheckAt: iso(14), policyIds: ['policy-license'], driftFindingIds: [], evidenceIds: ['evidence-copilot-retained'], createdAt: iso(1), updatedAt: iso(7) },
  { id: 'po-risk', tenantId: 'demo', outcomeId: 'outcome-owner', actionId: 'ga-owner', assetType: 'SAAS', name: 'SaaS ownership cleanup', status: 'AT_RISK', valueType: 'PRODUCTIVITY', protectedMonthlyValue: 9000, protectedAnnualValue: 108000, retainedMonthlyValue: 8500, retainedAnnualValue: 102000, driftedMonthlyValue: 500, driftedAnnualValue: 6000, currency: 'USD', protectionStart: iso(2), lastCheckedAt: iso(8), nextCheckAt: iso(13), policyIds: ['policy-owner'], driftFindingIds: ['df-owner'], evidenceIds: ['evidence-owner-gap'], createdAt: iso(2), updatedAt: iso(8) },
  { id: 'po-drifted', tenantId: 'demo', outcomeId: 'outcome-cloud', actionId: 'ga-cloud', assetType: 'CLOUD', name: 'Cloud rightsizing savings', status: 'DRIFTED', valueType: 'SAVINGS', protectedMonthlyValue: 26000, protectedAnnualValue: 312000, retainedMonthlyValue: 21000, retainedAnnualValue: 252000, driftedMonthlyValue: 5000, driftedAnnualValue: 60000, currency: 'USD', protectionStart: iso(3), lastCheckedAt: iso(8), nextCheckAt: iso(15), policyIds: ['policy-spend'], driftFindingIds: ['df-value'], evidenceIds: ['evidence-cloud-spend'], createdAt: iso(3), updatedAt: iso(8) },
  { id: 'po-remediation', tenantId: 'demo', outcomeId: 'outcome-ai-route', actionId: 'ga-ai', assetType: 'AI_ASSET', name: 'AI model route optimisation', status: 'REMEDIATION_OPEN', valueType: 'COST_AVOIDANCE', protectedMonthlyValue: 14000, protectedAnnualValue: 168000, retainedMonthlyValue: 11000, retainedAnnualValue: 132000, driftedMonthlyValue: 3000, driftedAnnualValue: 36000, currency: 'USD', protectionStart: iso(4), lastCheckedAt: iso(8), nextCheckAt: iso(11), policyIds: ['policy-route'], driftFindingIds: ['df-policy'], evidenceIds: ['evidence-ai-policy'], createdAt: iso(4), updatedAt: iso(8) },
  { id: 'po-resolved', tenantId: 'demo', outcomeId: 'outcome-snowflake', actionId: 'ga-snowflake', assetType: 'OTHER', name: 'Snowflake warehouse suspend', status: 'RESOLVED', valueType: 'SAVINGS', protectedMonthlyValue: 12000, protectedAnnualValue: 144000, retainedMonthlyValue: 12000, retainedAnnualValue: 144000, driftedMonthlyValue: 0, driftedAnnualValue: 0, currency: 'USD', protectionStart: iso(1), lastCheckedAt: iso(8), nextCheckAt: iso(16), policyIds: ['policy-config'], driftFindingIds: [], evidenceIds: ['evidence-snowflake'], createdAt: iso(1), updatedAt: iso(8) },
]
export const demoDriftFindings: DriftFinding[] = [
  { id: 'df-value', tenantId: 'demo', protectedOutcomeId: 'po-drifted', signalIds: ['signal-spend'], status: 'OPEN', severity: 'HIGH', driftType: 'VALUE_LEAKAGE', estimatedMonthlyLeakage: 5000, estimatedAnnualLeakage: 60000, reason: 'Licence reassigned after reclaim and spend returned.', recommendedAction: 'Reapply policy and reopen governed action.', createdAt: iso(8), updatedAt: iso(8) },
  { id: 'df-owner', tenantId: 'demo', protectedOutcomeId: 'po-risk', signalIds: ['signal-owner'], status: 'ACKNOWLEDGED', severity: 'LOW', driftType: 'OWNERSHIP_DRIFT', estimatedMonthlyLeakage: 500, estimatedAnnualLeakage: 6000, reason: 'Application owner was removed after cleanup.', recommendedAction: 'Request owner review.', createdAt: iso(8), updatedAt: iso(8) },
  { id: 'df-policy', tenantId: 'demo', protectedOutcomeId: 'po-remediation', signalIds: ['signal-policy'], status: 'REMEDIATION_CREATED', severity: 'MEDIUM', driftType: 'POLICY_DRIFT', estimatedMonthlyLeakage: 3000, estimatedAnnualLeakage: 36000, reason: 'Model route reverted to a higher-cost provider.', recommendedAction: 'Reapply execution and verify route policy.', createdAt: iso(8), updatedAt: iso(8) },
]
export const demoRemediations: DriftRemediationAction[] = [
  { id: 'rem-value', protectedOutcomeId: 'po-drifted', driftFindingId: 'df-value', governedActionId: 'ga-drift-cloud', status: 'OPEN', actionType: 'CREATE_NEW_GOVERNED_ACTION', description: 'Reopen Cloud Rightsizing drift remediation', createdAt: iso(8), updatedAt: iso(8) },
  { id: 'rem-policy', protectedOutcomeId: 'po-remediation', driftFindingId: 'df-policy', governedActionId: 'ga-ai-policy', status: 'IN_PROGRESS', actionType: 'REAPPLY_EXECUTION', description: 'Reapply model routing policy', createdAt: iso(8), updatedAt: iso(8) },
]
export function summarizeOutcomeProtection(outcomes: ProtectedOutcome[]): OutcomeProtectionDashboard { const open = demoDriftFindings.filter((f) => ['OPEN', 'ACKNOWLEDGED', 'REMEDIATION_CREATED'].includes(f.status)); const retained = outcomes.filter((o) => ['PROTECTED', 'RESOLVED'].includes(o.status)).length; return { protectedOutcomes: outcomes.length, retainedOutcomes: retained, atRiskOutcomes: outcomes.filter((o) => o.status === 'AT_RISK').length, driftedOutcomes: outcomes.filter((o) => o.status === 'DRIFTED').length, remediationOpen: outcomes.filter((o) => o.status === 'REMEDIATION_OPEN').length, protectedMonthlyValue: outcomes.reduce((s, o) => s + (o.protectedMonthlyValue ?? 0), 0), protectedAnnualValue: outcomes.reduce((s, o) => s + (o.protectedAnnualValue ?? 0), 0), retainedMonthlyValue: outcomes.reduce((s, o) => s + (o.retainedMonthlyValue ?? 0), 0), retainedAnnualValue: outcomes.reduce((s, o) => s + (o.retainedAnnualValue ?? 0), 0), driftedMonthlyValue: outcomes.reduce((s, o) => s + (o.driftedMonthlyValue ?? 0), 0), driftedAnnualValue: outcomes.reduce((s, o) => s + (o.driftedAnnualValue ?? 0), 0), retentionRate: outcomes.length ? Math.round((outcomes.reduce((s, o) => s + (o.retainedAnnualValue ?? 0), 0) / Math.max(outcomes.reduce((s, o) => s + (o.protectedAnnualValue ?? 0), 0), 1)) * 100) : null, openDriftFindings: open, upcomingChecks: outcomes.filter((o) => o.nextCheckAt).slice(0, 5) } }
export const demoOutcomeProtectionData: OutcomeProtectionData = { dashboard: summarizeOutcomeProtection(demoProtectedOutcomes), outcomes: demoProtectedOutcomes, isDemo: true, dataState: 'DEMO' }
const notConnectedOutcomeProtectionData: OutcomeProtectionData = { dashboard: emptyDashboard, outcomes: [], isDemo: true, dataState: 'NOT_CONNECTED' }
export const emptyOutcomeProtectionData: OutcomeProtectionData = { dashboard: emptyDashboard, outcomes: [], isDemo: false, dataState: 'NO_DATA' }
export function buildDemoOutcomeDetail(outcomeId: string): ProtectedOutcomeDetail { const outcome = demoProtectedOutcomes.find((o) => o.id === outcomeId) ?? demoProtectedOutcomes[0]; return { outcome, policies: outcome.policyIds.map((id) => ({ id, name: id.replace('policy-', 'Policy '), policyType: id.includes('owner') ? 'OWNER_REMOVED' : id.includes('route') ? 'MODEL_ROUTE_REVERTED' : 'SPEND_REAPPEARED', checkFrequency: 'WEEKLY' as const, enabled: true })), findings: demoDriftFindings.filter((f) => f.protectedOutcomeId === outcome.id), retentionChecks: [{ id: `${outcome.id}-check`, result: outcome.status === 'DRIFTED' ? 'FAILED' : outcome.status === 'AT_RISK' ? 'AT_RISK' : 'PASSED', retainedMonthlyValue: outcome.retainedMonthlyValue, retainedAnnualValue: outcome.retainedAnnualValue, driftedMonthlyValue: outcome.driftedMonthlyValue, driftedAnnualValue: outcome.driftedAnnualValue, evidenceIds: outcome.evidenceIds, checkedAt: outcome.lastCheckedAt ?? outcome.updatedAt }], remediations: demoRemediations.filter((r) => r.protectedOutcomeId === outcome.id), dataState: 'DEMO' } }
function unavailableOutcomeDetail(id: string, knownOutcome: ProtectedOutcome | undefined, dataState: OutcomeProtectionDataState, error?: string): ProtectedOutcomeDetail {
  const outcome: ProtectedOutcome = knownOutcome ?? { id, tenantId: '', outcomeId: id, name: 'Outcome unavailable', status: 'AT_RISK', valueType: 'OTHER', protectionStart: '', policyIds: [], driftFindingIds: [], evidenceIds: [], createdAt: '', updatedAt: '' }
  return { outcome, policies: [], findings: [], retentionChecks: [], remediations: [], dataState, error }
}
function normalizeDashboard(value: Partial<OutcomeProtectionDashboard> | null | undefined): OutcomeProtectionDashboard { return { ...emptyDashboard, ...(value ?? {}) } }
export function normalizeOutcomes(value: unknown): ProtectedOutcome[] { return Array.isArray(value) ? value as ProtectedOutcome[] : [] }

export function useOutcomeProtectionData() { const workspace = useWorkspace(); const [data, setData] = useState<OutcomeProtectionData>(() => workspace.mode === 'demo' ? demoOutcomeProtectionData : notConnectedOutcomeProtectionData); const [loading, setLoading] = useState(false)
  const refresh = useCallback(async () => { if (workspace.mode === 'demo') { setData(demoOutcomeProtectionData); return demoOutcomeProtectionData } if (!workspace.dataReady) { setData(notConnectedOutcomeProtectionData); return notConnectedOutcomeProtectionData } setLoading(true); try { const [dashboard, outcomes] = await Promise.all([liveFetch<OutcomeProtectionDashboard>('/api/outcome-protection/dashboard'), liveFetch<ProtectedOutcome[]>('/api/outcome-protection/outcomes')]); const normalizedOutcomes = normalizeOutcomes(outcomes); const next: OutcomeProtectionData = { dashboard: normalizeDashboard(dashboard), outcomes: normalizedOutcomes, isDemo: false, dataState: normalizedOutcomes.length === 0 ? 'NO_DATA' : 'LIVE' }; setData(next); return next } catch (error) { const err = normalizeApiError(error); const fallback: OutcomeProtectionData = { dashboard: emptyDashboard, outcomes: [], isDemo: false, dataState: 'NO_DATA', error: err.message }; setData(fallback); return fallback } finally { setLoading(false) } }, [workspace.mode, workspace.dataReady])
  const fetchOutcomeDetail = useCallback(async (id: string): Promise<ProtectedOutcomeDetail> => {
    if (data.isDemo || workspace.mode === 'demo') return buildDemoOutcomeDetail(id)
    if (!workspace.dataReady) return unavailableOutcomeDetail(id, data.outcomes.find((o) => o.id === id), 'NOT_CONNECTED')
    try {
      const detail = await liveFetch<Omit<ProtectedOutcomeDetail, 'dataState'>>(`/api/outcome-protection/outcomes/${id}`)
      return { ...detail, dataState: detail?.outcome ? 'LIVE' : 'NO_DATA' }
    } catch (error) {
      return unavailableOutcomeDetail(id, data.outcomes.find((o) => o.id === id), 'NO_DATA', normalizeApiError(error).message)
    }
  }, [data.isDemo, data.outcomes, workspace.mode, workspace.dataReady])
  useEffect(() => { void refresh() }, [refresh])
  return useMemo(() => ({ ...data, loading, refresh, fetchOutcomeDetail }), [data, loading, refresh, fetchOutcomeDetail]) }
