import { useMemo } from 'react'
import { useWorkspace } from '../lib/workspaceContext'
import { useLiveResource } from './useLiveResource'

export type OwnershipFinding = { id:string; vendorName:string; applicationName:string; ownershipStatus:string; gapType:string; riskLevel:string; recommendation:string; businessOwner?:string; technicalOwner?:string; budgetOwner?:string; renewalOwner?:string; executiveSponsor?:string; costCentre?:string; annualCost?:number; renewalDate?:string; activeUsers?:number; sourceContext:string[]; trustScore:number; rationale:string; recommendedAction:string; evidenceRefs:string[] }
export type OwnershipData = { summary:{ applicationsReviewed:number; ownerlessApplications:number; partiallyOwnedApplications:number; conflictedOwners:number; staleOwners:number; annualSpendWithoutOwner:number; renewalsWithoutOwner:number; aiApplicationsWithoutOwner:number; highRiskOwnershipFindings:number; recommendedActions:string[]; evidenceRefs:string[] }; findings:OwnershipFinding[]; opportunity:OwnershipData['summary']; ownershipStatusBreakdown:Record<string,number>; accountabilityRiskScore:number; evidenceRefs:string[] }
const addDays = (days:number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10)
const finding = (id:string, vendorName:string, app:string, status:string, gap:string, risk:string, recommendation:string, annualCost:number|undefined, renewalDate:string|undefined, sourceContext:string[], action:string, extra:Partial<OwnershipFinding>={}): OwnershipFinding => ({ id, vendorName, applicationName: app, ownershipStatus: status, gapType: gap, riskLevel: risk, recommendation, annualCost, renewalDate, sourceContext, trustScore: 80, rationale: `${app} requires accountability review for ${gap.toLowerCase().replace(/_/g, ' ')}.`, recommendedAction: action, evidenceRefs: [`ownership:${id}`, `application:${id}`], ...extra })
const demoFindings: OwnershipFinding[] = [
  finding('slack-renewal', 'Slack', 'Slack', 'PARTIALLY_OWNED', 'NO_RENEWAL_OWNER', 'CRITICAL', 'ASSIGN_RENEWAL_OWNER', 180000, addDays(45), ['RENEWALS', 'SAAS_RATIONALISATION'], 'Assign renewal owner.', { businessOwner:'engineering@example.com', technicalOwner:'collaboration-admin@example.com', budgetOwner:'engineering-finance@example.com' }),
  finding('zoom-budget', 'Zoom', 'Zoom', 'PARTIALLY_OWNED', 'NO_BUDGET_OWNER', 'HIGH', 'ASSIGN_BUDGET_OWNER', 95000, undefined, ['SAAS_RATIONALISATION'], 'Assign budget owner.', { businessOwner:'it@example.com', technicalOwner:'uc-admin@example.com' }),
  finding('tableau-exec', 'Tableau', 'Tableau', 'PARTIALLY_OWNED', 'NO_EXECUTIVE_SPONSOR', 'HIGH', 'ESCALATE_TO_EXECUTIVE', 140000, addDays(87), ['RENEWALS'], 'Escalate high-spend ownerless app.', { businessOwner:'data@example.com', technicalOwner:'bi-admin@example.com', budgetOwner:'data-finance@example.com', renewalOwner:'data@example.com' }),
  finding('dropbox-business', 'Dropbox', 'Dropbox', 'OWNERLESS', 'NO_BUSINESS_OWNER', 'HIGH', 'ASSIGN_OWNER', 52000, undefined, ['SHADOW_IT', 'SAAS_RATIONALISATION'], 'Assign business owner.'),
  finding('dropbox-technical', 'Dropbox', 'Dropbox', 'OWNERLESS', 'NO_TECHNICAL_OWNER', 'HIGH', 'ASSIGN_OWNER', 52000, undefined, ['SHADOW_IT', 'SAAS_RATIONALISATION'], 'Assign technical owner.'),
  finding('chatgpt-business', 'OpenAI', 'ChatGPT', 'PARTIALLY_OWNED', 'NO_BUSINESS_OWNER', 'HIGH', 'ASSIGN_OWNER', 36000, undefined, ['AI_GOVERNANCE'], 'Assign business owner.', { technicalOwner:'platform@example.com' }),
  finding('chatgpt-budget', 'OpenAI', 'ChatGPT', 'PARTIALLY_OWNED', 'NO_BUDGET_OWNER', 'HIGH', 'ASSIGN_BUDGET_OWNER', 36000, undefined, ['AI_GOVERNANCE'], 'Assign budget owner.', { technicalOwner:'platform@example.com' }),
  finding('claude-ownerless', 'Anthropic', 'Claude', 'OWNERLESS', 'NO_BUSINESS_OWNER', 'HIGH', 'ASSIGN_OWNER', 24000, undefined, ['AI_GOVERNANCE'], 'Assign business owner.'),
  finding('box-technical', 'Box', 'Box', 'PARTIALLY_OWNED', 'NO_TECHNICAL_OWNER', 'MEDIUM', 'ASSIGN_OWNER', 60000, undefined, ['RENEWALS', 'SAAS_RATIONALISATION'], 'Assign technical owner.', { businessOwner:'legal@example.com', budgetOwner:'legal-finance@example.com' }),
  finding('miro-stale', 'Miro', 'Miro', 'STALE', 'OWNER_STALE', 'MEDIUM', 'CONFIRM_OWNER', 38000, undefined, ['SAAS_RATIONALISATION'], 'Confirm stale owner.', { businessOwner:'product@example.com', technicalOwner:'workspace-admin@example.com', budgetOwner:'product-finance@example.com' }),
  finding('hubspot-conflict', 'HubSpot', 'HubSpot', 'CONFLICTED', 'OWNER_CONFLICT', 'HIGH', 'RESOLVE_CONFLICT', 120000, undefined, ['SAAS_RATIONALISATION', 'RENEWALS'], 'Resolve owner conflict.', { businessOwner:'marketing@example.com', technicalOwner:'marketing-ops@example.com', budgetOwner:'marketing-finance@example.com' }),
]
const fullyOwnedVendor = 'Salesforce'
const actions = ['Assign business owner', 'Assign technical owner', 'Assign budget owner', 'Assign renewal owner', 'Confirm stale owner', 'Resolve owner conflict', 'Escalate high-spend ownerless app']
export const demoOwnershipIntelligenceData: OwnershipData = { summary: { applicationsReviewed:10, ownerlessApplications:2, partiallyOwnedApplications:6, conflictedOwners:1, staleOwners:1, annualSpendWithoutOwner:709000, renewalsWithoutOwner:2, aiApplicationsWithoutOwner:2, highRiskOwnershipFindings:9, recommendedActions:actions, evidenceRefs:Array.from(new Set([...demoFindings.flatMap((f)=>f.evidenceRefs), 'owner:Salesforce'])) }, findings: demoFindings, opportunity: { applicationsReviewed:10, ownerlessApplications:2, partiallyOwnedApplications:6, conflictedOwners:1, staleOwners:1, annualSpendWithoutOwner:709000, renewalsWithoutOwner:2, aiApplicationsWithoutOwner:2, highRiskOwnershipFindings:9, recommendedActions:actions, evidenceRefs:Array.from(new Set([...demoFindings.flatMap((f)=>f.evidenceRefs), 'owner:Salesforce'])) }, ownershipStatusBreakdown:{ OWNED:1, PARTIALLY_OWNED:6, OWNERLESS:2, STALE:1, CONFLICTED:1 }, accountabilityRiskScore:92, evidenceRefs:Array.from(new Set([...demoFindings.flatMap((f)=>f.evidenceRefs), 'owner:Salesforce'])) }
export function normalizeOwnershipIntelligencePayload(payload:any): OwnershipData { const summary = payload?.summary ?? demoOwnershipIntelligenceData.summary; const findings = Array.isArray(payload?.findings) ? payload.findings : []; return { summary:{...demoOwnershipIntelligenceData.summary, ...summary}, findings, opportunity: payload?.opportunity ?? {...demoOwnershipIntelligenceData.opportunity, evidenceRefs:[]}, ownershipStatusBreakdown: payload?.ownershipStatusBreakdown ?? {}, accountabilityRiskScore: Number(payload?.accountabilityRiskScore ?? 0), evidenceRefs: Array.isArray(payload?.evidenceRefs) ? payload.evidenceRefs : [] } }
export function useOwnershipIntelligenceData() { const workspace = useWorkspace(); const live = useLiveResource<OwnershipData>({ path:'/api/playbooks/ownership/exposure', enabled: workspace.mode === 'live', requireDataReady: false, initialData: demoOwnershipIntelligenceData, normalizer: normalizeOwnershipIntelligencePayload, isEmpty: (data) => data.findings.length === 0 }); return useMemo(() => { if (workspace.mode === 'demo') return { data: demoOwnershipIntelligenceData, loading:false, error:null, isEmptyLive:false, refresh: () => Promise.resolve(demoOwnershipIntelligenceData) }; return { data: live.data.findings.length ? live.data : demoOwnershipIntelligenceData, loading: live.loading, error: live.error, isEmptyLive: live.isEmpty, refresh: live.refresh } }, [workspace.mode, live.data, live.loading, live.error, live.isEmpty, live.refresh]) }
