import { useEffect, useMemo, useState } from 'react'
import { liveFetch } from '../lib/liveApi'
import { getOwnershipEvidencePackCompleteness, inferOwnershipDecision, type OwnershipDecision, type OwnershipEvidenceStatus } from '../lib/program3OwnershipAccountability'
import { useWorkspace } from '../lib/workspaceContext'

export type OwnerType = 'RESPONSIBLE_OWNER' | 'BUSINESS_OWNER' | 'TECHNICAL_OWNER' | 'EXECUTIVE_SPONSOR' | 'RENEWAL_OWNER'
export type OwnershipScenario = 'FULLY_OWNED' | 'MISSING_OWNER' | 'OWNER_CONFLICT' | 'EXECUTIVE_SPONSOR_ASSIGNED' | 'BUSINESS_OWNER_MISSING' | 'TECHNICAL_OWNER_MISSING' | 'RENEWAL_OWNER_MISSING' | 'OWNER_DEPARTED' | 'TEMPORARY_DELEGATION' | 'SHARED_REVIEW'
export type OwnershipFinding = { id:string; assetIdentifier:string; assetName:string; vendorName:string; contractId?:string; renewalDate?:string; spend?:number; businessOutcome?:string; responsibleOwner?:string; businessOwner?:string; technicalOwner?:string; executiveSponsor?:string; renewalOwner?:string; delegatedOwner?:string; ownerType?:OwnerType; ownerStatus:'VERIFIED'|'MISSING'|'CONFLICTED'|'DEPARTED'|'DELEGATED'|'PARTIAL'; businessUnit?:string; costCentre?:string; assignmentBasis?:string; decisionAuthority?:string; sourceSystem?:string; lineage?:string; timestamp?:string; confidence?:number; verificationStatus:'VERIFIED'|'PENDING'|'MISSING_EVIDENCE'; evidenceStatus:OwnershipEvidenceStatus; riskLevel:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL'; scenario:OwnershipScenario; ownerConflict?:boolean; outcomeProtectionLinkage?:string; decision:OwnershipDecision; decisionReason:string; evidenceRefs:string[] }
export type OwnershipData = { mode:'DEMO'|'LIVE'; summary:{ governedAssets:number; assetsMissingOwner:number; verifiedOwnership:number; renewalOwnerGaps:number; executiveSponsorshipCoverage?:number; ownershipConflicts:number; highRiskOrphanedAssets:number; evidenceCompleteness?:number; accountabilityRiskScore?:number; ownerlessApplications?:number; applicationsReviewed?:number; highRiskOwnershipFindings?:number }; findings:OwnershipFinding[]; evidenceRefs:string[] }

export const emptyOwnershipData: OwnershipData = { mode:'LIVE', summary:{ governedAssets:0, applicationsReviewed:0, assetsMissingOwner:0, ownerlessApplications:0, verifiedOwnership:0, renewalOwnerGaps:0, executiveSponsorshipCoverage:undefined, ownershipConflicts:0, highRiskOrphanedAssets:0, highRiskOwnershipFindings:0, evidenceCompleteness:undefined, accountabilityRiskScore:undefined }, findings:[], evidenceRefs:[] }

const base = { timestamp:'2026-07-05T00:00:00.000Z', sourceSystem:'DEMO_OWNERSHIP_AUTHORITY', lineage:'demo/ownership-accountability/2026-07-05' }
function finding(input: Omit<OwnershipFinding,'decision'|'decisionReason'|'evidenceStatus'> & { evidenceStatus?: OwnershipEvidenceStatus }): OwnershipFinding {
  const evidenceStatus = input.evidenceStatus ?? getOwnershipEvidencePackCompleteness({ assetIdentifier: input.assetIdentifier, ownerIdentity: input.responsibleOwner ?? input.businessOwner ?? input.technicalOwner ?? input.renewalOwner, ownerType: input.ownerType ?? 'RESPONSIBLE_OWNER', businessUnit: input.businessUnit, costCentre: input.costCentre, assignmentBasis: input.assignmentBasis, executiveSponsor: input.executiveSponsor, renewalResponsibility: input.renewalOwner, decisionAuthority: input.decisionAuthority, verificationStatus: input.verificationStatus, confidence: input.confidence, sourceSystem: input.sourceSystem, timestamp: input.timestamp, lineage: input.lineage, outcomeProtectionLinkage: input.outcomeProtectionLinkage, executiveSponsorApplicable: true, renewalApplicable: Boolean(input.renewalDate), outcomeApplicable: Boolean(input.outcomeProtectionLinkage) }).status
  const decision = inferOwnershipDecision({ ownerIdentity: input.responsibleOwner ?? input.businessOwner ?? input.technicalOwner ?? input.renewalOwner, ownerStatus: input.ownerStatus, ownerConflict: input.ownerConflict, executiveSponsor: input.executiveSponsor, evidenceStatus, verificationStatus: input.verificationStatus })
  return { ...input, evidenceStatus, decision: decision.decision, decisionReason: decision.reason }
}

export function demoOwnershipIntelligenceData(): OwnershipData {
  const findings: OwnershipFinding[] = [
    finding({ id:'own-m365', assetIdentifier:'asset-m365-e5', assetName:'Microsoft 365 E5', vendorName:'Microsoft', contractId:'ctr-m365-2026', renewalDate:'2026-08-18', spend:850000, businessOutcome:'Productivity and collaboration continuity', responsibleOwner:'Jane Owner', businessOwner:'Corporate IT', technicalOwner:'M365 Platform Lead', executiveSponsor:'CIO', renewalOwner:'IT Commercial Lead', ownerType:'RESPONSIBLE_OWNER', ownerStatus:'VERIFIED', businessUnit:'Corporate IT', costCentre:'IT-100', assignmentBasis:'HR manager record and contract owner match', decisionAuthority:'CIO delegated renewal authority', confidence:94, verificationStatus:'VERIFIED', riskLevel:'LOW', scenario:'FULLY_OWNED', outcomeProtectionLinkage:'outcome:m365:licence-optimisation', evidenceRefs:['identity:jane-owner','contract:ctr-m365-2026','finance:it-100'], ...base }),
    finding({ id:'own-legacy-crm', assetIdentifier:'asset-legacy-crm', assetName:'Legacy CRM', vendorName:'LegacyCo', contractId:'ctr-legacy-crm', renewalDate:'2026-09-05', spend:400000, businessOutcome:'Revenue operations workflow', ownerStatus:'MISSING', businessUnit:'Revenue Operations', costCentre:'REV-220', assignmentBasis:'No active owner in HR or contract records', decisionAuthority:'Revenue Operations VP required', confidence:41, verificationStatus:'PENDING', riskLevel:'HIGH', scenario:'MISSING_OWNER', evidenceRefs:['contract:legacy-crm','hr:owner-missing'], ...base }),
    finding({ id:'own-ai-notes', assetIdentifier:'asset-shadow-ai', assetName:'Unapproved AI Notes App', vendorName:'Unknown AI Vendor', spend:72000, businessOutcome:'Unapproved meeting summarisation', ownerStatus:'MISSING', assignmentBasis:'Detected spend and OAuth use without approved owner', decisionAuthority:'AI Governance Council', confidence:22, verificationStatus:'MISSING_EVIDENCE', riskLevel:'CRITICAL', scenario:'BUSINESS_OWNER_MISSING', evidenceRefs:['oauth:shadow-ai','finance:unknown-ai'], ...base }),
    finding({ id:'own-slack-teams', assetIdentifier:'capability-collaboration', assetName:'Slack / Teams collaboration capability', vendorName:'Salesforce + Microsoft', contractId:'cap-collaboration', renewalDate:'2026-11-12', spend:390000, businessOutcome:'Enterprise collaboration', responsibleOwner:'Collab Owner A', businessOwner:'Operations', technicalOwner:'Collab Owner B', executiveSponsor:'COO', renewalOwner:'SaaS Commercial Lead', ownerType:'RESPONSIBLE_OWNER', ownerStatus:'CONFLICTED', businessUnit:'Operations', costCentre:'OPS-210', assignmentBasis:'Two owners claim decision authority for overlapping tools', decisionAuthority:'COO arbitration required', confidence:68, verificationStatus:'PENDING', riskLevel:'MEDIUM', scenario:'OWNER_CONFLICT', ownerConflict:true, evidenceRefs:['owner:collab-a','owner:collab-b','overlap:slack-teams'], ...base }),
    finding({ id:'own-tableau', assetIdentifier:'asset-tableau', assetName:'Tableau Creator', vendorName:'Salesforce', contractId:'ctr-tableau', renewalDate:'2026-10-02', spend:145000, businessOutcome:'Finance analytics', responsibleOwner:'Analytics Lead', businessOwner:'Finance', executiveSponsor:'CFO', ownerType:'RENEWAL_OWNER', ownerStatus:'PARTIAL', businessUnit:'Finance', costCentre:'FIN-300', assignmentBasis:'Usage owner exists but renewal owner absent', decisionAuthority:'CFO renewal review', confidence:73, verificationStatus:'PENDING', riskLevel:'MEDIUM', scenario:'RENEWAL_OWNER_MISSING', evidenceRefs:['usage:tableau','contract:tableau'], ...base }),
    finding({ id:'own-snowflake', assetIdentifier:'asset-snowflake', assetName:'Snowflake Enterprise', vendorName:'Snowflake', contractId:'ctr-snowflake', renewalDate:'2027-01-15', spend:520000, businessOutcome:'Data platform', responsibleOwner:'Departed Data Owner', businessOwner:'Data Office', technicalOwner:'Data Platform Lead', executiveSponsor:'CDO', renewalOwner:'Data Commercial Lead', ownerType:'RESPONSIBLE_OWNER', ownerStatus:'DEPARTED', businessUnit:'Data', costCentre:'DATA-400', assignmentBasis:'Owner identity inactive in HR', decisionAuthority:'CDO reassignment required', confidence:81, verificationStatus:'VERIFIED', riskLevel:'HIGH', scenario:'OWNER_DEPARTED', evidenceRefs:['hr:departed-owner','contract:snowflake'], ...base }),
    finding({ id:'own-servicenow', assetIdentifier:'asset-servicenow', assetName:'ServiceNow ITSM', vendorName:'ServiceNow', contractId:'ctr-servicenow', renewalDate:'2026-12-20', spend:310000, businessOutcome:'IT service management', responsibleOwner:'Interim ITSM Owner', businessOwner:'IT Operations', technicalOwner:'Platform Engineering', executiveSponsor:'CIO', renewalOwner:'IT Commercial Lead', delegatedOwner:'Interim ITSM Owner', ownerType:'RESPONSIBLE_OWNER', ownerStatus:'DELEGATED', businessUnit:'IT Operations', costCentre:'IT-240', assignmentBasis:'Temporary delegation expires in 45 days', decisionAuthority:'CIO confirms permanent owner', confidence:76, verificationStatus:'PENDING', riskLevel:'MEDIUM', scenario:'TEMPORARY_DELEGATION', evidenceRefs:['delegation:itsm','contract:servicenow'], ...base }),
  ]
  return { mode:'DEMO', summary:{ governedAssets:findings.length, applicationsReviewed:findings.length, assetsMissingOwner:2, ownerlessApplications:2, verifiedOwnership:1, renewalOwnerGaps:1, executiveSponsorshipCoverage:57, ownershipConflicts:1, highRiskOrphanedAssets:2, highRiskOwnershipFindings:5, evidenceCompleteness:43, accountabilityRiskScore:84 }, findings, evidenceRefs:Array.from(new Set(findings.flatMap((item)=>item.evidenceRefs))) }
}

export function summarizeOwnershipKpis(data: OwnershipData) { return data.summary }
export function buildOwnershipEvidencePack(f: OwnershipFinding) { return getOwnershipEvidencePackCompleteness({ assetIdentifier:f.assetIdentifier, ownerIdentity:f.responsibleOwner ?? f.businessOwner ?? f.technicalOwner ?? f.renewalOwner, ownerType:f.ownerType ?? 'RESPONSIBLE_OWNER', businessUnit:f.businessUnit, costCentre:f.costCentre, assignmentBasis:f.assignmentBasis, executiveSponsor:f.executiveSponsor, renewalResponsibility:f.renewalOwner, decisionAuthority:f.decisionAuthority, verificationStatus:f.verificationStatus, confidence:f.confidence, sourceSystem:f.sourceSystem, timestamp:f.timestamp, lineage:f.lineage, outcomeProtectionLinkage:f.outcomeProtectionLinkage, executiveSponsorApplicable:true, renewalApplicable:Boolean(f.renewalDate), outcomeApplicable:Boolean(f.outcomeProtectionLinkage) }) }
export function normalizeOwnershipIntelligencePayload(payload:any): OwnershipData { if (!payload || !Array.isArray(payload.findings)) return emptyOwnershipData; return { ...emptyOwnershipData, ...payload, mode:'LIVE', summary:{...emptyOwnershipData.summary, ...(payload.summary ?? {})}, findings:payload.findings, evidenceRefs:Array.isArray(payload.evidenceRefs)?payload.evidenceRefs:[] } }

export function useOwnershipIntelligenceData() { const workspace=useWorkspace(); const [data,setData]=useState<OwnershipData>(()=>workspace.mode==='demo'?demoOwnershipIntelligenceData():emptyOwnershipData); const [loading,setLoading]=useState(workspace.mode==='live'&&workspace.dataReady); const [error,setError]=useState<Error|null>(null); useEffect(()=>{let cancel=false;if(workspace.mode==='demo'){setData(demoOwnershipIntelligenceData());setLoading(false);setError(null);return undefined} if(!workspace.dataReady){setData(emptyOwnershipData);setLoading(false);setError(null);return undefined} setLoading(true); liveFetch<OwnershipData>('/api/playbooks/ownership/exposure').then((payload)=>{if(!cancel)setData(normalizeOwnershipIntelligencePayload(payload))}).catch((err)=>{if(!cancel){setData(emptyOwnershipData);setError(err instanceof Error?err:new Error(String(err)))}}).finally(()=>{if(!cancel)setLoading(false)});return()=>{cancel=true}},[workspace.mode,workspace.dataReady]); return useMemo(()=>({data,loading,error,isEmptyLive:workspace.mode==='live'&&data.findings.length===0,isDemo:workspace.mode==='demo',isLiveUnconnected:workspace.mode==='live'&&!workspace.dataReady,refresh:()=>Promise.resolve(data)}),[data,loading,error,workspace.mode,workspace.dataReady]) }
