import { useMemo } from 'react'
import { useWorkspace } from '../lib/workspaceContext'
import { useLiveResource } from './useLiveResource'

export type RenewalFinding = { id:string; vendorName:string; applicationName:string; findingType:string; riskLevel:string; recommendation:string; renewalDate?:string; daysToRenewal?:number; annualCost?:number; assignedUsers?:number; activeUsers?:number; utilisationRate?:number; owner?:string; duplicateWith?:string[]; potentialAnnualSavings?:number; trustScore:number; rationale:string; recommendedAction:string; evidenceRefs:string[] }
export type RenewalCalendarWindow = { label:'0–30 days'|'31–60 days'|'61–90 days'|'91–120 days'|'121–180 days'; findings:RenewalFinding[] }
export type RenewalContractData = { summary:{ upcomingRenewals:number; annualSpendReviewed:number; potentialAnnualSavings:number; highRiskRenewals:number; contractsMissingOwner:number; negotiationOpportunities:number }; findings:RenewalFinding[]; opportunity:{ totalPotentialAnnualSavings:number; savingsConfidence:string; findingsWithSavings:RenewalFinding[]; governanceOnlyFindings:RenewalFinding[]; upcomingRenewals:RenewalFinding[]; topRenewalActions:string[]; evidenceRefs:string[] }; upcomingRenewals:RenewalFinding[]; renewalCalendar:RenewalCalendarWindow[]; riskBreakdown:Record<string,number>; evidenceRefs:string[] }

const addDays = (days:number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10)
const finding = (id:string, vendorName:string, app:string, findingType:string, riskLevel:string, recommendation:string, days:number|undefined, annualCost:number|undefined, utilisationRate:number|undefined, owner:string|undefined, duplicateWith:string[]|undefined, savings:number|undefined, action:string): RenewalFinding => ({ id, vendorName, applicationName: app, findingType, riskLevel, recommendation, renewalDate: days === undefined ? undefined : addDays(days), daysToRenewal: days, annualCost, assignedUsers: 100, activeUsers: utilisationRate === undefined ? undefined : Math.round(100 * utilisationRate), utilisationRate, owner, duplicateWith, potentialAnnualSavings: savings, trustScore: owner ? 100 : 85, rationale: `${vendorName} requires renewal review for ${findingType.toLowerCase().replace(/_/g, ' ')}.`, recommendedAction: action, evidenceRefs: [`contract:${id}`, `usage:${id}`, `renewal:${id}`] })

const demoFindings: RenewalFinding[] = [
  finding('slack', 'Slack', 'Slack', 'HIGH_COST_LOW_USAGE_RENEWAL', 'HIGH', 'REDUCE', 45, 180000, 0.41, 'engineering@example.com', ['Microsoft Teams'], 45000, 'Reduce seats before renewal.'),
  finding('slack-duplicate', 'Slack', 'Slack', 'DUPLICATE_VENDOR_RENEWAL', 'HIGH', 'CONSOLIDATE', 45, 180000, 0.41, 'engineering@example.com', ['Microsoft Teams'], 54000, 'Consolidate duplicate vendors.'),
  finding('zoom', 'Zoom', 'Zoom', 'NEGOTIATION_OPPORTUNITY', 'MEDIUM', 'RENEGOTIATE', 60, 95000, 0.48, 'it@example.com', ['Microsoft Teams'], 14250, 'Renegotiate before renewal.'),
  finding('tableau', 'Tableau', 'Tableau', 'HIGH_COST_LOW_USAGE_RENEWAL', 'HIGH', 'REDUCE', 87, 140000, 0.29, 'data@example.com', ['Power BI'], 35000, 'Reduce seats before renewal.'),
  finding('dropbox', 'Dropbox', 'Dropbox', 'CONSOLIDATION_BEFORE_RENEWAL', 'HIGH', 'CONSOLIDATE', 110, 52000, 0.18, 'finance-ops@example.com', ['OneDrive'], 20800, 'Consolidate before renewal.'),
  finding('figma', 'Figma', 'Figma', 'DUPLICATE_VENDOR_RENEWAL', 'HIGH', 'CONSOLIDATE', 135, 72000, 0.66, 'design@example.com', ['Canva'], 21600, 'Review duplicate vendor renewal.'),
  finding('hubspot', 'HubSpot', 'HubSpot', 'NEGOTIATION_OPPORTUNITY', 'MEDIUM', 'RENEGOTIATE', 75, 120000, 0.54, 'revenue@example.com', ['Salesforce'], 18000, 'Renegotiate before renewal.'),
  finding('miro', 'Miro', 'Miro', 'CONSOLIDATION_BEFORE_RENEWAL', 'HIGH', 'CONSOLIDATE', 160, 38000, 0.22, 'product@example.com', ['Lucid'], 15200, 'Consolidate duplicate vendors.'),
  finding('claude-owner', 'Anthropic', 'Claude', 'OWNER_GAP', 'HIGH', 'INVESTIGATE', undefined, 24000, 0.7, undefined, undefined, undefined, 'Assign contract owner.'),
  finding('box-usage', 'Box', 'Box', 'MISSING_USAGE_DATA', 'MEDIUM', 'INVESTIGATE', 95, 60000, undefined, 'legal@example.com', undefined, undefined, 'Validate missing usage data before renewal.'),
]

const windows: RenewalCalendarWindow[] = ['0–30 days', '31–60 days', '61–90 days', '91–120 days', '121–180 days'].map((label) => ({ label: label as RenewalCalendarWindow['label'], findings: demoFindings.filter((finding) => { const d = finding.daysToRenewal; if (typeof d !== 'number') return false; if (label === '0–30 days') return d <= 30; if (label === '31–60 days') return d >= 31 && d <= 60; if (label === '61–90 days') return d >= 61 && d <= 90; if (label === '91–120 days') return d >= 91 && d <= 120; return d >= 121 && d <= 180 }) }))
export const demoRenewalContractData: RenewalContractData = { summary: { upcomingRenewals: 7, annualSpendReviewed: 781000, potentialAnnualSavings: 208850, highRiskRenewals: 7, contractsMissingOwner: 1, negotiationOpportunities: 2 }, findings: demoFindings, opportunity: { totalPotentialAnnualSavings: 208850, savingsConfidence: 'HIGH', findingsWithSavings: demoFindings.filter((finding) => Number(finding.potentialAnnualSavings) > 0), governanceOnlyFindings: demoFindings.filter((finding) => !finding.potentialAnnualSavings), upcomingRenewals: demoFindings.filter((finding) => typeof finding.daysToRenewal === 'number' && finding.daysToRenewal <= 120), topRenewalActions: ['Renegotiate before renewal', 'Reduce seats before renewal', 'Consolidate duplicate vendors', 'Retire low-use tools', 'Assign contract owner', 'Validate missing usage/cost data', 'Prepare executive renewal review'], evidenceRefs: Array.from(new Set(demoFindings.flatMap((finding) => finding.evidenceRefs))) }, upcomingRenewals: demoFindings.filter((finding) => typeof finding.daysToRenewal === 'number' && finding.daysToRenewal <= 120), renewalCalendar: windows, riskBreakdown: { LOW: 0, MEDIUM: 3, HIGH: 7, CRITICAL: 0 }, evidenceRefs: Array.from(new Set(demoFindings.flatMap((finding) => finding.evidenceRefs))) }

const emptyRenewalContractData: RenewalContractData = { summary: { upcomingRenewals: 0, annualSpendReviewed: 0, potentialAnnualSavings: 0, highRiskRenewals: 0, contractsMissingOwner: 0, negotiationOpportunities: 0 }, findings: [], opportunity: { totalPotentialAnnualSavings: 0, savingsConfidence: 'UNKNOWN', findingsWithSavings: [], governanceOnlyFindings: [], upcomingRenewals: [], topRenewalActions: [], evidenceRefs: [] }, upcomingRenewals: [], renewalCalendar: [], riskBreakdown: {}, evidenceRefs: [] }
export function normalizeRenewalContractPayload(payload:any): RenewalContractData { const summary = payload?.summary ?? emptyRenewalContractData.summary; const findings = Array.isArray(payload?.findings) ? payload.findings : []; const opportunity = payload?.opportunity ?? { ...emptyRenewalContractData.opportunity, findingsWithSavings: findings.filter((finding: RenewalFinding) => Number(finding.potentialAnnualSavings) > 0), governanceOnlyFindings: findings.filter((finding: RenewalFinding) => !finding.potentialAnnualSavings) }; return { summary: { ...emptyRenewalContractData.summary, ...summary }, findings, opportunity, upcomingRenewals: Array.isArray(payload?.upcomingRenewals) ? payload.upcomingRenewals : [], renewalCalendar: Array.isArray(payload?.renewalCalendar) ? payload.renewalCalendar : [], riskBreakdown: payload?.riskBreakdown ?? {}, evidenceRefs: Array.isArray(payload?.evidenceRefs) ? payload.evidenceRefs : [] } }

export function useRenewalContractData() { const workspace = useWorkspace(); const live = useLiveResource<RenewalContractData>({ path: '/api/playbooks/renewals/exposure', enabled: workspace.mode === 'live' && workspace.dataReady, requireDataReady: true, initialData: emptyRenewalContractData, normalizer: normalizeRenewalContractPayload, isEmpty: (data) => data.findings.length === 0 }); return useMemo(() => { if (workspace.mode === 'demo') return { data: demoRenewalContractData, loading: false, error: null, isEmptyLive: false, refresh: () => Promise.resolve(demoRenewalContractData) }; if (!workspace.dataReady) return { data: emptyRenewalContractData, loading: false, error: null, isEmptyLive: true, refresh: () => Promise.resolve(emptyRenewalContractData) }; return { data: live.data, loading: live.loading, error: live.error, isEmptyLive: live.isEmpty, refresh: live.refresh } }, [workspace.mode, workspace.dataReady, live.data, live.loading, live.error, live.isEmpty, live.refresh]) }
