import { useMemo } from 'react'
import { useWorkspace } from '../lib/workspaceContext'
import { useLiveResource } from './useLiveResource'

type Category = 'COLLABORATION' | 'COMMUNICATION' | 'PROJECT_MANAGEMENT' | 'DESIGN' | 'DOCUMENT_STORAGE' | 'AI_PRODUCTIVITY' | 'CRM' | 'ANALYTICS' | 'OTHER'
export type SaaSRationalisationFinding = { id:string; vendorName:string; applicationName:string; findingType:string; riskLevel:string; capabilityCategory:Category; overlapGroup?:string; usersAssigned?:number; activeUsers?:number; utilisationRate?:number; owner?:string; annualCostEstimate?:number; potentialAnnualSavings?:number; trustScore:number; rationale:string; recommendedAction:string; evidenceRefs:string[] }
export type SaaSOverlapGroup = { id:string; capabilityCategory:Category; displayName:string; applications:{ vendorName:string; applicationName:string; approved?:boolean; status:'approved'|'active'|'underused'|'unmanaged'|'dormant'; usersAssigned?:number; activeUsers?:number }[] }
export type SaaSRationalisationData = { summary:{ applicationsReviewed:number; overlapGroups:number; duplicateCapabilityFindings:number; potentialAnnualSavings:number; governanceFindings:number; renewalRisks:number }; findings:SaaSRationalisationFinding[]; opportunity:{ totalPotentialAnnualSavings:number; savingsConfidence:string; findingsWithSavings:SaaSRationalisationFinding[]; governanceOnlyFindings:SaaSRationalisationFinding[]; topRationalisationActions:string[]; evidenceRefs:string[] }; overlapGroups:SaaSOverlapGroup[]; governanceExposureScore:number; evidenceRefs:string[] }

const finding = (id:string, vendorName:string, applicationName:string, findingType:string, riskLevel:string, capabilityCategory:Category, usersAssigned:number, activeUsers:number, annualCostEstimate:number|undefined, potentialAnnualSavings:number|undefined, recommendedAction:string, extra:Partial<SaaSRationalisationFinding>={}): SaaSRationalisationFinding => ({ id, vendorName, applicationName, findingType, riskLevel, capabilityCategory, usersAssigned, activeUsers, utilisationRate: usersAssigned ? Number((activeUsers / usersAssigned).toFixed(2)) : undefined, annualCostEstimate, potentialAnnualSavings, trustScore: 90, rationale: `${applicationName} requires rationalisation review for ${findingType.toLowerCase().replace(/_/g, ' ')}.`, recommendedAction, evidenceRefs: [`enterprise-app:${id}`, `usage:${id}`], ...extra })

const demoFindings: SaaSRationalisationFinding[] = [
  finding('slack-renewal', 'Slack', 'Slack', 'RENEWAL_RISK', 'HIGH', 'COMMUNICATION', 280, 96, 42000, 8400, 'Review renewal-risk vendor before commitment date.', { owner: 'engineering@example.com', overlapGroup: 'Communication' }),
  finding('slack-underused', 'Slack', 'Slack', 'UNDERUSED_VENDOR', 'MEDIUM', 'COMMUNICATION', 280, 96, 42000, 27600, 'Validate whether unused seats can be reclaimed.', { owner: 'engineering@example.com', overlapGroup: 'Communication' }),
  finding('dropbox-dormant', 'Dropbox', 'Dropbox', 'DORMANT_VENDOR', 'MEDIUM', 'DOCUMENT_STORAGE', 62, 4, 18600, 18600, 'Review retirement or renewal removal options.', { owner: 'finance-ops@example.com', overlapGroup: 'Document Storage' }),
  finding('box-owner', 'Box', 'Box', 'OWNER_GAP', 'HIGH', 'DOCUMENT_STORAGE', 40, 2, 14400, undefined, 'Assign business owner before rationalisation decisions.', { overlapGroup: 'Document Storage' }),
  finding('box-unmanaged', 'Box', 'Box', 'UNMANAGED_VENDOR', 'HIGH', 'DOCUMENT_STORAGE', 40, 2, 14400, undefined, 'Review approval status and create an exception or remediation plan.', { overlapGroup: 'Document Storage' }),
  finding('tableau-high-cost', 'Tableau', 'Tableau', 'HIGH_COST_LOW_USAGE', 'HIGH', 'ANALYTICS', 150, 28, 72000, 18000, 'Validate underused high-cost app with business owner.', { owner: 'data@example.com', overlapGroup: 'Analytics' }),
  finding('canva-consolidation', 'Canva', 'Canva', 'CONSOLIDATION_CANDIDATE', 'MEDIUM', 'DESIGN', 44, 7, 6600, 6600, 'Assess whether users can move to the preferred design tool.', { overlapGroup: 'Design' }),
  finding('claude-owner-gap', 'Anthropic', 'Claude', 'OWNER_GAP', 'HIGH', 'AI_PRODUCTIVITY', 18, 15, 5400, undefined, 'Assign business owner and review AI policy coverage.', { overlapGroup: 'AI Productivity', evidenceRefs: ['enterprise-app:claude', 'oauth-app:claude', 'usage:claude'] }),
  finding('teams-duplicate', 'Microsoft', 'Microsoft Teams', 'DUPLICATE_CAPABILITY', 'MEDIUM', 'COMMUNICATION', 1240, 1090, 0, undefined, 'Review consolidation opportunity.', { owner: 'collaboration@example.com', overlapGroup: 'Communication' }),
  finding('copilot-duplicate', 'Microsoft', 'Microsoft Copilot', 'DUPLICATE_CAPABILITY', 'MEDIUM', 'AI_PRODUCTIVITY', 320, 84, 115200, undefined, 'Decide preferred AI productivity tool per policy.', { owner: 'ai-governance@example.com', overlapGroup: 'AI Productivity' }),
]

export const demoSaaSRationalisationData: SaaSRationalisationData = {
  summary: { applicationsReviewed: 20, overlapGroups: 7, duplicateCapabilityFindings: 10, potentialAnnualSavings: 75100, governanceFindings: 4, renewalRisks: 1 },
  findings: demoFindings,
  opportunity: { totalPotentialAnnualSavings: 75100, savingsConfidence: 'HIGH', findingsWithSavings: demoFindings.filter((finding) => finding.potentialAnnualSavings), governanceOnlyFindings: demoFindings.filter((finding) => !finding.potentialAnnualSavings), topRationalisationActions: ['Consolidate duplicate tools', 'Retire dormant vendors', 'Assign missing owners', 'Review renewal-risk vendors', 'Validate underused high-cost apps', 'Decide preferred tool per capability category'], evidenceRefs: Array.from(new Set(demoFindings.flatMap((finding) => finding.evidenceRefs))) },
  overlapGroups: [
    { id:'communication', capabilityCategory:'COMMUNICATION', displayName:'Communication', applications:[{vendorName:'Microsoft',applicationName:'Microsoft Teams',approved:true,status:'approved',usersAssigned:1240,activeUsers:1090},{vendorName:'Slack',applicationName:'Slack',approved:true,status:'underused',usersAssigned:280,activeUsers:96},{vendorName:'Zoom',applicationName:'Zoom',approved:true,status:'underused',usersAssigned:410,activeUsers:148}] },
    { id:'storage', capabilityCategory:'DOCUMENT_STORAGE', displayName:'Storage', applications:[{vendorName:'Microsoft',applicationName:'OneDrive',approved:true,status:'approved',usersAssigned:1240,activeUsers:1180},{vendorName:'Dropbox',applicationName:'Dropbox',approved:false,status:'unmanaged',usersAssigned:62,activeUsers:4},{vendorName:'Box',applicationName:'Box',approved:false,status:'unmanaged',usersAssigned:40,activeUsers:2}] },
    { id:'collaboration', capabilityCategory:'COLLABORATION', displayName:'Collaboration', applications:[{vendorName:'Miro',applicationName:'Miro',approved:true,status:'approved',usersAssigned:80,activeUsers:42},{vendorName:'Lucid',applicationName:'Lucid',approved:true,status:'underused',usersAssigned:36,activeUsers:9}] },
    { id:'project', capabilityCategory:'PROJECT_MANAGEMENT', displayName:'Project Management', applications:[{vendorName:'Asana',applicationName:'Asana',approved:true,status:'underused',usersAssigned:120,activeUsers:38},{vendorName:'Monday',applicationName:'Monday',approved:false,status:'unmanaged',usersAssigned:48,activeUsers:13},{vendorName:'Atlassian',applicationName:'Jira',approved:true,status:'approved',usersAssigned:360,activeUsers:302}] },

    { id:'design', capabilityCategory:'DESIGN', displayName:'Design', applications:[{vendorName:'Figma',applicationName:'Figma',approved:true,status:'approved',usersAssigned:86,activeUsers:70},{vendorName:'Canva',applicationName:'Canva',approved:false,status:'unmanaged',usersAssigned:44,activeUsers:7}] },
    { id:'ai', capabilityCategory:'AI_PRODUCTIVITY', displayName:'AI Productivity', applications:[{vendorName:'OpenAI',applicationName:'ChatGPT',approved:false,status:'unmanaged',usersAssigned:34,activeUsers:31},{vendorName:'Microsoft',applicationName:'Microsoft Copilot',approved:true,status:'underused',usersAssigned:320,activeUsers:84},{vendorName:'Anthropic',applicationName:'Claude',approved:false,status:'unmanaged',usersAssigned:18,activeUsers:15}] },
    { id:'analytics', capabilityCategory:'ANALYTICS', displayName:'Analytics', applications:[{vendorName:'Tableau',applicationName:'Tableau',approved:true,status:'underused',usersAssigned:150,activeUsers:28},{vendorName:'Microsoft',applicationName:'Power BI',approved:true,status:'approved',usersAssigned:620,activeUsers:500}] },
    { id:'crm', capabilityCategory:'CRM', displayName:'CRM', applications:[{vendorName:'Salesforce',applicationName:'Salesforce',approved:true,status:'approved',usersAssigned:540,activeUsers:430},{vendorName:'HubSpot',applicationName:'HubSpot',approved:true,status:'underused',usersAssigned:70,activeUsers:22}] },
  ],
  governanceExposureScore: 20,
  evidenceRefs: Array.from(new Set(demoFindings.flatMap((finding) => finding.evidenceRefs))),
}

export function normalizeSaaSRationalisationPayload(payload: any): SaaSRationalisationData { return { summary: { ...demoSaaSRationalisationData.summary, ...(payload?.summary ?? {}) }, findings: Array.isArray(payload?.findings) ? payload.findings : [], opportunity: { ...demoSaaSRationalisationData.opportunity, ...(payload?.opportunity ?? {}), findingsWithSavings: payload?.opportunity?.findingsWithSavings ?? [], governanceOnlyFindings: payload?.opportunity?.governanceOnlyFindings ?? [] }, overlapGroups: Array.isArray(payload?.overlapGroups) ? payload.overlapGroups : [], governanceExposureScore: Number(payload?.governanceExposureScore ?? 0), evidenceRefs: Array.isArray(payload?.evidenceRefs) ? payload.evidenceRefs : [] } }

export function useSaaSRationalisationData() { const workspace = useWorkspace(); const live = useLiveResource<SaaSRationalisationData>({ path: '/api/playbooks/saas-rationalisation/exposure', enabled: workspace.mode === 'live', requireDataReady: false, initialData: demoSaaSRationalisationData, normalizer: normalizeSaaSRationalisationPayload, isEmpty: (data) => data.findings.length === 0 }); return useMemo(() => { if (workspace.mode === 'demo') return { data: demoSaaSRationalisationData, loading: false, error: null, isEmptyLive: false, refresh: () => Promise.resolve(demoSaaSRationalisationData) }; return { data: live.data.findings.length ? live.data : demoSaaSRationalisationData, loading: live.loading, error: live.error, isEmptyLive: live.isEmpty, refresh: live.refresh } }, [workspace.mode, live.data, live.loading, live.error, live.isEmpty, live.refresh]) }
