import { Router } from 'express';
import { runConnectorImplementationAdaptersAudit, connectorAdapterRegistry } from '../lib/connector-adapters';
const router = Router();
const ensureDefaults = () => { if (!connectorAdapterRegistry.list().length) connectorAdapterRegistry.registerDefaultAdapters(); };
const adapter = (key: string) => { ensureDefaults(); const found = connectorAdapterRegistry.get(key); if (!found) throw new Error('CONNECTOR_ADAPTER_NOT_FOUND'); return found; };
const wrap = (fn: any) => async (req: any, res: any) => { try { res.json(await fn(req)); } catch (error: any) { res.status(400).json({ error: error.message }); } };
router.post('/register-defaults', wrap(() => { ensureDefaults(); return { adapters: connectorAdapterRegistry.list().map((a) => ({ connectorKey: a.connectorKey, connectorFamily: a.connectorFamily })) }; }));
router.get('/adapters', wrap(() => { ensureDefaults(); return { adapters: connectorAdapterRegistry.list().map((a) => ({ connectorKey: a.connectorKey, connectorFamily: a.connectorFamily, manifest: a.manifest })) }; }));
router.get('/adapters/:connectorKey', wrap((req: any) => adapter(req.params.connectorKey)));
router.get('/adapters/:connectorKey/auth-requirements', wrap((req: any) => adapter(req.params.connectorKey).getAuthRequirements()));
router.get('/adapters/:connectorKey/permission-checklist', wrap((req: any) => adapter(req.params.connectorKey).getPermissionChecklist()));
router.post('/adapters/:connectorKey/discover-capabilities', wrap((req: any) => adapter(req.params.connectorKey).discoverCapabilities({ ...req.body, connectorKey: req.params.connectorKey })));
router.post('/adapters/:connectorKey/validate-config', wrap((req: any) => adapter(req.params.connectorKey).validateConfig({ ...req.body, connectorKey: req.params.connectorKey })));
router.post('/adapters/:connectorKey/sample-fetch', wrap((req: any) => adapter(req.params.connectorKey).sampleFetch({ ...req.body, connectorKey: req.params.connectorKey })));
router.post('/adapters/:connectorKey/normalise/:outputContract', wrap((req: any) => adapter(req.params.connectorKey).normalise(req.params.outputContract, req.body?.payload ?? req.body ?? {})));
router.post('/adapters/:connectorKey/evidence/:outputContract', wrap((req: any) => adapter(req.params.connectorKey).buildEvidence(req.params.outputContract, req.body?.payload ?? req.body ?? {})));
router.post('/adapters/:connectorKey/graph/:outputContract', wrap((req: any) => adapter(req.params.connectorKey).mapToGraph(req.params.outputContract, req.body?.normalised ?? req.body ?? {})));
router.post('/adapters/:connectorKey/classify-error', wrap((req: any) => adapter(req.params.connectorKey).classifyError(new Error(String(req.body?.message ?? 'unknown')))));
router.get('/adapters/:connectorKey/rate-limit-policy', wrap((req: any) => adapter(req.params.connectorKey).getRateLimitPolicy()));
router.get('/audit', wrap(() => runConnectorImplementationAdaptersAudit()));
export default router;
