import { Router } from "express";
import { and, desc, eq } from "drizzle-orm";
import { db, executionEscalationsTable } from "@workspace/db";
import { ExecutionOrchestrationRepository } from "../lib/execution-orchestration/execution-orchestration.repository";
import { ExecutionAutomationPromotionService, ExecutionBatchService, ExecutionQueueService } from "../lib/execution-orchestration/execution-orchestration-service";

const router = Router();
const repo = new ExecutionOrchestrationRepository();
const queueService = new ExecutionQueueService(repo);
const batchService = new ExecutionBatchService(repo);
const automationService = new ExecutionAutomationPromotionService(repo);
function scope(req: any) { return { tenantId: req.headers["x-tenant-id"] ?? "default", actorId: req.headers["x-actor-id"] ?? "system" }; }

function parseId(raw: string) { const id = Number(raw); return Number.isInteger(id) && id > 0 ? id : null; }

router.get("/plans", async (req, res) => { const { tenantId } = scope(req); res.json(await repo.listPlans(String(tenantId))); });
router.get("/plans/:id", async (req, res) => { const { tenantId } = scope(req); const id=parseId(req.params.id); if(!id) return res.status(400).json({error:"Invalid plan id"}); return res.json(await repo.getPlan(String(tenantId), id)); });
router.get("/plans/:id/items", async (req, res) => { const { tenantId } = scope(req); const id=parseId(req.params.id); if(!id) return res.status(400).json({error:"Invalid plan id"}); return res.json(await repo.getPlanItems(String(tenantId), id)); });
router.get("/plans/:id/events", async (req, res) => { const { tenantId } = scope(req); const id=parseId(req.params.id); if(!id) return res.status(400).json({error:"Invalid plan id"}); return res.json(await repo.getPlanEvents(String(tenantId), id)); });
router.get("/queue/status", async (req, res) => { const { tenantId } = scope(req); const ready = await repo.getReadyQueueItems(String(tenantId), 100); res.json({ tenantId, readyCount: ready.length }); });
router.post("/plans/:id/pause", async (_req, res) => res.status(501).json({ error: "pause plan not implemented in execution engine yet" }));
router.post("/plans/:id/resume", async (req, res) => { try { const { tenantId, actorId } = scope(req); const plan = await repo.getPlan(String(tenantId), Number(req.params.id)); if (!plan) return res.status(404).json({ error: "Plan not found" }); return res.json(await queueService.resumePlan(plan, String(actorId))); } catch (e:any) { return res.status(409).json({ error: e.message }); } });
router.post("/plans/:id/cancel", async (_req, res) => res.status(501).json({ error: "cancel plan not implemented in execution engine yet" }));
router.post("/items/:id/retry", async (req, res) => { try { const { tenantId, actorId } = scope(req); return res.json(await queueService.retryQueueItem(String(tenantId), Number(req.params.id), String(actorId))); } catch (e:any) { return res.status(409).json({ error: e.message }); } });
router.post("/items/:id/cancel", async (req, res) => { try { const { tenantId, actorId } = scope(req); return res.json(await queueService.cancelQueueItem(String(tenantId), Number(req.params.id), String(actorId))); } catch (e:any) { return res.status(409).json({ error: e.message }); } });


router.get("/batches", async (req,res)=>{ const {tenantId}=scope(req); res.json(await repo.listBatches(String(tenantId))); });
router.get("/batches/:id", async (req,res)=>{ const {tenantId}=scope(req); res.json(await repo.getBatch(String(tenantId), Number(req.params.id))); });
router.get("/batches/:id/items", async (req,res)=>{ const {tenantId}=scope(req); res.json(await repo.getBatchItems(String(tenantId), Number(req.params.id))); });
router.post("/batches/:id/pause", async (req,res)=>{ const {tenantId,actorId}=scope(req); const batch=await repo.getBatch(String(tenantId), Number(req.params.id)); if(!batch) return res.status(404).json({error:"Batch not found"}); if(["COMPLETED","FAILED","CANCELLED"].includes(batch.status)) return res.status(409).json({error:"Completed batches cannot be mutated"}); const out=await batchService.pauseBatch(String(tenantId), Number(req.params.id)); await repo.appendEvent({tenantId:String(tenantId),planId:batch.planId,eventType:"BATCH_PAUSED",source:"execution-orchestration",actorId:String(actorId),payload:{batchId:batch.id}}); return res.json(out); });
router.post("/batches/:id/cancel", async (req,res)=>{ const {tenantId,actorId}=scope(req); const batch=await repo.getBatch(String(tenantId), Number(req.params.id)); if(!batch) return res.status(404).json({error:"Batch not found"}); if(["COMPLETED","FAILED","CANCELLED"].includes(batch.status)) return res.status(409).json({error:"Completed batches cannot be mutated"}); const out=await batchService.cancelBatch(String(tenantId), Number(req.params.id)); await repo.appendEvent({tenantId:String(tenantId),planId:batch.planId,eventType:"BATCH_CANCELLED",source:"execution-orchestration",actorId:String(actorId),payload:{batchId:batch.id}}); return res.json(out); });
router.post("/batches/:id/evaluate-readiness", async (req,res)=>{ const {tenantId,actorId}=scope(req); const out=await batchService.evaluateBatchReadiness(String(tenantId), Number(req.params.id)); await repo.appendEvent({tenantId:String(tenantId),planId:out?.planId,eventType:"BATCH_READINESS_EVALUATED",source:"execution-orchestration",actorId:String(actorId),payload:{batchId:Number(req.params.id),status:out?.status,readiness:out?.readiness}}); res.json(out); });

router.get("/automation-candidates", async (req,res)=>{ const {tenantId}=scope(req); res.json(await repo.listAutomationCandidates(String(tenantId))); });
router.get("/automation-candidates/:id", async (req,res)=>{ const {tenantId}=scope(req); res.json(await repo.getAutomationCandidate(String(tenantId), Number(req.params.id))); });
router.post("/automation-candidates/:id/approve-scheduled", async (req,res)=>{ const {tenantId,actorId}=scope(req); const c:any=await repo.getAutomationCandidate(String(tenantId), Number(req.params.id)); if(!c) return res.status(404).json({error:"Candidate not found"}); if(c.riskClass==="B" && c.approvalPolicy!="ALLOW_CLASS_B_SCHEDULED") return res.status(409).json({error:"Class B scheduled approval policy not satisfied"}); const out=await repo.updateAutomationCandidate(String(tenantId), c.id,{currentMode:"SCHEDULED_SUPERVISED",recommendedMode:"SCHEDULED_SUPERVISED",promotionStatus:"APPROVED"}); await repo.appendEvent({tenantId:String(tenantId),eventType:"AUTOMATION_PROMOTED",source:"execution-orchestration",actorId:String(actorId),payload:{candidateId:c.id,mode:"SCHEDULED_SUPERVISED"}}); return res.json(out); });
router.post("/automation-candidates/:id/approve-auto-safe", async (req,res)=>{ const {tenantId,actorId}=scope(req); const c:any=await repo.getAutomationCandidate(String(tenantId), Number(req.params.id)); if(!c) return res.status(404).json({error:"Candidate not found"}); if(c.riskClass!=="A" || c.blastRadiusBand!=="LOW") return res.status(409).json({error:"Only Class A + LOW blast radius can be auto-safe"}); if(!c.rollbackAvailable) return res.status(409).json({error:"Rollback is required for auto-safe"}); if(c.lastCriticalEscalationAt) return res.status(409).json({error:"Critical escalation history must be resolved"}); const out=await repo.updateAutomationCandidate(String(tenantId), c.id,{currentMode:"AUTO_EXECUTE_SAFE",recommendedMode:"AUTO_EXECUTE_SAFE",promotionStatus:"APPROVED"}); await repo.appendEvent({tenantId:String(tenantId),eventType:"AUTOMATION_PROMOTED",source:"execution-orchestration",actorId:String(actorId),payload:{candidateId:c.id,mode:"AUTO_EXECUTE_SAFE"}}); return res.json(out); });
router.post("/automation-candidates/:id/reject", async (req,res)=>{ const {tenantId,actorId}=scope(req); const reason=String(req.body?.reason??"REJECTED_BY_OPERATOR"); const out=await repo.updateAutomationCandidate(String(tenantId), Number(req.params.id),{promotionStatus:"REJECTED",promotionEvidence:{...req.body,preservedReason:reason}}); await repo.appendEvent({tenantId:String(tenantId),eventType:"AUTOMATION_NOT_ELIGIBLE",source:"execution-orchestration",actorId:String(actorId),payload:{candidateId:Number(req.params.id),reason}}); res.json(out); });
router.post("/automation-candidates/:id/revoke", async (req,res)=>{ const {tenantId,actorId}=scope(req); const reason=String(req.body?.reason??"REVOKED_BY_OPERATOR"); const out=await repo.updateAutomationCandidate(String(tenantId), Number(req.params.id),{currentMode:"RECOMMEND_ONLY",promotionStatus:"REVOKED",promotionEvidence:{...req.body,preservedReason:reason}}); await repo.appendEvent({tenantId:String(tenantId),eventType:"AUTOMATION_REVOKED",source:"execution-orchestration",actorId:String(actorId),payload:{candidateId:Number(req.params.id),reason}}); res.json(out); });

router.get("/observability/summary", async (req,res)=>{ const { tenantId } = scope(req); const [plans,ready,running,blocked,quarantined,escalations,batches,candidates,events]= await Promise.all([repo.listPlans(String(tenantId)), repo.getReadyQueueItems(String(tenantId),500), repo.listQueueByStatus(String(tenantId),"RUNNING",500), repo.listQueueByStatus(String(tenantId),"BLOCKED",500), repo.listQueueByStatus(String(tenantId),"QUARANTINED",500), db.select().from(executionEscalationsTable).where(and(eq(executionEscalationsTable.tenantId, String(tenantId)), eq(executionEscalationsTable.status,"OPEN"))), repo.listBatches(String(tenantId)), repo.listAutomationCandidates(String(tenantId)), repo.getRecentEvents(String(tenantId),200)]); const now=Date.now(); const oldestReadyItemAgeMinutes=ready.length?Math.max(...ready.map((i:any)=>Math.floor((now-new Date(i.createdAt).getTime())/60000))):0; return res.json({activePlans:plans.filter((p:any)=>!["COMPLETED","CANCELLED","FAILED"].includes(p.status)).length,readyItems:ready.length,runningItems:running.length,blockedItems:blocked.length,quarantinedItems:quarantined.length,openEscalations:escalations.length,slaBreaches:escalations.filter((e:any)=>String(e.escalationType).includes("SLA")).length,activeBatches:batches.filter((b:any)=>!["COMPLETED","CANCELLED","FAILED"].includes(b.status)).length,automationCandidatesReadyForReview:candidates.filter((c:any)=>c.promotionStatus==="READY_FOR_REVIEW").length,autoSafeApprovedCandidates:candidates.filter((c:any)=>c.currentMode==="AUTO_EXECUTE_SAFE" && c.promotionStatus==="APPROVED").length,recentFailures:events.filter((e:any)=>String(e.eventType).includes("FAIL")).length,recentRuntimeBlocks:events.filter((e:any)=>String(e.eventType).includes("RUNTIME_BLOCK")).length,recentDemotions:events.filter((e:any)=>String(e.eventType).includes("DEMOT")).length,oldestReadyItemAgeMinutes}); });

router.get("/escalations", async (req, res) => { const { tenantId } = scope(req); res.json(await db.select().from(executionEscalationsTable).where(eq(executionEscalationsTable.tenantId, String(tenantId))).orderBy(desc(executionEscalationsTable.createdAt)).limit(500)); });
router.post("/escalations/:id/acknowledge", async (req, res) => { const { tenantId } = scope(req); const [row] = await db.update(executionEscalationsTable).set({ status: "ACKNOWLEDGED", acknowledgedAt: new Date() }).where(and(eq(executionEscalationsTable.tenantId, String(tenantId)), eq(executionEscalationsTable.id, Number(req.params.id)))).returning(); res.json(row ?? { error: "Escalation not found" }); });
router.post("/escalations/:id/resolve", async (req, res) => { const { tenantId } = scope(req); const [row] = await db.update(executionEscalationsTable).set({ status: "RESOLVED", resolvedAt: new Date() }).where(and(eq(executionEscalationsTable.tenantId, String(tenantId)), eq(executionEscalationsTable.id, Number(req.params.id)))).returning(); res.json(row ?? { error: "Escalation not found" }); });

export default router;
