import {Router} from 'express';import {ExecutiveProofPackService,runExecutiveProofPacksAudit} from '../lib/executive-proof-packs';import {decisionAuthorityService} from '../lib/decision-authority/decision-authority-service';import {valueRealisationAuthorityService} from '../lib/value-realisation/value-realisation-service';import {workflowValueGraphService} from '../lib/workflow-value-graph/workflow-value-graph-service';import {aiValueAttributionService} from '../lib/ai-value-attribution/ai-value-attribution-service';import {aiEconomicsAuthorityService} from '../lib/ai-economics/ai-economics-service';import {aiInitiativePortfolioService} from '../lib/ai-initiative-portfolio/ai-initiative-portfolio-service';
const router=Router();const svc=new ExecutiveProofPackService(undefined,undefined,{decisionAuthorityService,valueRealisationAuthorityService,workflowValueGraphService,aiValueAttributionService,aiEconomicsAuthorityService,aiInitiativePortfolioService});const tenant=(req:any)=>req.tenantId??req.header('x-tenant-id')??'default';
router.post('/build/:packType',async(req:any,res,next)=>{try{res.json(await svc.buildProofPack(tenant(req),req.params.packType,req.body??{}))}catch(e){next(e)}});
router.post('/build-all',async(req:any,res,next)=>{try{res.json(await svc.buildAllProofPacks(tenant(req),req.body??{}))}catch(e){next(e)}});
router.get('/packs',async(req:any,res,next)=>{try{res.json(await svc.repo.listPacks(tenant(req),req.query as any))}catch(e){next(e)}});
router.get('/packs/:id',async(req:any,res,next)=>{try{res.json(await svc.repo.getPack(tenant(req),req.params.id))}catch(e){next(e)}});
router.get('/packs/:id/summary',async(req:any,res,next)=>{try{res.json(await svc.getPackSummary(tenant(req),req.params.id))}catch(e){next(e)}});
router.get('/packs/:id/sections',async(req:any,res,next)=>{try{res.json(await svc.repo.listSections(tenant(req),{packId:req.params.id}))}catch(e){next(e)}});
router.get('/packs/:id/evidence',async(req:any,res,next)=>{try{res.json(await svc.repo.listEvidenceBindings(tenant(req),{packId:req.params.id}))}catch(e){next(e)}});
router.get('/packs/:id/audience-summary',async(req:any,res,next)=>{try{res.json((await svc.repo.listAudienceSummaries(tenant(req),{packId:req.params.id}))[0])}catch(e){next(e)}});
router.get('/packs/:id/readiness',async(req:any,res,next)=>{try{res.json(await svc.repo.listReadinessChecks(tenant(req),{packId:req.params.id}))}catch(e){next(e)}});
router.get('/packs/:id/exports',async(req:any,res,next)=>{try{res.json(await svc.repo.listExports(tenant(req),{packId:req.params.id}))}catch(e){next(e)}});
router.post('/packs/:id/bind-evidence',async(req:any,res,next)=>{try{res.json(await svc.bindEvidenceToPack(tenant(req),req.params.id,req.body?.evidence??[]))}catch(e){next(e)}});
router.post('/packs/:id/evaluate-readiness',async(req:any,res,next)=>{try{res.json(await svc.evaluatePackReadiness(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/packs/:id/generate-audience-summary',async(req:any,res,next)=>{try{res.json(await svc.generateAudienceSummary(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/packs/:id/export/:exportType',async(req:any,res,next)=>{try{res.json(await svc.generateExport(tenant(req),req.params.id,req.params.exportType,req.body?.generatedBy))}catch(e){next(e)}});
router.post('/packs/:id/archive',async(req:any,res,next)=>{try{res.json(await svc.archivePack(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/snapshot/build',async(req:any,res,next)=>{try{res.json(await svc.buildProofPackSnapshot(tenant(req)))}catch(e){next(e)}});
router.get('/snapshot/latest',async(req:any,res,next)=>{try{res.json((await svc.repo.listSnapshots(tenant(req))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0])}catch(e){next(e)}});
router.get('/summary',async(req:any,res,next)=>{try{res.json(await svc.summariseTenantProofPacks(tenant(req)))}catch(e){next(e)}});
router.get('/audit',async(_req,res,next)=>{try{res.json(await runExecutiveProofPacksAudit())}catch(e){next(e)}});
export default router;
