import {Router} from 'express';import {GovernedExecutionService,runGovernedExecutionExpansionAudit} from '../lib/governed-execution';
const router=Router();const svc=new GovernedExecutionService();const tenant=(req:any)=>req.tenantId??req.header('x-tenant-id')??'default';
router.post('/plans',async(req:any,res,next)=>{try{res.json(await svc.createExecutionPlan({tenantId:tenant(req),...(req.body??{})}))}catch(e){next(e)}});
router.post('/plans/from-recommendation/:recommendationId',async(req:any,res,next)=>{try{res.json(await svc.createPlanFromRecommendation(tenant(req),req.params.recommendationId))}catch(e){next(e)}});
router.post('/plans/from-portfolio-recommendation/:portfolioRecommendationId',async(req:any,res,next)=>{try{res.json(await svc.createPlanFromPortfolioRecommendation(tenant(req),req.params.portfolioRecommendationId))}catch(e){next(e)}});
router.get('/plans',async(req:any,res,next)=>{try{res.json(await svc.repo.listPlans(tenant(req),req.query as any))}catch(e){next(e)}});
router.get('/plans/:id',async(req:any,res,next)=>{try{res.json(await svc.repo.getPlan(tenant(req),req.params.id))}catch(e){next(e)}});
router.get('/plans/:id/summary',async(req:any,res,next)=>{try{res.json(await svc.summarisePlan(tenant(req),req.params.id))}catch(e){next(e)}});
router.get('/plans/:id/steps',async(req:any,res,next)=>{try{res.json(await svc.repo.listSteps(tenant(req),{planId:req.params.id}))}catch(e){next(e)}});
router.get('/plans/:id/gates',async(req:any,res,next)=>{try{res.json(await svc.repo.listGateChecks(tenant(req),{planId:req.params.id}))}catch(e){next(e)}});
router.get('/plans/:id/dry-runs',async(req:any,res,next)=>{try{res.json(await svc.repo.listDryRuns(tenant(req),{planId:req.params.id}))}catch(e){next(e)}});
router.get('/plans/:id/runs',async(req:any,res,next)=>{try{res.json(await svc.repo.listRuns(tenant(req),{planId:req.params.id}))}catch(e){next(e)}});
router.get('/plans/:id/rollback',async(req:any,res,next)=>{try{res.json((await svc.repo.listRollbackPlans(tenant(req),{planId:req.params.id}))[0])}catch(e){next(e)}});
router.get('/plans/:id/verifications',async(req:any,res,next)=>{try{res.json(await svc.repo.listVerifications(tenant(req),{planId:req.params.id}))}catch(e){next(e)}});
router.post('/plans/:id/generate-steps',async(req:any,res,next)=>{try{res.json(await svc.generateExecutionSteps(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/plans/:id/generate-rollback',async(req:any,res,next)=>{try{res.json(await svc.generateRollbackPlan(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/plans/:id/dry-run',async(req:any,res,next)=>{try{res.json(await svc.runDryRun(tenant(req),req.params.id,req.body??{}))}catch(e){next(e)}});
router.post('/plans/:id/evaluate-gates',async(req:any,res,next)=>{try{res.json(await svc.evaluateExecutionGates(tenant(req),req.params.id,req.body??{}))}catch(e){next(e)}});
router.post('/plans/:id/submit-approval',async(req:any,res,next)=>{try{res.json(await svc.submitForApproval(tenant(req),req.params.id))}catch(e){next(e)}});
router.post('/plans/:id/approve',async(req:any,res,next)=>{try{res.json(await svc.markApproved(tenant(req),req.params.id,req.body?.approvedByUserId??req.body?.approvedBy??'approver'))}catch(e){next(e)}});
router.post('/plans/:id/execute',async(req:any,res,next)=>{try{res.json(await svc.runExecution(tenant(req),req.params.id,req.body??{}))}catch(e){next(e)}});
router.post('/plans/:id/cancel',async(req:any,res,next)=>{try{res.json(await svc.cancelExecution(tenant(req),req.params.id,req.body?.reason??'Cancelled'))}catch(e){next(e)}});
router.post('/plans/:id/verify',async(req:any,res,next)=>{try{res.json(await svc.verifyExecution(tenant(req),req.params.id,req.body?.runId))}catch(e){next(e)}});
router.post('/snapshot/build',async(req:any,res,next)=>{try{res.json(await svc.buildExecutionSnapshot(tenant(req)))}catch(e){next(e)}});
router.get('/snapshot/latest',async(req:any,res,next)=>{try{res.json((await svc.repo.listSnapshots(tenant(req))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0])}catch(e){next(e)}});
router.get('/summary',async(req:any,res,next)=>{try{res.json(await svc.summariseTenantExecution(tenant(req)))}catch(e){next(e)}});
router.get('/audit',async(_req,res,next)=>{try{res.json(await runGovernedExecutionExpansionAudit())}catch(e){next(e)}});
export default router;
