import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import connectorsRouter from "./connectors";
import recommendationsRouter from "./recommendations";
import executionRouter from "./execution";
import outcomesRouter from "./outcomes";
import driftRouter from "./drift";
import tenantPricingRouter from "./tenant-pricing";
import reconciliationRouter from "./reconciliation";
import jobsRouter from "./jobs";
import verificationRouter from "./verification";
import approvalsRouter from "./approvals";
import governanceRouter from "./governance";
import governanceExceptionsRouter from "./governance-exceptions";
import operationalizationRouter from "./operationalization";
import enterpriseRouter from "./enterprise";
import onboardingRouter from "./onboarding";
import platformEventsRouter from "./platform-events";
import authRouter from "./auth";
import executionOrchestrationRouter from "./execution-orchestration";
import playbooksRouter from "./playbooks";
import demoRouter from "./demo";
import simulationsRouter from "./simulations";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/dashboard", dashboardRouter);
router.use("/connectors", connectorsRouter);
router.use("/recommendations", recommendationsRouter);
router.use("/execution", executionRouter);
router.use("/outcomes", outcomesRouter);
router.use("/drift", driftRouter);
router.use("/pricing/tenant", tenantPricingRouter);
router.use("/reconciliation", reconciliationRouter);
router.use("/jobs", jobsRouter);
router.use("/verification", verificationRouter);
router.use("/approvals", approvalsRouter);
router.use("/governance", governanceRouter);
router.use("/governance/exceptions", governanceExceptionsRouter);
router.use("/operationalization", operationalizationRouter);
router.use("/enterprise", enterpriseRouter);
router.use("/onboarding", onboardingRouter);
router.use("/platform-events", platformEventsRouter);
router.use("/auth", authRouter);
router.use("/execution-orchestration", executionOrchestrationRouter);
router.use("/playbooks", playbooksRouter);
router.use("/demo", demoRouter);
router.use("/simulations", simulationsRouter);

export default router;
