import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import connectorsRouter from "./connectors";
import recommendationsRouter from "./recommendations";
import executionRequestsRouter from "./execution-requests";
import executionDryRunRouter from "./execution-dry-run";
import executionRuntimeRouter from "./execution-runtime";
import executionRouter from "./execution";
import outcomesRouter from "./outcomes";
import driftRouter from "./drift";
import tenantPricingRouter from "./tenant-pricing";
import reconciliationRouter from "./reconciliation";
import jobsRouter from "./jobs";
import verificationRouter from "./verification";
import approvalsRouter from "./approvals";
import governanceRouter from "./governance";
import governanceExceptionsRouter from "./governance-exceptions";
import operationalizationRouter from "./operationalization";
import enterpriseRouter from "./enterprise";
import onboardingRouter from "./onboarding";
import platformEventsRouter from "./platform-events";
import telemetryRouter from "./telemetry";
import authRouter from "./auth";
import executionOrchestrationRouter from "./execution-orchestration";
import playbooksRouter from "./playbooks";
import demoRouter from "./demo";
import simulationsRouter from "./simulations";
import graphRouter from "./graph";
import discoveryRouter from "./discovery";
import workflowRouter from "./workflow";
import pilotRouter from "./pilot";
import economicOperationsRouter from "./economic-operations";
import packsRouter from "./packs";
import executionResultsOutcomeRouter from "./execution-results-outcome";
import campaignsRouter from "./campaigns";
import schedulesRouter from "./schedules";
import approvalWorkflowsRouter from "./approval-workflows";
import approvalAuthorityRouter from "./approval-authority";
import eventsRouter from "./events";
import auditPacksRouter from "./audit-packs";
import runtimeObservabilityRouter from "./runtime-observability";
import securityRouter from "./security";
import runtimeRecoveryRouter from "./runtime-recovery";
import trustRouter from "./trust";
import vendorChangesRouter from "./vendor-changes";
import opportunitiesRouter from "./opportunities";
import opportunityFactoryRouter from "./opportunity-factory";
import renewalsRouter from "./renewals";
import benchmarksRouter from "./benchmarks";
import contractsRouter from "./contracts";
import prioritiesRouter from "./priorities";
import utilizationRouter from "./utilization";
import { requireCapability, requireTenantContext } from "../middleware/security-guards";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/dashboard", dashboardRouter);
router.use("/connectors", requireTenantContext(), requireCapability("READ_CONNECTORS"), connectorsRouter);
router.use("/recommendations", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), recommendationsRouter);
router.use("/trust", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), trustRouter);
router.use("/vendor-changes", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), vendorChangesRouter);
router.use("/opportunities", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), opportunitiesRouter);
router.use("/opportunity-factory", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), opportunityFactoryRouter);
router.use("/renewals", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), renewalsRouter);
router.use("/benchmarks", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), benchmarksRouter);
router.use("/contracts", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), contractsRouter);
router.use("/priorities", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), prioritiesRouter);
router.use("/utilization", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), utilizationRouter);
router.use("/campaigns", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), campaignsRouter);
router.use("/schedules", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), schedulesRouter);
router.use("/approval-workflows", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), approvalWorkflowsRouter);
router.use("/approval-authority", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), approvalAuthorityRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), eventsRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), auditPacksRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), runtimeObservabilityRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), securityRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), runtimeRecoveryRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), executionRequestsRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), executionDryRunRouter);
router.use("/", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), executionRuntimeRouter);
router.use("/execution", executionRouter);
router.use("/outcomes", outcomesRouter);
router.use("/drift", driftRouter);
router.use("/pricing/tenant", tenantPricingRouter);
router.use("/reconciliation", reconciliationRouter);
router.use("/jobs", jobsRouter);
router.use("/verification", verificationRouter);
router.use("/approvals", approvalsRouter);
router.use("/governance", requireTenantContext(), requireCapability("MANAGE_POLICIES"), governanceRouter);
router.use("/governance/exceptions", governanceExceptionsRouter);
router.use("/operationalization", operationalizationRouter);
router.use("/enterprise", enterpriseRouter);
router.use("/onboarding", onboardingRouter);
router.use("/platform-events", platformEventsRouter);
router.use("/telemetry", requireTenantContext(), requireCapability("READ_TELEMETRY"), telemetryRouter);
router.use("/auth", authRouter);
router.use("/execution-orchestration", executionOrchestrationRouter);
router.use("/playbooks", requireTenantContext(), requireCapability("READ_RECOMMENDATIONS"), playbooksRouter);
router.use("/demo", demoRouter);
router.use("/simulations", requireTenantContext(), requireCapability("CREATE_SIMULATIONS"), simulationsRouter);
router.use("/graph", requireTenantContext(), requireCapability("READ_GRAPH"), graphRouter);
router.use("/discovery", requireTenantContext(), requireCapability("READ_GRAPH"), discoveryRouter);
router.use("/workflow", workflowRouter);
router.use("/economic-operations", economicOperationsRouter);
router.use("/packs", packsRouter);
router.use('/', executionResultsOutcomeRouter);
router.use("/", pilotRouter);

export default router;
