import { randomUUID } from "node:crypto";
import { Router } from "express";
import { requireCapability } from "../middleware/security-guards";
import { ProductionConnectorRunner, runProductionConnectorsAudit } from "../lib/production-connectors";
import { EncryptedMicrosoftTokenStore, MicrosoftOAuthService, MicrosoftPermissionValidator } from "../lib/microsoft-auth";
const router = Router();
const runner = new ProductionConnectorRunner();
const tokenStore = new EncryptedMicrosoftTokenStore();
const oauth = new MicrosoftOAuthService({ clientId: process.env.MICROSOFT_CLIENT_ID ?? "local-client", clientSecret: process.env.MICROSOFT_CLIENT_SECRET, redirectUri: process.env.MICROSOFT_REDIRECT_URI ?? "http://localhost/api/production-connectors/microsoft/oauth/callback", tokenStore });
const tenant = (req: { tenantId?: string; header(name: string): string | undefined }) => req.tenantId ?? req.header("x-tenant-id") ?? "default-tenant";
const connectorKey = (v: unknown) => String(v ?? "M365") === "ENTRA_ID" ? "ENTRA_ID" as const : "M365" as const;
const publicConnection = (connection: any) => connection ? ({ ...connection, credentialRef: connection.credentialRef }) : connection;
router.get("/microsoft/auth-url", (req, res) => res.json(oauth.generateAuthorizationUrl({ tenantId: tenant(req), connectorKey: connectorKey(req.query.connectorKey), scopes: String(req.query.scopes ?? "User.Read.All Group.Read.All Reports.Read.All Directory.Read.All").split(/[,\s]+/).filter(Boolean), state: String(req.query.state ?? randomUUID()) })));
router.post("/microsoft/oauth/callback", async (req, res) => res.json(publicConnection(await oauth.exchangeAuthorizationCode({ tenantId: tenant(req), connectorKey: connectorKey(req.body?.connectorKey), code: String(req.body?.code), state: String(req.body?.state), scopes: req.body?.scopes ?? [] }))));
router.post("/microsoft/client-credentials/connect", async (req, res) => res.json(publicConnection(await oauth.connectClientCredentials({ tenantId: tenant(req), connectorKey: connectorKey(req.body?.connectorKey), scopes: req.body?.scopes ?? [] }))));
router.post("/microsoft/refresh", async (req, res) => res.json(publicConnection(await oauth.refreshAccessToken(tenant(req), String(req.body?.credentialRef)))));
router.post("/microsoft/validate-permissions", async (req, res) => res.json(new MicrosoftPermissionValidator().validate(req.body?.grantedScopes ?? [], req.body?.requiredScopes ?? [])));
router.post("/microsoft/disconnect", async (req, res) => res.json(publicConnection(await oauth.revokeOrDisableConnection(tenant(req), String(req.body?.credentialRef)))));
router.get("/connectors", (_req, res) => res.json(runner.listConnectors()));
router.get("/connectors/:connectorKey/capabilities", async (req, res) => res.json(await runner.discoverCapabilities(tenant(req), String(req.params.connectorKey), req.body ?? {})));
router.post("/connectors/:connectorKey/validate", async (req, res) => res.json(await runner.validateConnection(tenant(req), String(req.params.connectorKey), req.body ?? {})));
router.post("/connectors/:connectorKey/dry-run", async (req, res) => res.json(await runner.dryRun(tenant(req), String(req.params.connectorKey), req.body ?? {})));
router.post("/connectors/:connectorKey/write-plan", async (req, res) => res.json(await runner.buildWritePlan(tenant(req), String(req.params.connectorKey), req.body ?? {})));
router.post("/connectors/:connectorKey/sync", requireCapability("RUN_READ_ONLY_SYNC"), async (req, res) => res.json(await runner.sync(tenant(req), String(req.params.connectorKey), req.body ?? {})));
router.get("/runs", (req, res) => res.json(runner.listRuns(tenant(req), req.query as any)));
router.get("/runs/:runId", (req, res) => res.json(runner.getRun(tenant(req), String(req.params.runId)) ?? null));
router.get("/audit", async (_req, res) => res.json(await runProductionConnectorsAudit()));
export default router;
