import { EconomicGraphService } from '../economic-graph/economic-graph-service'; import { platformEventService } from '../events/platform-event-service'; import { ownershipIntelligenceRepository, OwnershipIntelligenceRepository } from './ownership-intelligence-repository'; import type { OwnershipAssignment, OwnershipApprovalRoute, OwnershipSnapshot } from './ownership-intelligence-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export class OwnershipIntelligenceService{constructor(private readonly repo:OwnershipIntelligenceRepository=ownershipIntelligenceRepository, private readonly graph:any=new EconomicGraphService()){} private stamp<T extends {id?:string;createdAt?:string;updatedAt?:string;source?:string;evidenceRefs?:string[]}>(p:string,o:T){const t=now();return {...o,id:o.id??id(p),source:o.source??'ownership-intelligence',evidenceRefs:o.evidenceRefs??[],createdAt:o.createdAt??t,updatedAt:t} as any} private async link(tenantId:string,entityType:string,entityId:string,name:string,edges:{from:string;to:string;type:string}[]=[]){try{await this.graph.createNode({tenantId,entityType,canonicalName:name,canonicalKey:entityId,confidenceScore:1,evidence:[{sourceSystem:'ownership-intelligence',sourceReferenceId:entityId,observedAt:now()}],metadata:{ownershipIntelligence:true}}); for(const e of edges)await this.graph.createEdge({tenantId,fromEntityId:e.from,toEntityId:e.to,relationshipType:e.type,confidenceScore:1,evidence:[{sourceSystem:'ownership-intelligence',sourceReferenceId:entityId,observedAt:now()}]})}catch(error){await platformEventService.recordSystemEvent(tenantId,'OWNERSHIP_INTELLIGENCE_GRAPH_LINK_FAILED',{severity:'WARNING',entityType,entityId,metadata:{error:String(error)}}).catch(()=>undefined)}}
 async createUser(input:any){const v=await this.repo.upsertUser(this.stamp('user',{status:'UNKNOWN',...input})); const edges=[] as any[]; if(v.managerId)edges.push({from:v.managerId,to:v.id,type:'MANAGES'}); if(v.departmentId)edges.push({from:v.id,to:v.departmentId,type:'BELONGS_TO'}); await this.link(v.tenantId,'USER',v.id,v.displayName,edges); return v}
 async createDepartment(input:any){const v=await this.repo.upsertDepartment(this.stamp('department',{costCentreIds:[],...input})); const edges=[] as any[]; if(v.parentDepartmentId)edges.push({from:v.id,to:v.parentDepartmentId,type:'BELONGS_TO'}); for(const c of v.costCentreIds)edges.push({from:v.id,to:c,type:'FUNDS'}); if(v.executiveOwnerId)edges.push({from:v.executiveOwnerId,to:v.id,type:'OWNS'}); await this.link(v.tenantId,'DEPARTMENT',v.id,v.name,edges); return v}
 async createExecutiveOwner(input:any){const v=await this.repo.upsertExecutiveOwner(this.stamp('executive-owner',{departmentIds:[],costCentreIds:[],...input})); await this.link(v.tenantId,'EXECUTIVE_OWNER',v.id,v.displayName,[...v.departmentIds.map((d:string)=>({from:v.id,to:d,type:'OWNS'})),...v.costCentreIds.map((c:string)=>({from:v.id,to:c,type:'OWNS'}))]); return v}
 async createAssignment(input:Partial<OwnershipAssignment>&{tenantId:string}){const v=await this.repo.upsertAssignment(this.stamp('assignment',input)); const edges=[] as any[]; if(v.ownerUserId)edges.push({from:v.ownerUserId,to:v.targetId,type:'OWNS'}); if(v.departmentId)edges.push({from:v.departmentId,to:v.targetId,type:'OWNS'}); if(v.costCentreId)edges.push({from:v.costCentreId,to:v.targetId,type:'FUNDS'}); if(v.executiveOwnerId)edges.push({from:v.executiveOwnerId,to:v.targetId,type:'OWNS'}); await this.link(v.tenantId,'OWNERSHIP_ASSIGNMENT',v.id,v.id,edges); return v}
 async createResponsibility(input:any){const v=await this.repo.upsertResponsibility(this.stamp('responsibility',input)); await this.link(v.tenantId,'RESPONSIBILITY',v.id,v.id,[{from:v.id,to:v.targetId,type:'DERIVED_FROM'},...v.evidenceRefs.map((e:string)=>({from:v.id,to:e,type:'SUPPORTED_BY_EVIDENCE'}))]); return v}
 async createApprovalRoute(input:Partial<OwnershipApprovalRoute>&{tenantId:string}){const v=await this.repo.upsertApprovalRoute(this.stamp('approval-route',{requiredApproverUserIds:[],requiredExecutiveOwnerIds:[],requiredDepartmentIds:[],requiredCostCentreIds:[],status:'READY',...input})); await this.link(v.tenantId,'APPROVAL_ROUTE',v.id,v.id,[...v.requiredApproverUserIds.map(u=>({from:u,to:v.targetId,type:'APPROVES'})),...v.requiredExecutiveOwnerIds.map(e=>({from:e,to:v.targetId,type:'APPROVES'}))]); return v}
 async resolveOwnershipChain(t:string,targetType:string,targetId:string){const a=(await this.repo.listAssignments(t,{targetType,targetId}))[0]; const chain:any={tenantId:t,targetType,targetId,assignment:a}; if(a){Object.assign(chain,{ownerUserId:a.ownerUserId,managerUserId:a.managerUserId,departmentId:a.departmentId,costCentreId:a.costCentreId,executiveOwnerId:a.executiveOwnerId}); const u=a.ownerUserId?await this.repo.getUser(t,a.ownerUserId):undefined; if(u){chain.ownerUser=u; chain.managerUserId??=u.managerId; chain.departmentId??=u.departmentId; chain.costCentreId??=u.costCentreId; chain.executiveOwnerId??=u.executiveOwnerId} const d=chain.departmentId?await this.repo.getDepartment(t,chain.departmentId):undefined; if(d){chain.department=d; chain.executiveOwnerId??=d.executiveOwnerId; chain.costCentreId??=d.costCentreIds[0]} } chain.missingFields=['ownerUserId','managerUserId','departmentId','costCentreId','executiveOwnerId'].filter(f=>!chain[f]); return chain}
 calculateOwnershipCompleteness(chain:any){return {completenessScore:['ownerUserId','managerUserId','departmentId','costCentreId','executiveOwnerId'].filter(f=>chain[f]).length*20,missingFields:['ownerUserId','managerUserId','departmentId','costCentreId','executiveOwnerId'].filter(f=>!chain[f])}}
 private snapshotReadiness(m:string[]):OwnershipSnapshot['readiness']{if(!m.length)return 'COMPLETE'; if(m.length>1)return 'INCOMPLETE'; return ({ownerUserId:'MISSING_OWNER',managerUserId:'MISSING_MANAGER',departmentId:'MISSING_DEPARTMENT',costCentreId:'MISSING_COST_CENTRE',executiveOwnerId:'MISSING_EXECUTIVE'} as any)[m[0]]}
 approvalStatus(c:any):OwnershipApprovalRoute['status']{const miss=['ownerUserId','departmentId','costCentreId','executiveOwnerId'].filter(f=>!c[f]); if(miss.length>2)return 'BLOCKED'; if(miss.includes('ownerUserId'))return 'MISSING_OWNER'; if(miss.includes('costCentreId'))return 'MISSING_COST_CENTRE'; if(miss.includes('executiveOwnerId'))return 'MISSING_EXECUTIVE'; return 'READY'}
 async createOwnershipSnapshot(t:string,targetType:string,targetId:string){const c=await this.resolveOwnershipChain(t,targetType,targetId); const calc=this.calculateOwnershipCompleteness(c); const v=await this.repo.upsertSnapshot(this.stamp('snapshot',{tenantId:t,targetType,targetId,...c,...calc,readiness:this.snapshotReadiness(calc.missingFields)})); await this.link(t,'OWNERSHIP_SNAPSHOT',v.id,v.id); return v}
 async buildApprovalRouteForRecommendation(t:string,recommendationId:string){const c=await this.resolveOwnershipChain(t,'RECOMMENDATION',recommendationId); return this.createApprovalRoute({tenantId:t,targetType:'RECOMMENDATION',targetId:recommendationId,requiredApproverUserIds:c.ownerUserId?[c.ownerUserId]:[],requiredExecutiveOwnerIds:c.executiveOwnerId?[c.executiveOwnerId]:[],requiredDepartmentIds:c.departmentId?[c.departmentId]:[],requiredCostCentreIds:c.costCentreId?[c.costCentreId]:[],approvalReason:'BUDGET_IMPACT',status:this.approvalStatus(c)})}
 async buildApprovalRouteForAction(t:string,actionId:string){const c=await this.resolveOwnershipChain(t,'GOVERNED_ACTION',actionId); return this.createApprovalRoute({tenantId:t,targetType:'GOVERNED_ACTION',targetId:actionId,requiredApproverUserIds:c.ownerUserId?[c.ownerUserId]:[],requiredExecutiveOwnerIds:c.executiveOwnerId?[c.executiveOwnerId]:[],requiredDepartmentIds:c.departmentId?[c.departmentId]:[],requiredCostCentreIds:c.costCentreId?[c.costCentreId]:[],approvalReason:'SERVICE_IMPACT',status:this.approvalStatus(c)})}
 async summariseDepartmentOwnership(t:string,departmentId:string){const a=await this.repo.listAssignments(t,{departmentId}); const r=await this.repo.listResponsibilities(t,{departmentId}); return {tenantId:t,departmentId,assignmentCount:a.length,responsibilityCount:r.length,ownedTargets:a.map(x=>({targetType:x.targetType,targetId:x.targetId}))}}
 async summariseExecutiveOwnership(t:string,executiveOwnerId:string){const a=await this.repo.listAssignments(t,{executiveOwnerId}); const r=await this.repo.listResponsibilities(t,{executiveOwnerId}); return {tenantId:t,executiveOwnerId,assignmentCount:a.length,responsibilityCount:r.length,ownedTargets:a.map(x=>({targetType:x.targetType,targetId:x.targetId}))}}
 async summariseTenantOwnership(t:string){const [users,departments,executives,assignments,responsibilities,routes,snapshots]=await Promise.all([this.repo.listUsers(t),this.repo.listDepartments(t),this.repo.listExecutiveOwners(t),this.repo.listAssignments(t),this.repo.listResponsibilities(t),this.repo.listApprovalRoutes(t),this.repo.listSnapshots(t)]); return {tenantId:t,userCount:users.length,departmentCount:departments.length,executiveOwnerCount:executives.length,assignmentCount:assignments.length,responsibilityCount:responsibilities.length,approvalRouteCount:routes.length,snapshotCount:snapshots.length,averageCompleteness:snapshots.length?Math.round(snapshots.reduce((s,x)=>s+x.completenessScore,0)/snapshots.length):0}}
}
export const ownershipIntelligenceService=new OwnershipIntelligenceService();
