export type OwnershipCollection='OWNERSHIP_USERS'|'OWNERSHIP_MANAGERS'|'OWNERSHIP_DEPARTMENTS'|'OWNERSHIP_EXECUTIVE_OWNERS'|'OWNERSHIP_ASSIGNMENTS'|'OWNERSHIP_RESPONSIBILITIES'|'OWNERSHIP_APPROVAL_ROUTES'|'OWNERSHIP_SNAPSHOTS';
export const OWNERSHIP_COLLECTIONS:OwnershipCollection[]=['OWNERSHIP_USERS','OWNERSHIP_MANAGERS','OWNERSHIP_DEPARTMENTS','OWNERSHIP_EXECUTIVE_OWNERS','OWNERSHIP_ASSIGNMENTS','OWNERSHIP_RESPONSIBILITIES','OWNERSHIP_APPROVAL_ROUTES','OWNERSHIP_SNAPSHOTS'];
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(tenantId:string,id:string):Promise<T|undefined>;list(tenantId:string,filters?:Record<string,unknown>):Promise<T[]>;deleteTenant(tenantId:string):Promise<void>;size():Promise<number>}
export interface OwnershipUser{id:string;tenantId:string;email:string;displayName:string;jobTitle?:string;managerId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;status:'ACTIVE'|'INACTIVE'|'UNKNOWN';source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface OwnershipDepartment{id:string;tenantId:string;name:string;code?:string;parentDepartmentId?:string;managerUserId?:string;executiveOwnerId?:string;costCentreIds:string[];source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ExecutiveOwner{id:string;tenantId:string;userId?:string;displayName:string;title?:string;portfolio?:string;departmentIds:string[];costCentreIds:string[];source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export type AssignmentTargetType='APPLICATION'|'AI_MODEL'|'AI_AGENT'|'AI_WORKFLOW'|'MCP_SERVER'|'TOOL'|'VENDOR'|'CONTRACT'|'ENTITLEMENT'|'RENEWAL'|'INVOICE'|'PURCHASE_ORDER'|'RECOMMENDATION'|'GOVERNED_ACTION'|'OUTCOME_EVENT'|'RISK';
export interface OwnershipAssignment{id:string;tenantId:string;ownerUserId?:string;managerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;targetType:AssignmentTargetType;targetId:string;assignmentType:'BUSINESS_OWNER'|'TECHNICAL_OWNER'|'BUDGET_OWNER'|'APPROVER'|'EXECUTIVE_SPONSOR'|'RISK_OWNER'|'FINANCE_OWNER';confidence:number;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface OwnershipResponsibility{id:string;tenantId:string;responsibleUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;responsibilityType:'SPEND'|'BUDGET'|'SAVINGS'|'RISK'|'APPROVAL'|'EXECUTION'|'OUTCOME'|'COMPLIANCE';targetType:'VENDOR'|'CONTRACT'|'ENTITLEMENT'|'RENEWAL'|'RECOMMENDATION'|'GOVERNED_ACTION'|'OUTCOME_EVENT'|'FINANCE_RECONCILIATION'|'RISK';targetId:string;valueAmount?:number;currency?:string;fiscalPeriod?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface OwnershipApprovalRoute{id:string;tenantId:string;targetType:'RECOMMENDATION'|'GOVERNED_ACTION'|'CONTRACT'|'RENEWAL'|'RISK'|'FINANCE_RECONCILIATION';targetId:string;requiredApproverUserIds:string[];requiredExecutiveOwnerIds:string[];requiredDepartmentIds:string[];requiredCostCentreIds:string[];approvalReason:'BUDGET_IMPACT'|'CONTRACTUAL_CHANGE'|'SECURITY_RISK'|'SERVICE_IMPACT'|'FINANCIAL_RECONCILIATION'|'EXECUTIVE_SIGNOFF';status:'READY'|'MISSING_OWNER'|'MISSING_COST_CENTRE'|'MISSING_EXECUTIVE'|'BLOCKED';source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface OwnershipSnapshot{id:string;tenantId:string;targetType:string;targetId:string;ownerUserId?:string;managerUserId?:string;departmentId?:string;costCentreId?:string;executiveOwnerId?:string;completenessScore:number;missingFields:string[];readiness:'COMPLETE'|'MISSING_OWNER'|'MISSING_MANAGER'|'MISSING_DEPARTMENT'|'MISSING_COST_CENTRE'|'MISSING_EXECUTIVE'|'INCOMPLETE';source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
