import { createPersistenceStore, MemoryPersistenceStore } from './ownership-intelligence-persistence';
import type { ExecutiveOwner, OwnershipApprovalRoute, OwnershipAssignment, OwnershipDepartment, OwnershipResponsibility, OwnershipSnapshot, OwnershipUser, PersistenceStore } from './ownership-intelligence-types';
export interface OwnershipIntelligenceStores{users:PersistenceStore<OwnershipUser>;managers:PersistenceStore<OwnershipUser>;departments:PersistenceStore<OwnershipDepartment>;executiveOwners:PersistenceStore<ExecutiveOwner>;assignments:PersistenceStore<OwnershipAssignment>;responsibilities:PersistenceStore<OwnershipResponsibility>;approvalRoutes:PersistenceStore<OwnershipApprovalRoute>;snapshots:PersistenceStore<OwnershipSnapshot>}
export const createOwnershipIntelligenceStores=():OwnershipIntelligenceStores=>({users:createPersistenceStore('OWNERSHIP_USERS'),managers:createPersistenceStore('OWNERSHIP_MANAGERS'),departments:createPersistenceStore('OWNERSHIP_DEPARTMENTS'),executiveOwners:createPersistenceStore('OWNERSHIP_EXECUTIVE_OWNERS'),assignments:createPersistenceStore('OWNERSHIP_ASSIGNMENTS'),responsibilities:createPersistenceStore('OWNERSHIP_RESPONSIBILITIES'),approvalRoutes:createPersistenceStore('OWNERSHIP_APPROVAL_ROUTES'),snapshots:createPersistenceStore('OWNERSHIP_SNAPSHOTS')});
export const createInMemoryOwnershipIntelligenceStores=():OwnershipIntelligenceStores=>({users:new MemoryPersistenceStore('OWNERSHIP_USERS'),managers:new MemoryPersistenceStore('OWNERSHIP_MANAGERS'),departments:new MemoryPersistenceStore('OWNERSHIP_DEPARTMENTS'),executiveOwners:new MemoryPersistenceStore('OWNERSHIP_EXECUTIVE_OWNERS'),assignments:new MemoryPersistenceStore('OWNERSHIP_ASSIGNMENTS'),responsibilities:new MemoryPersistenceStore('OWNERSHIP_RESPONSIBILITIES'),approvalRoutes:new MemoryPersistenceStore('OWNERSHIP_APPROVAL_ROUTES'),snapshots:new MemoryPersistenceStore('OWNERSHIP_SNAPSHOTS')});
const email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/; const reqTarget=(v:{targetId?:string})=>{if(!v.targetId)throw new Error('targetId is required')};
export class OwnershipIntelligenceRepository{constructor(private readonly s:OwnershipIntelligenceStores=createOwnershipIntelligenceStores()){} private user(v:OwnershipUser){if(!email.test(v.email))throw new Error('invalid email');return v} private conf(v:OwnershipAssignment){reqTarget(v); if(v.confidence<0||v.confidence>1)throw new Error('confidence must be between 0 and 1');return v} private score(v:OwnershipSnapshot){reqTarget(v); if(v.completenessScore<0||v.completenessScore>100)throw new Error('completeness score must be between 0 and 100');return v}
 upsertUser(v:OwnershipUser){return this.s.users.upsert(this.user(v))} getUser(t:string,id:string){return this.s.users.get(t,id)} listUsers(t:string,f={}){return this.s.users.list(t,f)}
 upsertDepartment(v:OwnershipDepartment){return this.s.departments.upsert(v)} getDepartment(t:string,id:string){return this.s.departments.get(t,id)} listDepartments(t:string,f={}){return this.s.departments.list(t,f)}
 upsertExecutiveOwner(v:ExecutiveOwner){return this.s.executiveOwners.upsert(v)} getExecutiveOwner(t:string,id:string){return this.s.executiveOwners.get(t,id)} listExecutiveOwners(t:string,f={}){return this.s.executiveOwners.list(t,f)}
 upsertAssignment(v:OwnershipAssignment){return this.s.assignments.upsert(this.conf(v))} getAssignment(t:string,id:string){return this.s.assignments.get(t,id)} listAssignments(t:string,f={}){return this.s.assignments.list(t,f)}
 upsertResponsibility(v:OwnershipResponsibility){reqTarget(v);return this.s.responsibilities.upsert(v)} getResponsibility(t:string,id:string){return this.s.responsibilities.get(t,id)} listResponsibilities(t:string,f={}){return this.s.responsibilities.list(t,f)}
 upsertApprovalRoute(v:OwnershipApprovalRoute){reqTarget(v);return this.s.approvalRoutes.upsert(v)} getApprovalRoute(t:string,id:string){return this.s.approvalRoutes.get(t,id)} listApprovalRoutes(t:string,f={}){return this.s.approvalRoutes.list(t,f)}
 upsertSnapshot(v:OwnershipSnapshot){return this.s.snapshots.upsert(this.score(v))} getSnapshot(t:string,id:string){return this.s.snapshots.get(t,id)} listSnapshots(t:string,f={}){return this.s.snapshots.list(t,f)}
 async deleteTenantOwnershipData(t:string){await Promise.all(Object.values(this.s).map(x=>x.deleteTenant(t)))} async collectionStatus(){const out:Record<string,number>={}; for(const [k,v] of Object.entries(this.s))out[k]=await v.size(); return out}}
export const ownershipIntelligenceRepository=new OwnershipIntelligenceRepository();
