export type DemoScenarioId = 'openai-token-explosion' | 'm365-disabled-user-reclaim' | 'aws-connector-degradation' | 'drift-recurrence' | 'flexera-entitlement-reconciliation'
export interface DemoScenario { id: DemoScenarioId; title: string; narrative: string; impacts: string[]; askHint: string }
export const DEMO_SCENARIOS: DemoScenario[] = [
  { id: 'openai-token-explosion', title: 'OpenAI Token Explosion', narrative: 'A product workflow begins consuming significantly more GPT-4 tokens after prompt growth and retry amplification.', impacts: ['AI spend spike', 'Model governance review', 'Projected savings with verification pending'], askHint: 'Where is drift increasing?' },
  { id: 'm365-disabled-user-reclaim', title: 'Disabled M365 User Reclaim', narrative: 'A disabled employee retains high-cost Microsoft licensing after offboarding.', impacts: ['M365 recommendation created', 'Governance review required', 'Reclaim action enters verification lifecycle', 'Flexera confidence boost in demo simulation'], askHint: 'What is my highest-confidence saving opportunity?' },
  { id: 'aws-connector-degradation', title: 'AWS Connector Degradation', narrative: 'Credential freshness and evidence quality degrade below policy thresholds.', impacts: ['Connector degraded', 'Readiness impact increases', 'Actions blocked pending remediation'], askHint: 'Which connectors need attention?' },
  { id: 'drift-recurrence', title: 'Drift Recurrence', narrative: 'A previously optimized workflow begins drifting back toward inefficient spend patterns.', impacts: ['Recurrence risk elevated', 'Drift detection triggered', 'Governance response with verification maturity checks', 'Flexera mismatch can block action'], askHint: 'What changed today?' },
  { id: 'flexera-entitlement-reconciliation', title: 'Flexera Entitlement Reconciliation', narrative: 'Flexera entitlement evidence validates or blocks recommendations by reconciling consumed licenses against entitlement position.', impacts: ['Authority evidence', 'Confidence boost', 'Mismatch blocker', 'Proof lineage'], askHint: 'Are there entitlement mismatches?' },
]
