export type QuerySource='API'|'SLACK'|'TEAMS'|'MCP'|'UI'|'SYSTEM'|'UNKNOWN';
export type QueryIntent='AI_CAPITAL_ALLOCATION'|'AI_INITIATIVE_PORTFOLIO'|'AI_ECONOMICS'|'AI_VALUE_ATTRIBUTION'|'WORKFLOW_VALUE'|'VALUE_REALISATION'|'OUTCOME_PROTECTION'|'DECISION_LINEAGE'|'EVIDENCE_LOOKUP'|'EXECUTIVE_SUMMARY'|'UNKNOWN';
export type QueryStatus='RECEIVED'|'ROUTED'|'ANSWERED'|'FAILED'|'INSUFFICIENT_CONTEXT'|'UNKNOWN';
export type AnswerType='DIRECT_ANSWER'|'RANKED_LIST'|'SUMMARY'|'EXPLANATION'|'EVIDENCE_TRACE'|'ACTION_GUIDANCE'|'INSUFFICIENT_CONTEXT'|'ERROR';
export type SourceType='EVIDENCE'|'DECISION'|'OUTCOME'|'INVESTMENT'|'WORKFLOW'|'AI_ATTRIBUTION'|'AI_ECONOMICS'|'AI_INITIATIVE'|'AI_CAPITAL_ALLOCATION'|'PROOF_PACK'|'UNKNOWN';
export type RelationshipType='SUPPORTS'|'EXPLAINS'|'PROVES'|'RANKS'|'RECOMMENDS'|'BLOCKS'|'WARNINGS'|'UNKNOWN';
export type AuthorityQuery={id:string;tenantId:string;queryText:string;normalizedQuery:string;querySource:QuerySource;queryIntent:QueryIntent;queryStatus:QueryStatus;requestedByPrincipalId?:string;createdAt:string;completedAt?:string;metadata:Record<string,unknown>};
export type AuthorityQueryAnswer={id:string;tenantId:string;queryId:string;answerType:AnswerType;title:string;summary:string;recommendation:string;confidence:number;createdAt:string;metadata:Record<string,unknown>};
export type AuthorityQuerySource={id:string;tenantId:string;queryId:string;answerId:string;sourceType:SourceType;sourceId:string;sourceLabel:string;sourceAuthority:string;relationshipType:RelationshipType;createdAt:string;metadata:Record<string,unknown>};
export type AuthorityQueryAnswerPayload={intent:QueryIntent;title:string;summary:string;recommendation:string;confidence:number;facts:Array<{label:string;value:string|number;unit?:string;sourceId?:string}>;rankedItems:Array<{rank:number;label:string;verdict:string;value?:string|number;confidence:number;sourceId?:string;reason:string}>;sources:Array<{sourceType:SourceType;sourceId:string;label:string;authority:string;relationshipType:RelationshipType}>;warnings:string[];nextQuestions:string[]};
type Input={tenantId:string;queryText:string;querySource?:QuerySource;requestedByPrincipalId?:string;metadata?:Record<string,unknown>;context?:Record<string,unknown>};
type SeedRecord={id:string;tenantId:string;authority:QueryIntent|'EVIDENCE_LOOKUP';label:string;verdict?:string;value?:number;cost?:number;confidence?:number;evidenceIds?:string[];workflowIds?:string[];outcomeIds?:string[];decisionRationale?:string;approvedBy?:string;metadata?:Record<string,unknown>};
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`; const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const rules: Array<[QueryIntent,string[]]>= [
 ['AI_CAPITAL_ALLOCATION',['where should next ai dollar go','which initiatives should get more funding','increase funding','reduce funding','stop funding','capital allocation']],
 ['AI_INITIATIVE_PORTFOLIO',['which ai initiatives','portfolio','scale maintain optimise retire','scale maintain optimize retire']],
 ['AI_ECONOMICS',['economic','efficient','value to cost','roi','cost per value','spend versus value']],
 ['AI_VALUE_ATTRIBUTION',['what value did ai create','attributed value','ai value']],
 ['WORKFLOW_VALUE',['which workflow','workflow created value','workflow value']],
 ['VALUE_REALISATION',['did investment create value','verified value','protected value']],
 ['OUTCOME_PROTECTION',['drift','protected','stop it happening again','value stayed fixed']],
 ['DECISION_LINEAGE',['why did we decide','who approved','decision evidence']],
 ['EVIDENCE_LOOKUP',['what evidence proves','evidence proves','proof trail','supporting evidence']],
 ['EXECUTIVE_SUMMARY',['summarise','summarize','summary','board','cfo','executive']]
];
class AuthorityQueryRepository{queries=new Map<string,AuthorityQuery>();answers=new Map<string,AuthorityQueryAnswer>();sources=new Map<string,AuthorityQuerySource>();records:SeedRecord[]=[];saveQuery(q:AuthorityQuery){this.queries.set(q.id,q);return q}saveAnswer(a:AuthorityQueryAnswer){this.answers.set(a.id,a);return a}saveSource(s:AuthorityQuerySource){this.sources.set(s.id,s);return s}listQueries(t:string){return [...this.queries.values()].filter(q=>q.tenantId===t).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}getQuery(t:string,id:string){const q=this.queries.get(id);return q?.tenantId===t?q:undefined}getAnswerByQuery(t:string,qid:string){return [...this.answers.values()].find(a=>a.tenantId===t&&a.queryId===qid)}getSources(t:string,qid:string){return [...this.sources.values()].filter(s=>s.tenantId===t&&s.queryId===qid)}seed(r:SeedRecord){this.records.push(r)}listRecords(t:string,i:QueryIntent){return this.records.filter(r=>r.tenantId===t&&r.authority===i)}}
export class AuthorityQueryService{constructor(private repo=new AuthorityQueryRepository()){} seedAuthorityRecord(r:SeedRecord){this.repo.seed(r)} classifyIntent(queryText:string):QueryIntent{const q=norm(queryText); return rules.find(([,ks])=>ks.some(k=>q.includes(norm(k))))?.[0]??'UNKNOWN'} async routeQuery(input:Input){return this.answerQuery(input)} async answerQuery(input:Input){if(!input.tenantId)throw new Error('TENANT_ID_REQUIRED'); if(!input.queryText?.trim())throw new Error('QUERY_TEXT_REQUIRED'); const intent=this.classifyIntent(input.queryText); const q=this.repo.saveQuery({id:id('aq'),tenantId:input.tenantId,queryText:input.queryText,normalizedQuery:norm(input.queryText),querySource:input.querySource??'UNKNOWN',queryIntent:intent,queryStatus:intent==='UNKNOWN'?'INSUFFICIENT_CONTEXT':'ROUTED',requestedByPrincipalId:input.requestedByPrincipalId,createdAt:now(),metadata:{...(input.metadata??{}),readOnly:true,actionsExecuted:0}}); const payload=this.resolve(input.tenantId,intent,input.queryText); const answer=this.repo.saveAnswer({id:id('aqa'),tenantId:input.tenantId,queryId:q.id,answerType:intent==='UNKNOWN'?'INSUFFICIENT_CONTEXT':payload.rankedItems.length?'RANKED_LIST':'SUMMARY',title:payload.title,summary:payload.summary,recommendation:payload.recommendation,confidence:payload.confidence,createdAt:now(),metadata:{payload}}); const sources=payload.sources.map(s=>this.repo.saveSource({id:id('aqs'),tenantId:input.tenantId,queryId:q.id,answerId:answer.id,sourceType:s.sourceType,sourceId:s.sourceId,sourceLabel:s.label,sourceAuthority:s.authority,relationshipType:s.relationshipType,createdAt:now(),metadata:{}})); q.queryStatus=intent==='UNKNOWN'?'INSUFFICIENT_CONTEXT':'ANSWERED'; q.completedAt=now(); this.repo.saveQuery(q); return {query:q,answer,sources}} getQueryById(t:string,id:string){return this.repo.getQuery(t,id)} getAnswerByQuery(t:string,q:string){return this.repo.getAnswerByQuery(t,q)} getQuerySources(t:string,q:string){return this.repo.getSources(t,q)} listQueries(t:string){return this.repo.listQueries(t)}
 private resolve(t:string,intent:QueryIntent,queryText:string):AuthorityQueryAnswerPayload{if(intent==='UNKNOWN')return {intent,title:'Insufficient context',summary:'The query could not be mapped to a supported authority intent.',recommendation:'Ask about capital allocation, AI economics, AI value attribution, workflow value, decision lineage, or evidence.',confidence:.2,facts:[],rankedItems:[],sources:[],warnings:['Unsupported intent; no authority was routed.'],nextQuestions:['Which AI initiatives should we stop funding?','Was Copilot economically efficient?']}; const records=this.repo.listRecords(t,intent); const ranked=records.map((r,i)=>({rank:i+1,label:r.label,verdict:r.verdict??'REVIEW',value:r.value,confidence:r.confidence??.75,sourceId:r.id,reason:r.decisionRationale??`${r.label} ranked by ${intent}.`})); const facts=records.flatMap(r=> intent==='AI_ECONOMICS'?[{label:'Value-to-cost ratio',value:r.cost?Number(((r.value??0)/r.cost).toFixed(2)):0,unit:'ratio',sourceId:r.id},{label:'Economics verdict',value:r.verdict??'UNKNOWN',sourceId:r.id}]: intent==='AI_VALUE_ATTRIBUTION'?[{label:'Attributed AI value',value:r.value??0,unit:'currency',sourceId:r.id},{label:'Attribution confidence',value:r.confidence??0,unit:'confidence',sourceId:r.id}]:[]); const srcs=records.flatMap(r=>[{sourceType:this.sourceType(intent),sourceId:r.id,label:r.label,authority:intent,relationshipType:'SUPPORTS' as RelationshipType},...(r.evidenceIds??[]).map(e=>({sourceType:'EVIDENCE' as SourceType,sourceId:e,label:`Evidence ${e}`,authority:'Evidence Registry',relationshipType:'PROVES' as RelationshipType})),...(r.workflowIds??[]).map(w=>({sourceType:'WORKFLOW' as SourceType,sourceId:w,label:`Workflow ${w}`,authority:'Workflow Value Graph',relationshipType:'SUPPORTS' as RelationshipType}))]); const hasProofSources=srcs.some(s=>s.sourceType==='EVIDENCE'||s.sourceType==='PROOF_PACK'||s.sourceType==='WORKFLOW'||s.sourceType==='DECISION'||s.sourceType==='OUTCOME'); const warnings=hasProofSources?[]:['No evidence/proof sources were available; confidence reduced.']; const base=records.length? .82:.35; const summary=records.length?`${records.length} authority record(s) matched ${intent}.`:'No matching authority records were available.'; return {intent,title:this.title(intent),summary,recommendation:ranked[0]?`Prioritise ${ranked[0].label} (${ranked[0].verdict}).`:'Collect source authority evidence before relying on this answer.',confidence:warnings.length?Math.min(base,.45):base,facts,rankedItems:ranked,sources:srcs,warnings,nextQuestions:['Show the supporting evidence.','What changed since the last review?']}}
 private title(i:QueryIntent){return i.split('_').map(w=>w[0]+w.slice(1).toLowerCase()).join(' ')} private sourceType(i:QueryIntent):SourceType{return ({AI_CAPITAL_ALLOCATION:'AI_CAPITAL_ALLOCATION',AI_INITIATIVE_PORTFOLIO:'AI_INITIATIVE',AI_ECONOMICS:'AI_ECONOMICS',AI_VALUE_ATTRIBUTION:'AI_ATTRIBUTION',WORKFLOW_VALUE:'WORKFLOW',VALUE_REALISATION:'INVESTMENT',OUTCOME_PROTECTION:'OUTCOME',DECISION_LINEAGE:'DECISION',EVIDENCE_LOOKUP:'EVIDENCE',EXECUTIVE_SUMMARY:'PROOF_PACK'} as any)[i]??'UNKNOWN'}}
export const authorityQueryService=new AuthorityQueryService();
export async function answerHeadlessQuestion(input:Input & {principalHint?:string}){const out=await authorityQueryService.answerQuery({...input,requestedByPrincipalId:input.requestedByPrincipalId??input.principalHint}); const payload=(out.answer.metadata as any).payload as AuthorityQueryAnswerPayload; return {plainText:`${payload.title}: ${payload.summary} ${payload.recommendation}`.trim(),structuredAnswer:payload,sources:out.sources,confidence:payload.confidence,warnings:payload.warnings}}
