export type M365ConnectorReadinessStatus = 'READY' | 'DEGRADED' | 'BLOCKED' | 'NOT_CONFIGURED'
export type M365CheckStatus = 'PASSED' | 'WARNING' | 'FAILED' | 'NOT_AVAILABLE'
export type M365SyncStatus = 'NEVER_SYNCED' | 'SYNCING' | 'COMPLETED' | 'PARTIAL' | 'FAILED'
export type M365RecommendationType = 'DISABLED_LICENSED_USER_RECLAIM' | 'INACTIVE_USER_RECLAIM' | 'HIGH_TIER_RIGHTSIZE' | 'ADD_ON_RECLAIM' | 'COPILOT_UNDERUTILIZATION'
export type M365RecommendationState = 'DISCOVERED' | 'GOVERNED' | 'APPROVAL_REQUIRED' | 'DRY_RUN_READY' | 'DRY_RUN_COMPLETED' | 'EXECUTION_DISABLED_BETA' | 'BLOCKED_DATA_TRUST' | 'PROJECTED' | 'VERIFIED' | 'DRIFT_MONITORED'
export type M365BetaExecutionMode = 'READ_ONLY' | 'DRY_RUN_ONLY' | 'APPROVAL_REQUIRED' | 'GOVERNED_EXECUTION_DISABLED'
export type M365ActionRiskClass = 'LOW' | 'MEDIUM' | 'HIGH' | 'BLOCKED'
export const DEFAULT_INACTIVE_DAYS = 90
export const LIVE_EXECUTION_ENABLED = process.env.ENABLE_LIVE_M365_EXECUTION === 'true'
