export type GovernedExecutionActionType =
  | 'M365_LICENSE_RECLAIM' | 'M365_LICENSE_ASSIGN' | 'M365_LICENSE_SWAP'
  | 'M365_GROUP_MEMBERSHIP_REVIEW' | 'M365_COPILOT_REVIEW' | 'ENTRA_OWNERSHIP_REVIEW'
  | 'SAAS_SEAT_REVIEW' | 'CONTRACT_RENEWAL_REVIEW' | 'ENTITLEMENT_RIGHTSIZE'
  | 'FINANCE_RECONCILIATION_REVIEW' | 'PORTFOLIO_RISK_REVIEW' | 'EVIDENCE_COLLECTION'
  | 'MANUAL_TASK' | 'CUSTOM';
export type TargetType='USER'|'GROUP'|'ENTITLEMENT'|'CONTRACT'|'RENEWAL'|'PORTFOLIO_ASSET'|'PORTFOLIO_VENDOR'|'PORTFOLIO_PRODUCT'|'APPLICATION'|'RISK'|'EVIDENCE'|'OTHER';
export type PlanStatus='DRAFT'|'PLANNED'|'DRY_RUN_PASSED'|'DRY_RUN_FAILED'|'AWAITING_APPROVAL'|'APPROVED'|'BLOCKED'|'EXECUTING'|'COMPLETED'|'FAILED'|'CANCELLED';
export type ExecutionMode='DRY_RUN'|'VALIDATE'|'EXECUTE';
export type GateKey='APPROVAL_PRESENT'|'OWNER_PRESENT'|'COST_CENTRE_PRESENT'|'EVIDENCE_PRESENT'|'LIVE_TENANT_READY'|'CONNECTOR_READY'|'ACTION_SUPPORTED'|'DESTRUCTIVE_ACTION_ALLOWED'|'ROLLBACK_AVAILABLE'|'FINANCE_VERIFICATION_AVAILABLE'|'GRAPH_READY';
export type StepType='VALIDATE_TARGET'|'VALIDATE_OWNER'|'VALIDATE_APPROVAL'|'VALIDATE_EVIDENCE'|'VALIDATE_LIVE_READINESS'|'SIMULATE_CHANGE'|'PREPARE_WRITE'|'EXECUTE_WRITE'|'VERIFY_RESULT'|'CAPTURE_EVIDENCE'|'UPDATE_GRAPH'|'UPDATE_OUTCOME'|'MANUAL_REVIEW';
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(t:string,id:string):Promise<T|undefined>;list(t:string,f?:Record<string,unknown>):Promise<T[]>;deleteTenant(t:string):Promise<void>;size():Promise<number>}
export const GOVERNED_EXECUTION_COLLECTIONS=['GOVERNED_EXECUTION_PLANS','GOVERNED_EXECUTION_STEPS','GOVERNED_EXECUTION_DRY_RUNS','GOVERNED_EXECUTION_GATE_CHECKS','GOVERNED_EXECUTION_RUNS','GOVERNED_EXECUTION_STEP_RESULTS','GOVERNED_EXECUTION_ROLLBACK_PLANS','GOVERNED_EXECUTION_VERIFICATIONS','GOVERNED_EXECUTION_EVIDENCE_BINDINGS','GOVERNED_EXECUTION_SNAPSHOTS'] as const;
export type GovernedExecutionCollection=typeof GOVERNED_EXECUTION_COLLECTIONS[number];
export interface GovernedExecutionPlan{id:string;tenantId:string;recommendationId?:string;portfolioRecommendationId?:string;actionId?:string;actionType:GovernedExecutionActionType;title:string;description:string;mode:'DRY_RUN_ONLY'|'APPROVAL_REQUIRED'|'READY_TO_EXECUTE'|'EXECUTION_DISABLED';status:PlanStatus;targetType:TargetType;targetId:string;ownerUserId?:string;approverUserIds:string[];executiveOwnerId?:string;costCentreId?:string;projectedValue?:number;currency?:string;riskLevel:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';destructive:boolean;reversible:boolean;requiresApproval:boolean;requiresEvidence:boolean;requiresOwnership:boolean;requiresFinanceVerification:boolean;requiresLiveReadiness:boolean;stepIds:string[];dryRunIds:string[];gateCheckIds:string[];rollbackPlanId?:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface GovernedExecutionStep{id:string;tenantId:string;planId:string;order:number;stepType:StepType;title:string;description:string;status:'PENDING'|'READY'|'BLOCKED'|'RUNNING'|'COMPLETED'|'FAILED'|'SKIPPED';adapterKey?:string;input:Record<string,unknown>;expectedOutput?:Record<string,unknown>;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface GovernedExecutionDryRun{id:string;tenantId:string;planId:string;status:'PASS'|'WARN'|'FAIL';simulatedAt:string;simulatedSteps:Array<{stepId:string;status:'PASS'|'WARN'|'FAIL';reason?:string}>;projectedImpact?:{projectedValue?:number;affectedUsers?:number;affectedLicenses?:number;affectedContracts?:number;affectedAssets?:number;currency?:string};blockers:Array<{blockerType:'MISSING_APPROVAL'|'MISSING_OWNER'|'MISSING_EVIDENCE'|'LIVE_READINESS_BLOCKED'|'CONNECTOR_NOT_READY'|'ACTION_NOT_SUPPORTED'|'DESTRUCTIVE_ACTION_DISABLED'|'VALIDATION_FAILED'|'UNKNOWN';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';description:string;nextStep:string}>;evidenceRefs:string[];createdAt:string}
export interface GovernedExecutionGateCheck{id:string;tenantId:string;planId:string;gateKey:GateKey;status:'PASS'|'WARN'|'FAIL'|'NOT_APPLICABLE';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';reason?:string;nextStep?:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface GovernedExecutionRun{id:string;tenantId:string;planId:string;mode:ExecutionMode;status:'PENDING'|'RUNNING'|'COMPLETED'|'FAILED'|'BLOCKED'|'CANCELLED';startedAt?:string;completedAt?:string;executedBy?:string;stepResultIds:string[];authorityWriteCount:number;graphWriteCount:number;evidenceRefs:string[];failureReason?:string;createdAt:string;updatedAt:string}
export interface GovernedExecutionStepResult{id:string;tenantId:string;runId:string;planId:string;stepId:string;status:'PASS'|'WARN'|'FAIL'|'SKIPPED';output?:Record<string,unknown>;errorCode?:'APPROVAL_MISSING'|'OWNER_MISSING'|'EVIDENCE_MISSING'|'LIVE_READINESS_BLOCKED'|'CONNECTOR_NOT_READY'|'ACTION_UNSUPPORTED'|'DESTRUCTIVE_ACTION_BLOCKED'|'ADAPTER_FAILED'|'VERIFICATION_FAILED'|'UNKNOWN';message?:string;evidenceRefs:string[];createdAt:string}
export interface GovernedExecutionRollbackPlan{id:string;tenantId:string;planId:string;available:boolean;rollbackType:'NO_OP'|'MANUAL'|'RESTORE_PREVIOUS_STATE'|'REASSIGN_LICENSE'|'REVERT_GROUP_MEMBERSHIP'|'REOPEN_REVIEW'|'CUSTOM';steps:Array<{order:number;title:string;description:string;manual:boolean}>;limitations:string[];evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface GovernedExecutionVerification{id:string;tenantId:string;planId:string;runId?:string;status:'VERIFIED'|'PARTIAL'|'FAILED'|'PENDING'|'NOT_APPLICABLE';verificationType:'STATE_CHANGED'|'VALUE_REALISED'|'EVIDENCE_CAPTURED'|'OUTCOME_RECORDED'|'FINANCE_RECONCILED'|'MANUAL_CONFIRMATION';expectedState?:Record<string,unknown>;actualState?:Record<string,unknown>;verifiedValue?:number;currency?:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface GovernedExecutionEvidenceBinding{id:string;tenantId:string;planId:string;evidenceRef:string;evidenceType:'PLAN'|'GATE'|'DRY_RUN'|'APPROVAL'|'EXECUTION'|'STEP_RESULT'|'ROLLBACK'|'VERIFICATION'|'BLOCKED'|'CANCELLED';demo:boolean;createdAt:string;updatedAt:string}
export interface GovernedExecutionSnapshot{id:string;tenantId:string;generatedAt:string;planCount:number;readyCount:number;awaitingApprovalCount:number;blockedCount:number;completedCount:number;failedCount:number;dryRunPassedCount:number;dryRunFailedCount:number;evidenceReadyCount:number;ownershipReadyCount:number;liveReadinessBlockedCount:number;projectedValue?:number;verifiedValue?:number;currency?:string;readiness:'READY'|'PARTIAL'|'BLOCKED'|'MISSING_DATA'|'DEMO';createdAt:string}
