import { OperationalGraphService } from '../operational-graph/service'; import { platformEventService } from '../events/platform-event-service'; import { financialTruthAuthorityRepository, FinancialTruthAuthorityRepository } from './financial-truth-repository';
import type { FinanceReconciliation, FinancialBudget, FinancialCostCentre, FinancialInvoice, FinancialPurchaseOrder, FinancialVendorSpend } from './financial-truth-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const variance=(verified:number,expected:number)=>({varianceAmount:verified-expected,variancePercent:expected===0?0:((verified-expected)/expected)*100});
export class FinancialTruthAuthorityService{constructor(private readonly repo:FinancialTruthAuthorityRepository=financialTruthAuthorityRepository, private readonly graph:any=new OperationalGraphService()){} private stamp<T extends {id?:string;createdAt?:string;updatedAt?:string;source?:string;evidenceRefs?:string[]}>(p:string,o:T){const t=now();return {...o,id:o.id??id(p),source:o.source??'financial-truth-authority',evidenceRefs:o.evidenceRefs??[],createdAt:o.createdAt??t,updatedAt:t} as any}
 private async link(tenantId:string,entityType:string,entityId:string,name:string,edges:{from:string;to:string;type:string}[]=[]){try{await this.graph.createNode({tenantId,entityType,canonicalName:name,canonicalKey:entityId,confidenceScore:1,evidence:[{sourceSystem:'financial-truth-authority',sourceReferenceId:entityId,observedAt:now()}],metadata:{financialTruthAuthority:true}}); for(const e of edges)await this.graph.createEdge({tenantId,fromEntityId:e.from,toEntityId:e.to,relationshipType:e.type,confidenceScore:1,evidence:[{sourceSystem:'financial-truth-authority',sourceReferenceId:entityId,observedAt:now()}]})}catch(error){await platformEventService.recordSystemEvent(tenantId,'FINANCIAL_TRUTH_GRAPH_LINK_FAILED',{severity:'WARNING',entityType,entityId,metadata:{error:String(error)}}).catch(()=>undefined)}}
 async createCostCentre(input:Partial<FinancialCostCentre>&{tenantId:string;code:string;name:string;currency:string}){const v=await this.repo.upsertCostCentre(this.stamp('cost-centre',input)); await this.link(v.tenantId,'COST_CENTRE',v.id,v.name); return v}
 async createBudget(input:Partial<FinancialBudget>&{tenantId:string;costCentreId:string;fiscalYear:string;annualBudget:number;consumedBudget:number;remainingBudget:number;currency:string}){const v=await this.repo.upsertBudget(this.stamp('budget',input)); await this.link(v.tenantId,'BUDGET',v.id,v.fiscalYear,[{from:v.id,to:v.costCentreId,type:'FUNDS'}]); return v}
 async createPurchaseOrder(input:Partial<FinancialPurchaseOrder>&{tenantId:string;poNumber:string;vendorId:string;amount:number;currency:string;status:FinancialPurchaseOrder['status']}){const v=await this.repo.upsertPurchaseOrder(this.stamp('purchase-order',input)); const edges=[] as any[]; if(v.entitlementId)edges.push({from:v.id,to:v.entitlementId,type:'FUNDS'}); if(v.contractId)edges.push({from:v.id,to:v.contractId,type:'GOVERNED_BY'}); await this.link(v.tenantId,'PURCHASE_ORDER',v.id,v.poNumber,edges); return v}
 async createInvoice(input:Partial<FinancialInvoice>&{tenantId:string;invoiceNumber:string;vendorId:string;invoiceDate:string;amount:number;currency:string;status:FinancialInvoice['status']}){const v=await this.repo.upsertInvoice(this.stamp('invoice',input)); const edges=[] as any[]; if(v.costCentreId)edges.push({from:v.id,to:v.costCentreId,type:'BELONGS_TO'}); if(v.purchaseOrderId)edges.push({from:v.id,to:v.purchaseOrderId,type:'DERIVED_FROM'}); await this.link(v.tenantId,'INVOICE',v.id,v.invoiceNumber,edges); return v}
 async createVendorSpend(input:Partial<FinancialVendorSpend>&{tenantId:string;vendorId:string;fiscalPeriod:string;fiscalYear:string;totalInvoiced:number;totalPaid:number;currency:string}){const v=await this.repo.upsertVendorSpend(this.stamp('vendor-spend',{invoiceIds:[],purchaseOrderIds:[],...input})); await this.link(v.tenantId,'VENDOR_SPEND',v.id,v.vendorId,v.invoiceIds.map(i=>({from:v.id,to:i,type:'DERIVED_FROM'}))); return v}
 async createReconciliation(input:Partial<FinanceReconciliation>&{tenantId:string;projectedSavings:number;expectedSavings:number;verifiedSavings:number;status:FinanceReconciliation['status']}){const calc=variance(input.verifiedSavings,input.expectedSavings); const confidence=this.calculateSavingsVerification({...input,...calc,evidenceRefs:input.evidenceRefs??[]} as FinanceReconciliation).confidence; const v=await this.repo.upsertReconciliation(this.stamp('reconciliation',{...input,...calc,confidence})); const edges=[] as any[]; if(v.outcomeId)edges.push({from:v.id,to:v.outcomeId,type:'VERIFIES'}); if(v.actionId)edges.push({from:v.id,to:v.actionId,type:'DERIVED_FROM'}); for(const e of v.evidenceRefs)edges.push({from:v.id,to:e,type:'SUPPORTED_BY_EVIDENCE'}); await this.link(v.tenantId,'FINANCE_RECONCILIATION',v.id,v.id,edges); return v}
 calculateBudgetPosition(b:FinancialBudget){return {remainingBudget:b.annualBudget-b.consumedBudget,consumedPercent:b.annualBudget===0?0:Math.round((b.consumedBudget/b.annualBudget)*100)}}
 async calculateVendorSpendPosition(t:string,vendorId:string){const invoices=await this.repo.listInvoices(t,{vendorId}); const pos=await this.repo.listPurchaseOrders(t,{vendorId}); const spend=await this.repo.listVendorSpend(t,{vendorId}); return {tenantId:t,vendorId,totalInvoiced:invoices.reduce((s,i)=>s+i.amount,0)+spend.reduce((s,v)=>s+v.totalInvoiced,0),totalPaid:invoices.filter(i=>i.status==='PAID').reduce((s,i)=>s+i.amount,0)+spend.reduce((s,v)=>s+v.totalPaid,0),totalCommitted:pos.reduce((s,p)=>s+p.amount,0)+spend.reduce((s,v)=>s+(v.totalCommitted??0),0),invoiceCount:invoices.length,poCount:pos.length}}
 calculateSavingsVerification(r:FinanceReconciliation){const pct=Math.abs(r.variancePercent??variance(r.verifiedSavings,r.expectedSavings).variancePercent); const confidence=r.status==='VERIFIED'&&r.evidenceRefs.length>0&&pct<=10?'HIGH':(r.status==='PARTIAL'||r.evidenceRefs.length>0?'MEDIUM':'LOW'); return {...variance(r.verifiedSavings,r.expectedSavings),confidence}}
 async summariseCostCentreFinancialPosition(t:string,costCentreId:string){const costCentre=await this.repo.getCostCentre(t,costCentreId); const budgets=await this.repo.listBudgets(t,{costCentreId}); const invoices=await this.repo.listInvoices(t,{costCentreId}); const purchaseOrders=await this.repo.listPurchaseOrders(t,{costCentreId}); return {tenantId:t,costCentreId,costCentre,budgetCount:budgets.length,invoiceCount:invoices.length,poCount:purchaseOrders.length,totalBudget:budgets.reduce((s,b)=>s+b.annualBudget,0),consumedBudget:budgets.reduce((s,b)=>s+b.consumedBudget,0),invoiceSpend:invoices.reduce((s,i)=>s+i.amount,0),committedSpend:purchaseOrders.reduce((s,p)=>s+p.amount,0)}}
 async summariseVendorFinancialPosition(t:string,vendorId:string){const position=await this.calculateVendorSpendPosition(t,vendorId); const reconciliations=await this.repo.listReconciliations(t,{vendorId}); return {...position,reconciliationCount:reconciliations.length,verifiedSavings:reconciliations.reduce((s,r)=>s+r.verifiedSavings,0)}}
 async summariseTenantFinancialTruth(t:string){const costCentres=await this.repo.listCostCentres(t); const budgets=await this.repo.listBudgets(t); const invoices=await this.repo.listInvoices(t); const pos=await this.repo.listPurchaseOrders(t); const recs=await this.repo.listReconciliations(t); return {tenantId:t,costCentreCount:costCentres.length,budgetCount:budgets.length,invoiceCount:invoices.length,poCount:pos.length,reconciliationCount:recs.length,totalBudget:budgets.reduce((s,b)=>s+b.annualBudget,0),totalInvoiced:invoices.reduce((s,i)=>s+i.amount,0),totalCommitted:pos.reduce((s,p)=>s+p.amount,0),verifiedSavings:recs.reduce((s,r)=>s+r.verifiedSavings,0),highConfidenceReconciliationCount:recs.filter(r=>r.confidence==='HIGH').length}}
}
export const financialTruthAuthorityService=new FinancialTruthAuthorityService();
