export const FINANCIAL_TRUTH_COLLECTIONS=['FINANCIAL_TRUTH_VENDOR_SPEND','FINANCIAL_TRUTH_INVOICES','FINANCIAL_TRUTH_PURCHASE_ORDERS','FINANCIAL_TRUTH_BUDGETS','FINANCIAL_TRUTH_COST_CENTRES','FINANCIAL_TRUTH_RECONCILIATIONS'] as const;
export type FinancialTruthCollection=(typeof FINANCIAL_TRUTH_COLLECTIONS)[number]; export type Confidence='LOW'|'MEDIUM'|'HIGH';
export interface FinancialCostCentre{ id:string;tenantId:string;code:string;name:string;departmentId?:string;ownerUserId?:string;executiveOwnerId?:string;currency:string;annualBudget?:number;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface FinancialBudget{ id:string;tenantId:string;costCentreId:string;departmentId?:string;fiscalYear:string;annualBudget:number;consumedBudget:number;remainingBudget:number;currency:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface FinancialPurchaseOrder{ id:string;tenantId:string;poNumber:string;vendorId:string;contractId?:string;entitlementId?:string;costCentreId?:string;ownerUserId?:string;amount:number;currency:string;status:'DRAFT'|'APPROVED'|'PARTIALLY_INVOICED'|'INVOICED'|'CLOSED'|'CANCELLED';issueDate?:string;expiryDate?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface FinancialInvoice{ id:string;tenantId:string;invoiceNumber:string;vendorId:string;contractId?:string;entitlementId?:string;purchaseOrderId?:string;costCentreId?:string;invoiceDate:string;dueDate?:string;paidDate?:string;amount:number;taxAmount?:number;currency:string;status:'RECEIVED'|'APPROVED'|'PAID'|'OVERDUE'|'DISPUTED'|'VOID';source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface FinancialVendorSpend{ id:string;tenantId:string;vendorId:string;fiscalPeriod:string;fiscalYear:string;totalInvoiced:number;totalPaid:number;totalCommitted?:number;currency:string;invoiceIds:string[];purchaseOrderIds:string[];source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface FinanceReconciliation{ id:string;tenantId:string;recommendationId?:string;actionId?:string;outcomeId?:string;vendorId?:string;contractId?:string;entitlementId?:string;costCentreId?:string;fiscalPeriod?:string;projectedSavings:number;expectedSavings:number;actualSpendBefore?:number;actualSpendAfter?:number;verifiedSavings:number;varianceAmount:number;variancePercent?:number;confidence:Confidence;status:'PENDING'|'PARTIAL'|'VERIFIED'|'DISPUTED'|'REJECTED';evidenceRefs:string[];source:string;createdAt:string;updatedAt:string; }
export interface PersistenceStore<T extends {id:string;tenantId:string}>{ upsert(v:T):Promise<T>; get(tenantId:string,id:string):Promise<T|undefined>; list(tenantId:string,filters?:Record<string,unknown>):Promise<T[]>; deleteTenant(tenantId:string):Promise<void>; size():Promise<number>; }
