import { createPersistenceStore, MemoryPersistenceStore } from './financial-truth-persistence';
import type { FinanceReconciliation, FinancialBudget, FinancialCostCentre, FinancialInvoice, FinancialPurchaseOrder, FinancialVendorSpend, PersistenceStore } from './financial-truth-types';
const validDate=(s?:string)=>!s||!Number.isNaN(Date.parse(s)); const nonNeg=(n?:number)=>n===undefined||n>=0; const same=(a:number,b:number)=>Math.abs(a-b)<0.01;
function base(o:any){if(!o?.tenantId||!o?.id)throw new Error('tenantId and id required'); if(!Array.isArray(o.evidenceRefs))throw new Error('evidenceRefs required'); if(!validDate(o.createdAt)||!validDate(o.updatedAt))throw new Error('invalid timestamp')}
function dates(...d:(string|undefined)[]){if(!d.every(validDate))throw new Error('invalid date')}
function amounts(...n:(number|undefined)[]){if(!n.every(nonNeg))throw new Error('negative financial amount rejected')}
export interface FinancialTruthAuthorityStores{costCentres:PersistenceStore<FinancialCostCentre>;budgets:PersistenceStore<FinancialBudget>;purchaseOrders:PersistenceStore<FinancialPurchaseOrder>;invoices:PersistenceStore<FinancialInvoice>;vendorSpend:PersistenceStore<FinancialVendorSpend>;reconciliations:PersistenceStore<FinanceReconciliation>}
export const createFinancialTruthAuthorityStores=():FinancialTruthAuthorityStores=>({costCentres:createPersistenceStore('FINANCIAL_TRUTH_COST_CENTRES'),budgets:createPersistenceStore('FINANCIAL_TRUTH_BUDGETS'),purchaseOrders:createPersistenceStore('FINANCIAL_TRUTH_PURCHASE_ORDERS'),invoices:createPersistenceStore('FINANCIAL_TRUTH_INVOICES'),vendorSpend:createPersistenceStore('FINANCIAL_TRUTH_VENDOR_SPEND'),reconciliations:createPersistenceStore('FINANCIAL_TRUTH_RECONCILIATIONS')});
export const createInMemoryFinancialTruthAuthorityStores=():FinancialTruthAuthorityStores=>({costCentres:new MemoryPersistenceStore('FINANCIAL_TRUTH_COST_CENTRES'),budgets:new MemoryPersistenceStore('FINANCIAL_TRUTH_BUDGETS'),purchaseOrders:new MemoryPersistenceStore('FINANCIAL_TRUTH_PURCHASE_ORDERS'),invoices:new MemoryPersistenceStore('FINANCIAL_TRUTH_INVOICES'),vendorSpend:new MemoryPersistenceStore('FINANCIAL_TRUTH_VENDOR_SPEND'),reconciliations:new MemoryPersistenceStore('FINANCIAL_TRUTH_RECONCILIATIONS')});
export class FinancialTruthAuthorityRepository{constructor(private readonly stores:FinancialTruthAuthorityStores=createFinancialTruthAuthorityStores()){} async collectionStatus(){return {FINANCIAL_TRUTH_VENDOR_SPEND:await this.stores.vendorSpend.size(),FINANCIAL_TRUTH_INVOICES:await this.stores.invoices.size(),FINANCIAL_TRUTH_PURCHASE_ORDERS:await this.stores.purchaseOrders.size(),FINANCIAL_TRUTH_BUDGETS:await this.stores.budgets.size(),FINANCIAL_TRUTH_COST_CENTRES:await this.stores.costCentres.size(),FINANCIAL_TRUTH_RECONCILIATIONS:await this.stores.reconciliations.size()}}
 async upsertCostCentre(v:FinancialCostCentre){base(v);amounts(v.annualBudget);return this.stores.costCentres.upsert(v)} async getCostCentre(t:string,id:string){return this.stores.costCentres.get(t,id)} async listCostCentres(t:string,f={}){return this.stores.costCentres.list(t,f)}
 async upsertBudget(v:FinancialBudget){base(v);amounts(v.annualBudget,v.consumedBudget,v.remainingBudget); if(!same(v.annualBudget-v.consumedBudget,v.remainingBudget))throw new Error('invalid budget math'); return this.stores.budgets.upsert(v)} async getBudget(t:string,id:string){return this.stores.budgets.get(t,id)} async listBudgets(t:string,f={}){return this.stores.budgets.list(t,f)}
 async upsertPurchaseOrder(v:FinancialPurchaseOrder){base(v);dates(v.issueDate,v.expiryDate);amounts(v.amount);return this.stores.purchaseOrders.upsert(v)} async getPurchaseOrder(t:string,id:string){return this.stores.purchaseOrders.get(t,id)} async listPurchaseOrders(t:string,f={}){return this.stores.purchaseOrders.list(t,f)}
 async upsertInvoice(v:FinancialInvoice){base(v);dates(v.invoiceDate,v.dueDate,v.paidDate);amounts(v.amount,v.taxAmount);return this.stores.invoices.upsert(v)} async getInvoice(t:string,id:string){return this.stores.invoices.get(t,id)} async listInvoices(t:string,f={}){return this.stores.invoices.list(t,f)}
 async upsertVendorSpend(v:FinancialVendorSpend){base(v);amounts(v.totalInvoiced,v.totalPaid,v.totalCommitted);return this.stores.vendorSpend.upsert(v)} async getVendorSpend(t:string,id:string){return this.stores.vendorSpend.get(t,id)} async listVendorSpend(t:string,f={}){return this.stores.vendorSpend.list(t,f)}
 async upsertReconciliation(v:FinanceReconciliation){base(v);amounts(v.projectedSavings,v.expectedSavings,v.actualSpendBefore,v.actualSpendAfter,v.verifiedSavings); if(!same(v.verifiedSavings-v.expectedSavings,v.varianceAmount))throw new Error('invalid reconciliation variance math'); return this.stores.reconciliations.upsert(v)} async getReconciliation(t:string,id:string){return this.stores.reconciliations.get(t,id)} async listReconciliations(t:string,f={}){return this.stores.reconciliations.list(t,f)}
 async deleteTenantFinancialData(t:string){await Promise.all([this.stores.costCentres.deleteTenant(t),this.stores.budgets.deleteTenant(t),this.stores.purchaseOrders.deleteTenant(t),this.stores.invoices.deleteTenant(t),this.stores.vendorSpend.deleteTenant(t),this.stores.reconciliations.deleteTenant(t)])}}
export const financialTruthAuthorityRepository=new FinancialTruthAuthorityRepository();
