export type EvidenceStatus='COLLECTED'|'VALIDATED'|'REDACTED'|'EXPIRED'|'REVOKED'|'REJECTED'|'MISSING'|'FAILED';
export type EvidenceType='CONNECTOR_CONFIGURATION'|'AUTHORIZATION'|'PERMISSION_VALIDATION'|'CAPABILITY_DISCOVERY'|'RAW_SNAPSHOT'|'NORMALISATION_RESULT'|'VALIDATION_RESULT'|'REJECTION_REASON'|'DRY_RUN_SUMMARY'|'SYNC_SUMMARY'|'GRAPH_MAPPING'|'COMMERCIAL_RECORD'|'FINANCIAL_RECORD'|'OWNERSHIP_RECORD'|'OUTCOME_ATTRIBUTION'|'VALUE_LEDGER'|'FINANCE_RECONCILIATION'|'PORTFOLIO_RECORD'|'RISK_RECORD'|'RECOMMENDATION'|'APPROVAL'|'GOVERNED_ACTION'|'EXECUTION'|'OUTCOME_VERIFICATION'|'AUDIT_CHECK'|'WORKSPACE_SUMMARY'|'MANUAL_UPLOAD'|'EXTERNAL_DOCUMENT'|'VALUE_SIGNAL'|'VALUE_ATTRIBUTION'|'OTHER';
export type SourceSystem='M365'|'ENTRA_ID'|'FLEXERA'|'SERVICENOW'|'ERP'|'AP'|'PROCUREMENT'|'HRIS'|'AI_PROVIDER'|'MANUAL_UPLOAD'|'CERTEN'|'DEMO'|'UNKNOWN';
export type TargetType='CONNECTOR'|'VENDOR'|'CONTRACT'|'ENTITLEMENT'|'RENEWAL'|'INVOICE'|'PURCHASE_ORDER'|'COST_CENTRE'|'USER'|'DEPARTMENT'|'APPLICATION'|'PORTFOLIO_ASSET'|'PORTFOLIO_VENDOR'|'PORTFOLIO_PRODUCT'|'PORTFOLIO_APPLICATION'|'RECOMMENDATION'|'APPROVAL'|'GOVERNED_ACTION'|'EXECUTION'|'OUTCOME'|'FINANCE_RECONCILIATION'|'VALUE_LEDGER'|'RISK'|'AUDIT'|'WORKSPACE'|'GRAPH'|'TENANT'|'INVESTMENT'|'BUSINESS_CAPABILITY'|'VALUE_SIGNAL'|'VALUE_ATTRIBUTION'|'OTHER';
export interface EvidenceRecord{id:string;tenantId:string;evidenceRef:string;title:string;description?:string;evidenceType:EvidenceType;sourceSystem:SourceSystem;sourceObjectType?:string;sourceObjectId?:string;targetType:TargetType;targetId:string;status:EvidenceStatus;classification:'PUBLIC'|'INTERNAL'|'CONFIDENTIAL'|'RESTRICTED'|'SECRET';trustLevel:'LOW'|'MEDIUM'|'HIGH'|'CERTIFIED';artifactIds:string[];linkedEvidenceRefs:string[];hash?:string;hashAlgorithm?:'SHA256'|'SHA512'|'NONE';redactionRequired:boolean;redactionStatus:'NOT_REQUIRED'|'PENDING'|'REDACTED'|'FAILED';retentionPolicyId?:string;expiresAt?:string;collectedAt:string;validatedAt?:string;createdBy?:string;createdAt:string;updatedAt:string;metadata:Record<string,unknown>}
export interface EvidenceArtifact{id:string;tenantId:string;evidenceRef:string;artifactType:'JSON'|'CSV'|'PDF'|'TEXT'|'SCREENSHOT'|'HASH_ONLY'|'EXTERNAL_URI'|'STORAGE_REF'|'SUMMARY';storageRef?:string;externalUri?:string;contentHash?:string;hashAlgorithm?:'SHA256'|'SHA512'|'NONE';sizeBytes?:number;mimeType?:string;redacted:boolean;redactedArtifactId?:string;createdAt:string;metadata:Record<string,unknown>}
export interface EvidenceLink{id:string;tenantId:string;evidenceRef:string;targetType:TargetType;targetId:string;relationshipType:'SUPPORTS'|'PROVES'|'DERIVED_FROM'|'VALIDATES'|'REJECTS'|'SUPERSEDES'|'AUDITS'|'EXPORTS';confidence:number;createdAt:string;metadata:Record<string,unknown>}
export interface EvidenceProvenanceEvent{id:string;tenantId:string;evidenceRef:string;eventType:'COLLECTED'|'VALIDATED'|'LINKED'|'HASHED'|'REDACTED'|'EXPORTED'|'ACCESSED'|'EXPIRED'|'REVOKED'|'SUPERSEDED'|'FAILED';actorType:'SYSTEM'|'USER'|'CONNECTOR'|'API'|'AUDIT';actorId?:string;sourceSystem:SourceSystem;occurredAt:string;details:Record<string,unknown>}
export interface EvidenceIntegrityCheck{id:string;tenantId:string;evidenceRef:string;status:'PASS'|'WARN'|'FAIL'|'NOT_APPLICABLE';checkType:'HASH_MATCH'|'ARTIFACT_PRESENT'|'LINK_VALID'|'REDACTION_COMPLETE'|'RETENTION_VALID'|'PROVENANCE_COMPLETE';checkedAt:string;reason?:string;expectedHash?:string;actualHash?:string;metadata:Record<string,unknown>}
export interface EvidenceLifecycleEvent{id:string;tenantId:string;evidenceRef:string;fromStatus?:EvidenceStatus;toStatus:EvidenceStatus;transitionReason:string;actorType:'SYSTEM'|'USER'|'CONNECTOR'|'API'|'AUDIT';actorId?:string;occurredAt:string;metadata:Record<string,unknown>}
export interface EvidenceRetentionPolicy{id:string;tenantId:string;name:string;evidenceTypes:EvidenceType[];classification:EvidenceRecord['classification']|'ANY';retentionDays:number;actionOnExpiry:'EXPIRE'|'REVIEW'|'ARCHIVE'|'DELETE_METADATA_ONLY';legalHold:boolean;source:string;createdAt:string;updatedAt:string}
export interface EvidenceRedactionRecord{id:string;tenantId:string;evidenceRef:string;status:'PENDING'|'REDACTED'|'FAILED'|'NOT_REQUIRED';redactionTypes:Array<'TOKEN'|'SECRET'|'PASSWORD'|'EMAIL'|'PHONE'|'PERSON_NAME'|'FINANCIAL_ACCOUNT'|'RAW_PAYLOAD'|'CUSTOM'>;redactedFields:string[];reason?:string;redactedArtifactId?:string;createdAt:string;updatedAt:string}
export interface EvidenceExportMarker{id:string;tenantId:string;evidenceRef:string;exportType:'EXECUTIVE_PROOF_PACK'|'AUDIT_EXPORT'|'BOARD_PACK'|'CFO_PACK'|'CIO_PACK'|'PROCUREMENT_PACK'|'JSON'|'CSV';exportedAt:string;exportedBy?:string;destination?:string;metadata:Record<string,unknown>}
export interface EvidenceRegistrySnapshot{id:string;tenantId:string;generatedAt:string;evidenceCount:number;validatedCount:number;missingCount:number;failedCount:number;expiredCount:number;redactionPendingCount:number;restrictedCount:number;evidenceCoverageScore:number;integrityScore:number;provenanceScore:number;targetCoverage:Record<string,number>;sourceCoverage:Record<string,number>;typeCoverage:Record<string,number>;criticalGaps:Array<{targetType:string;targetId:string;reason:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL'}>;readiness:'READY'|'PARTIAL'|'MISSING_DATA'|'BLOCKED'|'DEMO';createdAt:string}
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(t:string,id:string):Promise<T|undefined>;list(t:string,f?:Record<string,unknown>):Promise<T[]>;deleteTenant(t:string):Promise<void>;size():Promise<number>}
export type EvidenceCollection='EVIDENCE_REGISTRY_RECORDS'|'EVIDENCE_REGISTRY_ARTIFACTS'|'EVIDENCE_REGISTRY_LINKS'|'EVIDENCE_REGISTRY_PROVENANCE_EVENTS'|'EVIDENCE_REGISTRY_INTEGRITY_CHECKS'|'EVIDENCE_REGISTRY_LIFECYCLE_EVENTS'|'EVIDENCE_REGISTRY_RETENTION_POLICIES'|'EVIDENCE_REGISTRY_REDACTION_RECORDS'|'EVIDENCE_REGISTRY_EXPORT_MARKERS'|'EVIDENCE_REGISTRY_SNAPSHOTS';
