import type { AuthRole } from "../auth/auth-context";

export type Capability =
  | "READ_CONNECTORS"
  | "RUN_READ_ONLY_SYNC"
  | "READ_RECOMMENDATIONS"
  | "REVIEW_RECOMMENDATIONS"
  | "APPROVE_ACTIONS"
  | "RESOLVE_FINDINGS"
  | "SUPPRESS_FINDINGS"
  | "CREATE_SIMULATIONS"
  | "READ_OUTCOMES"
  | "MANAGE_POLICIES"
  | "READ_GRAPH"
  | "REBUILD_GRAPH"
  | "READ_TELEMETRY"
  | "READ_AUDIT"
  | "MANAGE_TENANT_SETTINGS";

export type SecurityRole =
  | "TENANT_ADMIN"
  | "GOVERNANCE_ADMIN"
  | "APPROVER"
  | "OPERATOR"
  | "AUDITOR"
  | "READ_ONLY"
  | "SYSTEM_ADMIN";

const roleAliases: Record<AuthRole, SecurityRole> = {
  PLATFORM_ADMIN: "SYSTEM_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  APPROVER: "APPROVER",
  OPERATOR: "OPERATOR",
  VIEWER: "READ_ONLY",
};

const roleCapabilities: Record<SecurityRole, Capability[]> = {
  SYSTEM_ADMIN: ["READ_CONNECTORS","RUN_READ_ONLY_SYNC","READ_RECOMMENDATIONS","REVIEW_RECOMMENDATIONS","APPROVE_ACTIONS","RESOLVE_FINDINGS","SUPPRESS_FINDINGS","CREATE_SIMULATIONS","READ_OUTCOMES","MANAGE_POLICIES","READ_GRAPH","REBUILD_GRAPH","READ_TELEMETRY","READ_AUDIT","MANAGE_TENANT_SETTINGS"],
  TENANT_ADMIN: ["READ_CONNECTORS","RUN_READ_ONLY_SYNC","READ_RECOMMENDATIONS","REVIEW_RECOMMENDATIONS","APPROVE_ACTIONS","RESOLVE_FINDINGS","SUPPRESS_FINDINGS","CREATE_SIMULATIONS","READ_OUTCOMES","MANAGE_POLICIES","READ_GRAPH","REBUILD_GRAPH","READ_TELEMETRY","READ_AUDIT","MANAGE_TENANT_SETTINGS"],
  GOVERNANCE_ADMIN: ["READ_RECOMMENDATIONS","REVIEW_RECOMMENDATIONS","APPROVE_ACTIONS","RESOLVE_FINDINGS","SUPPRESS_FINDINGS","MANAGE_POLICIES","READ_AUDIT","READ_TELEMETRY"],
  APPROVER: ["READ_RECOMMENDATIONS","REVIEW_RECOMMENDATIONS","APPROVE_ACTIONS","READ_OUTCOMES","READ_GRAPH","READ_TELEMETRY"],
  OPERATOR: ["READ_CONNECTORS","RUN_READ_ONLY_SYNC","READ_RECOMMENDATIONS","REVIEW_RECOMMENDATIONS","RESOLVE_FINDINGS","CREATE_SIMULATIONS","READ_OUTCOMES","READ_GRAPH","READ_TELEMETRY"],
  AUDITOR: ["READ_CONNECTORS","READ_RECOMMENDATIONS","READ_OUTCOMES","READ_GRAPH","READ_TELEMETRY","READ_AUDIT"],
  READ_ONLY: ["READ_CONNECTORS","READ_RECOMMENDATIONS","READ_OUTCOMES","READ_GRAPH","READ_TELEMETRY"],
};

export class AuthorizationService {
  normalizeRole(role: AuthRole | SecurityRole): SecurityRole {
    return (role in roleAliases ? roleAliases[role as AuthRole] : role) as SecurityRole;
  }
  hasCapability(role: AuthRole | SecurityRole, capability: Capability): boolean {
    const normalized = this.normalizeRole(role);
    return roleCapabilities[normalized].includes(capability);
  }
  requireCapability(role: AuthRole | SecurityRole, capability: Capability): void {
    if (!this.hasCapability(role, capability)) throw new Error("CAPABILITY_FORBIDDEN");
  }
}

export const authorizationService = new AuthorizationService();
