import { OperationalGraphService } from '../operational-graph/service'; import { platformEventService } from '../events/platform-event-service';
import { technologyCommercialAuthorityRepository, TechnologyCommercialAuthorityRepository } from './commercial-authority-repository';
import type { CommercialCommitment, CommercialExposure, CommercialRenewal, CommercialVendor, TechnologyContract, TechnologyEntitlement } from './commercial-authority-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export class TechnologyCommercialAuthorityService{
 constructor(private readonly repo:TechnologyCommercialAuthorityRepository=technologyCommercialAuthorityRepository, private readonly graph:any=new OperationalGraphService()){}
 private stamp<T extends {id?:string;createdAt?:string;updatedAt?:string;source?:string;evidenceRefs?:string[]}>(p:string,o:T){const t=now(); return {...o,id:o.id??id(p),source:o.source??'technology-commercial-authority',evidenceRefs:o.evidenceRefs??[],createdAt:o.createdAt??t,updatedAt:t} as any}
 private async link(tenantId:string, entityType:string, entityId:string, name:string, edges:{from:string;to:string;type:string}[]=[]){try{await this.graph.createNode({tenantId,entityType,canonicalName:name,canonicalKey:entityId,confidenceScore:1,evidence:[{sourceSystem:'technology-commercial-authority',sourceReferenceId:entityId,observedAt:now()}],metadata:{commercialAuthority:true}}); for(const e of edges) await this.graph.createEdge({tenantId,fromEntityId:e.from,toEntityId:e.to,relationshipType:e.type,confidenceScore:1,evidence:[{sourceSystem:'technology-commercial-authority',sourceReferenceId:entityId,observedAt:now()}]});}catch(error){await platformEventService.recordSystemEvent(tenantId,'TECH_COMMERCIAL_GRAPH_LINK_FAILED',{severity:'WARNING',entityType,entityId,metadata:{error:String(error)}}).catch(()=>undefined)}}
 async createVendor(input:Partial<CommercialVendor>&{tenantId:string;name:string;category:CommercialVendor['category'];currency:string;riskLevel:CommercialVendor['riskLevel']}){const v=await this.repo.upsertVendor(this.stamp('vendor',input)); await this.link(v.tenantId,'VENDOR',v.id,v.name); return v}
 async createContract(input:Partial<TechnologyContract>&{tenantId:string;vendorId:string;name:string;status:TechnologyContract['status'];startDate:string;endDate:string;autoRenewal:boolean;currency:string;auditRights:boolean;trueUpRights:boolean}){const v=await this.repo.upsertContract(this.stamp('contract',input)); await this.link(v.tenantId,'CONTRACT',v.id,v.name,[{from:v.vendorId,to:v.id,type:'HAS_CONTRACT'}]); return v}
 async createEntitlement(input:Partial<TechnologyEntitlement>&{tenantId:string;vendorId:string;productName:string;entitlementType:TechnologyEntitlement['entitlementType'];totalQuantity:number;currency:string}){const v=await this.repo.upsertEntitlement(this.stamp('entitlement',input)); await this.link(v.tenantId,'ENTITLEMENT',v.id,v.productName,v.contractId?[{from:v.contractId,to:v.id,type:'HAS_ENTITLEMENT'},{from:v.id,to:v.contractId,type:'GOVERNED_BY'}]:[]); return v}
 async createCommitment(input:Partial<CommercialCommitment>&{tenantId:string;vendorId:string;contractId:string;commitmentType:CommercialCommitment['commitmentType'];committedValue:number;consumedValue:number;startDate:string;endDate:string}){const pos=this.calculateCommitmentPosition(input as CommercialCommitment); const v=await this.repo.upsertCommitment(this.stamp('commitment',{...input,...pos})); if(v.blocksSavings&&v.entitlementId) await this.link(v.tenantId,'CONTRACT',v.contractId,v.contractId,[{from:v.id,to:v.entitlementId,type:'BLOCKS_SAVINGS'}]); return v}
 async createRenewal(input:Partial<CommercialRenewal>&{tenantId:string;vendorId:string;contractId:string;renewalDate:string;currentAnnualSpend:number;negotiationLeverage:CommercialRenewal['negotiationLeverage'];readinessScore:number;status:CommercialRenewal['status']}){const v=await this.repo.upsertRenewal(this.stamp('renewal',input)); await this.link(v.tenantId,'RENEWAL',v.id,v.id,[{from:v.contractId,to:v.id,type:'HAS_RENEWAL'},{from:v.id,to:v.contractId,type:'CREATES_LEVERAGE'}]); return v}
 async createExposure(input:Partial<CommercialExposure>&{tenantId:string;vendorId:string;exposureType:CommercialExposure['exposureType'];severity:CommercialExposure['severity'];currency:string;description:string}){const v=await this.repo.upsertExposure(this.stamp('risk',input)); const edges=[] as any[]; if(v.contractId)edges.push({from:v.contractId,to:v.id,type:'HAS_RISK'}); if(v.entitlementId)edges.push({from:v.entitlementId,to:v.id,type:'HAS_RISK'}); await this.link(v.tenantId,'RISK',v.id,v.description,edges); return v}
 calculateEntitlementUtilisation(e:TechnologyEntitlement){const used=e.consumedQuantity??e.assignedQuantity??0; return {used,available:e.availableQuantity??Math.max(0,e.totalQuantity-used),utilisationPercent:e.totalQuantity?clamp(used/e.totalQuantity*100):0}}
 calculateCommitmentPosition(c:CommercialCommitment|Partial<CommercialCommitment>){const remaining=Math.max(0,Number(c.committedValue??0)-Number(c.consumedValue??0)); return {remainingValue:remaining,blocksSavings:remaining>0||Boolean(c.blocksSavings)}}
 calculateRenewalReadiness(r:CommercialRenewal,c:TechnologyContract,ents:TechnologyEntitlement[],coms:CommercialCommitment[],exps:CommercialExposure[]){return clamp(30+(c.ownerUserId?15:0)+(ents.length?15:0)+(coms.every(x=>x.remainingValue===0)?15:0)-exps.filter(x=>['HIGH','CRITICAL'].includes(x.severity)).length*10+(r.utilisationPercent!==undefined?15:0))}
 detectBlockedSavings(_rec:any,_e:TechnologyEntitlement,_c:TechnologyContract,com?:CommercialCommitment){return Boolean(com?.blocksSavings&&com.remainingValue>0)}
 async summariseVendorCommercialPosition(t:string,vendorId:string){const vendor=await this.repo.getVendor(t,vendorId); const contracts=await this.repo.listContracts(t,{vendorId}); const entitlements=await this.repo.listEntitlements(t,{vendorId}); const renewals=await this.repo.listRenewals(t,{vendorId}); const exposures=await this.repo.listExposures(t,{vendorId}); return {tenantId:t,vendorId,vendor,totalSpend:(vendor?.annualSpend??0)+contracts.reduce((s,c)=>s+(c.committedSpend??0),0)+entitlements.reduce((s,e)=>s+(e.annualCost??0),0),contractCount:contracts.length,entitlementCount:entitlements.length,renewalCount:renewals.length,exposureCount:exposures.length,criticalExposureCount:exposures.filter(e=>e.severity==='CRITICAL').length}}
 async summariseTenantCommercialPortfolio(t:string){const vendors=await this.repo.listVendors(t); const contracts=await this.repo.listContracts(t); const entitlements=await this.repo.listEntitlements(t); const renewals=await this.repo.listRenewals(t); const exposures=await this.repo.listExposures(t); return {tenantId:t,vendorCount:vendors.length,contractCount:contracts.length,entitlementCount:entitlements.length,renewalCount:renewals.length,exposureCount:exposures.length,totalAnnualSpend:vendors.reduce((s,v)=>s+(v.annualSpend??0),0)+contracts.reduce((s,c)=>s+(c.committedSpend??0),0),highRiskVendorCount:vendors.filter(v=>['HIGH','CRITICAL'].includes(v.riskLevel)).length,criticalExposureCount:exposures.filter(e=>e.severity==='CRITICAL').length,averageRenewalReadiness:renewals.length?Math.round(renewals.reduce((s,r)=>s+r.readinessScore,0)/renewals.length):0}}
}
export const technologyCommercialAuthorityService=new TechnologyCommercialAuthorityService();
