import { createPersistenceStore, MemoryPersistenceStore } from './commercial-authority-persistence';
import type { CommercialCommitment, CommercialExposure, CommercialRenewal, CommercialVendor, PersistenceStore, TechnologyContract, TechnologyEntitlement } from './commercial-authority-types';
const validDate=(s?:string)=>!s||!Number.isNaN(Date.parse(s)); const nonNeg=(n?:number)=>n===undefined||n>=0;
function validateBase(o:any){ if(!o?.tenantId||!o?.id) throw new Error('tenantId and id required'); if(!Array.isArray(o.evidenceRefs)) throw new Error('evidenceRefs required'); if(!validDate(o.createdAt)||!validDate(o.updatedAt)) throw new Error('invalid timestamp'); }
function validateDates(...dates:(string|undefined)[]){ if(!dates.every(validDate)) throw new Error('invalid date'); }
export interface TechnologyCommercialAuthorityStores{ vendors:PersistenceStore<CommercialVendor>; contracts:PersistenceStore<TechnologyContract>; entitlements:PersistenceStore<TechnologyEntitlement>; commitments:PersistenceStore<CommercialCommitment>; renewals:PersistenceStore<CommercialRenewal>; exposures:PersistenceStore<CommercialExposure>; readinessSnapshots:PersistenceStore<any>; }
export const createTechnologyCommercialAuthorityStores=():TechnologyCommercialAuthorityStores=>({ vendors:createPersistenceStore('TECH_COMMERCIAL_VENDORS'), contracts:createPersistenceStore('TECH_COMMERCIAL_CONTRACTS'), entitlements:createPersistenceStore('TECH_COMMERCIAL_ENTITLEMENTS'), commitments:createPersistenceStore('TECH_COMMERCIAL_COMMITMENTS'), renewals:createPersistenceStore('TECH_COMMERCIAL_RENEWALS'), exposures:createPersistenceStore('TECH_COMMERCIAL_EXPOSURES'), readinessSnapshots:createPersistenceStore('TECH_COMMERCIAL_READINESS_SNAPSHOTS') });
export const createInMemoryTechnologyCommercialAuthorityStores=():TechnologyCommercialAuthorityStores=>({ vendors:new MemoryPersistenceStore('TECH_COMMERCIAL_VENDORS'), contracts:new MemoryPersistenceStore('TECH_COMMERCIAL_CONTRACTS'), entitlements:new MemoryPersistenceStore('TECH_COMMERCIAL_ENTITLEMENTS'), commitments:new MemoryPersistenceStore('TECH_COMMERCIAL_COMMITMENTS'), renewals:new MemoryPersistenceStore('TECH_COMMERCIAL_RENEWALS'), exposures:new MemoryPersistenceStore('TECH_COMMERCIAL_EXPOSURES'), readinessSnapshots:new MemoryPersistenceStore('TECH_COMMERCIAL_READINESS_SNAPSHOTS') });
export class TechnologyCommercialAuthorityRepository{
  constructor(private readonly stores:TechnologyCommercialAuthorityStores=createTechnologyCommercialAuthorityStores()){}
  async collectionStatus(){return {TECH_COMMERCIAL_VENDORS:await this.stores.vendors.size(),TECH_COMMERCIAL_CONTRACTS:await this.stores.contracts.size(),TECH_COMMERCIAL_ENTITLEMENTS:await this.stores.entitlements.size(),TECH_COMMERCIAL_COMMITMENTS:await this.stores.commitments.size(),TECH_COMMERCIAL_RENEWALS:await this.stores.renewals.size(),TECH_COMMERCIAL_EXPOSURES:await this.stores.exposures.size(),TECH_COMMERCIAL_READINESS_SNAPSHOTS:await this.stores.readinessSnapshots.size()}}
  async upsertVendor(v:CommercialVendor){validateBase(v); if(!nonNeg(v.annualSpend)) throw new Error('negative spend rejected'); return this.stores.vendors.upsert(v)} async getVendor(t:string,id:string){return this.stores.vendors.get(t,id)} async listVendors(t:string,f={}){return this.stores.vendors.list(t,f)}
  async upsertContract(v:TechnologyContract){validateBase(v); validateDates(v.startDate,v.endDate,v.renewalDate); if(!nonNeg(v.minimumCommitment)||!nonNeg(v.committedSpend)) throw new Error('negative spend rejected'); return this.stores.contracts.upsert(v)} async getContract(t:string,id:string){return this.stores.contracts.get(t,id)} async listContracts(t:string,f={}){return this.stores.contracts.list(t,f)}
  async upsertEntitlement(v:TechnologyEntitlement){validateBase(v); for(const n of [v.totalQuantity,v.assignedQuantity,v.consumedQuantity,v.availableQuantity,v.unitCost,v.annualCost]) if(!nonNeg(n)) throw new Error('negative quantity or spend rejected'); return this.stores.entitlements.upsert(v)} async getEntitlement(t:string,id:string){return this.stores.entitlements.get(t,id)} async listEntitlements(t:string,f={}){return this.stores.entitlements.list(t,f)}
  async upsertCommitment(v:CommercialCommitment){validateBase(v); validateDates(v.startDate,v.endDate); for(const n of [v.committedValue,v.consumedValue,v.remainingValue]) if(!nonNeg(n)) throw new Error('negative commitment rejected'); return this.stores.commitments.upsert(v)} async getCommitment(t:string,id:string){return this.stores.commitments.get(t,id)} async listCommitments(t:string,f={}){return this.stores.commitments.list(t,f)}
  async upsertRenewal(v:CommercialRenewal){validateBase(v); validateDates(v.renewalDate,v.noticeDeadline); if(!nonNeg(v.currentAnnualSpend)||!nonNeg(v.reclaimableValue)||!nonNeg(v.savingsPotential)) throw new Error('negative spend rejected'); if(v.readinessScore<0||v.readinessScore>100) throw new Error('readinessScore must be 0-100'); return this.stores.renewals.upsert(v)} async getRenewal(t:string,id:string){return this.stores.renewals.get(t,id)} async listRenewals(t:string,f={}){return this.stores.renewals.list(t,f)}
  async upsertExposure(v:CommercialExposure){validateBase(v); if(!nonNeg(v.estimatedValue)) throw new Error('negative spend rejected'); return this.stores.exposures.upsert(v)} async getExposure(t:string,id:string){return this.stores.exposures.get(t,id)} async listExposures(t:string,f={}){return this.stores.exposures.list(t,f)}
  async deleteTenantCommercialData(t:string){await Promise.all([this.stores.vendors.deleteTenant(t),this.stores.contracts.deleteTenant(t),this.stores.entitlements.deleteTenant(t),this.stores.commitments.deleteTenant(t),this.stores.renewals.deleteTenant(t),this.stores.exposures.deleteTenant(t),this.stores.readinessSnapshots.deleteTenant(t)])}
}
export const technologyCommercialAuthorityRepository=new TechnologyCommercialAuthorityRepository();
