export const TECHNOLOGY_COMMERCIAL_AUTHORITY_COLLECTIONS = [
  'TECH_COMMERCIAL_VENDORS','TECH_COMMERCIAL_CONTRACTS','TECH_COMMERCIAL_ENTITLEMENTS','TECH_COMMERCIAL_COMMITMENTS','TECH_COMMERCIAL_RENEWALS','TECH_COMMERCIAL_EXPOSURES','TECH_COMMERCIAL_READINESS_SNAPSHOTS',
] as const;
export type CommercialCategory='SAAS'|'CLOUD'|'AI'|'DATA'|'INFRASTRUCTURE'|'SECURITY'|'OTHER'; export type RiskLevel='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export interface CommercialVendor{ id:string;tenantId:string;name:string;category:CommercialCategory;website?:string;ownerUserId?:string;departmentId?:string;costCentreId?:string;annualSpend?:number;currency:string;riskLevel:RiskLevel;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface TechnologyContract{ id:string;tenantId:string;vendorId:string;contractNumber?:string;name:string;status:'DRAFT'|'ACTIVE'|'EXPIRED'|'TERMINATED'|'PENDING_RENEWAL';startDate:string;endDate:string;renewalDate?:string;noticePeriodDays?:number;autoRenewal:boolean;minimumCommitment?:number;committedSpend?:number;currency:string;auditRights:boolean;trueUpRights:boolean;terminationRights?:string;priceEscalatorPercent?:number;ownerUserId?:string;procurementOwnerId?:string;legalOwnerId?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface TechnologyEntitlement{ id:string;tenantId:string;vendorId:string;contractId?:string;productName:string;entitlementType:'SEAT'|'TOKEN'|'CREDIT'|'CONSUMPTION'|'CAPACITY'|'FEATURE'|'SUPPORT';totalQuantity:number;assignedQuantity?:number;consumedQuantity?:number;availableQuantity?:number;unitCost?:number;annualCost?:number;currency:string;renewalId?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface CommercialCommitment{ id:string;tenantId:string;vendorId:string;contractId:string;entitlementId?:string;commitmentType:'MINIMUM_SPEND'|'MINIMUM_SEATS'|'CONSUMPTION_COMMIT'|'TERM_COMMIT'|'EA_COMMIT';committedValue:number;consumedValue:number;remainingValue:number;currency?:string;startDate:string;endDate:string;blocksSavings:boolean;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface CommercialRenewal{ id:string;tenantId:string;vendorId:string;contractId:string;renewalDate:string;noticeDeadline?:string;currentAnnualSpend:number;utilisationPercent?:number;reclaimableValue?:number;negotiationLeverage:RiskLevel;savingsPotential?:number;readinessScore:number;status:'NOT_STARTED'|'DISCOVERY'|'ANALYSIS'|'NEGOTIATION'|'APPROVED'|'COMPLETED'|'MISSED';source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface CommercialExposure{ id:string;tenantId:string;vendorId:string;contractId?:string;entitlementId?:string;exposureType:'AUDIT'|'TRUE_UP'|'OVER_CONSUMPTION'|'UNDER_UTILISATION'|'AUTO_RENEWAL'|'PRICE_ESCALATION'|'COMMITMENT_SHORTFALL';severity:RiskLevel;estimatedValue?:number;currency:string;description:string;recommendedAction?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string; }
export interface PersistenceStore<T extends {id:string;tenantId:string}>{ upsert(v:T):Promise<T>; get(tenantId:string,id:string):Promise<T|undefined>; list(tenantId:string,filters?:Record<string,unknown>):Promise<T[]>; deleteTenant(tenantId:string):Promise<void>; size():Promise<number>; }
