import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import express from 'express';
import { AuthorityQueryService, answerHeadlessQuestion, authorityQueryService } from '../lib/authority-query/authority-query-service';
import authorityQueryRouter from '../routes/authority-query';
function seeded(){const s=new AuthorityQueryService(); const t='tenant-a'; s.seedAuthorityRecord({tenantId:t,id:'cap-1',authority:'AI_CAPITAL_ALLOCATION',label:'Copilot expansion',verdict:'INCREASE',value:120000,confidence:.9,evidenceIds:['ev-cap'],decisionRationale:'Highest verified value per dollar.'}); s.seedAuthorityRecord({tenantId:t,id:'eco-1',authority:'AI_ECONOMICS',label:'Copilot',verdict:'EFFICIENT',value:100000,cost:25000,confidence:.88,evidenceIds:['ev-eco']}); s.seedAuthorityRecord({tenantId:t,id:'attr-1',authority:'AI_VALUE_ATTRIBUTION',label:'Copilot automation',value:64000,confidence:.77,evidenceIds:['ev-attr'],workflowIds:['wf-1']}); s.seedAuthorityRecord({tenantId:t,id:'wfv-1',authority:'WORKFLOW_VALUE',label:'Invoice triage',verdict:'VERIFIED',value:31000,confidence:.8,evidenceIds:['ev-wf'],workflowIds:['wf-invoice']}); s.seedAuthorityRecord({tenantId:t,id:'dec-1',authority:'DECISION_LINEAGE',label:'Approve Copilot rollout',verdict:'APPROVED',confidence:.86,evidenceIds:['ev-dec'],decisionRationale:'Approved after evidence showed efficiency.',approvedBy:'cfo'}); return {s,t}}
test('authority query intent classification covers supported examples',()=>{const {s}=seeded(); assert.equal(s.classifyIntent('Where should next AI dollar go?'),'AI_CAPITAL_ALLOCATION'); assert.equal(s.classifyIntent('Was Copilot economically efficient?'),'AI_ECONOMICS'); assert.equal(s.classifyIntent('What value did AI create?'),'AI_VALUE_ATTRIBUTION'); assert.equal(s.classifyIntent('Which workflow created value?'),'WORKFLOW_VALUE'); assert.equal(s.classifyIntent('Why did we decide this and who approved?'),'DECISION_LINEAGE')});
test('unknown intent returns insufficient context',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'How is the weather?',querySource:'API'}); assert.equal(out.query.queryStatus,'INSUFFICIENT_CONTEXT'); assert.equal(out.answer.answerType,'INSUFFICIENT_CONTEXT')});
test('capital allocation answer includes ranked recommendations and persistence',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'Which initiatives should get more funding?',querySource:'API'}); const p:any=out.answer.metadata.payload; assert.ok(p.rankedItems.length); assert.ok(s.getQueryById(t,out.query.id)); assert.ok(s.getAnswerByQuery(t,out.query.id)); assert.ok(s.getQuerySources(t,out.query.id).length)});
test('economics answer includes ratio and verdict',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'Was Copilot economically efficient?',querySource:'API'}); const facts=(out.answer.metadata as any).payload.facts; assert.ok(facts.some((f:any)=>f.label==='Value-to-cost ratio'&&f.value===4)); assert.ok(facts.some((f:any)=>f.label==='Economics verdict'&&f.value==='EFFICIENT'))});
test('value attribution answer includes attributed value',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'What value did AI create?',querySource:'API'}); assert.ok((out.answer.metadata as any).payload.facts.some((f:any)=>f.label==='Attributed AI value'&&f.value===64000))});
test('workflow answer includes workflow sources',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'Which workflow created value?',querySource:'API'}); assert.ok(out.sources.some(s=>s.sourceType==='WORKFLOW'))});
test('decision answer includes rationale/evidence source',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'Why did we decide to approve this?',querySource:'API'}); const p:any=out.answer.metadata.payload; assert.match(p.rankedItems[0].reason,/Approved/); assert.ok(out.sources.some(s=>s.sourceType==='EVIDENCE'))});
test('answer with no sources reduces confidence and warns',async()=>{const s=new AuthorityQueryService(); s.seedAuthorityRecord({tenantId:'t',id:'cap-empty',authority:'AI_CAPITAL_ALLOCATION',label:'No evidence item'}); const out=await s.answerQuery({tenantId:'t',queryText:'capital allocation',querySource:'API'}); const p:any=out.answer.metadata.payload; assert.ok(p.confidence<=.45); assert.ok(p.warnings.length)});
test('headless adapter returns plainText and structured answer',async()=>{authorityQueryService.seedAuthorityRecord({tenantId:'headless',id:'eco-h',authority:'AI_ECONOMICS',label:'Copilot',verdict:'EFFICIENT',value:2,cost:1,evidenceIds:['ev']}); const out=await answerHeadlessQuestion({tenantId:'headless',queryText:'ROI and economic efficiency',querySource:'API'}); assert.ok(out.plainText); assert.equal(out.structuredAnswer.intent,'AI_ECONOMICS'); assert.ok(out.sources.length)});
test('guardrail: query layer never executes or mutates actions',async()=>{const {s,t}=seeded(); const out=await s.answerQuery({tenantId:t,queryText:'stop funding and execute it now',querySource:'API'}); assert.equal(out.query.metadata.actionsExecuted,0); assert.equal(out.query.metadata.readOnly,true)});
test('API ask endpoint returns query answer and sources',async()=>{authorityQueryService.seedAuthorityRecord({tenantId:'api-t',id:'cap-api',authority:'AI_CAPITAL_ALLOCATION',label:'Retire unused model',verdict:'REDUCE',evidenceIds:['ev-api']}); const api=express(); api.use(express.json()); api.use('/api/authority-query',(req:any,_res,next)=>{req.tenantId=req.query.tenantId; next()},authorityQueryRouter); const server=api.listen(0); try{const port=(server.address() as any).port; const body=JSON.stringify({queryText:'Which AI initiatives should we stop funding?',querySource:'API'}); const res:any=await new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,path:'/api/authority-query/ask?tenantId=api-t',method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(body)}},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>resolve({status:r.statusCode,json:JSON.parse(d)}))});req.on('error',reject);req.write(body);req.end()}); assert.equal(res.status,200); assert.ok(res.json.query); assert.ok(res.json.answer); assert.ok(res.json.sources.length)}finally{server.close()}});
