import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { governedActionService } from "../lib/actions/governed-actions";
import { approvalAuthorityEngine, approveRequest, createApprovalRequest, submitApprovalRequest } from "../lib/approval-authority/approval-authority";
import { trustReadinessAuthorityService } from "../lib/trust-readiness/trust-readiness-authority";
import { createDefaultExecutionConnector } from "../lib/execution/execution-connectors";
import { governedExecutionService, type GovernedExecutionType } from "../lib/execution/governed-execution";
import { outcomeProtectionService } from "../lib/outcome-protection/outcome-protection";
import { economicOutcomeAttributionService } from "../lib/economic-outcomes/economic-outcome-attribution";
import { clearAwsArtifacts } from "../lib/connectors/aws/aws-artifacts";
import { clearAwsExecutionState, readEc2State, rollbackAwsExecution, verifyAwsExecution } from "../lib/connectors/aws/aws-execution";
import { getAwsWedgeCertification } from "../lib/connectors/aws/aws-wedge-certification";
import { clearTenantExecutionPolicies, evaluateLiveTenantExecutionGate, getTenantExecutionPolicy, setTenantExecutionPolicy } from "../lib/runtime/live-tenant-safety";

const tenantId = "tenant-aws-wedge-test";
const playbooks = [
  ["EC2 Rightsizing", "AWS_RIGHTSIZE_EC2", "aws ec2 rightsizing recommendation"],
  ["Idle Resource Shutdown", "AWS_STOP_EC2", "aws idle resource shutdown recommendation"],
  ["Savings Plans Coverage", "AWS_CREATE_SAVINGS_PLAN_REVIEW", "aws savings plan coverage recommendation"],
  ["Reserved Instance Optimisation", "AWS_CREATE_RI_REVIEW", "aws reserved instance optimisation recommendation"],
  ["Orphaned Resource Cleanup", "AWS_DELETE_EBS", "aws orphaned resource cleanup recommendation"],
] as const;

async function reset(tenant = tenantId) {
  governedExecutionService.clear(); await governedActionService.clear(); approvalAuthorityEngine.clear(); trustReadinessAuthorityService.clear(); outcomeProtectionService.clear(); economicOutcomeAttributionService.clearForTests(); clearAwsArtifacts(); clearAwsExecutionState(); clearTenantExecutionPolicies();
  return governedExecutionService.registerConnector(createDefaultExecutionConnector({ tenantId: tenant, connectorType: "AWS", executionMode: "APPROVAL_REQUIRED" }));
}
async function action(name: string, type: GovernedExecutionType, tenant = tenantId, overrides: Record<string, unknown> = {}) {
  const sourceId = `${name.toLowerCase().replace(/\s+/g, "-")}-aws-resource`;
  return governedActionService.create({ tenantId: tenant, title: name, description: `${name} governed AWS cost optimisation`, domain: "CLOUD", sourceType: "RECOMMENDATION", sourceId, status: "APPROVED", priority: "MEDIUM", readiness: "APPROVAL_REQUIRED", ownerId: "cloud-owner", approverId: "approver", trustScore: 0.93, projectedMonthlyValue: 100, projectedAnnualValue: 1200, blastRadius: "LOW", rollbackCapability: type === "AWS_DELETE_EBS" || type === "AWS_RELEASE_EIP" ? "PARTIAL" : "FULL", recommendationIds: [`rec-${sourceId}`], evidenceIds: [`discovery-aws-${sourceId}`, `trust-readiness-aws-${sourceId}`, `approval-aws-${sourceId}`, `executive-proof-aws-${sourceId}`], ...overrides } as any);
}
async function approve(actionId: string, tenant = tenantId) { const req = await createApprovalRequest({ tenantId: tenant, actionId, approverIds: ["approver"], evidenceIds: ["approval-evidence"] }); await submitApprovalRequest(tenant, req.id); await approveRequest(tenant, req.id, "approver"); }
async function execute(name: string, type: GovernedExecutionType, connectorId: string) { const a = await action(name, type); await approve(a.id); const result = await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId, executionType: type, approved: true }); await verifyAwsExecution(tenantId, result.execution.id); return { a, result }; }

test("Missing AWS execution fails certification", async () => { await reset(); const cert = await getAwsWedgeCertification(tenantId); assert.equal(cert.certified, false); assert.equal(cert.playbooks.find((p) => p.name === "EC2 Rightsizing")!.execution, "NOT_IMPLEMENTED"); });
test("Missing capabilities fails certification", async () => { const connector = await reset(); governedExecutionService.registerConnector({ ...connector, capabilities: ["READ_EC2"] }); const a = await action("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_RIGHTSIZE_EC2", approved: true }); const cert = await getAwsWedgeCertification(tenantId); assert.match(cert.playbooks.find((p) => p.name === "EC2 Rightsizing")!.blockers.join(" "), /Missing AWS capabilities/); });
test("Missing rollback fails certification", async () => { const connector = await reset(); const a = await action("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2"); await approve(a.id); const result = await governedExecutionService.simulateExecution({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_RIGHTSIZE_EC2" }); governedExecutionService.updateExecution({ ...result.execution, status: "COMPLETED", executionMode: "CONTROLLED" }); const cert = await getAwsWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "EC2 Rightsizing")!.rollback, "MISSING"); });
test("Missing verification fails certification", async () => { const connector = await reset(); const a = await action("Idle Resource Shutdown", "AWS_STOP_EC2"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_STOP_EC2", approved: true }); const cert = await getAwsWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "Idle Resource Shutdown")!.verification, "MISSING"); });
for (const [name, type] of playbooks) test(`${name} certifies`, async () => { const connector = await reset(); await execute(name, type, connector.id); const cert = await getAwsWedgeCertification(tenantId); const row = cert.playbooks.find((p) => p.name === name)!; assert.equal(row.certified, true); assert.equal(row.execution, "CONTROLLED_EXECUTION"); });
test("full AWS wedge certifies", async () => { const connector = await reset(); for (const [name, type] of playbooks) await execute(name, type, connector.id); const cert = await getAwsWedgeCertification(tenantId); assert.equal(cert.certified, true); assert.equal(cert.certifiedPlaybooks, 5); });
test("Pre-state, post-state, rollback payload, outcome, protection, drift, executive proof", async () => { const connector = await reset(); const { result } = await execute("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2", connector.id); const evidence = governedExecutionService.listEvidence(tenantId, result.execution.id); for (const type of ["PRE_STATE", "POST_STATE", "ROLLBACK_PAYLOAD", "VERIFICATION_RESULT"]) assert.ok(evidence.some((row) => row.evidenceType === type)); const row = (await getAwsWedgeCertification(tenantId)).playbooks.find((p) => p.name === "EC2 Rightsizing")!; assert.equal(row.outcome, "COMPLETE"); assert.equal(row.protection, "COMPLETE"); assert.equal(row.drift, "COMPLETE"); assert.equal(row.executiveProof, "COMPLETE"); });
test("Partial rollback evidence recorded", async () => { const connector = await reset(); const { result } = await execute("Orphaned Resource Cleanup", "AWS_DELETE_EBS", connector.id); const rb = await rollbackAwsExecution(tenantId, result.execution.id); assert.equal(rb.partial, true); assert.match(rb.evidence.summary, /PARTIAL/); });
test("EC2 rollback restores prior instance type", async () => { const connector = await reset(); const { a, result } = await execute("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2", connector.id); await rollbackAwsExecution(tenantId, result.execution.id); assert.equal(readEc2State({ tenantId, resourceId: a.sourceId }).instanceType, "m5.2xlarge"); });
test("Demo mode blocks writes", async () => { const connector = await reset(); setTenantExecutionPolicy({ tenantId, mode: "DEMO" }); const a = await action("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2"); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_RIGHTSIZE_EC2", approved: true }), /DEMO|READ_ONLY/); });
test("Approval blocks execution", async () => { const connector = await reset(); const a = await action("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2"); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_RIGHTSIZE_EC2" }), /APPROVAL|READINESS/); });
test("Trust blocks execution", async () => { const connector = await reset(); const a = await action("Savings Plans Coverage", "AWS_CREATE_SAVINGS_PLAN_REVIEW", tenantId, { trustScore: 0, evidenceIds: ["discovery-aws", "approval-aws"] }); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AWS_CREATE_SAVINGS_PLAN_REVIEW", approved: true }), /READINESS|TRUST|NOT_READY/); });
test("Live tenant gate blocks uncertified AWS execution", async () => { await reset(); const a = await action("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2"); const gate = evaluateLiveTenantExecutionGate({ policy: getTenantExecutionPolicy(tenantId), action: a, wedgeCertification: { certified: false }, request: { tenantId, domain: "AWS", executionMode: "CONTROLLED", dryRun: false, destructive: true, blastRadius: "LOW" } }); assert.equal(gate.verdict, "BLOCK_UNCERTIFIED_WEDGE"); });
test("Tenant isolation", async () => { const connector = await reset(); await execute("EC2 Rightsizing", "AWS_RIGHTSIZE_EC2", connector.id); const other = await getAwsWedgeCertification("tenant-other"); assert.equal(other.certifiedPlaybooks, 0); });
test("No autonomous execution", async () => { const connector = await reset(); const { result } = await execute("Reserved Instance Optimisation", "AWS_CREATE_RI_REVIEW", connector.id); assert.equal(result.evidence.every((row) => JSON.stringify(row.payload ?? {}).includes('"autonomous":true') === false), true); });
test("No prohibited labels", () => { const root = path.resolve(process.cwd(), "src"); const files = ["lib/connectors/aws/aws-wedge-certification.ts", "lib/connectors/aws/aws-execution.ts", "lib/connectors/aws/aws-artifacts.ts"].map((file) => fs.readFileSync(path.join(root, file), "utf8")).join("\n"); assert.equal(files.includes("LeftShield"), false); assert.equal(files.includes("Agent Security Analytics"), false); });
