import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { governedActionService } from "../lib/actions/governed-actions";
import { approvalAuthorityEngine, approveRequest, createApprovalRequest, submitApprovalRequest } from "../lib/approval-authority/approval-authority";
import { trustReadinessAuthorityService } from "../lib/trust-readiness/trust-readiness-authority";
import { createDefaultExecutionConnector } from "../lib/execution/execution-connectors";
import { governedExecutionService, type GovernedExecutionType } from "../lib/execution/governed-execution";
import { outcomeProtectionService } from "../lib/outcome-protection/outcome-protection";
import { economicOutcomeAttributionService } from "../lib/economic-outcomes/economic-outcome-attribution";
import { clearAzureArtifacts } from "../lib/connectors/azure/azure-artifacts";
import { clearAzureExecutionState, readAzureVmState, rollbackAzureExecution, verifyAzureExecution } from "../lib/connectors/azure/azure-execution";
import { getAzureWedgeCertification } from "../lib/connectors/azure/azure-wedge-certification";
import { clearTenantExecutionPolicies, evaluateLiveTenantExecutionGate, getTenantExecutionPolicy, setTenantExecutionPolicy } from "../lib/runtime/live-tenant-safety";

const tenantId = "tenant-azure-wedge-test";
const playbooks = [
  ["Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM", "azure vm rightsizing recommendation"],
  ["Idle Resource Shutdown", "AZURE_STOP_VM", "azure idle resource shutdown recommendation"],
  ["Reserved Instance Coverage", "AZURE_CREATE_RI_REVIEW", "azure reserved instance coverage recommendation"],
  ["Savings Plan Optimisation", "AZURE_CREATE_SAVINGS_PLAN_REVIEW", "azure savings plan optimisation recommendation"],
  ["Orphaned Resource Cleanup", "AZURE_DELETE_MANAGED_DISK", "azure orphaned resource cleanup recommendation"],
] as const;

async function reset(tenant = tenantId) {
  governedExecutionService.clear(); await governedActionService.clear(); approvalAuthorityEngine.clear(); trustReadinessAuthorityService.clear(); outcomeProtectionService.clear(); economicOutcomeAttributionService.clearForTests(); clearAzureArtifacts(); clearAzureExecutionState(); clearTenantExecutionPolicies();
  return governedExecutionService.registerConnector(createDefaultExecutionConnector({ tenantId: tenant, connectorType: "AZURE", executionMode: "APPROVAL_REQUIRED" }));
}
async function action(name: string, type: GovernedExecutionType, tenant = tenantId, overrides: Record<string, unknown> = {}) {
  const sourceId = `${name.toLowerCase().replace(/\s+/g, "-")}-azure-resource`;
  return governedActionService.create({ tenantId: tenant, title: name, description: `${name} governed Azure cost optimisation`, domain: "CLOUD", sourceType: "RECOMMENDATION", sourceId, status: "APPROVED", priority: "MEDIUM", readiness: "APPROVAL_REQUIRED", ownerId: "cloud-owner", approverId: "approver", trustScore: 0.93, projectedMonthlyValue: 100, projectedAnnualValue: 1200, blastRadius: "LOW", rollbackCapability: type === "AZURE_DELETE_MANAGED_DISK" || type === "AZURE_RELEASE_PUBLIC_IP" ? "PARTIAL" : "FULL", recommendationIds: [`rec-${sourceId}`], evidenceIds: [`discovery-azure-${sourceId}`, `trust-readiness-azure-${sourceId}`, `approval-azure-${sourceId}`, `executive-proof-azure-${sourceId}`], ...overrides } as any);
}
async function approve(actionId: string, tenant = tenantId) { const req = await createApprovalRequest({ tenantId: tenant, actionId, approverIds: ["approver"], evidenceIds: ["approval-evidence"] }); await submitApprovalRequest(tenant, req.id); await approveRequest(tenant, req.id, "approver"); }
async function execute(name: string, type: GovernedExecutionType, connectorId: string) { const a = await action(name, type); await approve(a.id); const result = await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId, executionType: type, approved: true }); await verifyAzureExecution(tenantId, result.execution.id); return { a, result }; }

test("Missing Azure execution fails certification", async () => { await reset(); const cert = await getAzureWedgeCertification(tenantId); assert.equal(cert.certified, false); assert.equal(cert.playbooks.find((p) => p.name === "Azure VM Rightsizing")!.execution, "NOT_IMPLEMENTED"); });
test("Missing capabilities fails certification", async () => { const connector = await reset(); governedExecutionService.registerConnector({ ...connector, capabilities: ["READ_EC2"] }); const a = await action("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_RIGHTSIZE_VM", approved: true }); const cert = await getAzureWedgeCertification(tenantId); assert.match(cert.playbooks.find((p) => p.name === "Azure VM Rightsizing")!.blockers.join(" "), /Missing Azure capabilities/); });
test("Missing rollback fails certification", async () => { const connector = await reset(); const a = await action("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM"); await approve(a.id); const result = await governedExecutionService.simulateExecution({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_RIGHTSIZE_VM" }); governedExecutionService.updateExecution({ ...result.execution, status: "COMPLETED", executionMode: "CONTROLLED" }); const cert = await getAzureWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "Azure VM Rightsizing")!.rollback, "MISSING"); });
test("Missing verification fails certification", async () => { const connector = await reset(); const a = await action("Idle Resource Shutdown", "AZURE_STOP_VM"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_STOP_VM", approved: true }); const cert = await getAzureWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "Idle Resource Shutdown")!.verification, "MISSING"); });
for (const [name, type] of playbooks) test(`${name} certifies`, async () => { const connector = await reset(); await execute(name, type, connector.id); const cert = await getAzureWedgeCertification(tenantId); const row = cert.playbooks.find((p) => p.name === name)!; assert.equal(row.certified, true); assert.equal(row.execution, "CONTROLLED_EXECUTION"); });
test("full Azure wedge certifies", async () => { const connector = await reset(); for (const [name, type] of playbooks) await execute(name, type, connector.id); const cert = await getAzureWedgeCertification(tenantId); assert.equal(cert.certified, true); assert.equal(cert.certifiedPlaybooks, 5); });
test("Pre-state, post-state, rollback payload, outcome, protection, drift, executive proof", async () => { const connector = await reset(); const { result } = await execute("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM", connector.id); const evidence = governedExecutionService.listEvidence(tenantId, result.execution.id); for (const type of ["PRE_STATE", "POST_STATE", "ROLLBACK_PAYLOAD", "VERIFICATION_RESULT"]) assert.ok(evidence.some((row) => row.evidenceType === type)); const row = (await getAzureWedgeCertification(tenantId)).playbooks.find((p) => p.name === "Azure VM Rightsizing")!; assert.equal(row.outcome, "COMPLETE"); assert.equal(row.protection, "COMPLETE"); assert.equal(row.drift, "COMPLETE"); assert.equal(row.executiveProof, "COMPLETE"); });
test("Partial rollback evidence recorded", async () => { const connector = await reset(); const { result } = await execute("Orphaned Resource Cleanup", "AZURE_DELETE_MANAGED_DISK", connector.id); const rb = await rollbackAzureExecution(tenantId, result.execution.id); assert.equal(rb.partial, true); assert.match(rb.evidence.summary, /PARTIAL/); });
test("VM rollback restores prior SKU", async () => { const connector = await reset(); const { a, result } = await execute("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM", connector.id); await rollbackAzureExecution(tenantId, result.execution.id); assert.equal(readAzureVmState({ tenantId, resourceId: a.sourceId }).sku, "Standard_D8s_v5"); });
test("Demo mode blocks writes", async () => { const connector = await reset(); setTenantExecutionPolicy({ tenantId, mode: "DEMO" }); const a = await action("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM"); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_RIGHTSIZE_VM", approved: true }), /DEMO|READ_ONLY/); });
test("Approval blocks execution", async () => { const connector = await reset(); const a = await action("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM"); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_RIGHTSIZE_VM" }), /APPROVAL|READINESS/); });
test("Trust blocks execution", async () => { const connector = await reset(); const a = await action("Savings Plan Optimisation", "AZURE_CREATE_SAVINGS_PLAN_REVIEW", tenantId, { trustScore: 0, evidenceIds: ["discovery-azure", "approval-azure"] }); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: connector.id, executionType: "AZURE_CREATE_SAVINGS_PLAN_REVIEW", approved: true }), /READINESS|TRUST|NOT_READY/); });
test("Live tenant gate blocks uncertified Azure execution", async () => { await reset(); const a = await action("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM"); const gate = evaluateLiveTenantExecutionGate({ policy: getTenantExecutionPolicy(tenantId), action: a, wedgeCertification: { certified: false }, request: { tenantId, domain: "AZURE", executionMode: "CONTROLLED", dryRun: false, destructive: true, blastRadius: "LOW" } }); assert.equal(gate.verdict, "BLOCK_UNCERTIFIED_WEDGE"); });
test("Tenant isolation", async () => { const connector = await reset(); await execute("Azure VM Rightsizing", "AZURE_RIGHTSIZE_VM", connector.id); const other = await getAzureWedgeCertification("tenant-other"); assert.equal(other.certifiedPlaybooks, 0); });
test("No autonomous execution", async () => { const connector = await reset(); const { result } = await execute("Reserved Instance Coverage", "AZURE_CREATE_RI_REVIEW", connector.id); assert.equal(result.evidence.every((row) => JSON.stringify(row.payload ?? {}).includes('"autonomous":true') === false), true); });
test("No prohibited labels", () => { const root = path.resolve(process.cwd(), "src"); const files = ["lib/connectors/azure/azure-wedge-certification.ts", "lib/connectors/azure/azure-execution.ts", "lib/connectors/azure/azure-artifacts.ts"].map((file) => fs.readFileSync(path.join(root, file), "utf8")).join("\n"); assert.equal(files.includes("LeftShield"), false); assert.equal(files.includes("Agent Security Analytics"), false); });
