import test from 'node:test'; import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { TechnologyCommercialAuthorityService, TechnologyCommercialAuthorityRepository, createInMemoryTechnologyCommercialAuthorityStores } from '../lib/technology-commercial-authority';
import { FinancialTruthAuthorityService, FinancialTruthAuthorityRepository, createInMemoryFinancialTruthAuthorityStores } from '../lib/financial-truth-authority';
import { OwnershipIntelligenceService, OwnershipIntelligenceRepository, createInMemoryOwnershipIntelligenceStores } from '../lib/ownership-intelligence';
import { OutcomeFinanceReconciliationService, OutcomeFinanceReconciliationRepository, createInMemoryOutcomeFinanceReconciliationStores, InMemoryOutcomeFinanceGraphWriter } from '../lib/outcome-finance-reconciliation';
import { EconomicGraphService, InMemoryEconomicGraphRepository } from '../lib/economic-graph';
import { runEconomicControlChainAudit } from '../lib/economic-control-chain-audit';

test('end-to-end Certen economic control chain persists and traverses to finance verified value', async()=>{const tenantId='chain-a', other='chain-b'; const graphRepo=new InMemoryEconomicGraphRepository(); const graph=new EconomicGraphService(graphRepo); const commercial=new TechnologyCommercialAuthorityService(new TechnologyCommercialAuthorityRepository(createInMemoryTechnologyCommercialAuthorityStores()),graph); const financeRepo=new FinancialTruthAuthorityRepository(createInMemoryFinancialTruthAuthorityStores()); const finance=new FinancialTruthAuthorityService(financeRepo,graph); const ownershipRepo=new OwnershipIntelligenceRepository(createInMemoryOwnershipIntelligenceStores()); const ownership=new OwnershipIntelligenceService(ownershipRepo,graph); const ofRepo=new OutcomeFinanceReconciliationRepository(createInMemoryOutcomeFinanceReconciliationStores()); const ofGraph=new InMemoryOutcomeFinanceGraphWriter(); const of=new OutcomeFinanceReconciliationService(ofRepo,ofGraph);
 const vendor=await commercial.createVendor({tenantId,name:'Vendor',category:'SAAS',currency:'USD',riskLevel:'LOW'}); const contract=await commercial.createContract({tenantId,vendorId:vendor.id,name:'Contract',status:'ACTIVE',startDate:'2026-01-01',endDate:'2026-12-31',autoRenewal:false,currency:'USD',auditRights:true,trueUpRights:true}); const entitlement=await commercial.createEntitlement({tenantId,vendorId:vendor.id,contractId:contract.id,productName:'Seats',entitlementType:'SEAT',totalQuantity:100,currency:'USD'}); const commitment=await commercial.createCommitment({tenantId,vendorId:vendor.id,contractId:contract.id,entitlementId:entitlement.id,commitmentType:'MINIMUM_SEATS',committedValue:100,consumedValue:100,startDate:'2026-01-01',endDate:'2026-12-31'}); const renewal=await commercial.createRenewal({tenantId,vendorId:vendor.id,contractId:contract.id,renewalDate:'2026-11-01',currentAnnualSpend:1000,negotiationLeverage:'HIGH',readinessScore:90,status:'APPROVED'});
 const recommendation='rec-chain', approval='approval-chain', action='action-chain', execution='execution-chain', evidence='evidence-chain', outcome='outcome-chain'; await graph.createNode({tenantId,entityType:'RECOMMENDATION',canonicalName:recommendation,canonicalKey:recommendation,confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:recommendation,observedAt:new Date().toISOString()}]}); await graph.createNode({tenantId,entityType:'APPROVAL',canonicalName:approval,canonicalKey:approval,confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:approval,observedAt:new Date().toISOString()}]}); await graph.createNode({tenantId,entityType:'GOVERNED_ACTION',canonicalName:action,canonicalKey:action,confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:action,observedAt:new Date().toISOString()}]}); await graph.createEdge({tenantId,fromEntityId:entitlement.id,toEntityId:recommendation,relationshipType:'DERIVED_FROM',confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:'path',observedAt:new Date().toISOString()}]}); await graph.createEdge({tenantId,fromEntityId:recommendation,toEntityId:approval,relationshipType:'APPROVED_BY',confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:'path',observedAt:new Date().toISOString()}]}); await graph.createEdge({tenantId,fromEntityId:approval,toEntityId:action,relationshipType:'GOVERNED_BY',confidenceScore:1,evidence:[{sourceSystem:'test',sourceReferenceId:'path',observedAt:new Date().toISOString()}]});
 const cc=await finance.createCostCentre({tenantId,code:'CC-1',name:'Finance',currency:'USD'}); const fr=await finance.createReconciliation({tenantId,vendorId:vendor.id,outcomeId:outcome,actionId:action,projectedSavings:700,expectedSavings:640,verifiedSavings:590,status:'VERIFIED',evidenceRefs:[evidence]}); const mgr=await ownership.createUser({tenantId,email:'mgr@example.com',displayName:'Manager'}); const dep=await ownership.createDepartment({tenantId,name:'IT',managerUserId:mgr.id,costCentreIds:[cc.id]}); const ex=await ownership.createExecutiveOwner({tenantId,displayName:'CFO',departmentIds:[dep.id],costCentreIds:[cc.id]}); const user=await ownership.createUser({tenantId,email:'owner@example.com',displayName:'Owner',managerId:mgr.id,departmentId:dep.id,costCentreId:cc.id,executiveOwnerId:ex.id}); const assign=await ownership.createAssignment({tenantId,ownerUserId:user.id,managerUserId:mgr.id,departmentId:dep.id,costCentreId:cc.id,executiveOwnerId:ex.id,targetType:'RECOMMENDATION',targetId:recommendation,assignmentType:'BUSINESS_OWNER',confidence:1});
 const attr=await of.createAttribution({tenantId,recommendationId:recommendation,actionId:action,executionId:execution,outcomeId:outcome,financeReconciliationId:fr.id,vendorId:vendor.id,contractId:contract.id,entitlementId:entitlement.id,costCentreId:cc.id,departmentId:dep.id,executiveOwnerId:ex.id,ownerUserId:user.id,projectedSavings:700,expectedSavings:640,executedSavings:615,verifiedSavings:590,status:'VERIFIED',confidence:'HIGH',evidenceRefs:[evidence]}); const ledger=await of.appendValueLedgerEntry({tenantId,attributionId:attr.id,eventType:'FINANCE_VERIFIED_VALUE_RECORDED',amount:590,currency:'USD',recommendationId:recommendation,actionId:action,executionId:execution,outcomeId:outcome,financeReconciliationId:fr.id,ownerUserId:user.id,departmentId:dep.id,costCentreId:cc.id,executiveOwnerId:ex.id,evidenceRefs:[evidence]}); const variance=await of.createVarianceRecord({tenantId,attributionId:attr.id,expectedSavings:640,verifiedSavings:590,varianceType:'EXPECTED_VS_VERIFIED',costCentreId:cc.id,departmentId:dep.id,executiveOwnerId:ex.id}); const snap=await of.createConfidenceSnapshot({tenantId,attributionId:attr.id,recommendationPresent:true,actionPresent:true,executionPresent:true,outcomePresent:true,financeReconciliationPresent:true,ownershipPresent:true,evidencePresent:true,evidenceRefs:[evidence]});
 assert.ok(vendor&&contract&&entitlement&&commitment&&renewal&&fr&&attr&&ledger&&variance&&assign); assert.equal((await ofRepo.listAttributions(other)).length,0); assert.ok(ofGraph.nodes.some(n=>n.entityType==='VALUE_ATTRIBUTION'||n.type==='VALUE_ATTRIBUTION')); assert.ok(ofGraph.edges.some(e=>e.relationshipType==='DERIVED_FROM'||e.type==='DERIVED_FROM')); assert.equal(await ofGraph.hasPath(tenantId,recommendation,attr.id),true); assert.equal(attr.evidenceRefs[0],evidence); assert.equal(attr.ownerUserId,user.id); assert.equal(attr.departmentId,dep.id); assert.equal(attr.costCentreId,cc.id); assert.equal(attr.executiveOwnerId,ex.id); assert.equal((await of.summariseTenantOutcomeFinance(tenantId)).verifiedSavings,590); assert.equal(snap.confidence,'HIGH'); assert.equal((await runEconomicControlChainAudit()).status,'PASS');});

test('all economic authorities use the shared EconomicGraphService path',()=>{for(const file of ['src/lib/technology-commercial-authority/commercial-authority-service.ts','src/lib/financial-truth-authority/financial-truth-service.ts','src/lib/ownership-intelligence/ownership-intelligence-service.ts','src/lib/outcome-finance-reconciliation/outcome-finance-reconciliation-service.ts']){const body=readFileSync(resolve(process.cwd(),file),'utf8'); assert.ok(body.includes('EconomicGraphService'),file); assert.equal(body.includes('new OperationalGraphService()'),false,file)}});
