import assert from 'node:assert/strict';
import test from 'node:test';
import { CONNECTOR_FAMILIES, defaultConnectorManifests } from '../lib/connector-readiness';
import { ConnectorAdapterFactory, ConnectorAdapterRegistry } from '../lib/connector-adapters';

test('default adapters registered, families covered, manifests covered, duplicates rejected', () => { const registry = new ConnectorAdapterRegistry(); const adapters = registry.registerDefaultAdapters(); assert.equal(adapters.length, defaultConnectorManifests.length); assert.ok(CONNECTOR_FAMILIES.every((f) => registry.listByFamily(f).length >= 1)); assert.ok(defaultConnectorManifests.every((m) => registry.has(m.connectorKey))); assert.throws(() => registry.register(adapters[0]), /DUPLICATE_CONNECTOR_ADAPTER/); });

test('auth, permissions, capabilities, config validation safety, fixtures, normalisation, evidence, graph, errors, rate limits', async () => { const adapter = new ConnectorAdapterFactory().createAdapter('m365'); assert.equal(adapter.getAuthRequirements().authType, 'OAUTH2'); assert.equal(adapter.getAuthRequirements().requiresAdminConsent, true); assert.ok(adapter.getPermissionChecklist().items.some((i) => i.label.includes('Graph'))); const demo = { tenantId: 't', connectorKey: 'm365', mode: 'DEMO' as const, config: {}, source: 'demo-fixture' }; assert.equal((await adapter.discoverCapabilities(demo)).status, 'PARTIAL'); assert.equal((await adapter.validateConfig(demo)).status, 'PASS'); assert.equal((await adapter.validateConfig({ ...demo, mode: 'LIVE', source: 'customer-config', credentialRef: 'cred' })).status, 'WARN'); assert.equal((await adapter.validateConfig({ ...demo, mode: 'LIVE' })).status, 'FAIL'); assert.equal((await adapter.validateConfig({ ...demo, mode: 'LIVE', source: 'customer-config' })).status, 'FAIL'); const sample = await adapter.sampleFetch(demo); assert.equal(sample.source, 'connector-contract-fixtures'); assert.ok(sample.recordsDetected > 0); const first = sample.sampleRecords[0]; const norm = await adapter.normalise(first.outputContract, first.payload); assert.equal(norm.status, 'PASS'); assert.ok(norm.normalised); assert.equal((await adapter.buildEvidence(first.outputContract, first.payload)).status, 'CREATED'); assert.equal((await adapter.mapToGraph(first.outputContract, norm.normalised ?? {})).status, 'READY'); assert.equal(adapter.classifyError(new Error('permission scope missing')).category, 'PERMISSION'); assert.equal(adapter.classifyError(new Error('schema violation')).category, 'SCHEMA'); assert.equal(adapter.getRateLimitPolicy().strategy, 'EXPONENTIAL_BACKOFF'); });

test('factory creates one adapter, all adapters, and adapters by family', () => { const factory = new ConnectorAdapterFactory(); assert.equal(factory.createAdapter('m365').connectorFamily, 'M365'); assert.equal(factory.createAllDefaultAdapters().length, defaultConnectorManifests.length); assert.equal(factory.createAdaptersByFamily('ERP').length, 1); });
