import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { governedActionService } from "../lib/actions/governed-actions";
import { approvalAuthorityEngine, createApprovalRequest, submitApprovalRequest, approveRequest } from "../lib/approval-authority/approval-authority";
import { trustReadinessAuthorityService } from "../lib/trust-readiness/trust-readiness-authority";
import { governedExecutionService, type GovernedExecutionType } from "../lib/execution/governed-execution";
import { createDefaultExecutionConnector } from "../lib/execution/execution-connectors";
import { outcomeProtectionService } from "../lib/outcome-protection/outcome-protection";
import { economicOutcomeAttributionService } from "../lib/economic-outcomes/economic-outcome-attribution";
import { clearDataPlatformArtifacts } from "../lib/connectors/data-platform/data-platform-artifacts";
import { getDataPlatformWedgeCertification } from "../lib/connectors/data-platform/data-platform-wedge-certification";
import { clearSnowflakeExecutionState, readSnowflakeWarehouseState, rollbackSnowflakeWarehouseConfig, verifySnowflakeExecution } from "../lib/connectors/snowflake/snowflake-execution";
import { clearDatabricksExecutionState, readDatabricksClusterState, rollbackDatabricksClusterConfig, verifyDatabricksExecution } from "../lib/connectors/databricks/databricks-execution";
import { clearTenantExecutionPolicies, evaluateLiveTenantExecutionGate, getTenantExecutionPolicy, setTenantExecutionPolicy } from "../lib/runtime/live-tenant-safety";

const tenantId = "tenant-data-platform-wedge-test";
const playbooks = [
  ["Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND", "snowflake warehouse auto suspend recommendation"],
  ["Warehouse Rightsizing", "SNOWFLAKE_RESIZE_WAREHOUSE", "snowflake warehouse rightsizing recommendation"],
  ["Idle Warehouse Suspension", "SNOWFLAKE_SUSPEND_WAREHOUSE", "snowflake idle warehouse suspension recommendation"],
  ["Query Spend Anomaly Review", "SNOWFLAKE_CREATE_SPEND_REVIEW", "snowflake query spend anomaly review recommendation"],
  ["Cluster Auto-Termination Enforcement", "DATABRICKS_SET_AUTO_TERMINATION", "databricks cluster auto termination recommendation"],
  ["Cluster Rightsizing", "DATABRICKS_RESIZE_CLUSTER", "databricks cluster rightsizing recommendation"],
  ["Idle Cluster Termination", "DATABRICKS_TERMINATE_CLUSTER", "databricks idle cluster termination recommendation"],
  ["Job Compute Optimisation", "DATABRICKS_CREATE_JOB_REVIEW", "databricks job compute optimisation recommendation"],
] as const;
async function reset(tenant = tenantId) { governedExecutionService.clear(); await governedActionService.clear(); approvalAuthorityEngine.clear(); trustReadinessAuthorityService.clear(); outcomeProtectionService.clear(); economicOutcomeAttributionService.clearForTests(); clearDataPlatformArtifacts(); clearSnowflakeExecutionState(); clearDatabricksExecutionState(); clearTenantExecutionPolicies(); const snowflake = governedExecutionService.registerConnector(createDefaultExecutionConnector({ tenantId: tenant, connectorType: "SNOWFLAKE", executionMode: "APPROVAL_REQUIRED" })); const databricks = governedExecutionService.registerConnector(createDefaultExecutionConnector({ tenantId: tenant, connectorType: "DATABRICKS", executionMode: "APPROVAL_REQUIRED" })); return { snowflake, databricks }; }
async function action(name: string, type: GovernedExecutionType, source = `${name.toLowerCase().replace(/\s+/g, "-")}-asset`, tenant = tenantId, overrides: Record<string, unknown> = {}) { return governedActionService.create({ tenantId: tenant, title: name, description: `${name} governed data platform cost optimisation`, domain: "DATA", sourceType: "RECOMMENDATION", sourceId: source, status: "APPROVED", priority: "MEDIUM", readiness: "APPROVAL_REQUIRED", ownerId: "cost-owner", approverId: "approver", trustScore: 0.92, projectedMonthlyValue: 100, projectedAnnualValue: 1200, blastRadius: "LOW", rollbackCapability: type.includes("SUSPEND") || type.includes("TERMINATE") ? "PARTIAL" : "FULL", recommendationIds: [`rec-${source}`], evidenceIds: [`discovery-${source}`, `trust-readiness-${source}`, `approval-${source}`, `executive-proof-${source}`], ...overrides } as any); }
async function approve(actionId: string, tenant = tenantId) { const req = await createApprovalRequest({ tenantId: tenant, actionId, approverIds: ["approver"], evidenceIds: ["approval-evidence"] }); await submitApprovalRequest(tenant, req.id); await approveRequest(tenant, req.id, "approver"); }
async function execute(name: string, type: GovernedExecutionType, connectorId: string) { const a = await action(name, type); await approve(a.id); const result = await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId, executionType: type, approved: true }); if (type.startsWith("SNOWFLAKE")) await verifySnowflakeExecution(tenantId, result.execution.id); else await verifyDatabricksExecution(tenantId, result.execution.id); return { a, result }; }

test("certification fails when Snowflake execution is missing", async () => { await reset(); const cert = await getDataPlatformWedgeCertification(tenantId); assert.equal(cert.snowflakeCertified, false); assert.equal(cert.playbooks.find((p) => p.name === "Warehouse Auto-Suspend Enforcement")!.execution, "NOT_IMPLEMENTED"); });
test("certification fails when Databricks execution is missing", async () => { await reset(); const cert = await getDataPlatformWedgeCertification(tenantId); assert.equal(cert.databricksCertified, false); assert.equal(cert.playbooks.find((p) => p.name === "Cluster Auto-Termination Enforcement")!.execution, "NOT_IMPLEMENTED"); });
test("certification fails when required provider capabilities are missing", async () => { const { snowflake } = await reset(); governedExecutionService.registerConnector({ ...snowflake, capabilities: ["READ_WAREHOUSE_STATE"] }); const a = await action("Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: snowflake.id, executionType: "SNOWFLAKE_SET_AUTO_SUSPEND", approved: true }); const cert = await getDataPlatformWedgeCertification(tenantId); assert.match(cert.playbooks.find((p) => p.name === "Warehouse Auto-Suspend Enforcement")!.blockers.join(" "), /Missing provider capabilities/); });
test("certification fails when rollback is missing where required", async () => { const { snowflake } = await reset(); const a = await action("Warehouse Rightsizing", "SNOWFLAKE_RESIZE_WAREHOUSE"); await approve(a.id); const result = await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: snowflake.id, executionType: "SNOWFLAKE_RESIZE_WAREHOUSE", approved: true, dryRun: true }); governedExecutionService.updateExecution({ ...result.execution, status: "COMPLETED", executionMode: "CONTROLLED" }); const cert = await getDataPlatformWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "Warehouse Rightsizing")!.verification, "MISSING"); });
test("certification fails when verification is missing", async () => { const { databricks } = await reset(); const a = await action("Cluster Rightsizing", "DATABRICKS_RESIZE_CLUSTER"); await approve(a.id); await governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: databricks.id, executionType: "DATABRICKS_RESIZE_CLUSTER", approved: true }); const cert = await getDataPlatformWedgeCertification(tenantId); assert.equal(cert.playbooks.find((p) => p.name === "Cluster Rightsizing")!.verification, "MISSING"); });
test("certification passes only when full lifecycle exists", async () => { const { snowflake, databricks } = await reset(); for (const [name, type] of playbooks) await execute(name, type, type.startsWith("SNOWFLAKE") ? snowflake.id : databricks.id); const cert = await getDataPlatformWedgeCertification(tenantId); assert.equal(cert.certified, true); assert.equal(cert.certifiedPlaybooks, 8); });
for (const [name, type] of playbooks) test(`${name} supports controlled execution`, async () => { const connectors = await reset(); const { result } = await execute(name, type, type.startsWith("SNOWFLAKE") ? connectors.snowflake.id : connectors.databricks.id); assert.equal(result.execution.executionMode, "CONTROLLED"); assert.equal((result.rollbackPayload as any)?.provider, type.startsWith("SNOWFLAKE") ? "SNOWFLAKE" : "DATABRICKS"); });
test("pre-state evidence, post-state evidence, rollback payload, economic outcome, protected outcome, drift, executive proof are created", async () => { const { snowflake } = await reset(); const { result } = await execute("Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND", snowflake.id); const evidence = governedExecutionService.listEvidence(tenantId, result.execution.id); for (const type of ["PRE_STATE", "POST_STATE", "ROLLBACK_PAYLOAD", "VERIFICATION_RESULT"]) assert.ok(evidence.some((e) => e.evidenceType === type)); const cert = await getDataPlatformWedgeCertification(tenantId); const row = cert.playbooks.find((p) => p.name === "Warehouse Auto-Suspend Enforcement")!; assert.equal(row.outcome, "COMPLETE"); assert.equal(row.protection, "COMPLETE"); assert.equal(row.drift, "COMPLETE"); assert.equal(row.executiveProof, "COMPLETE"); });
test("rollback restores prior config or records partial rollback evidence", async () => { const { snowflake, databricks } = await reset(); const right = await execute("Warehouse Rightsizing", "SNOWFLAKE_RESIZE_WAREHOUSE", snowflake.id); await rollbackSnowflakeWarehouseConfig(tenantId, right.result.execution.id); assert.equal(readSnowflakeWarehouseState({ tenantId, warehouseId: right.a.sourceId }).size, "LARGE"); const idle = await execute("Idle Cluster Termination", "DATABRICKS_TERMINATE_CLUSTER", databricks.id); const rb = await rollbackDatabricksClusterConfig(tenantId, idle.result.execution.id); assert.equal(rb.partial, true); });
test("demo mode blocks real provider writes", async () => { const { snowflake } = await reset(); setTenantExecutionPolicy({ tenantId, mode: "DEMO" }); const a = await action("Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND"); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: snowflake.id, executionType: "SNOWFLAKE_SET_AUTO_SUSPEND", approved: true }), /DEMO|READ_ONLY/); });
test("Approval Authority blocks execution when approval missing", async () => { const { databricks } = await reset(); const a = await action("Cluster Auto-Termination Enforcement", "DATABRICKS_SET_AUTO_TERMINATION"); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: databricks.id, executionType: "DATABRICKS_SET_AUTO_TERMINATION" }), /APPROVAL|READINESS/); });
test("Trust Authority blocks execution when BLOCKED", async () => { const { snowflake } = await reset(); const a = await action("Query Spend Anomaly Review", "SNOWFLAKE_CREATE_SPEND_REVIEW", undefined, tenantId, { trustScore: 0, evidenceIds: ["discovery-snowflake", "approval-snowflake"] }); await approve(a.id); await assert.rejects(() => governedExecutionService.executeGovernedAction({ tenantId, actionId: a.id, connectorId: snowflake.id, executionType: "SNOWFLAKE_CREATE_SPEND_REVIEW", approved: true }), /READINESS|TRUST|NOT_READY/); });
test("live tenant gate blocks uncertified data-platform execution", async () => { await reset(); const a = await action("Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND"); const gate = evaluateLiveTenantExecutionGate({ policy: getTenantExecutionPolicy(tenantId), action: a, wedgeCertification: { certified: false }, request: { tenantId, domain: "SNOWFLAKE", executionMode: "CONTROLLED", dryRun: false, destructive: true, blastRadius: "LOW" } }); assert.equal(gate.verdict, "BLOCK_UNCERTIFIED_WEDGE"); });
test("tenant isolation", async () => { const { snowflake } = await reset(); await execute("Warehouse Auto-Suspend Enforcement", "SNOWFLAKE_SET_AUTO_SUSPEND", snowflake.id); const other = await getDataPlatformWedgeCertification("tenant-other"); assert.equal(other.certifiedPlaybooks, 0); });
test("no autonomous execution", async () => { const { databricks } = await reset(); const { result } = await execute("Job Compute Optimisation", "DATABRICKS_CREATE_JOB_REVIEW", databricks.id); assert.equal(result.evidence.every((e) => JSON.stringify(e.payload ?? {}).includes('"autonomous":true') === false), true); });
test("No LeftShield objects and no Agent Security Analytics labels", () => { const root = path.resolve(process.cwd(), "src"); const files = ["lib/connectors/data-platform/data-platform-wedge-certification.ts", "lib/connectors/snowflake/snowflake-execution.ts", "lib/connectors/databricks/databricks-execution.ts"].map((f) => fs.readFileSync(path.join(root, f), "utf8")).join("\n"); assert.equal(files.includes("LeftShield"), false); assert.equal(files.includes("Agent Security Analytics"), false); });
