import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read = (p: string) => fs.readFileSync(new URL(p, import.meta.url), "utf8");

test("non-execution routes do not import execution-engine", () => {
  for (const route of ["../routes/recommendations.ts","../routes/workflow.ts","../routes/simulations.ts","../routes/governance.ts","../routes/outcomes.ts"]) {
    assert.equal(read(route).includes("execution-engine"), false);
  }
});

test("cross-domain layer remains non-executing", () => {
  const content = read("../lib/cross-domain/cross-domain-governance-intelligence.ts");
  assert.equal(content.includes("execution-engine"), false);
  assert.equal(content.includes("execute"), false);
});

test("scale simulation remains non-executing",()=>{ const scale=read('../lib/runtime-hardening/sustained-runtime-load-phase-c.ts'); assert.equal(scale.includes('execution-engine'), false); assert.equal(scale.includes('auto-approval'), false); assert.equal(scale.includes('workflow-triggered execution'), false); });

test("decision-intelligence has no direct mutation paths",()=>{ const detector=read("../lib/decision-intelligence/recommendation-conflict-detector.ts"); ["Graph","ServiceNow","license removal execution","approval bypass"].forEach(k=>assert.equal(detector.includes(k), false)); });


test("m365 integration excludes direct license mutation instructions",()=>{ const m=read("../lib/decision-intelligence/m365-expansion-pack-1.ts"); ["REMOVE /users","PATCH /users","direct licence removal","approval bypass"].forEach(k=>assert.equal(m.includes(k), false)); });


test("ai-economics boundary keywords absent",()=>{ const ai=read("../lib/ai-economics/ai-decision-intelligence-integration.ts")+read("../lib/ai-economics/ai-cost-playbooks.ts"); ["AUTO_EXECUTE","AUTO_REMEDIATE","approval bypass","direct vendor API mutation","new execution engine","new replay engine","new telemetry engine","new workflow engine"].forEach(k=>assert.equal(ai.includes(k), false)); });


test("cross-domain-economics boundary keywords absent",()=>{ const x=read("../lib/cross-domain-economics/cross-domain-recommendation-arbitration.ts")+read("../lib/cross-domain-economics/cross-domain-economic-report.ts"); ["AUTO_EXECUTE","AUTO_REMEDIATE","autonomous spend control","autonomous licence changes","autonomous model switching","autonomous procurement actions","direct vendor API mutation","approval bypass","execution engine creation","replay engine fork","telemetry engine fork","workflow engine fork","outcome-ledger fork"].forEach(k=>assert.equal(x.includes(k), false)); });

test('economic-forecasting has no execution/runtime expansion keywords',()=>{ const ef=read('../lib/economic-forecasting/forecast-confidence-engine.ts')+read('../lib/economic-forecasting/economic-intelligence-report.ts'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous procurement','autonomous budget mutation','autonomous vendor actions','direct SaaS mutation','approval bypass','execution-engine creation','replay-engine fork','telemetry-engine fork','workflow-engine fork','outcome-ledger fork'].forEach(k=>assert.equal(ef.includes(k), false)); });

test('economic-simulation has no execution/runtime expansion keywords',()=>{ const sim=read('../lib/economic-simulation/scenario-definition-engine.ts')+read('../lib/economic-simulation/economic-scenario-report.ts'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous procurement','autonomous SaaS mutation','autonomous vendor actions','approval bypass','execution engine creation','replay engine forks','telemetry engine forks','workflow engine forks'].forEach(k=>assert.equal(sim.includes(k), false)); });


test('economic-memory module remains non-executing and non-mutating',()=>{ const mem=read('../lib/economic-memory/index.ts')+read('../lib/economic-memory/economic-memory-report.ts'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous procurement','budget mutation','vendor mutation','policy mutation','execution engine','replay fork','telemetry fork','workflow fork'].forEach(k=>assert.equal(mem.includes(k), false)); });

test('finops-operationalization remains governed non-mutating',()=>{ const mem=read('../lib/finops-operationalization/index.ts')+read('../lib/finops-operationalization/finops-operationalization-report.ts'); ['AUTO_EXECUTE','AUTO_REMEDIATE','direct cloud mutation','resource deletion','resource resize execution','commitment purchase','ServiceNow API mutation','budget mutation','vendor mutation','approval bypass','new execution engine','replay fork','telemetry fork','workflow fork'].forEach(k=>assert.equal(mem.includes(k), false)); });

test('executive-economic-governance remains non-mutating',()=>{ const body=read('../lib/executive-economic-governance/index.ts')+read('../lib/executive-economic-governance/executive-economic-governance-report.ts'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous budgeting','autonomous procurement','policy mutation','ERP mutation','ServiceNow mutation','cloud mutation','vendor mutation','execution engine','replay fork','telemetry fork','workflow fork'].forEach(k=>assert.equal(body.includes(k), false)); });
test('execution boundary: enterprise decision module does not contain autonomous mutation terms',()=>{ const body=read('../lib/enterprise-economic-decision/enterprise-decision-report.ts')+read('../lib/enterprise-economic-decision/investment-allocation-engine.ts'); ['autonomous budgeting','autonomous procurement','policy mutation','ERP mutation','ServiceNow mutation','cloud mutation','SaaS mutation','vendor mutation'].forEach(k=>assert.equal(body.includes(k), false)); });


test('cloud-economic-intelligence boundaries enforced',()=>{ const dir=new URL('../lib/cloud-economic-intelligence/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/cloud-economic-intelligence/${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); ['auto_execute','auto_remediate','resource deletion','resource resize execution','commitment purchase','direct aws mutation','direct azure mutation','direct gcp mutation','cloud mutation','budget mutation','vendor mutation','execution engine','telemetry fork','replay fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.includes(k), false)); });

test('commitment-economics boundaries enforced',()=>{ const dir=new URL('../lib/commitment-economics/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/commitment-economics/${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); ['auto_execute','auto_remediate','commitment purchase','reservation purchase','direct aws mutation','direct azure mutation','direct gcp mutation','cloud mutation','budget mutation','vendor mutation','execution engine','telemetry fork','replay fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.includes(k), false)); });

test('kubernetes-economics boundaries enforced',()=>{ const dir=new URL('../lib/kubernetes-economics/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/kubernetes-economics/${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); ['auto_execute','auto_remediate','pod deletion','node scaling','cluster mutation','namespace deletion','workload mutation','direct kubernetes api mutation','direct cloud mutation','execution engine','telemetry fork','replay fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.includes(k), false)); });

test('execution boundary protection includes new economic hardening folders',()=>{ const dirs=['../lib/economic-intelligence-kernel/','../lib/economic-causality/','../lib/economic-memory-drift/','../lib/ai-runtime-economics/']; const forbidden=['kubectl','deletepod','deletedeployment','patchdeployment','scaledeployment','applymanifest','createjob','deletejob','restartpod','cordon','drain','taint','autoscale','setreplicas','cloudexecute','executeaws','executeazure','executegcp','remediate','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','agentexecute','modelroute','promptrewrite','gpuschedule']; dirs.forEach((d)=>{ const dir=new URL(d, import.meta.url); const body=fs.readdirSync(dir).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});


test('next maturity economic layers enforce forbidden terms',()=>{ const dirs=['../lib/semantic-hardening/','../lib/cross-layer-integration/','../lib/calibration-realism/','../lib/economic-arbitration/']; const forbidden=['kubectl','deletepod','patchdeployment','restartpod','scaledeployment','applymanifest','cloudexecute','executeaws','executeazure','executegcp','agentexecute','modelroute','promptrewrite','gpuschedule','autooptimize','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','autonomousoptimization','policyexecution','dynamicexecution']; dirs.forEach((d)=>{ const dir=new URL(d, import.meta.url); const body=fs.readdirSync(dir).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});


test('sprint folders enforce forbidden terms',()=>{ const dirs=['../lib/contract-migration/','../lib/golden-path/','../lib/economic-arbitration/','../lib/oracle-java-governance/']; const forbidden=['kubectl','deletepod','patchdeployment','restartpod','scaledeployment','applymanifest','cloudexecute','executeaws','executeazure','executegcp','agentexecute','modelroute','promptrewrite','gpuschedule','autooptimize','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','autonomousoptimization','policyexecution','dynamicexecution','uninstalljava','removejava','changeoracleconfig','alterdatabase','migrateworkload','reassignlicense','scanendpoint','deployagent']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false)); });});



test('new maturity sprint folders enforce forbidden terms',()=>{ const dirs=['../lib/calibration-weighting/','../lib/economic-graph/','../lib/economic-policy-language/','../lib/scenario-benchmarks/']; const forbidden=['kubectl','deletepod','patchdeployment','restartpod','scaledeployment','applymanifest','cloudexecute','executeaws','executeazure','executegcp','agentexecute','modelroute','promptrewrite','gpuschedule','autooptimize','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','autonomousoptimization','policyexecution','dynamicexecution','uninstalljava','removejava','changeoracleconfig','alterdatabase','migrateworkload','reassignlicense','scanendpoint','deployagent','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});


test('governance verification maturity folders enforce forbidden terms',()=>{ const dirs=['../lib/governance-dsl/','../lib/economic-graph-constraints/','../lib/benchmark-realism/','../lib/governance-verification/','../lib/executive-reasoning/']; const forbidden=['kubectl','deletepod','patchdeployment','restartpod','scaledeployment','applymanifest','cloudexecute','executeaws','executeazure','executegcp','agentexecute','modelroute','promptrewrite','gpuschedule','autooptimize','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','autonomousoptimization','policyexecution','dynamicexecution','uninstalljava','removejava','changeoracleconfig','alterdatabase','migrateworkload','reassignlicense','scanendpoint','deployagent','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});


test('new governance maturity folders enforce forbidden terms',()=>{ const dirs=['../lib/governance-precedence/','../lib/evidence-integrity/','../lib/governance-certification/','../lib/enterprise-realism/','../lib/governance-contradictions/','../lib/explainability-citations/','../lib/execution-eligibility/','../lib/blast-radius-governance/','../lib/reversibility-classification/','../lib/post-execution-verification/','../lib/recurrence-prevention/','../lib/governance-trust/','../lib/execution-certification/','../lib/governed-dry-run/','../lib/connector-execution-contracts/','../lib/approval-gated-execution-planning/','../lib/rollback-compensation/','../lib/outcome-ledger-execution-proof/','../lib/economic-attribution-graph/','../lib/runtime-economic-intelligence/','../lib/governed-execution-simulation/','../lib/execution-runtime-boundary/','../lib/m365-governed-execution-adapter/','../lib/end-to-end-execution-readiness/','../lib/cross-module-invariants/','../lib/runtime-calibration-learning/','../lib/mcp-cost-control/','../lib/snowflake-governance-pack/','../lib/databricks-governance-pack/','../lib/finance-grade-tbm/','../lib/cost-per-outcome-economics/','../lib/metadata-contextual-optimization/','../lib/transparent-optimization-actions/','../lib/ai-agent-runtime-governance/']; const forbidden=['kubectl','deletepod','patchdeployment','restartpod','scaledeployment','applymanifest','cloudexecute','executeaws','executeazure','executegcp','agentexecute','modelroute','promptrewrite','gpuschedule','autooptimize','autoremediate','mutate','mutationpayload','workflowfork','runtimefork','replayfork','orchestrationfork','autonomousoptimization','policyexecution','dynamicexecution','uninstalljava','removejava','changeoracleconfig','alterdatabase','migrateworkload','reassignlicense','scanendpoint','deployagent','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test('oracle-java-governance-pack and servicenow-sam-realism boundary keywords enforced',()=>{ const dirs=['../lib/oracle-java-governance-pack/','../lib/servicenow-sam-realism/']; const forbidden=['legalcomplianceverdict','compliantnow','noncompliantnow','oraclelmsclone','uninstalljavanow','alteroracledatabasenow','enableoracleoptionnow','changepartitioningnow','mutateservicenowrecord','triggerservicenowworkflow','removesoftwarenow','reclaimentitlementnow','modifyentitlementnow','livemutation','directmutation','bypassgovernance','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test('forecasting and digital twin folders enforce forbidden forecasting terms',()=>{ const dirs=['../lib/digital-twin-foundation/','../lib/economic-forecasting/','../lib/governance-scenario-simulation/','../lib/forecast-calibration/']; const forbidden=['stochasticforecast','blackboxprediction','autonomousbudgetaction','autocommitmentpurchase','executeforecastaction','mutatebudgetnow','aihallucinationforecast','uncontrolledoptimization','orchestrationruntime','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test('enterprise-operational-realism folders enforce forbidden terms',()=>{ const dirs=['../lib/economic-elasticity-realism/','../lib/seasonality-business-cycle/','../lib/organizational-behavior-curves/','../lib/execution-failure-propagation/','../lib/gpu-ai-scaling-realism/','../lib/topology-graph-realism/','../lib/savings-decay-realism/','../lib/platform-governance-hardening/']; const forbidden=['blackboxprediction','autonomousoptimization','uncontrolledexecution','orchestrationruntime','livemutation','stochasticai','hallucinatedforecast','executenow','eval']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});



test("quantitative depth folders enforce deterministic boundary terms",()=>{ const dirs=["../lib/quantitative-depth/","../lib/confidence-bounds/","../lib/unit-economics-formulas/","../lib/nonlinear-propagation/","../lib/savings-durability-formulas/","../lib/execution-realization-formulas/","../lib/scenario-chain-explainability/"]; const forbidden=["stochasticforecast","randomsimulation","blackboxprediction","hallucinatedforecast","autonomousoptimization","executenow","livemutation","eval"]; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),"utf8")).join("\n").toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test("empirical calibration folders enforce forbidden terms",()=>{ const dirs=["../lib/coefficient-provenance/","../lib/enterprise-benchmark-fixtures/","../lib/replay-calibration/","../lib/empirical-elasticity-packs/","../lib/workload-volatility-benchmarking/","../lib/savings-persistence-benchmarking/","../lib/organizational-timing-benchmarks/","../lib/calibration-drift-governance/"]; const forbidden=["hiddencoefficient","blackboxcalibration","stochastictuning","autonomousretuning","livebenchmarkfetch","opaqueweighting","executenow","livemutation","eval"]; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),"utf8")).join("\n").toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test("governed execution runtime folders enforce forbidden terms",()=>{ const dirs=["../lib/governed-execution-contracts/","../lib/execution-certification/","../lib/execution-policy-engine/","../lib/execution-simulation/","../lib/execution-lineage/","../lib/governed-execution-connectors/","../lib/execution-replay-governance/","../lib/execution-ux-contracts/"]; const forbidden=["autonomousremediation","executeimmediately","uncontrolledmutation","hiddenexecution","selfmodifyingexecution","livekubernetesmutation","destructiveaction","backgroundautomation","eval"]; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),"utf8")).join("\n").toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test("controlled live execution folders enforce forbidden terms",()=>{ const dirs=["../lib/live-execution-transactions/","../lib/governed-live-connectors/","../lib/rollback-enforcement/","../lib/execution-runtime-guardrails/","../lib/execution-window-enforcement/","../lib/post-execution-verification/","../lib/execution-forensics/","../lib/execution-verdict-engine/"]; const forbidden=["autonomousremediation","hiddenmutation","unrestrictedexecution","selfmodifyingexecution","uncontrolledcloudmutation","kubernetescontrolplane","backgroundautomation","broaddestructiveaction","eval"]; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),"utf8")).join("\n").toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test("canonical runtime folders enforce forbidden terms",()=>{ const dirs=["../lib/canonical-runtime-orchestration/","../lib/runtime-phase-adapters/","../lib/canonical-runtime-pipeline/","../lib/runtime-proof-continuity/","../lib/runtime-verdict-continuity/","../lib/runtime-narrative-engine/","../lib/runtime-replay-learning/","../lib/runtime-interface-contracts/"]; const forbidden=["genericworkflowengine","arbitrarytaskrunner","hiddenexecution","bypasscanonicalruntime","skipgovernance","backgroundremediation","uncontrolledorchestration","kubernetescontroller","eval"]; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),"utf8")).join("\n").toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false));});});

test('connector semantics realism folders enforce boundaries',()=>{ const dirs=['../lib/connector-capability-model/','../lib/connector-action-semantics/','../lib/execution-dependency-graph/','../lib/partial-failure-semantics/','../lib/rollback-dependency-chains/','../lib/connector-transaction-realism/','../lib/execution-topology-realism/','../lib/execution-concurrency-realism/','../lib/multi-step-governed-execution/','../lib/enterprise-operational-constraints/']; const forbidden=['genericworkflowengine','arbitrarytaskrunner','kubernetesmutation','unrestrictedcloudmutation','hiddenexecution','bypassconnectorcapability','unboundedretry','uncontrolledconcurrency','backgroundremediation','placeholderonly','deterministiconlyplaceholder','scaffoldonly','connectorasorchestrator','bypasscanonicalruntime','providerspecificorchestrator','uncontrolledprovidermutation','hiddenproviderlogic','eval']; const allowed=['semanticprofile','connectorcapability','actionsemantics','dependencygraph','rollbackchain','preflight','postflight','boundedretry','executionlock','operationalconstraint','partialfailure','multistepgovernance','providersemanticprofile','propagationrisk','dependencyrisk','verificationdelay','rollbacksemantics','providerrealism']; dirs.forEach((d)=>{ const body=fs.readdirSync(new URL(d, import.meta.url)).map((n)=>fs.readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k)=>assert.equal(body.includes(k), false)); assert.ok(allowed.some((k)=>body.includes(k))); });});

test('calibration folders enforce forbidden terms',()=>{ const dirs=['../lib/semantic-weight-registry/','../lib/provider-risk-calibration/','../lib/propagation-delay-calibration/','../lib/verification-window-calibration/','../lib/rollback-success-calibration/','../lib/approval-friction-calibration/','../lib/blast-radius-calibration/','../lib/replay-semantic-learning/','../lib/calibrated-verdict-impact/']; const forbidden=['hiddenweight','blackboxscoring','automutateweight','stochasticprediction','mltuning','livetelemetrydependency','providerruntimebypass','bypasscanonicalruntime','eval']; const allowed=['semanticweight','calibratedrisk','verificationwindow','rollbacksuccess','approvalfriction','blastradiuscalibration','replaylearningproposal','calibratedverdict']; dirs.forEach((d)=>{ const body=require('node:fs').readdirSync(new URL(d, import.meta.url)).map((n:string)=>require('node:fs').readFileSync(new URL(`${d}${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); forbidden.forEach((k:string)=>assert.equal(body.includes(k), false)); assert.ok(allowed.some((k)=>body.includes(k))); });});

test('positioning boundary forbids runtime-governance terminology',()=>{ const body=require('node:fs').readFileSync(new URL('../lib/economic-operations-productization.ts', import.meta.url),'utf8').toLowerCase(); ['runtime governance','runtime platform','runtime control plane','runtime orchestration'].forEach((k)=>assert.equal(body.includes(k), false));});
