import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { governedActionService } from "../lib/actions/governed-actions";
import { createDefaultExecutionConnector } from "../lib/execution/execution-connectors";
import { governedExecutionService } from "../lib/execution/governed-execution";
import { outcomeProtectionService } from "../lib/outcome-protection/outcome-protection";
import { economicOutcomeAttributionService } from "../lib/economic-outcomes/economic-outcome-attribution";
import { approvalAuthorityEngine } from "../lib/approval-authority/approval-authority";
import { trustReadinessAuthorityService } from "../lib/trust-readiness/trust-readiness-authority";
import { clearConnectorHealth, evaluateConnectorHealth, refreshConnectorCredentialMetadata } from "../lib/connectors/connector-health";
import { evaluateEvidenceExportReadiness } from "../lib/evidence-pack/evidence-export-readiness";
import { assertNoCrossTenantMutation, assertTenantScopedCollection, assertTenantScopedResource, clearTenantExecutionPolicies, evaluateLiveTenantExecutionGate, getLiveTenantReadinessDashboard, getTenantExecutionPolicy, requireRole, setTenantExecutionPolicy, structuredProductionError, validateAuditCompleteness } from "../lib/runtime/live-tenant-safety";

const tenantId = "tenant-live-hardening";
function reset() { governedExecutionService.clear(); governedActionService.clear(); approvalAuthorityEngine.clear(); trustReadinessAuthorityService.clear(); outcomeProtectionService.clear(); economicOutcomeAttributionService.clearForTests(); clearConnectorHealth(); clearTenantExecutionPolicies(); }
function connector() { return governedExecutionService.registerConnector(createDefaultExecutionConnector({ tenantId, connectorType: "M365", executionMode: "APPROVAL_REQUIRED" })); }
async function action(overrides: Record<string, unknown> = {}) { return governedActionService.create({ tenantId, title: "Live tenant M365 action", domain: "M365", sourceType: "RECOMMENDATION", sourceId: "user-live", status: "APPROVED", priority: "MEDIUM", readiness: "APPROVAL_REQUIRED", ownerId: "owner", approverId: "approver", trustScore: 0.9, projectedMonthlyValue: 10, projectedAnnualValue: 120, blastRadius: "LOW", rollbackCapability: "FULL", recommendationIds: ["rec-live"], evidenceIds: ["recommendation-live", "trust-live", "approval-live", "rollback-live"], ...overrides } as any); }
function gateInput(policy: any, act: any, conn: any, extra: any = {}) { return { policy, action: act, trustAuthorityReport: { verdict: "ELIGIBLE" }, approvalAuthorityReport: { verdict: "APPROVED" }, connector: conn, wedgeCertification: { certified: true }, request: { tenantId, domain: "M365", executionMode: "CONTROLLED", dryRun: false, destructive: true, blastRadius: "LOW", ...extra } } as any; }

test("tenant runtime modes centrally gate writes and dry-runs", async () => { reset(); const conn = connector(); const act = await action(); assert.equal(evaluateLiveTenantExecutionGate(gateInput(setTenantExecutionPolicy({ tenantId, mode: "DEMO" }), act, conn)).verdict, "BLOCK_DEMO_MODE"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(setTenantExecutionPolicy({ tenantId, mode: "PILOT_READ_ONLY" }), act, conn)).verdict, "BLOCK_READ_ONLY_MODE"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(getTenantExecutionPolicy(tenantId), act, conn, { executionMode: "SIMULATION", dryRun: true })).verdict, "DRY_RUN_ONLY"); setTenantExecutionPolicy({ tenantId, mode: "PILOT_CONTROLLED_EXECUTION" }); assert.equal(evaluateLiveTenantExecutionGate(gateInput(getTenantExecutionPolicy(tenantId), act, conn)).verdict, "ALLOW"); });

test("production controlled execution requires certified wedge, trust, approval, evidence and rollback", async () => { reset(); const conn = connector(); const act = await action(); refreshConnectorCredentialMetadata(tenantId, conn.id, { scopes: ["a"], requiredScopes: ["a"] }); evaluateConnectorHealth({ tenantId, connectorId: conn.id }); const policy = setTenantExecutionPolicy({ tenantId, mode: "PRODUCTION_CONTROLLED_EXECUTION" }); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, act, conn)).verdict, "ALLOW"); assert.equal(evaluateLiveTenantExecutionGate({ ...gateInput(policy, act, conn), wedgeCertification: { certified: false } }).verdict, "BLOCK_UNCERTIFIED_WEDGE"); assert.equal(evaluateLiveTenantExecutionGate({ ...gateInput(policy, act, conn), trustAuthorityReport: { verdict: "BLOCKED" } }).verdict, "BLOCK_TRUST"); assert.equal(evaluateLiveTenantExecutionGate({ ...gateInput(policy, act, conn), approvalAuthorityReport: { verdict: "PENDING" } }).verdict, "BLOCK_APPROVAL"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, await action({ id: "no-evidence", evidenceIds: [] }), conn)).verdict, "BLOCK_EVIDENCE"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, await action({ id: "no-rollback", rollbackCapability: "NONE" }), conn)).verdict, "BLOCK_ROLLBACK"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(setTenantExecutionPolicy({ tenantId, mode: "PRODUCTION_CONTROLLED_EXECUTION", maxBlastRadiusAllowed: "LOW" }), await action({ id: "high-blast", blastRadius: "HIGH" }), conn, { blastRadius: "HIGH" })).verdict, "BLOCK_BLAST_RADIUS"); });

test("connector health blocks or downgrades live execution", async () => { reset(); const conn = connector(); const act = await action(); const policy = setTenantExecutionPolicy({ tenantId, mode: "PRODUCTION_CONTROLLED_EXECUTION" }); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, act, conn)).reasons.some((r: string) => r.includes("Connector health")), true); refreshConnectorCredentialMetadata(tenantId, conn.id, { credentialExpiresAt: "2000-01-01T00:00:00Z" }); assert.equal(evaluateConnectorHealth({ tenantId, connectorId: conn.id }).status, "EXPIRED_CREDENTIALS"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, act, conn)).verdict, "BLOCK_READ_ONLY_MODE"); refreshConnectorCredentialMetadata(tenantId, conn.id, { scopes: ["a"], requiredScopes: ["a", "b"] }); assert.equal(evaluateConnectorHealth({ tenantId, connectorId: conn.id }).status, "MISSING_SCOPES"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, act, conn)).verdict, "BLOCK_EVIDENCE"); refreshConnectorCredentialMetadata(tenantId, conn.id, { statusOverride: "RATE_LIMITED", scopes: ["a"], requiredScopes: ["a"] }); assert.equal(evaluateConnectorHealth({ tenantId, connectorId: conn.id }).status, "RATE_LIMITED"); assert.equal(evaluateLiveTenantExecutionGate(gateInput(policy, act, conn)).verdict, "DRY_RUN_ONLY"); });

test("tenant isolation assertions and evidence export/audit readiness identify unsafe state", async () => { reset(); const act = await action(); assert.throws(() => assertTenantScopedResource(tenantId, { tenantId: "other" }), /TENANT_SCOPE/); assert.throws(() => assertTenantScopedCollection(tenantId, [{ tenantId }] as any).concat(assertTenantScopedCollection(tenantId, [{ tenantId: "other" }] as any)), /TENANT_SCOPE/); assert.throws(() => assertNoCrossTenantMutation(tenantId, { tenantId: "other" }), /CROSS_TENANT/); const audit = await validateAuditCompleteness(tenantId, act.id); assert.equal(audit.complete, false); assert.equal(audit.missingItems.includes("Pre-state evidence"), true); const exportReady = await evaluateEvidenceExportReadiness({ tenantId, actionId: act.id, wedge: "M365" }); assert.equal(exportReady.ready, false); assert.equal(exportReady.missingItems.includes("PRE_STATE_EVIDENCE"), true); });

test("role guards and production errors are structured", () => { reset(); assert.throws(() => requireRole(["EXECUTIVE_VIEWER"], "EXECUTE"), /ROLE_NOT_AUTHORIZED/); assert.equal(requireRole(["OPERATOR"], "EXECUTE"), true); const error = structuredProductionError("CONNECTOR_NOT_READY", "CONNECTOR_ISSUE", "Connector unhealthy", "Refresh connector credentials.", true); assert.deepEqual(Object.keys(error), ["code", "classification", "message", "remediation", "retryable"]); assert.equal(error.retryable, true); });

test("live tenant readiness dashboard reports wedge status and blocks production when audit/evidence incomplete", async () => { reset(); const conn = connector(); await action(); refreshConnectorCredentialMetadata(tenantId, conn.id, { scopes: ["a"], requiredScopes: ["a"] }); const health = [evaluateConnectorHealth({ tenantId, connectorId: conn.id })]; setTenantExecutionPolicy({ tenantId, mode: "PRODUCTION_CONTROLLED_EXECUTION" }); const dashboard = await getLiveTenantReadinessDashboard(tenantId, { m365: true, ai: true, servicenow: true }, health); assert.deepEqual(dashboard.certifiedWedges, { m365: true, ai: true, servicenow: true }); assert.equal(dashboard.readyForPilot, true); assert.equal(dashboard.readyForProduction, false); assert.equal(dashboard.evidenceExportReadiness.blocked > 0, true); });

test("hardening source applies to certified wedges and avoids autonomous or prohibited labels", () => { const files = ["src/lib/runtime/live-tenant-safety.ts", "src/lib/connectors/connector-health.ts", "src/routes/runtime.ts", "src/lib/connectors/m365/m365-graph-execution.ts", "src/lib/ai-economic-control/ai-provider-execution.ts", "src/lib/connectors/servicenow/servicenow-execution.ts"].map((file) => fs.readFileSync(path.join(process.cwd(), file), "utf8")).join("\n"); for (const text of ["M365", "AI", "SERVICENOW", "evaluateLiveTenantExecutionGate", "evaluateConnectorHealth", "validateAuditCompleteness", "evaluateEvidenceExportReadiness"]) assert.equal(files.includes(text), true); assert.equal(files.includes("autonomous: true"), false); assert.equal(files.includes("LeftShield"), false); assert.equal(files.includes("Agent Security Analytics"), false); });
