import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { ProductionConnectorRegistry, ProductionConnectorRunner, M365GraphClient, m365Fixtures, entraFixtures, flexeraFixtures, erpFixtures, ERPProfileRegistry, serviceNowFixtures } from "../lib/production-connectors";
describe("production connectors", () => {
  const registry = ProductionConnectorRegistry.withDefaults();
  it("registers all production connector families", () => { assert.deepEqual(new Set(registry.list().map((c) => c.connectorFamily)), new Set(["M365", "ENTRA_ID", "FLEXERA", "ERP", "SERVICENOW"])); });
  it("M365 capability and normalisers work with a mocked Graph client", async () => { const m365 = registry.get("m365"); const caps = await m365.discoverCapabilities({ tenantId: "t1", connectorKey: "m365", tokenProvider: async () => "token", client: new M365GraphClient({ tokenProvider: async () => "token" }) }); assert.equal(caps.status, "READY"); assert.equal(m365.normalise(m365Fixtures[0]).outputContract, "OWNERSHIP_USER"); assert.equal(m365.normalise(m365Fixtures[1]).outputContract, "TECHNOLOGY_ENTITLEMENT"); assert.equal(m365.normalise(m365Fixtures[2]).outputContract, "USAGE_SIGNAL"); const copilot = m365.normalise(m365Fixtures[3]); assert.equal(copilot.status, "WARN"); assert.equal(copilot.normalised?.status, "NOT_AVAILABLE"); });
  it("Entra maps identity ownership and preserves missing cost centre", () => { const entra = registry.get("entra-id"); const user = entra.normalise(entraFixtures[0]); assert.equal(user.outputContract, "OWNERSHIP_USER"); assert.deepEqual(user.normalised?.missingFields, ["costCentreId"]); const graph = entra.mapToGraph([entra.normalise(entraFixtures[1])]); assert.equal(graph.edges[0]?.type, "MANAGES"); });
  it("Flexera normalises contracts, entitlements, renewals and exposes export fallback", async () => { const flexera = registry.get("flexera"); assert.equal(flexera.normalise(flexeraFixtures[0]).outputContract, "TECHNOLOGY_CONTRACT"); assert.equal(flexera.normalise(flexeraFixtures[1]).outputContract, "TECHNOLOGY_ENTITLEMENT"); assert.equal(flexera.normalise(flexeraFixtures[2]).outputContract, "COMMERCIAL_RENEWAL"); const caps = await flexera.discoverCapabilities({ tenantId: "t1", connectorKey: "flexera" }); assert.ok(caps.endpointStatus.some((e) => e.endpoint === "export/file" && e.status === "AVAILABLE")); });
  it("ERP profiles and finance normalisers are registered", () => { const erp = registry.get("erp"); assert.ok(ERPProfileRegistry.includes("SAP")); assert.equal(erp.normalise(erpFixtures[0]).outputContract, "FINANCIAL_INVOICE"); assert.equal(erp.normalise(erpFixtures[1]).outputContract, "FINANCIAL_PURCHASE_ORDER"); assert.equal(erp.normalise(erpFixtures[2]).outputContract, "FINANCIAL_VENDOR_SPEND"); assert.equal(erp.normalise(erpFixtures[3]).outputContract, "FINANCIAL_COST_CENTRE"); });
  it("ServiceNow maps applications, owners, CMDB edges and missing tables", async () => { const sn = registry.get("servicenow"); assert.equal(sn.normalise(serviceNowFixtures[0]).outputContract, "APPLICATION_GRAPH_NODE"); assert.equal(sn.normalise(serviceNowFixtures[1]).outputContract, "OWNERSHIP_ASSIGNMENT"); assert.equal(sn.mapToGraph([sn.normalise(serviceNowFixtures[2])]).edges[0]?.type, "DEPENDS_ON"); const caps = await sn.discoverCapabilities({ tenantId: "t1", connectorKey: "servicenow" }); assert.ok(caps.endpointStatus.some((e) => e.endpoint === "missing_table" && e.status === "UNAVAILABLE")); });
  it("runner enforces dry-run/write-plan/sync safety", async () => { const runner = new ProductionConnectorRunner(registry); const dry = await runner.dryRun("t1", "m365", { tokenProvider: async () => "token", config: { useFixtures: true } }); assert.equal(dry.authorityWrites, 0); const plan = await runner.buildWritePlan("t1", "m365", { tokenProvider: async () => "token", config: { useFixtures: true } }); assert.equal(plan.safeToApply, false); assert.ok(plan.writes.length > 0); assert.equal((await runner.sync("t1", "m365", {})).failureReason, "TOKEN_PROVIDER_NOT_CONFIGURED"); assert.equal((await runner.sync("t1", "m365", { tokenProvider: async () => "token" })).failureReason, "CONNECTOR_CONFIG_NOT_AUTHORISED"); assert.equal((await runner.sync("t1", "m365", { tokenProvider: async () => "token", authorised: true })).failureReason, "LIVE_TENANT_READINESS_GATE_FAILED"); const synced = await runner.sync("t1", "m365", { tokenProvider: async () => "token", authorised: true, liveTenantReady: true, config: { useFixtures: true } }); assert.equal(synced.status, "COMPLETED"); assert.ok(synced.graphWrites > 0); assert.ok(synced.evidenceRefs.length > 0); });
  it("dry-run against an unconfigured/uncredentialed tenant is BLOCKED, never silently completed with fixture data", async () => {
    const runner = new ProductionConnectorRunner(registry);
    const dry = await runner.dryRun("t1", "m365", { tokenProvider: async () => "token" });
    assert.equal(dry.status, "BLOCKED");
    assert.equal(dry.failureReason, "MICROSOFT_CREDENTIALS_NOT_CONFIGURED");
    assert.equal(dry.recordsDiscovered, 0);
  });
});
