import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
test('runtime boundaries preserved',()=>{ const a=fs.readFileSync(new URL('../lib/runtime-hardening/runtime-hardening-phase-a.ts', import.meta.url),'utf8'); const c=fs.readFileSync(new URL('../lib/runtime-hardening/sustained-runtime-load-phase-c.ts', import.meta.url),'utf8'); const d=fs.readFileSync(new URL('../lib/runtime-hardening/runtime-resilience-phase-d.ts', import.meta.url),'utf8'); const e=fs.readFileSync(new URL('../lib/runtime-hardening/runtime-validation-phase-e.ts', import.meta.url),'utf8'); ['execution-engine','auto-approval','autonomous'].forEach(k=>{assert.equal(a.includes(k),false);assert.equal(c.includes(k),false);assert.equal(d.includes(k),false);assert.equal(e.includes(k),false);}); ['AUTO_EXECUTE','AUTO_REMEDIATE','AGENTIC_EXECUTION','SELF_HEALING_AUTONOMY'].forEach(k=>{assert.equal(d.includes(k),false);assert.equal(e.includes(k),false);});});

test('decision-intelligence remains non-executing',()=>{ const m=fs.readFileSync(new URL('../lib/decision-intelligence/recommendation-arbitration-engine.ts', import.meta.url),'utf8'); ['AUTO_EXECUTE','AUTO_REMEDIATE','graph.microsoft.com','ServiceNow','autonomous execution'].forEach(k=>assert.equal(m.includes(k), false)); });


test("m365 decision integration layer remains non-executing",()=>{ const m=fs.readFileSync(new URL('../lib/decision-intelligence/m365-expansion-pack-1.ts', import.meta.url),'utf8'); ['AUTO_EXECUTE','AUTO_REMEDIATE','graph.microsoft.com','executionPayload'].forEach(k=>assert.equal(m.includes(k), false)); });


test("ai-economics boundary keywords absent",()=>{ const ai=fs.readFileSync(new URL("../lib/ai-economics/ai-decision-intelligence-integration.ts", import.meta.url),"utf8")+fs.readFileSync(new URL("../lib/ai-economics/ai-cost-playbooks.ts", import.meta.url),"utf8"); ["AUTO_EXECUTE","AUTO_REMEDIATE","approval bypass","direct vendor API mutation","new execution engine","new replay engine","new telemetry engine","new workflow engine"].forEach(k=>assert.equal(ai.includes(k), false)); });


test("cross-domain-economics boundary keywords absent",()=>{ const x=fs.readFileSync(new URL("../lib/cross-domain-economics/cross-domain-recommendation-arbitration.ts", import.meta.url),"utf8")+fs.readFileSync(new URL("../lib/cross-domain-economics/cross-domain-economic-report.ts", import.meta.url),"utf8"); ["AUTO_EXECUTE","AUTO_REMEDIATE","autonomous spend control","autonomous licence changes","autonomous model switching","autonomous procurement actions","direct vendor API mutation","approval bypass","execution engine creation","replay engine fork","telemetry engine fork","workflow engine fork","outcome-ledger fork"].forEach(k=>assert.equal(x.includes(k), false)); });

test('economic-forecasting boundary keywords absent',()=>{ const ef=fs.readFileSync(new URL('../lib/economic-forecasting/index.ts', import.meta.url),'utf8')+fs.readFileSync(new URL('../lib/economic-forecasting/economic-intelligence-report.ts', import.meta.url),'utf8'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous procurement','autonomous budget mutation','autonomous vendor actions','direct SaaS mutation','approval bypass','execution-engine creation','replay-engine fork','telemetry-engine fork','workflow-engine fork','outcome-ledger fork'].forEach(k=>assert.equal(ef.includes(k), false)); });

test('economic-simulation boundary keywords absent',()=>{ const sim=fs.readFileSync(new URL('../lib/economic-simulation/index.ts', import.meta.url),'utf8')+fs.readFileSync(new URL('../lib/economic-simulation/economic-scenario-report.ts', import.meta.url),'utf8'); ['AUTO_EXECUTE','AUTO_REMEDIATE','autonomous procurement','autonomous SaaS mutation','autonomous vendor actions','approval bypass','execution engine creation','replay engine forks','telemetry engine forks','workflow engine forks'].forEach(k=>assert.equal(sim.includes(k), false)); });


test('economic-memory boundary keywords absent',()=>{ const dir=new URL('../lib/economic-memory/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/economic-memory/${n}`, import.meta.url),'utf8')).join('\n'); ['auto execute','auto remediate','vendor mutation','policy mutation','budget mutation','autonomous procurement','autonomous licence change','autonomous model switching','execution engine','replay fork','telemetry fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.toLowerCase().includes(k), false)); });

test('finops-operationalization boundary keywords absent',()=>{ const dir=new URL('../lib/finops-operationalization/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/finops-operationalization/${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); ['auto_execute','auto_remediate','direct cloud mutation','resource deletion','resource resize execution','commitment purchase','servicenow api mutation','budget mutation','vendor mutation','approval bypass','new execution engine','replay fork','telemetry fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.includes(k), false)); });

test('executive-economic-governance boundary keywords absent',()=>{ const dir=new URL('../lib/executive-economic-governance/', import.meta.url); const names=fs.readdirSync(dir); const body=names.map((n)=>fs.readFileSync(new URL(`../lib/executive-economic-governance/${n}`, import.meta.url),'utf8')).join('\n').toLowerCase(); ['auto_execute','auto_remediate','autonomous budgeting','autonomous procurement','policy mutation','erp mutation','servicenow mutation','cloud mutation','vendor mutation','execution engine','replay fork','telemetry fork','workflow fork','ui route','ui component'].forEach((k)=>assert.equal(body.includes(k), false)); });
