import test from 'node:test'; import assert from 'node:assert/strict';
import { createInMemoryTechnologyCommercialAuthorityStores, TechnologyCommercialAuthorityRepository, TechnologyCommercialAuthorityService } from '../lib/technology-commercial-authority';
function svc(graph:any={createNode:async()=>({}),createEdge:async()=>({})}){return new TechnologyCommercialAuthorityService(new TechnologyCommercialAuthorityRepository(createInMemoryTechnologyCommercialAuthorityStores()),graph)}
test('technology commercial authority CRUD, isolation, validation, calculations, summaries and graph links',async()=>{const nodes:any[]=[];const edges:any[]=[];const s=svc({createNode:async(n:any)=>nodes.push(n),createEdge:async(e:any)=>edges.push(e)}); const tenantId='tca-a';
 const v=await s.createVendor({tenantId,name:'OpenAI',category:'AI',currency:'USD',riskLevel:'MEDIUM',annualSpend:100}); assert.equal((await (s as any).repo.listVendors(tenantId)).length,1); assert.equal((await (s as any).repo.getVendor(tenantId,v.id))?.name,'OpenAI'); assert.equal((await (s as any).repo.listVendors('other')).length,0);
 await assert.rejects(()=>s.createVendor({tenantId,name:'Bad',category:'AI',currency:'USD',riskLevel:'LOW',annualSpend:-1} as any),/negative spend/);
 const c=await s.createContract({tenantId,vendorId:v.id,name:'EA',status:'ACTIVE',startDate:'2026-01-01',endDate:'2026-12-31',autoRenewal:true,currency:'USD',auditRights:true,trueUpRights:true,committedSpend:100}); assert.equal((await (s as any).repo.getContract(tenantId,c.id))?.name,'EA'); assert.equal((await (s as any).repo.listContracts(tenantId,{vendorId:v.id})).length,1);
 const e=await s.createEntitlement({tenantId,vendorId:v.id,contractId:c.id,productName:'Seats',entitlementType:'SEAT',totalQuantity:10,assignedQuantity:4,currency:'USD',annualCost:50}); assert.equal((await (s as any).repo.getEntitlement(tenantId,e.id))?.productName,'Seats'); assert.deepEqual(s.calculateEntitlementUtilisation(e),{used:4,available:6,utilisationPercent:40}); await assert.rejects(()=>s.createEntitlement({tenantId,vendorId:v.id,productName:'Bad',entitlementType:'SEAT',totalQuantity:-1,currency:'USD'} as any),/negative quantity/);
 const cm=await s.createCommitment({tenantId,vendorId:v.id,contractId:c.id,entitlementId:e.id,commitmentType:'MINIMUM_SEATS',committedValue:10,consumedValue:4,startDate:'2026-01-01',endDate:'2026-12-31'}); assert.equal((await (s as any).repo.getCommitment(tenantId,cm.id))?.remainingValue,6); assert.equal(s.detectBlockedSavings({},e,c,cm),true);
 const r=await s.createRenewal({tenantId,vendorId:v.id,contractId:c.id,renewalDate:'2026-10-01',currentAnnualSpend:100,negotiationLeverage:'HIGH',readinessScore:80,status:'ANALYSIS'}); assert.equal((await (s as any).repo.getRenewal(tenantId,r.id))?.status,'ANALYSIS'); assert.ok(s.calculateRenewalReadiness(r,c,[e],[cm],[])>=0&&s.calculateRenewalReadiness(r,c,[e],[cm],[])<=100); await assert.rejects(()=>s.createRenewal({tenantId,vendorId:v.id,contractId:c.id,renewalDate:'2026-10-01',currentAnnualSpend:1,negotiationLeverage:'LOW',readinessScore:101,status:'ANALYSIS'} as any),/0-100/);
 const x=await s.createExposure({tenantId,vendorId:v.id,contractId:c.id,entitlementId:e.id,exposureType:'AUTO_RENEWAL',severity:'CRITICAL',currency:'USD',description:'auto renew'}); assert.equal((await (s as any).repo.getExposure(tenantId,x.id))?.severity,'CRITICAL');
 const vs=await s.summariseVendorCommercialPosition(tenantId,v.id); assert.equal(vs.contractCount,1); assert.equal(vs.entitlementCount,1); assert.equal(vs.renewalCount,1); assert.equal(vs.exposureCount,1); assert.ok(vs.totalSpend>0);
 const ps=await s.summariseTenantCommercialPortfolio(tenantId); assert.equal(ps.vendorCount,1); assert.equal(ps.contractCount,1); assert.equal(ps.criticalExposureCount,1); assert.ok(nodes.some(n=>n.entityType==='VENDOR')); assert.ok(edges.some(e=>e.relationshipType==='HAS_CONTRACT'));});
test('graph failure is recorded but authority write succeeds',async()=>{const s=svc({createNode:async()=>{throw new Error('graph down')},createEdge:async()=>{}}); const v=await s.createVendor({tenantId:'graph-fail',name:'Vendor',category:'OTHER',currency:'USD',riskLevel:'LOW'}); assert.equal(v.name,'Vendor')});
