import { randomUUID } from 'node:crypto';
import { EconomicGraphService } from '../economic-graph/economic-graph-service';
import { InMemoryEconomicGraphRepository } from '../economic-graph/economic-graph-repository';
import { platformEventService } from '../events/platform-event-service';
import { OutcomeFinanceReconciliationRepository, outcomeFinanceReconciliationRepository } from './outcome-finance-reconciliation-repository';
import type { Confidence, OutcomeFinanceAttribution as A, OutcomeFinanceConfidenceSnapshot as C, OutcomeFinanceReconciliationLink as L, OutcomeFinanceValueLedgerEntry as E, OutcomeFinanceVarianceRecord as V } from './outcome-finance-reconciliation-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}_${randomUUID()}`; const sum=(xs:number[])=>xs.reduce((a,b)=>a+(b||0),0); const conf=(s:number):Confidence=>s>=80?'HIGH':s>=50?'MEDIUM':'LOW';
export const outcomeFinancePlatformEvents:any[]=[];
export class OutcomeFinanceEconomicGraphAdapter{constructor(private readonly graph:any=new EconomicGraphService()){}
 async node(type:string,id:string,data:any){return this.graph.createNode({tenantId:data.tenantId,entityType:type,canonicalName:id,canonicalKey:id,confidenceScore:1,evidence:[{sourceSystem:'outcome-finance-reconciliation',sourceReferenceId:id,observedAt:now()}],metadata:{outcomeFinanceReconciliation:true,...data}})}
 async edge(tenantId:string,from:string,type:string,to:string,sourceId:string){return this.graph.createEdge({tenantId,fromEntityId:from,toEntityId:to.includes(':')?to.split(':').slice(1).join(':'):to,relationshipType:type,confidenceScore:1,evidence:[{sourceSystem:'outcome-finance-reconciliation',sourceReferenceId:sourceId,observedAt:now()}]})}
 listNodes(t:string){return this.graph.listNodes(t)} listEdges(t:string){return this.graph.listEdges(t)} hasPath(t:string,f:string,to:string){return this.graph.hasPath(t,f,to)} }
export class InMemoryOutcomeFinanceGraphWriter extends OutcomeFinanceEconomicGraphAdapter{repo:InMemoryEconomicGraphRepository; nodes:any[]; edges:any[]; constructor(){const repo=new InMemoryEconomicGraphRepository(); super(new EconomicGraphService(repo)); this.repo=repo; this.nodes=repo.nodes; this.edges=repo.edges}}
export class OutcomeFinanceReconciliationService{constructor(private repo:OutcomeFinanceReconciliationRepository=outcomeFinanceReconciliationRepository, private graph:any=new OutcomeFinanceEconomicGraphAdapter()){} getGraphWriter(){return this.graph}
 private async glink(a:any,kind:string){try{await this.graph.node(kind,a.id,a); const edge=(from:string,type:string,to:string)=>this.graph.edge(a.tenantId,from,type,to,a.id); if(kind==='VALUE_ATTRIBUTION'){if(a.recommendationId)await edge(a.id,'DERIVED_FROM',`RECOMMENDATION:${a.recommendationId}`); if(a.actionId)await edge(a.id,'DERIVED_FROM',`GOVERNED_ACTION:${a.actionId}`); if(a.executionId)await edge(a.id,'DERIVED_FROM',`EXECUTION:${a.executionId}`); if(a.outcomeId)await edge(a.id,'VERIFIES',`OUTCOME_EVENT:${a.outcomeId}`); if(a.financeReconciliationId)await edge(a.id,'GOVERNED_BY',`FINANCE_RECONCILIATION:${a.financeReconciliationId}`)} else {if(a.attributionId)await edge(a.id,'DERIVED_FROM',`VALUE_ATTRIBUTION:${a.attributionId}`); if(a.costCentreId)await edge(a.id,'BELONGS_TO',`COST_CENTRE:${a.costCentreId}`); if(a.executiveOwnerId)await edge(a.id,'OWNED_BY',`EXECUTIVE_OWNER:${a.executiveOwnerId}`); if(kind==='FINANCE_RECONCILIATION_LINK'){await edge(a.id,'DERIVED_FROM',`FINANCE_RECONCILIATION:${a.financeReconciliationId}`); if(a.outcomeId)await edge(a.id,'VERIFIES',`OUTCOME_EVENT:${a.outcomeId}`)} if(kind==='CONFIDENCE_SNAPSHOT'&&a.evidenceRefs?.length)await edge(a.id,'SUPPORTED_BY_EVIDENCE',`EVIDENCE_PACK:${a.evidenceRefs[0]}`)}}catch(e){const event={eventType:'OUTCOME_FINANCE_GRAPH_LINK_FAILED',error:String((e as Error).message),createdAt:now()}; outcomeFinancePlatformEvents.push(event); await platformEventService.recordSystemEvent(a.tenantId??'unknown','OUTCOME_FINANCE_GRAPH_LINK_FAILED',{severity:'WARNING',metadata:event}).catch(()=>undefined)}}
 async createAttribution(input:Partial<A>&Pick<A,'tenantId'>){const t=now(); const a={id:id('ofr_attr'),attributionType:'PROJECTED',projectedSavings:0,expectedSavings:0,currency:'USD',confidence:'LOW',status:'PENDING',source:'outcome-finance-reconciliation',evidenceRefs:[],...input,createdAt:input.createdAt??t,updatedAt:t} as A; const saved=await this.repo.upsertAttribution(a); await this.glink(saved,'VALUE_ATTRIBUTION'); return saved}
 async appendValueLedgerEntry(input:Partial<E>&Pick<E,'tenantId'|'attributionId'|'eventType'|'amount'|'currency'>){const t=now(); const e={id:id('ofr_ledger'),evidenceRefs:[],source:'outcome-finance-reconciliation',occurredAt:t,createdAt:t,...input} as E; const saved=await this.repo.appendLedgerEntry(e); await this.glink(saved,'VALUE_LEDGER_ENTRY'); return saved}
 calculateVariance(expected:number,actual?:number){const varianceAmount=(actual??0)-expected; return {varianceAmount,variancePercent:expected===0?undefined:varianceAmount/expected*100}}
 calculateVarianceSeverity(variancePercent?:number, expected=0, actual?:number):V['severity']{if(variancePercent===undefined)return expected>0&&actual===undefined?'HIGH':'LOW'; const a=Math.abs(variancePercent); return a<=10?'LOW':a<=25?'MEDIUM':a<=50?'HIGH':'CRITICAL'}
 async createVarianceRecord(input:Partial<V>&Pick<V,'tenantId'|'attributionId'|'expectedSavings'|'varianceType'>){const actual=input.varianceType==='EXPECTED_VS_EXECUTED'?input.executedSavings:input.verifiedSavings; const c=this.calculateVariance(input.expectedSavings,actual); const t=now(); const v={id:id('ofr_var'),severity:this.calculateVarianceSeverity(c.variancePercent,input.expectedSavings,actual),source:'outcome-finance-reconciliation',evidenceRefs:[],...input,...c,createdAt:input.createdAt??t,updatedAt:t} as V; const saved=await this.repo.upsertVarianceRecord(v); await this.glink(saved,'VARIANCE_RECORD'); return saved}
 async createReconciliationLink(input:Partial<L>&Pick<L,'tenantId'|'financeReconciliationId'|'linkType'>){const t=now(); const l={id:id('ofr_link'),linkConfidence:1,source:'outcome-finance-reconciliation',evidenceRefs:[],...input,createdAt:input.createdAt??t,updatedAt:t} as L; const saved=await this.repo.upsertReconciliationLink(l); await this.glink(saved,'FINANCE_RECONCILIATION_LINK'); return saved}
 calculateConfidenceSnapshot(input:any){const fields=['recommendationPresent','actionPresent','executionPresent','outcomePresent','financeReconciliationPresent','ownershipPresent','evidencePresent']; const tr=fields.filter(f=>!!input[f]).length; const score=tr===7?100:tr*14; return {confidenceScore:score,confidence:conf(score),missingFields:fields.filter(f=>!input[f])}}
 async createConfidenceSnapshot(input:Partial<C>&Pick<C,'tenantId'|'attributionId'>){const calc=this.calculateConfidenceSnapshot(input); const t=now(); const s={id:id('ofr_conf'),recommendationPresent:false,actionPresent:false,executionPresent:false,outcomePresent:false,financeReconciliationPresent:false,ownershipPresent:false,evidencePresent:false,source:'outcome-finance-reconciliation',evidenceRefs:[],...input,...calc,createdAt:input.createdAt??t,updatedAt:t} as C; const saved=await this.repo.upsertConfidenceSnapshot(s); await this.glink(saved,'CONFIDENCE_SNAPSHOT'); return saved}
 buildAttributionFromFinanceReconciliation(tenantId:string,financeReconciliationId:string){return this.createAttribution({tenantId,financeReconciliationId,attributionType:'VERIFIED',status:'PENDING',source:'finance-reconciliation'})}
 buildAttributionFromOutcome(tenantId:string,outcomeId:string){return this.createAttribution({tenantId,outcomeId,attributionType:'EXECUTED',status:'PENDING',source:'outcome'})}
 async linkOutcomeToFinanceReconciliation(tenantId:string,outcomeId:string,financeReconciliationId:string){return this.createReconciliationLink({tenantId,outcomeId,financeReconciliationId,linkType:'OUTCOME_TO_RECONCILIATION',linkConfidence:1})}
 async summariseAttribution(t:string,idv:string){const attribution=await this.repo.getAttribution(t,idv); if(!attribution)return undefined; const ledger=await this.repo.listLedgerEntries(t,{attributionId:idv}); const variances=await this.repo.listVarianceRecords(t,{attributionId:idv}); const snapshots=await this.repo.listConfidenceSnapshots(t,{attributionId:idv}); return {attribution,ledger,variances,confidence:snapshots.at(-1)}}
 private async summary(t:string,f:Record<string,unknown>={}){const a=await this.repo.listAttributions(t,f), l=await this.repo.listLedgerEntries(t,f), v=await this.repo.listVarianceRecords(t,f); const expected=sum(a.map(x=>x.expectedSavings)), verified=sum(a.map(x=>x.verifiedSavings??0)); const varianceAmount=verified-expected; return {projectedSavings:sum(a.map(x=>x.projectedSavings)),expectedSavings:expected,executedSavings:sum(a.map(x=>x.executedSavings??0)),verifiedSavings:verified,varianceAmount,variancePercent:expected===0?undefined:varianceAmount/expected*100,attributionCount:a.length,verifiedAttributionCount:a.filter(x=>x.status==='VERIFIED').length,disputedAttributionCount:a.filter(x=>x.status==='DISPUTED').length,rejectedAttributionCount:a.filter(x=>x.status==='REJECTED').length,confidenceBreakdown:{LOW:a.filter(x=>x.confidence==='LOW').length,MEDIUM:a.filter(x=>x.confidence==='MEDIUM').length,HIGH:a.filter(x=>x.confidence==='HIGH').length},ledgerEntryCount:l.length,varianceRecordCount:v.length}}
 summariseTenantOutcomeFinance(t:string){return this.summary(t)} summariseCostCentreOutcomeFinance(t:string,costCentreId:string){return this.summary(t,{costCentreId})} summariseExecutiveOutcomeFinance(t:string,executiveOwnerId:string){return this.summary(t,{executiveOwnerId})}}
export const outcomeFinanceReconciliationService=new OutcomeFinanceReconciliationService();
