import { createPersistenceStore, MemoryPersistenceStore } from './outcome-finance-reconciliation-persistence';
import type { OutcomeFinanceAttribution as A, OutcomeFinanceConfidenceSnapshot as C, OutcomeFinanceReconciliationLink as L, OutcomeFinanceValueLedgerEntry as E, OutcomeFinanceVarianceRecord as V, PersistenceStore } from './outcome-finance-reconciliation-types';
export interface OutcomeFinanceReconciliationStores{attributions:PersistenceStore<A>;ledger:PersistenceStore<E>;variances:PersistenceStore<V>;links:PersistenceStore<L>;snapshots:PersistenceStore<C>}
export const createOutcomeFinanceReconciliationStores=():OutcomeFinanceReconciliationStores=>({attributions:createPersistenceStore('OUTCOME_FINANCE_ATTRIBUTIONS'),ledger:createPersistenceStore('OUTCOME_FINANCE_VALUE_LEDGER_ENTRIES'),variances:createPersistenceStore('OUTCOME_FINANCE_VARIANCE_RECORDS'),links:createPersistenceStore('OUTCOME_FINANCE_RECONCILIATION_LINKS'),snapshots:createPersistenceStore('OUTCOME_FINANCE_CONFIDENCE_SNAPSHOTS')});
export const createInMemoryOutcomeFinanceReconciliationStores=():OutcomeFinanceReconciliationStores=>({attributions:new MemoryPersistenceStore('OUTCOME_FINANCE_ATTRIBUTIONS'),ledger:new MemoryPersistenceStore('OUTCOME_FINANCE_VALUE_LEDGER_ENTRIES'),variances:new MemoryPersistenceStore('OUTCOME_FINANCE_VARIANCE_RECORDS'),links:new MemoryPersistenceStore('OUTCOME_FINANCE_RECONCILIATION_LINKS'),snapshots:new MemoryPersistenceStore('OUTCOME_FINANCE_CONFIDENCE_SNAPSHOTS')});
const anchor=(a:A)=>!!(a.recommendationId||a.actionId||a.executionId||a.outcomeId||a.financeReconciliationId); const req=(v:any,k:string)=>{if(!v[k])throw new Error(`${k} is required`)};
export class OutcomeFinanceReconciliationRepository{constructor(private stores:OutcomeFinanceReconciliationStores=createOutcomeFinanceReconciliationStores()){} getStores(){return this.stores}
 async upsertAttribution(a:A){if(!anchor(a))throw new Error('attribution requires at least one business anchor');return this.stores.attributions.upsert(a)} async getAttribution(t:string,id:string){return this.stores.attributions.get(t,id)} async listAttributions(t:string,f?:Record<string,unknown>){return this.stores.attributions.list(t,f)}
 async appendLedgerEntry(e:E){req(e,'attributionId'); if(e.amount<0&&!['VALUE_ADJUSTED','VALUE_REJECTED'].includes(e.eventType))throw new Error('negative ledger amount rejected'); if(await this.stores.ledger.get(e.tenantId,e.id))throw new Error('ledger entries are append-only'); return this.stores.ledger.upsert(e)} async getLedgerEntry(t:string,id:string){return this.stores.ledger.get(t,id)} async listLedgerEntries(t:string,f?:Record<string,unknown>){return this.stores.ledger.list(t,f)}
 async upsertVarianceRecord(v:V){req(v,'attributionId');return this.stores.variances.upsert(v)} async getVarianceRecord(t:string,id:string){return this.stores.variances.get(t,id)} async listVarianceRecords(t:string,f?:Record<string,unknown>){return this.stores.variances.list(t,f)}
 async upsertReconciliationLink(l:L){if(l.linkConfidence<0||l.linkConfidence>1)throw new Error('link confidence must be 0-1');return this.stores.links.upsert(l)} async getReconciliationLink(t:string,id:string){return this.stores.links.get(t,id)} async listReconciliationLinks(t:string,f?:Record<string,unknown>){return this.stores.links.list(t,f)}
 async upsertConfidenceSnapshot(s:C){req(s,'attributionId'); if(s.confidenceScore<0||s.confidenceScore>100)throw new Error('confidence score must be 0-100'); return this.stores.snapshots.upsert(s)} async getConfidenceSnapshot(t:string,id:string){return this.stores.snapshots.get(t,id)} async listConfidenceSnapshots(t:string,f?:Record<string,unknown>){return this.stores.snapshots.list(t,f)}
 async deleteTenantOutcomeFinanceData(t:string){await Promise.all(Object.values(this.stores).map(s=>s.deleteTenant(t)))} }
export const outcomeFinanceReconciliationRepository=new OutcomeFinanceReconciliationRepository();
