export interface AuthorityCatalogEntry {
  id: string;
  name: string;
  status: "ACTIVE" | "AVAILABLE" | "PREVIEW" | "PLANNED" | "BLOCKED";
  category: "TECHNOLOGY" | "AI" | "ITAM" | "CLOUD" | "WORKFLOW" | "FINANCE";
  description: string;
  connectors: string[];
  discoverySupported: boolean;
  executionSupported: boolean;
  verificationSupported: boolean;
  protectionSupported: boolean;
  opportunityCount?: number;
  projectedAnnualValue?: number;
  evidenceReady: boolean;
  certified: boolean;
  nextAction: string;
}

export const defaultAuthorities: AuthorityCatalogEntry[] = [
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    status: "ACTIVE",
    category: "TECHNOLOGY",
    description: "Identify, reclaim and protect Microsoft 365 licence value.",
    connectors: ["Microsoft Graph", "Entra ID"],
    discoverySupported: true,
    executionSupported: true,
    verificationSupported: true,
    protectionSupported: true,
    opportunityCount: 24,
    projectedAnnualValue: 320000,
    evidenceReady: true,
    certified: true,
    nextAction: "Run discovery",
  },
  {
    id: "ai-economic-control",
    name: "AI Economic Control",
    status: "AVAILABLE",
    category: "AI",
    description: "Govern AI spend, usage and exposure across model providers.",
    connectors: ["OpenAI", "Azure OpenAI", "Anthropic"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: true,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Connect AI usage sources",
  },
  {
    id: "flexera-itam",
    name: "Flexera / ITAM",
    status: "AVAILABLE",
    category: "ITAM",
    description: "Reconcile software asset entitlements and usage with ITAM data.",
    connectors: ["Flexera"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: true,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Connect Flexera",
  },
  {
    id: "aws-cost-governance",
    name: "AWS Cost Governance",
    status: "AVAILABLE",
    category: "CLOUD",
    description: "Identify and govern wasted spend across AWS accounts and organizations.",
    connectors: ["AWS Cost Explorer", "AWS Organizations"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: true,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Connect AWS",
  },
  {
    id: "snowflake-governance",
    name: "Snowflake Governance",
    status: "PLANNED",
    category: "CLOUD",
    description: "Govern Snowflake compute and storage spend against usage patterns.",
    connectors: ["Snowflake"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: false,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Coming soon",
  },
  {
    id: "databricks-governance",
    name: "Databricks Governance",
    status: "PLANNED",
    category: "CLOUD",
    description: "Govern Databricks workspace and compute spend against usage patterns.",
    connectors: ["Databricks"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: false,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Coming soon",
  },
  {
    id: "servicenow-execution",
    name: "ServiceNow Execution",
    status: "AVAILABLE",
    category: "WORKFLOW",
    description: "Execute governed actions and approvals through ServiceNow workflows.",
    connectors: ["ServiceNow"],
    discoverySupported: false,
    executionSupported: true,
    verificationSupported: false,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Connect ServiceNow",
  },
  {
    id: "azure-cost-governance",
    name: "Azure Cost Governance",
    status: "AVAILABLE",
    category: "CLOUD",
    description: "Identify and govern wasted spend across Azure subscriptions.",
    connectors: ["Azure Cost Management"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: true,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Connect Azure",
  },
  {
    id: "erp-finance",
    name: "ERP / Finance",
    status: "PREVIEW",
    category: "FINANCE",
    description: "Reconcile ERP financial records with cost governance outcomes.",
    connectors: ["SAP", "NetSuite", "Workday"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: false,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Join preview",
  },
  {
    id: "procurement-ap",
    name: "Procurement / AP",
    status: "PREVIEW",
    category: "FINANCE",
    description: "Surface procurement and accounts payable signals for spend governance.",
    connectors: ["Coupa", "Ariba"],
    discoverySupported: true,
    executionSupported: false,
    verificationSupported: false,
    protectionSupported: false,
    evidenceReady: false,
    certified: false,
    nextAction: "Join preview",
  },
];
