export type RecommendationMode = "READ_ONLY" | "RECOMMEND_ONLY" | "APPROVAL_REQUIRED";
export type RiskClass = "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
export interface CandidateEvidenceSummary { evidenceId: string; source: string; collectedAt: string; freshnessHours?: number; confidence?: number; notes?: string; }
export interface CandidateSavingsEstimate { annualizedSavingsEstimate: number; monthlySavingsEstimate?: number; currency: string; savingsConfidence: "LOW"|"MODERATE"|"HIGH"; methodology?: string; }
export interface CandidateRiskProfile { actionRiskClass: RiskClass; reversibility: "LOW"|"MEDIUM"|"HIGH"; blastRadius: "LOW"|"MEDIUM"|"HIGH"|"CRITICAL"; riskReasons: string[]; }
export interface CandidateTrustProfile { trustScore: number; trustBand: "VERY_HIGH"|"HIGH"|"MODERATE"|"LOW"; trustReasons: string[]; usageSignalFreshnessDays?: number; evidenceQuality?: number; }
export interface CandidateOperationalContext { ownerId?: string; ownerType?: string; ownerDefined: boolean; department?: string; costCenter?: string; recentActivityDays?: number; privileged: boolean; serviceAccount: boolean; sharedMailbox: boolean; vip: boolean; contractor: boolean; businessCriticalGroupMember: boolean; }
export interface CandidateApprovalRequirement { approvalRequired: boolean; requiredApproverRole?: string; escalationRequired?: boolean; approvalReasons: string[]; }
export interface CandidateArbitrationMetadata { precedenceHint?: number; mutuallyExclusiveGroup?: string; conflictHints?: string[]; emittedByVersion?: string; }
export interface RecommendationCandidate { candidateId: string; tenantId: string; domain: string; sourcePlaybookId: string; sourcePlaybookName: string; entityType: string; entityId: string; entityDisplayName: string; proposedActionType: string; proposedActionLabel: string; recommendationMode: RecommendationMode; evidenceRefs: CandidateEvidenceSummary[]; trustSnapshot: CandidateTrustProfile; actionRiskProfile: CandidateRiskProfile; savingsEstimate: CandidateSavingsEstimate; operationalContext: CandidateOperationalContext; approvalRequirement: CandidateApprovalRequirement; arbitrationMetadata?: CandidateArbitrationMetadata; createdAt: string; idempotencyKey: string; }
export interface FinalRecommendationDecision { candidateId: string; finalDecision: "PROMOTED"|"PROMOTED_WITH_APPROVAL"|"SUPPRESSED_DUPLICATE"|"SUPPRESSED_CONFLICT"|"DEFERRED"|"BLOCKED"; finalMode: RecommendationMode; arbitrationReasons: string[]; suppressionReasons: string[]; approvalEscalationReasons: string[]; winningCandidateId?: string; relatedCandidateIds: string[]; confidenceScore?: number; sensitivityClass?: RiskClass; }
