export type CloudProvider='AWS'|'AZURE'|'GCP'|'MULTI_CLOUD'|'UNKNOWN';
export type CloudResourceType='COMPUTE_INSTANCE'|'BLOCK_STORAGE'|'OBJECT_STORAGE'|'DATABASE'|'LOAD_BALANCER'|'STATIC_IP'|'SNAPSHOT'|'KUBERNETES_CLUSTER'|'CONTAINER_WORKLOAD'|'GPU_INSTANCE'|'AI_INFERENCE_ENDPOINT'|'DATA_TRANSFER'|'OTHER';
export type CloudEnvironmentType='PRODUCTION'|'STAGING'|'DEV'|'TEST'|'SANDBOX'|'UNKNOWN';
export type CloudRecommendationCategory='IDLE_REVIEW'|'RIGHTSIZE_REVIEW'|'SHUTDOWN_REVIEW'|'STORAGE_LIFECYCLE_REVIEW'|'TRANSFER_COST_REVIEW'|'AUTOSCALING_REVIEW'|'ENVIRONMENT_TTL_REVIEW'|'OWNERSHIP_REMEDIATION'|'GPU_UTILIZATION_REVIEW';
export type GovernanceMode='READ_ONLY'|'RECOMMEND_ONLY'|'APPROVAL_REQUIRED';
export interface CloudUtilizationSignal { cpuUtilization?:number; memoryUtilization?:number; storageUtilization?:number; networkUtilization?:number; gpuUtilization?:number; activeHours?:number; idleHours?:number; requestVolume?:number; activityRecencyHours?:number; }
export interface CloudCostSignal { monthlyCost:number; annualizedCost?:number; currency?:string; }
export interface CloudOwnershipSignal { ownerId?:string; ownerConfidence?:number; costCenter?:string; tags?:Record<string,string>; }
export interface CloudWorkloadSignal { usageVariability?:number; seasonality?:number; burstiness?:number; deploymentFrequency?:number; batchIndicator?:boolean; scheduledIndicator?:boolean; businessCycleDependency?:number; }
export interface CloudResourceEconomicSignal extends CloudUtilizationSignal, CloudCostSignal, CloudOwnershipSignal, CloudWorkloadSignal { tenantId:string; provider?:CloudProvider; accountId?:string; subscriptionId?:string; projectId?:string; resourceId:string; resourceName?:string; resourceType?:CloudResourceType; serviceName?:string; region?:string; environmentType?:CloudEnvironmentType; resourceCriticality?:'LOW'|'MEDIUM'|'HIGH'; evidenceRefs?:string[]; sourceSystem?:string; sourceCreatedAt?:string; sourceUpdatedAt?:string; replayCorrelationId?:string; lineageCorrelationId?:string; }
export interface CloudUtilizationEconomics { utilizationEfficiencyScore:number; wasteScore:number; economicWasteEstimate:number; rightsizingPotential:number; shutdownPotential:number; confidence:number; reasons:string[]; }
export interface CloudIdleConfidenceResult { idleConfidenceScore:number; idleConfidenceBand:'VERY_HIGH'|'HIGH'|'MODERATE'|'LOW'|'INSUFFICIENT_EVIDENCE'; idleReasons:string[]; falsePositiveRisk:number; recommendedReviewMode:GovernanceMode; }
export interface CloudWorkloadVolatilityResult { volatilityScore:number; volatilityBand:'HIGH'|'MEDIUM'|'LOW'; volatilityReasons:string[]; rightsizingRisk:number; shutdownRisk:number; forecastingRisk:number; }
export interface CloudAutoscalingWasteResult { autoscalingWasteScore:number; estimatedMonthlyWaste:number; estimatedAnnualWaste:number; scalingRisk:number; recommendedReview:string; confidence:number; }
export interface CloudEnvironmentLifecycleResult { lifecycleWasteScore:number; ttlPolicyRecommended:boolean; shutdownScheduleRecommended:boolean; ownerReviewRequired:boolean; estimatedMonthlySavings:number; recurrencePreventionPolicyHint:string; confidence:number; }
export interface CloudStorageLifecycleEconomics { storageWasteScore:number; lifecyclePolicyRecommended:boolean; archiveRecommended:boolean; deletionReviewRecommended:boolean; estimatedMonthlyWaste:number; retentionRisk:number; confidence:number; }
export interface CloudDataTransferEconomics { transferWasteScore:number; estimatedMonthlyTransferWaste:number; transferPatternRisk:number; optimizationReviewRecommended:boolean; confidence:number; reasons:string[]; }
export interface CloudEconomicRecommendation { recommendationId:string; tenantId:string; resourceId:string; recommendationCategory:CloudRecommendationCategory; recommendationSummary:string; estimatedMonthlySavings:number; estimatedAnnualSavings:number; confidence:number; recommendedMode:GovernanceMode; operationalRisk:number; evidenceRefs:string[]; replayCorrelationId:string; lineageCorrelationId:string; }
export interface CloudEconomicReport { tenantId:string; resourceCount:number; totalMonthlyCloudCost:number; totalAnnualizedCloudCost:number; estimatedMonthlyWaste:number; estimatedAnnualWaste:number; idleReviewCount:number; rightsizeReviewCount:number; shutdownReviewCount:number; storageReviewCount:number; transferReviewCount:number; autoscalingReviewCount:number; ownershipRemediationCount:number; averageUtilizationEfficiency:number; averageIdleConfidence:number; averageVolatility:number; cloudEconomicHealth:number; topWasteAreas:string[]; topRiskAreas:string[]; recommendedNextActions:string[]; readinessStatus:'READY_FOR_FINOPS_OPERATIONALIZATION'|'READY_WITH_LIMITS'|'HARDENING_REQUIRED'; }
