import type { ConnectorManifest,ConnectorFamily,AuthorityDomain,OutputContract,AuthType } from './connector-readiness-types';
const t='2026-01-01T00:00:00.000Z';
const base=(family:ConnectorFamily,name:string,domains:AuthorityDomain[],contracts:OutputContract[],authType:AuthType='API_KEY'):ConnectorManifest=>({connectorKey:family.toLowerCase(),connectorName:name,connectorFamily:family,supportedDomains:domains,authType,requiredScopes:[`${family}:read`],optionalScopes:[`${family}:metadata`],configSchema:{type:'object',required:['endpoint'],properties:{endpoint:{type:'string'},tenantHint:{type:'string'}}},capabilityManifest:{canDiscover:true,canValidate:true,canDryRunSync:true,canIngest:false,canWriteBack:false,canProduceEvidence:true,canMapToGraph:true},outputContracts:contracts,requiredForUseCases:['GENERAL'],readinessRequirements:['Manifest registered','Configuration saved','Authorization reference present','Sample payload validates','Graph mapping preview ready'],evidenceRequirements:['Configuration evidence','Dry-run evidence','Validation evidence','Graph-mapping evidence'],riskNotes:['Readiness only: no live third-party API calls and no authority ingestion.'],status:'READY',createdAt:t,updatedAt:t});
export const defaultConnectorManifests:ConnectorManifest[]=[
base('M365','Microsoft 365',['IDENTITY','USAGE','COMMERCIAL','ACTIONS','EVIDENCE','GRAPH'],['OWNERSHIP_USER','TECHNOLOGY_ENTITLEMENT','USAGE_SIGNAL','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'OAUTH2'),
base('ENTRA_ID','Azure AD / Entra ID',['IDENTITY','OWNERSHIP','GRAPH'],['OWNERSHIP_USER','OWNERSHIP_DEPARTMENT','OWNERSHIP_ASSIGNMENT','GRAPH_NODE','GRAPH_EDGE'],'OAUTH2'),
base('FLEXERA','Flexera',['COMMERCIAL','USAGE','EVIDENCE','GRAPH'],['COMMERCIAL_VENDOR','TECHNOLOGY_CONTRACT','TECHNOLOGY_ENTITLEMENT','COMMERCIAL_COMMITMENT','COMMERCIAL_RENEWAL','USAGE_SIGNAL','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE']),
base('SERVICENOW','ServiceNow',['COMMERCIAL','OWNERSHIP','ACTIONS','EVIDENCE','GRAPH'],['COMMERCIAL_VENDOR','OWNERSHIP_ASSIGNMENT','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE']),
base('ERP','ERP',['FINANCIAL','COMMERCIAL','EVIDENCE','GRAPH'],['FINANCIAL_VENDOR_SPEND','FINANCIAL_INVOICE','FINANCIAL_PURCHASE_ORDER','FINANCIAL_COST_CENTRE','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'SERVICE_ACCOUNT'),
base('AP','Accounts Payable',['FINANCIAL','EVIDENCE','GRAPH'],['FINANCIAL_INVOICE','FINANCIAL_VENDOR_SPEND','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'SERVICE_ACCOUNT'),
base('PROCUREMENT','Procurement',['COMMERCIAL','FINANCIAL','EVIDENCE','GRAPH'],['TECHNOLOGY_CONTRACT','COMMERCIAL_VENDOR','FINANCIAL_PURCHASE_ORDER','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE']),
base('HRIS','HRIS',['IDENTITY','OWNERSHIP','EVIDENCE','GRAPH'],['OWNERSHIP_USER','OWNERSHIP_DEPARTMENT','OWNERSHIP_ASSIGNMENT','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'SERVICE_ACCOUNT'),
base('SAAS_DISCOVERY','SaaS Discovery',['COMMERCIAL','USAGE','OWNERSHIP','GRAPH'],['COMMERCIAL_VENDOR','TECHNOLOGY_ENTITLEMENT','USAGE_SIGNAL','OWNERSHIP_ASSIGNMENT','GRAPH_NODE','GRAPH_EDGE']),
base('AI_PROVIDER','AI Provider',['USAGE','COMMERCIAL','OWNERSHIP','EVIDENCE','GRAPH'],['COMMERCIAL_VENDOR','TECHNOLOGY_ENTITLEMENT','USAGE_SIGNAL','OWNERSHIP_ASSIGNMENT','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE']),
base('MANUAL_UPLOAD','Manual Upload',['COMMERCIAL','FINANCIAL','OWNERSHIP','USAGE','EVIDENCE','GRAPH'],['COMMERCIAL_VENDOR','TECHNOLOGY_CONTRACT','TECHNOLOGY_ENTITLEMENT','FINANCIAL_INVOICE','FINANCIAL_VENDOR_SPEND','FINANCIAL_COST_CENTRE','OWNERSHIP_USER','OWNERSHIP_ASSIGNMENT','USAGE_SIGNAL','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'FILE_UPLOAD'),
base('CUSTOM','Custom Connector',['EVIDENCE','GRAPH'],['EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'],'CUSTOM')];
