import { createPersistenceStore, MemoryPersistenceStore } from './connector-readiness-persistence';
import { AUTH_TYPES, CONNECTOR_FAMILIES, type ConnectorConfig, type ConnectorDryRun, type ConnectorEvidenceOutput, type ConnectorGraphMapping, type ConnectorHealthCheck, type ConnectorManifest, type ConnectorValidationResult, type PersistenceStore } from './connector-readiness-types';
type WithTenant={id:string;tenantId:string}; type ManifestRecord=ConnectorManifest&WithTenant;
export interface ConnectorReadinessStores{manifests:PersistenceStore<ManifestRecord>;configs:PersistenceStore<ConnectorConfig>;health:PersistenceStore<ConnectorHealthCheck>;dryRuns:PersistenceStore<ConnectorDryRun>;validation:PersistenceStore<ConnectorValidationResult>;evidence:PersistenceStore<ConnectorEvidenceOutput>;graph:PersistenceStore<ConnectorGraphMapping>}
export const createConnectorReadinessStores=():ConnectorReadinessStores=>({manifests:createPersistenceStore('CONNECTOR_READINESS_MANIFESTS'),configs:createPersistenceStore('CONNECTOR_READINESS_CONFIGS'),health:createPersistenceStore('CONNECTOR_READINESS_HEALTH_CHECKS'),dryRuns:createPersistenceStore('CONNECTOR_READINESS_DRY_RUNS'),validation:createPersistenceStore('CONNECTOR_READINESS_VALIDATION_RESULTS'),evidence:createPersistenceStore('CONNECTOR_READINESS_EVIDENCE_OUTPUTS'),graph:createPersistenceStore('CONNECTOR_READINESS_GRAPH_MAPPINGS')});
export const createInMemoryConnectorReadinessStores=():ConnectorReadinessStores=>({manifests:new MemoryPersistenceStore('CONNECTOR_READINESS_MANIFESTS'),configs:new MemoryPersistenceStore('CONNECTOR_READINESS_CONFIGS'),health:new MemoryPersistenceStore('CONNECTOR_READINESS_HEALTH_CHECKS'),dryRuns:new MemoryPersistenceStore('CONNECTOR_READINESS_DRY_RUNS'),validation:new MemoryPersistenceStore('CONNECTOR_READINESS_VALIDATION_RESULTS'),evidence:new MemoryPersistenceStore('CONNECTOR_READINESS_EVIDENCE_OUTPUTS'),graph:new MemoryPersistenceStore('CONNECTOR_READINESS_GRAPH_MAPPINGS')});
const GLOBAL='__connector_manifest_registry__'; const req=(v:any,fs:string[])=>{for(const f of fs)if(v[f]===undefined||v[f]==='')throw new Error(`MISSING_REQUIRED_FIELD:${f}`)}; const valid=(x:any,xs:readonly string[],n:string)=>{if(!xs.includes(x))throw new Error(`INVALID_${n}`)};
export class ConnectorReadinessRepository{constructor(public stores:ConnectorReadinessStores=createConnectorReadinessStores()){} private async up<T extends WithTenant>(s:PersistenceStore<T>,v:T){req(v,['id','tenantId','source','createdAt','updatedAt']); if(!Array.isArray((v as any).evidenceRefs))throw new Error('INVALID_EVIDENCE_REFS'); return s.upsert(v)} private manifestRecord(m:ConnectorManifest):ManifestRecord{return {...m,id:m.connectorKey,tenantId:GLOBAL,source:'connector-readiness-registry',evidenceRefs:[] } as any}
 async upsertManifest(m:ConnectorManifest){req(m,['connectorKey','connectorName','connectorFamily','authType','status','createdAt','updatedAt']); valid(m.connectorFamily,CONNECTOR_FAMILIES,'CONNECTOR_FAMILY'); valid(m.authType,AUTH_TYPES,'AUTH_TYPE'); const existing=await this.getManifest(m.connectorKey); if(existing&&existing.connectorFamily!==m.connectorFamily)throw new Error('MANIFEST_CONNECTOR_KEY_NOT_UNIQUE'); return this.stores.manifests.upsert(this.manifestRecord(m)).then(()=>m)} async getManifest(k:string){const r=await this.stores.manifests.get(GLOBAL,k); if(!r)return undefined; const {id,tenantId,source,evidenceRefs,...m}=r as any; return m as ConnectorManifest} async listManifests(f:Record<string,unknown>={}){const rows=await this.stores.manifests.list(GLOBAL,f); return rows.map((r:any)=>{const {id,tenantId,source,evidenceRefs,...m}=r; return m as ConnectorManifest})}
 async upsertConfig(v:ConnectorConfig){valid(v.mode,['DEMO','LIVE'],'CONFIG_MODE'); if(v.mode==='LIVE'&&v.source==='demo-fixture')throw new Error('LIVE_CONFIG_REJECTS_DEMO_FIXTURE'); if(v.mode==='DEMO'&&v.source!=='demo-fixture')throw new Error('DEMO_MODE_REQUIRES_DEMO_SOURCE'); return this.up(this.stores.configs,v)} getConfig(t:string,id:string){return this.stores.configs.get(t,id)} listConfigs(t:string,f?:Record<string,unknown>){return this.stores.configs.list(t,f)}
 async upsertHealthCheck(v:ConnectorHealthCheck){return this.up(this.stores.health,v)} getHealthCheck(t:string,id:string){return this.stores.health.get(t,id)} listHealthChecks(t:string,f?:Record<string,unknown>){return this.stores.health.list(t,f)}
 async upsertDryRun(v:ConnectorDryRun){for(const k of ['recordsDetected','recordsValid','recordsRejected','graphMappingsPreviewed'])if((v as any)[k]<0)throw new Error('NEGATIVE_RECORD_COUNT'); if(v.recordsDetected!==v.recordsValid+v.recordsRejected)throw new Error('DRY_RUN_RECORD_COUNT_MISMATCH'); return this.up(this.stores.dryRuns,v)} getDryRun(t:string,id:string){return this.stores.dryRuns.get(t,id)} listDryRuns(t:string,f?:Record<string,unknown>){return this.stores.dryRuns.list(t,f)}
 async upsertValidationResult(v:ConnectorValidationResult){if(v.validRecords<0||v.rejectedRecords<0)throw new Error('NEGATIVE_RECORD_COUNT'); return this.up(this.stores.validation,v)} getValidationResult(t:string,id:string){return this.stores.validation.get(t,id)} listValidationResults(t:string,f?:Record<string,unknown>){return this.stores.validation.list(t,f)}
 async upsertEvidenceOutput(v:ConnectorEvidenceOutput){req(v,['id','tenantId','connectorKey','evidenceType','status','source','createdAt','updatedAt']); return this.stores.evidence.upsert(v)} getEvidenceOutput(t:string,id:string){return this.stores.evidence.get(t,id)} listEvidenceOutputs(t:string,f?:Record<string,unknown>){return this.stores.evidence.list(t,f)}
 async upsertGraphMapping(v:ConnectorGraphMapping){return this.up(this.stores.graph,v)} getGraphMapping(t:string,id:string){return this.stores.graph.get(t,id)} listGraphMappings(t:string,f?:Record<string,unknown>){return this.stores.graph.list(t,f)}
 async deleteTenantConnectorReadinessData(t:string){await Promise.all([this.stores.configs,this.stores.health,this.stores.dryRuns,this.stores.validation,this.stores.evidence,this.stores.graph].map(s=>s.deleteTenant(t)))} async collectionStatus(){return Object.fromEntries(await Promise.all(Object.entries(this.stores).map(async([k,s])=>[k,await s.size()])))} }
export const connectorReadinessRepository=new ConnectorReadinessRepository();
