export const CONNECTOR_FAMILIES=['M365','ENTRA_ID','FLEXERA','SERVICENOW','ERP','AP','PROCUREMENT','HRIS','SAAS_DISCOVERY','AI_PROVIDER','MANUAL_UPLOAD','CUSTOM'] as const;
export const AUTH_TYPES=['OAUTH2','API_KEY','SERVICE_ACCOUNT','FILE_UPLOAD','MANUAL','CUSTOM'] as const;
export const AUTHORITY_DOMAINS=['IDENTITY','COMMERCIAL','FINANCIAL','OWNERSHIP','USAGE','ACTIONS','EVIDENCE','GRAPH'] as const;
export const OUTPUT_CONTRACTS=['COMMERCIAL_VENDOR','TECHNOLOGY_CONTRACT','TECHNOLOGY_ENTITLEMENT','COMMERCIAL_COMMITMENT','COMMERCIAL_RENEWAL','FINANCIAL_INVOICE','FINANCIAL_PURCHASE_ORDER','FINANCIAL_VENDOR_SPEND','FINANCIAL_COST_CENTRE','OWNERSHIP_USER','OWNERSHIP_DEPARTMENT','OWNERSHIP_ASSIGNMENT','USAGE_SIGNAL','EVIDENCE_PACK','GRAPH_NODE','GRAPH_EDGE'] as const;
export type ConnectorFamily=typeof CONNECTOR_FAMILIES[number]; export type AuthType=typeof AUTH_TYPES[number]; export type AuthorityDomain=typeof AUTHORITY_DOMAINS[number]; export type OutputContract=typeof OUTPUT_CONTRACTS[number];
export type UseCase='M365_OPTIMISATION'|'AI_ECONOMIC_CONTROL'|'TECHNOLOGY_PORTFOLIO'|'COMMERCIAL_GOVERNANCE'|'FINANCIAL_VERIFICATION'|'GENERAL';
export interface ConnectorManifest{connectorKey:string;connectorName:string;connectorFamily:ConnectorFamily;supportedDomains:AuthorityDomain[];authType:AuthType;requiredScopes:string[];optionalScopes:string[];configSchema:Record<string,unknown>;capabilityManifest:{canDiscover:boolean;canValidate:boolean;canDryRunSync:boolean;canIngest:boolean;canWriteBack:boolean;canProduceEvidence:boolean;canMapToGraph:boolean};outputContracts:OutputContract[];requiredForUseCases:UseCase[];readinessRequirements:string[];evidenceRequirements:string[];riskNotes:string[];status:'DRAFT'|'READY'|'BLOCKED'|'DEPRECATED';createdAt:string;updatedAt:string}
export interface ConnectorConfig{id:string;tenantId:string;connectorKey:string;mode:'DEMO'|'LIVE';authType:string;configured:boolean;authorised:boolean;credentialRef?:string;config:Record<string,unknown>;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ConnectorHealthCheck{id:string;tenantId:string;connectorKey:string;status:'HEALTHY'|'DEGRADED'|'FAILED'|'NOT_CONFIGURED';checkedAt:string;reason?:string;nextStep?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ConnectorDryRun{id:string;tenantId:string;connectorKey:string;status:'PASS'|'WARN'|'FAIL';recordsDetected:number;recordsValid:number;recordsRejected:number;outputContracts:string[];graphMappingsPreviewed:number;evidenceGenerated:boolean;reason?:string;nextStep?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ConnectorValidationResult{id:string;tenantId:string;connectorKey:string;contractType:string;status:'PASS'|'WARN'|'FAIL';validRecords:number;rejectedRecords:number;errors:Array<{code:string;message:string;path?:string}>;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface ConnectorEvidenceOutput{id:string;tenantId:string;connectorKey:string;evidenceType:'CONFIGURATION'|'AUTHORIZATION'|'HEALTH_CHECK'|'DRY_RUN'|'VALIDATION'|'GRAPH_MAPPING'|'INGESTION_PREVIEW';status:'CREATED'|'FAILED';evidenceRef?:string;source:string;createdAt:string;updatedAt:string}
export interface ConnectorGraphMapping{id:string;tenantId:string;connectorKey:string;outputContract:string;nodeTypes:string[];edgeTypes:string[];status:'READY'|'PARTIAL'|'BLOCKED';reason?:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export type ConnectorReadinessCollection='CONNECTOR_READINESS_MANIFESTS'|'CONNECTOR_READINESS_CONFIGS'|'CONNECTOR_READINESS_HEALTH_CHECKS'|'CONNECTOR_READINESS_DRY_RUNS'|'CONNECTOR_READINESS_VALIDATION_RESULTS'|'CONNECTOR_READINESS_EVIDENCE_OUTPUTS'|'CONNECTOR_READINESS_GRAPH_MAPPINGS';
export interface PersistenceStore<T>{upsert(v:T):Promise<T>;get(t:string,id:string):Promise<T|undefined>;list(t:string,f?:Record<string,unknown>):Promise<T[]>;deleteTenant(t:string):Promise<void>;size():Promise<number>}
