import { liveTenantReadinessService } from '../live-tenant-readiness';
import { defaultConnectorManifests } from './connector-readiness-registry';
import { ConnectorReadinessRepository, connectorReadinessRepository } from './connector-readiness-repository';
import type { ConnectorManifest, ConnectorFamily, ConnectorEvidenceOutput } from './connector-readiness-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const stamp=(x:any)=>{const t=now();return {id:id('cr'),source:'connector-readiness-service',evidenceRefs:[],createdAt:t,updatedAt:t,...x}};
const domains=(contracts:string[])=>contracts.includes('FINANCIAL_INVOICE')?['FinancialRecord']:contracts.includes('OWNERSHIP_USER')?['User','Department']:['Vendor','Contract','Evidence'];
export class ConnectorReadinessService{constructor(public repo:ConnectorReadinessRepository=connectorReadinessRepository, public liveSvc:any=liveTenantReadinessService){} registerManifest(input:ConnectorManifest){return this.repo.upsertManifest(input)} async registerDefaultManifests(){return Promise.all(defaultConnectorManifests.map(m=>this.registerManifest({...m,updatedAt:now()})))} async configureConnector(tenantId:string,input:any){const m=await this.repo.getManifest(input.connectorKey); if(!m)throw new Error('CONNECTOR_MANIFEST_NOT_FOUND'); return this.repo.upsertConfig(stamp({tenantId,connectorKey:m.connectorKey,mode:input.mode??'LIVE',authType:input.authType??m.authType,configured:!!input.configured,authorised:!!input.authorised,credentialRef:input.credentialRef,config:input.config??{},source:input.source??'customer-config',evidenceRefs:input.evidenceRefs??[]}) as any)}
 async latestConfig(t:string,k:string){return (await this.repo.listConfigs(t,{connectorKey:k})).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]}
 async evaluateConnectorHealth(t:string,k:string){const c=await this.latestConfig(t,k); const status=!c?'NOT_CONFIGURED':!c.configured?'DEGRADED':!c.authorised?'FAILED':'HEALTHY'; const out=await this.repo.upsertHealthCheck(stamp({tenantId:t,connectorKey:k,status,checkedAt:now(),reason:status==='HEALTHY'?'Connector readiness prerequisites are met.':'Connector is not fully configured and authorised.',nextStep:status==='HEALTHY'?'Run dry-run sync.':'Complete connector configuration and authorization.',source:'connector-readiness-health',evidenceRefs:[]}) as any); await this.updateLiveTenantReadinessFromConnectors(t); return out}
 async validateOutputContract(t:string,k:string,contractType:string,sampleRecords:any[]=[]){const m=await this.repo.getManifest(k); const errors:any[]=[]; if(!m?.outputContracts.includes(contractType as any))errors.push({code:'UNSUPPORTED_CONTRACT',message:'Manifest does not support this contract type'}); sampleRecords.forEach((r,i)=>{if(!r||typeof r!=='object'||Object.keys(r).length===0)errors.push({code:'INVALID_SAMPLE_RECORD',message:'Sample record must be a non-empty object',path:`/${i}`})}); const rejected=errors.length?Math.max(1,errors.length):0, valid=errors.length?Math.max(0,sampleRecords.length-rejected):sampleRecords.length; const res=await this.repo.upsertValidationResult(stamp({tenantId:t,connectorKey:k,contractType,status:errors.length?'FAIL':sampleRecords.length?'PASS':'WARN',validRecords:valid,rejectedRecords:errors.length?rejected:0,errors,source:'connector-readiness-validation',evidenceRefs:[]}) as any); return res}
 async previewGraphMapping(t:string,k:string,outputContract:string){const m=await this.repo.getManifest(k); const ok=!!m?.outputContracts.includes(outputContract as any); return this.repo.upsertGraphMapping(stamp({tenantId:t,connectorKey:k,outputContract,nodeTypes:ok?domains([outputContract]):[],edgeTypes:ok?[`${outputContract}_MAPS_TO_GRAPH`]:[],status:ok?'READY':'BLOCKED',reason:ok?'Graph mapping preview ready.':'Output contract is not supported by this connector.',source:'connector-readiness-graph-preview',evidenceRefs:[]}) as any)}
 async generateConnectorEvidence(t:string,k:string,evidenceType:ConnectorEvidenceOutput['evidenceType']){return this.repo.upsertEvidenceOutput(stamp({tenantId:t,connectorKey:k,evidenceType,status:'CREATED',evidenceRef:`evidence://${t}/${k}/${evidenceType}/${Date.now()}`,source:'connector-readiness-evidence'}) as any)}
 async runDryRun(t:string,k:string){const c=await this.latestConfig(t,k), m=await this.repo.getManifest(k); if(!m)throw new Error('CONNECTOR_MANIFEST_NOT_FOUND'); if(!c||!c.configured||!c.authorised){const fail=await this.repo.upsertDryRun(stamp({tenantId:t,connectorKey:k,status:'FAIL',recordsDetected:0,recordsValid:0,recordsRejected:0,outputContracts:m.outputContracts,graphMappingsPreviewed:0,evidenceGenerated:false,reason:'Connector is not configured and authorised.',nextStep:'Configure and authorise connector.',source:'connector-readiness-dry-run',evidenceRefs:[]}) as any); await this.updateLiveTenantReadinessFromConnectors(t); return fail} const sample=m.outputContracts.map(x=>({contractType:x,sample:true})); const val=await this.validateOutputContract(t,k,m.outputContracts[0],sample); const mappings=await Promise.all(m.outputContracts.map(o=>this.previewGraphMapping(t,k,o))); const ev=await this.generateConnectorEvidence(t,k,'DRY_RUN'); const warn=!m.capabilityManifest.canProduceEvidence||!m.evidenceRequirements.length; const blocked=mappings.some(x=>x.status==='BLOCKED')||val.status==='FAIL'; const dr=await this.repo.upsertDryRun(stamp({tenantId:t,connectorKey:k,status:blocked?'FAIL':warn?'WARN':'PASS',recordsDetected:sample.length,recordsValid:blocked?0:sample.length,recordsRejected:blocked?sample.length:0,outputContracts:m.outputContracts,graphMappingsPreviewed:mappings.filter(x=>x.status==='READY').length,evidenceGenerated:!!ev.evidenceRef,reason:blocked?'Validation or graph mapping blocked.':warn?'Optional evidence capability is incomplete.':'Dry-run readiness passed without authority ingestion.',nextStep:blocked?'Fix validation or mapping issue.':'Connector can proceed to live readiness review.',source:'connector-readiness-dry-run',evidenceRefs:[ev.evidenceRef]}) as any); await this.updateLiveTenantReadinessFromConnectors(t); return dr}
 async summariseConnectorReadiness(t:string){const manifests=await this.repo.listManifests(); const configs=await this.repo.listConfigs(t); const dry=await this.repo.listDryRuns(t); const ready=manifests.filter(m=>dry.some(d=>d.connectorKey===m.connectorKey&&d.status==='PASS')).length; const partial=manifests.filter(m=>configs.some(c=>c.connectorKey===m.connectorKey)&&!dry.some(d=>d.connectorKey===m.connectorKey&&d.status==='PASS')).length; const blocked=dry.filter(d=>d.status==='FAIL').length; const status=blocked?'BLOCKED':ready===manifests.length&&manifests.length?'READY':ready||partial?'PARTIAL':'MISSING'; return {tenantId:t,status,ready,partial,blocked,missing:Math.max(0,manifests.length-ready-partial),total:manifests.length,connectors:manifests.map(m=>({connectorKey:m.connectorKey,connectorFamily:m.connectorFamily,status:dry.some(d=>d.connectorKey===m.connectorKey&&d.status==='PASS')?'READY':configs.some(c=>c.connectorKey===m.connectorKey)?'PARTIAL':'MISSING'}))}}
 async summariseConnectorFamilyReadiness(t:string,f:ConnectorFamily){const s=await this.summariseConnectorReadiness(t); const xs=s.connectors.filter((c:any)=>c.connectorFamily===f); return {tenantId:t,connectorFamily:f,status:xs.some((x:any)=>x.status==='READY')?'READY':xs.some((x:any)=>x.status==='PARTIAL')?'PARTIAL':'MISSING',connectors:xs}}
 async updateLiveTenantReadinessFromConnectors(t:string){const s=await this.summariseConnectorReadiness(t); for(const c of s.connectors){const m=await this.repo.getManifest(c.connectorKey); for(const d of m?.supportedDomains??[]) await this.liveSvc.upsertConnectorReadiness({tenantId:t,connectorKey:c.connectorKey,connectorName:m?.connectorName??c.connectorKey,domain:d,status:c.status==='READY'?'SYNCED':c.status==='PARTIAL'?'CONNECTED':'MISSING',health:c.status==='READY'?'HEALTHY':'NOT_APPLICABLE',requiredForLiveReadiness:false,source:'connector-readiness-service',evidenceRefs:[]});} await this.liveSvc.upsertDataCoverage({tenantId:t,domain:'EVIDENCE',coverageStatus:s.ready?'SUFFICIENT':'INSUFFICIENT',recordCount:s.ready,freshness:s.ready?'FRESH':'STALE',source:'connector-readiness-service',evidenceRefs:[]}); return s}}
export const connectorReadinessService=new ConnectorReadinessService();
