import { LiveTenantReadinessRepository, liveTenantReadinessRepository } from './live-tenant-readiness-repository';
import type { Domain, LiveTenantBlocker, LiveTenantReadinessSnapshot } from './live-tenant-readiness-types';
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const stamp=(v:any)=>{const t=now();return {id:id('ltr'),source:'platform',evidenceRefs:[],createdAt:t,updatedAt:t,...v}};
const risky=(v:any)=>v?.source==='demo-fixture'||v?.valueSource==='sample-tenant'||(v?.evidenceRefs??[]).some((e:string)=>e.toLowerCase().includes('demo'));
export class LiveTenantReadinessService{constructor(public repo:LiveTenantReadinessRepository=liveTenantReadinessRepository){}
 createTenantProfile(input:any){return this.repo.upsertTenantProfile(stamp(input) as any)} upsertConnectorReadiness(i:any){return this.repo.upsertConnectorReadiness(stamp(i) as any)} upsertDataCoverage(i:any){return this.repo.upsertDataCoverage(stamp(i) as any)} upsertReadinessCheck(i:any){return this.repo.upsertReadinessCheck(stamp(i) as any)} upsertOnboardingStep(i:any){return this.repo.upsertOnboardingStep(stamp(i) as any)} upsertSafetyGate(i:any){return this.repo.upsertSafetyGate(stamp(i) as any)} upsertBlocker(i:any){return this.repo.upsertBlocker(stamp(i) as any)}
 async evaluateRequiredConnectors(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p)return false; const cs=await this.repo.listConnectorReadiness(t); return p.requiredDomains.every(d=>cs.filter(c=>c.domain===d&&c.requiredForLiveReadiness).some(c=>['CONNECTED','SYNCED'].includes(c.status)&&['HEALTHY','NOT_APPLICABLE'].includes(c.health)))}
 async evaluateDataCoverage(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p)return false; const rows=await this.repo.listDataCoverage(t); return p.requiredDomains.every(d=>rows.filter(c=>c.domain===d).some(c=>['SUFFICIENT','COMPLETE','NOT_REQUIRED'].includes(c.coverageStatus)&&['FRESH','NOT_APPLICABLE'].includes(c.freshness)&&c.recordCount>=(c.minimumRequiredRecords??0)))}
 async evaluateSafetyGates(t:string){const gs=(await this.repo.listSafetyGates(t)).filter(g=>g.required); if(!gs.length)return false; return gs.every(g=>g.status==='PASSED'||(g.status==='WAIVED'&&!!(g.waiverReason&&g.waivedByUserId&&g.waivedAt)))}
 async evaluateDemoDataRisk(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p)return false; if(p.mode==='DEMO')return true; const all=[p,...await this.repo.listConnectorReadiness(t),...await this.repo.listDataCoverage(t),...await this.repo.listReadinessChecks(t),...await this.repo.listSafetyGates(t),...await this.repo.listBlockers(t)]; return all.some(risky)||process.env.DEMO_BANNER_ACTIVE==='true'||process.env.DEMO_SUMMARY_SOURCE==='demo-fixture'}
 async buildReadinessSnapshot(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p)throw new Error('TENANT_PROFILE_NOT_FOUND'); const requiredConnectorsReady=await this.evaluateRequiredConnectors(t), requiredDataCoverageReady=await this.evaluateDataCoverage(t), safetyGatesPassed=await this.evaluateSafetyGates(t), demoDataAbsentInLive=!(await this.evaluateDemoDataRisk(t)); const checks=await this.repo.listReadinessChecks(t); const economicControlChainReady=checks.some(c=>c.checkKey==='ECONOMIC_CONTROL_CHAIN_READY'&&c.status==='PASS')||checks.length===0&&requiredConnectorsReady&&requiredDataCoverageReady; let open=(await this.repo.listBlockers(t)).filter(b=>b.status==='OPEN'); const criticalBlockerCount=open.filter(b=>b.severity==='CRITICAL').length; let score=[requiredConnectorsReady,requiredDataCoverageReady,safetyGatesPassed,economicControlChainReady,demoDataAbsentInLive].filter(Boolean).length*20; let overallStatus:LiveTenantReadinessSnapshot['overallStatus']='PARTIAL'; if(p.mode==='DEMO'){overallStatus='DEMO';score=Math.max(score,0)} else if(requiredConnectorsReady&&requiredDataCoverageReady&&safetyGatesPassed&&economicControlChainReady&&demoDataAbsentInLive&&criticalBlockerCount===0) overallStatus='READY'; else if(criticalBlockerCount>0||!demoDataAbsentInLive||!requiredConnectorsReady||!requiredDataCoverageReady) overallStatus='BLOCKED'; const nextSteps=this.nextSteps({requiredConnectorsReady,requiredDataCoverageReady,safetyGatesPassed,economicControlChainReady,demoDataAbsentInLive}); return this.repo.upsertReadinessSnapshot(stamp({tenantId:t,mode:p.mode,overallStatus,readinessScore:score,requiredConnectorsReady,requiredDataCoverageReady,safetyGatesPassed,economicControlChainReady,demoDataAbsentInLive,blockerCount:open.length,criticalBlockerCount,nextSteps,source:'live-tenant-readiness-service',evidenceRefs:[]}) as any)}
 nextSteps(s:any){const a:any[]=[]; if(!s.requiredConnectorsReady)a.push({priority:'HIGH',title:'Connect required live sources',description:'At least one required connector per required domain must be connected or synced.',targetArea:'CONNECTORS'}); if(!s.requiredDataCoverageReady)a.push({priority:'HIGH',title:'Validate required data coverage',description:'Required domains need sufficient fresh coverage before live recommendations.',targetArea:'DATA_COVERAGE'}); if(!s.safetyGatesPassed)a.push({priority:'HIGH',title:'Pass or formally waive required safety gates',description:'Required gates must be passed or waived with evidence.',targetArea:'GOVERNANCE'}); if(!s.demoDataAbsentInLive)a.push({priority:'HIGH',title:'Remove demo data risk',description:'Live tenants cannot use demo fixtures or sample tenant value sources.',targetArea:'GOVERNANCE'}); if(!s.economicControlChainReady)a.push({priority:'MEDIUM',title:'Run economic control chain audit',description:'Control chain readiness must pass before READY.',targetArea:'GRAPH'}); return a}
 async evaluateLiveModeApproval(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p||p.mode==='DEMO')return false; const s=await this.buildReadinessSnapshot(t); return s.overallStatus==='READY'&&await this.evaluateSafetyGates(t)}
 async generateOnboardingPlan(t:string){const p=await this.repo.getLatestTenantProfile(t); if(!p)throw new Error('TENANT_PROFILE_NOT_FOUND'); const keys:any[]=['CREATE_TENANT_PROFILE','CONFIRM_USE_CASE',...p.requiredDomains.map((d:Domain)=>d==='IDENTITY'?'CONNECT_IDENTITY':d==='COMMERCIAL'?'CONNECT_COMMERCIAL_SOURCE':d==='FINANCIAL'?'CONNECT_FINANCIAL_SOURCE':d==='OWNERSHIP'?'CONNECT_OWNERSHIP_SOURCE':d==='USAGE'?'CONNECT_USAGE_SOURCE':undefined).filter(Boolean),'VALIDATE_DATA_COVERAGE','RUN_ECONOMIC_GRAPH_AUDIT','RUN_ECONOMIC_CONTROL_CHAIN_AUDIT','REVIEW_READINESS_BLOCKERS','APPROVE_LIVE_MODE']; return Promise.all(keys.map(k=>this.upsertOnboardingStep({tenantId:t,stepKey:k,label:String(k).replaceAll('_',' '),status:'NOT_STARTED',blockerIds:[]})))}
 async generateReadinessBlockers(t:string){const snap=await this.buildReadinessSnapshot(t); const mk=(x:any)=>this.upsertBlocker({tenantId:t,status:'OPEN',severity:'CRITICAL',...x}); const out:LiveTenantBlocker[]=[]; if(!snap.requiredConnectorsReady)out.push(await mk({blockerType:'CONNECTOR',title:'Required connectors are not ready',description:'A required live-readiness connector is missing or unhealthy.',nextStep:'Configure and sync at least one healthy required connector for each required domain.'}) as any); if(!snap.requiredDataCoverageReady)out.push(await mk({blockerType:'DATA_COVERAGE',title:'Required data coverage is not ready',description:'A required domain lacks sufficient fresh records.',nextStep:'Load or validate enough fresh records for required domains.'}) as any); if(!snap.demoDataAbsentInLive)out.push(await mk({blockerType:'DEMO_DATA_RISK',title:'Demo data risk detected',description:'Live mode cannot rely on demo fixture/sample tenant evidence.',nextStep:'Remove demo evidence/source references and rebuild the snapshot.'}) as any); return out}
 async approveLiveMode(t:string,approvedByUserId:string){if(!(await this.evaluateLiveModeApproval(t)))throw new Error('LIVE_MODE_APPROVAL_NOT_ALLOWED'); return this.upsertSafetyGate({tenantId:t,gateKey:'LIVE_MODE_APPROVAL',status:'PASSED',required:true,source:'live-approval',evidenceRefs:[`approved-by:${approvedByUserId}`]})}
 async summariseLiveTenantReadiness(t:string){const latest=(await this.repo.listReadinessSnapshots(t)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]??await this.buildReadinessSnapshot(t); return {...latest,canApproveLiveMode:latest.mode==='LIVE'&&latest.overallStatus==='READY'}}}
export const liveTenantReadinessService=new LiveTenantReadinessService();
