export const LIVE_TENANT_READINESS_COLLECTIONS=['LIVE_TENANT_PROFILES','LIVE_TENANT_CONNECTOR_READINESS','LIVE_TENANT_DATA_COVERAGE','LIVE_TENANT_READINESS_CHECKS','LIVE_TENANT_ONBOARDING_STEPS','LIVE_TENANT_SAFETY_GATES','LIVE_TENANT_BLOCKERS','LIVE_TENANT_READINESS_SNAPSHOTS'] as const;
export type LiveTenantReadinessCollection=(typeof LIVE_TENANT_READINESS_COLLECTIONS)[number];
export type Domain='IDENTITY'|'COMMERCIAL'|'FINANCIAL'|'OWNERSHIP'|'USAGE'|'ACTIONS'|'EVIDENCE'|'GRAPH'; export type Mode='DEMO'|'LIVE'; export type Sev='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export interface PersistenceStore<T extends {id:string;tenantId:string}>{upsert(v:T):Promise<T>;get(tenantId:string,id:string):Promise<T|undefined>;list(tenantId:string,filters?:Record<string,unknown>):Promise<T[]>;deleteTenant(tenantId:string):Promise<void>;size():Promise<number>}
export interface Base{id:string;tenantId:string;source:string;evidenceRefs:string[];createdAt:string;updatedAt:string}
export interface LiveTenantProfile extends Base{tenantName:string;mode:Mode;lifecycleStage:'NOT_STARTED'|'DISCOVERY'|'CONNECTING'|'VALIDATING'|'READY'|'BLOCKED'|'PAUSED';primaryUseCase:'M365_OPTIMISATION'|'AI_ECONOMIC_CONTROL'|'TECHNOLOGY_PORTFOLIO'|'COMMERCIAL_GOVERNANCE'|'FINANCIAL_VERIFICATION'|'GENERAL';requiredDomains:Domain[];ownerUserId?:string;executiveSponsorId?:string}
export interface LiveTenantConnectorReadiness extends Base{connectorKey:'M365'|'AZURE_AD'|'FLEXERA'|'SERVICENOW'|'ERP'|'AP'|'PROCUREMENT'|'HRIS'|'SaaS_DISCOVERY'|'AI_PROVIDER'|'MANUAL_UPLOAD'|'CUSTOM';connectorName:string;domain:Domain;status:'NOT_CONFIGURED'|'CONFIGURED'|'AUTHORISED'|'CONNECTED'|'SYNCED'|'FAILED'|'DISABLED'|'NOT_REQUIRED';health:'UNKNOWN'|'HEALTHY'|'DEGRADED'|'FAILED'|'NOT_APPLICABLE';lastCheckedAt?:string;lastSuccessfulSyncAt?:string;failureReason?:string;requiredForLiveReadiness:boolean}
export interface LiveTenantDataCoverage extends Base{domain:Domain;coverageStatus:'NONE'|'PARTIAL'|'SUFFICIENT'|'COMPLETE'|'NOT_REQUIRED';recordCount:number;coveragePercent?:number;freshness:'UNKNOWN'|'FRESH'|'STALE'|'EXPIRED'|'NOT_APPLICABLE';lastUpdatedAt?:string;minimumRequiredRecords?:number}
export interface LiveTenantReadinessCheck extends Base{checkKey:'NO_DEMO_DATA_IN_LIVE'|'REQUIRED_CONNECTORS_READY'|'REQUIRED_DATA_COVERAGE'|'GRAPH_READY'|'EVIDENCE_READY'|'OWNERSHIP_READY'|'FINANCIAL_TRUTH_READY'|'COMMERCIAL_AUTHORITY_READY'|'OUTCOME_FINANCE_READY'|'ACTION_SAFETY_READY'|'ECONOMIC_CONTROL_CHAIN_READY';status:'PASS'|'WARN'|'FAIL'|'NOT_APPLICABLE';severity:Sev;reason?:string;nextStep?:string}
export interface LiveTenantOnboardingStep extends Base{stepKey:'CREATE_TENANT_PROFILE'|'CONFIRM_USE_CASE'|'CONNECT_IDENTITY'|'CONNECT_COMMERCIAL_SOURCE'|'CONNECT_FINANCIAL_SOURCE'|'CONNECT_OWNERSHIP_SOURCE'|'CONNECT_USAGE_SOURCE'|'VALIDATE_DATA_COVERAGE'|'RUN_ECONOMIC_GRAPH_AUDIT'|'RUN_ECONOMIC_CONTROL_CHAIN_AUDIT'|'REVIEW_READINESS_BLOCKERS'|'APPROVE_LIVE_MODE';label:string;status:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'|'SKIPPED'|'NOT_REQUIRED';ownerUserId?:string;blockerIds:string[];completedAt?:string}
export interface LiveTenantSafetyGate extends Base{gateKey:'LIVE_MODE_APPROVAL'|'NO_SYNTHETIC_DATA'|'READINESS_CHECKS_PASS'|'ACTION_EXECUTION_DISABLED_UNTIL_APPROVED'|'FINANCE_VERIFICATION_REQUIRED_FOR_VALUE'|'EVIDENCE_REQUIRED_FOR_EXECUTION'|'OWNERSHIP_REQUIRED_FOR_APPROVAL';status:'OPEN'|'PASSED'|'FAILED'|'WAIVED';required:boolean;waiverReason?:string;waivedByUserId?:string;waivedAt?:string}
export interface LiveTenantBlocker extends Base{blockerType:'CONNECTOR'|'DATA_COVERAGE'|'GRAPH'|'EVIDENCE'|'OWNERSHIP'|'FINANCIAL'|'COMMERCIAL'|'ACTION_SAFETY'|'DEMO_DATA_RISK'|'UNKNOWN';severity:Sev;title:string;description:string;nextStep:string;relatedConnectorId?:string;relatedCheckId?:string;relatedGateId?:string;status:'OPEN'|'RESOLVED'|'WAIVED'}
export interface LiveTenantReadinessSnapshot extends Base{mode:Mode;overallStatus:'READY'|'PARTIAL'|'BLOCKED'|'DEMO';readinessScore:number;requiredConnectorsReady:boolean;requiredDataCoverageReady:boolean;safetyGatesPassed:boolean;economicControlChainReady:boolean;demoDataAbsentInLive:boolean;blockerCount:number;criticalBlockerCount:number;nextSteps:Array<{priority:'HIGH'|'MEDIUM'|'LOW';title:string;description:string;targetArea:'CONNECTORS'|'DATA_COVERAGE'|'GRAPH'|'EVIDENCE'|'OWNERSHIP'|'FINANCIAL'|'COMMERCIAL'|'ACTIONS'|'GOVERNANCE'}>}
