import { createPersistenceStore, MemoryPersistenceStore } from './live-tenant-readiness-persistence';
import type { LiveTenantProfile,LiveTenantConnectorReadiness,LiveTenantDataCoverage,LiveTenantReadinessCheck,LiveTenantOnboardingStep,LiveTenantSafetyGate,LiveTenantBlocker,LiveTenantReadinessSnapshot,PersistenceStore } from './live-tenant-readiness-types';
export interface LiveTenantReadinessStores{profiles:PersistenceStore<LiveTenantProfile>;connectors:PersistenceStore<LiveTenantConnectorReadiness>;coverage:PersistenceStore<LiveTenantDataCoverage>;checks:PersistenceStore<LiveTenantReadinessCheck>;steps:PersistenceStore<LiveTenantOnboardingStep>;gates:PersistenceStore<LiveTenantSafetyGate>;blockers:PersistenceStore<LiveTenantBlocker>;snapshots:PersistenceStore<LiveTenantReadinessSnapshot>}
export const createLiveTenantReadinessStores=():LiveTenantReadinessStores=>({profiles:createPersistenceStore('LIVE_TENANT_PROFILES'),connectors:createPersistenceStore('LIVE_TENANT_CONNECTOR_READINESS'),coverage:createPersistenceStore('LIVE_TENANT_DATA_COVERAGE'),checks:createPersistenceStore('LIVE_TENANT_READINESS_CHECKS'),steps:createPersistenceStore('LIVE_TENANT_ONBOARDING_STEPS'),gates:createPersistenceStore('LIVE_TENANT_SAFETY_GATES'),blockers:createPersistenceStore('LIVE_TENANT_BLOCKERS'),snapshots:createPersistenceStore('LIVE_TENANT_READINESS_SNAPSHOTS')});
export const createInMemoryLiveTenantReadinessStores=():LiveTenantReadinessStores=>({profiles:new MemoryPersistenceStore('LIVE_TENANT_PROFILES'),connectors:new MemoryPersistenceStore('LIVE_TENANT_CONNECTOR_READINESS'),coverage:new MemoryPersistenceStore('LIVE_TENANT_DATA_COVERAGE'),checks:new MemoryPersistenceStore('LIVE_TENANT_READINESS_CHECKS'),steps:new MemoryPersistenceStore('LIVE_TENANT_ONBOARDING_STEPS'),gates:new MemoryPersistenceStore('LIVE_TENANT_SAFETY_GATES'),blockers:new MemoryPersistenceStore('LIVE_TENANT_BLOCKERS'),snapshots:new MemoryPersistenceStore('LIVE_TENANT_READINESS_SNAPSHOTS')});
const req=(v:any,fields:string[])=>{for(const f of fields) if(v[f]===undefined||v[f]==='') throw new Error(`MISSING_REQUIRED_FIELD:${f}`)}; const range=(n:number,min:number,max:number,name:string)=>{if(!Number.isFinite(n)||n<min||n>max)throw new Error(`INVALID_${name}`)};
export class LiveTenantReadinessRepository{constructor(public stores:LiveTenantReadinessStores=createLiveTenantReadinessStores()){}
 private base(v:any){req(v,['id','tenantId','source','evidenceRefs','createdAt','updatedAt']); if(!Array.isArray(v.evidenceRefs))throw new Error('INVALID_EVIDENCE_REFS')}
 private async latest<T extends {createdAt:string;updatedAt:string}>(xs:T[]){return xs.sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)))[0]}
 async upsertTenantProfile(v:LiveTenantProfile){this.base(v);req(v,['tenantName','mode','lifecycleStage','primaryUseCase','requiredDomains']);return this.stores.profiles.upsert(v)} async getTenantProfile(t:string,id:string){return this.stores.profiles.get(t,id)} async getLatestTenantProfile(t:string){return this.latest(await this.stores.profiles.list(t))} async listTenantProfiles(t:string,f?:Record<string,unknown>){return this.stores.profiles.list(t,f)}
 async upsertConnectorReadiness(v:LiveTenantConnectorReadiness){this.base(v);req(v,['connectorKey','connectorName','domain','status','health','requiredForLiveReadiness']);return this.stores.connectors.upsert(v)} async getConnectorReadiness(t:string,id:string){return this.stores.connectors.get(t,id)} async listConnectorReadiness(t:string,f?:Record<string,unknown>){return this.stores.connectors.list(t,f)}
 async upsertDataCoverage(v:LiveTenantDataCoverage){this.base(v);req(v,['domain','coverageStatus','recordCount','freshness']); if(v.recordCount<0)throw new Error('NEGATIVE_RECORD_COUNT'); if(v.coveragePercent!==undefined)range(v.coveragePercent,0,100,'COVERAGE_PERCENT');return this.stores.coverage.upsert(v)} async getDataCoverage(t:string,id:string){return this.stores.coverage.get(t,id)} async listDataCoverage(t:string,f?:Record<string,unknown>){return this.stores.coverage.list(t,f)}
 async upsertReadinessCheck(v:LiveTenantReadinessCheck){this.base(v);req(v,['checkKey','status','severity']);return this.stores.checks.upsert(v)} async getReadinessCheck(t:string,id:string){return this.stores.checks.get(t,id)} async listReadinessChecks(t:string,f?:Record<string,unknown>){return this.stores.checks.list(t,f)}
 async upsertOnboardingStep(v:LiveTenantOnboardingStep){this.base(v);req(v,['stepKey','label','status','blockerIds']);return this.stores.steps.upsert(v)} async getOnboardingStep(t:string,id:string){return this.stores.steps.get(t,id)} async listOnboardingSteps(t:string,f?:Record<string,unknown>){return this.stores.steps.list(t,f)}
 async upsertSafetyGate(v:LiveTenantSafetyGate){this.base(v);req(v,['gateKey','status','required']); if(v.status==='WAIVED'&&!(v.waiverReason&&v.waivedByUserId&&v.waivedAt))throw new Error('WAIVER_REQUIRES_REASON_USER_TIME'); return this.stores.gates.upsert(v)} async getSafetyGate(t:string,id:string){return this.stores.gates.get(t,id)} async listSafetyGates(t:string,f?:Record<string,unknown>){return this.stores.gates.list(t,f)}
 async upsertBlocker(v:LiveTenantBlocker){this.base(v);req(v,['blockerType','severity','title','description','nextStep','status']);return this.stores.blockers.upsert(v)} async getBlocker(t:string,id:string){return this.stores.blockers.get(t,id)} async listBlockers(t:string,f?:Record<string,unknown>){return this.stores.blockers.list(t,f)}
 async upsertReadinessSnapshot(v:LiveTenantReadinessSnapshot){this.base(v);req(v,['mode','overallStatus','readinessScore']);range(v.readinessScore,0,100,'READINESS_SCORE');return this.stores.snapshots.upsert(v)} async getReadinessSnapshot(t:string,id:string){return this.stores.snapshots.get(t,id)} async listReadinessSnapshots(t:string,f?:Record<string,unknown>){return this.stores.snapshots.list(t,f)}
 async deleteTenantReadinessData(t:string){await Promise.all(Object.values(this.stores).map(s=>s.deleteTenant(t)))} async collectionStatus(){return Object.fromEntries(await Promise.all(Object.entries(this.stores).map(async([k,s])=>[k,await s.size()])))} }
export const liveTenantReadinessRepository=new LiveTenantReadinessRepository();
