import type { OpportunityDomain, OpportunityReadiness, OpportunityUrgency } from "../opportunities/opportunity-types";
import type { UtilizationOpportunity, UtilizationRecord } from "./utilization-types";

function domainFor(platform: string): OpportunityDomain { if (platform === "AWS") return "AWS"; if (platform === "AZURE") return "AZURE"; if (platform === "SNOWFLAKE") return "SNOWFLAKE"; if (platform === "DATABRICKS") return "DATABRICKS"; if (platform === "SALESFORCE") return "SALESFORCE"; if (platform === "SERVICENOW") return "SERVICENOW"; return "M365"; }
function titleFor(record: UtilizationRecord) { if (record.platform === "COPILOT") return "Copilot Reclaim Opportunity"; if (record.platform === "M365") return "M365 Rightsizing Opportunity"; if (record.platform === "SNOWFLAKE") return "Warehouse Optimization Opportunity"; if (record.platform === "SALESFORCE" || record.platform === "ADOBE" || record.platform === "SERVICENOW") return "License Reclaim Opportunity"; if (record.platform === "AWS" || record.platform === "AZURE") return "Reserved Capacity Optimization Opportunity"; return `${record.resourceName} Utilization Opportunity`; }
function urgencyFor(record: UtilizationRecord): OpportunityUrgency { if (record.utilizationBand === "UNUSED") return "CRITICAL"; if (record.wasteEstimate >= 10000) return "HIGH"; if (record.utilizationBand === "LOW") return "HIGH"; return "MEDIUM"; }
function readinessFor(record: UtilizationRecord): OpportunityReadiness { return record.utilizationBand === "UNUSED" || record.utilizationBand === "LOW" ? "APPROVAL_REQUIRED" : "ELIGIBLE"; }

export function generateUtilizationOpportunities(records: UtilizationRecord[]): UtilizationOpportunity[] {
  return records.filter((record) => record.utilizationBand !== "HIGH" && record.wasteEstimate > 0).map((record) => ({ id: `opp-utilization-${record.id}`, tenantId: record.tenantId, source: "UTILIZATION", title: titleFor(record), description: `${record.resourceName} is ${record.utilizationBand.toLowerCase()} utilization with ${record.assignedCount - record.activeCount} unused or underused assignments.`, domain: domainFor(record.platform), projectedMonthlySavings: record.wasteEstimate, trustScore: record.lastActivityAt ? 82 : 68, confidenceScore: record.utilizationBand === "UNUSED" ? 88 : 78, urgency: urgencyFor(record), readiness: readinessFor(record), sourceReferenceId: record.id, createdAt: record.lastActivityAt, utilizationRecordId: record.id, utilizationBand: record.utilizationBand }));
}
