import type { CanonicalGraphEntityType, CanonicalRelationshipType, GraphEvidence } from '../operational-graph/types';
import { buildLineage } from '../operational-graph/lineage';
import { EconomicGraphRepository } from './economic-graph-repository';
export class EconomicGraphService {
  constructor(private readonly repo:any = new EconomicGraphRepository()) {}
  async createNode(params:{tenantId:string;entityType:CanonicalGraphEntityType|string;canonicalName:string;canonicalKey:string;trustScore?:number;confidenceScore?:number;evidence:GraphEvidence[];runId?:string;metadata?:Record<string,unknown>}){const lineage=buildLineage(params.runId);return this.repo.createNode({tenantId:params.tenantId,entityType:params.entityType,canonicalName:params.canonicalName,canonicalKey:params.canonicalKey,sourceSystem:params.evidence[0]?.sourceSystem??'unknown',entityTrustScore:params.trustScore??0,entityConfidenceScore:params.confidenceScore??0,sourceReferences:params.evidence,metadata:{...(params.metadata??{}),lineage}})}
  async createEdge(params:{tenantId:string;fromEntityId:string;toEntityId:string;relationshipType:CanonicalRelationshipType|string;confidenceScore:number;trustScore?:number;evidence:GraphEvidence[];runId?:string}){const lineage=buildLineage(params.runId);return this.repo.createEdge({tenantId:params.tenantId,fromEntityId:params.fromEntityId,toEntityId:params.toEntityId,relationshipType:params.relationshipType,relationshipConfidenceScore:params.confidenceScore,relationshipTrustScore:params.trustScore??params.confidenceScore,sourceSystem:params.evidence[0]?.sourceSystem??'unknown',sourceReferenceId:params.evidence[0]?.sourceReferenceId??'unknown',edgeProvenance:{lineage,evidence:params.evidence},edgeMetadata:{conflictingTruths:params.evidence.length>1}})}
  listNodes(tenantId:string){return this.repo.listNodes(tenantId)} listEdges(tenantId:string){return this.repo.listEdges(tenantId)} findNodeByKey(tenantId:string,key:string){return this.repo.findNodeByKey(tenantId,key)}
  async hasPath(tenantId:string,from:string,to:string){const edges=await this.listEdges(tenantId); const q=[from], seen=new Set<string>(); while(q.length){const x=q.shift()!; if(x===to)return true; if(seen.has(x))continue; seen.add(x); for(const e of edges.filter((e:any)=>e.fromEntityId===x))q.push(e.toEntityId); for(const e of edges.filter((e:any)=>e.toEntityId===x))q.push(e.fromEntityId)} return false}
}
