import { index, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
export const evidenceRegistryRecordsTable = pgTable("evidence_registry_records", { id:text("id").primaryKey(), tenantId:text("tenant_id").notNull(), collection:text("collection").notNull(), recordId:text("record_id").notNull(), payload:jsonb("payload").notNull().default({}), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow().$onUpdate(()=>new Date()) }, (table)=>({ tenantCollectionRecordIdx:uniqueIndex("evidence_registry_tenant_collection_record_idx").on(table.tenantId,table.collection,table.recordId), tenantCollectionIdx:index("evidence_registry_tenant_collection_idx").on(table.tenantId,table.collection) }));

export const evidenceItemsTable = pgTable("evidence_items", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), evidenceType: text("evidence_type").notNull(), sourceSystem: text("source_system"), sourceEntityType: text("source_entity_type"), sourceEntityId: text("source_entity_id"), collectedAt: timestamp("collected_at", { withTimezone: true }).notNull().defaultNow(), collectedByPrincipalId: text("collected_by_principal_id"), trustScore: text("trust_score"), hash: text("hash").notNull(), summary: text("summary"), payload: jsonb("payload").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("evidence_items_tenant_idx").on(t.tenantId), index("evidence_items_source_idx").on(t.tenantId, t.sourceEntityType, t.sourceEntityId)]);

export const evidenceLinksTable = pgTable("evidence_links", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), evidenceItemId: text("evidence_item_id").notNull(), linkedEntityType: text("linked_entity_type").notNull(), linkedEntityId: text("linked_entity_id").notNull(), relationshipType: text("relationship_type").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("evidence_links_entity_idx").on(t.tenantId, t.linkedEntityType, t.linkedEntityId), index("evidence_links_item_idx").on(t.tenantId, t.evidenceItemId)]);
