import { boolean, integer, jsonb, pgTable, serial, text, timestamp, real } from "drizzle-orm/pg-core";

export const executionGovernancePoliciesTable = pgTable("execution_governance_policies", {
  id: serial("id").primaryKey(),
  tenantId: text("tenant_id").notNull().default("default"),
  policyName: text("policy_name").notNull(),
  description: text("description").notNull().default(""),
  policyType: text("policy_type").notNull(),
  enabled: boolean("enabled").notNull().default(true),
  maxAutoSafeRiskClass: text("max_auto_safe_risk_class"),
  maxAutoSafeBlastRadius: text("max_auto_safe_blast_radius"),
  requiresApprovalRiskClass: text("requires_approval_risk_class"),
  requiresSampleBatchBlastRadius: text("requires_sample_batch_blast_radius"),
  maxBatchFailureRatePercent: real("max_batch_failure_rate_percent"),
  maxBatchSize: integer("max_batch_size"),
  maxAnnualizedSavingsWithoutApproval: real("max_annualized_savings_without_approval"),
  allowAutomationPromotion: boolean("allow_automation_promotion").notNull().default(true),
  allowAutoSafeExecution: boolean("allow_auto_safe_execution").notNull().default(true),
  allowRollbackRecommendation: boolean("allow_rollback_recommendation").notNull().default(true),
  restrictedActionTypes: jsonb("restricted_action_types").notNull().default([]),
  restrictedPlaybooks: jsonb("restricted_playbooks").notNull().default([]),
  restrictedTargetPatterns: jsonb("restricted_target_patterns").notNull().default([]),
  approvalRoles: jsonb("approval_roles").notNull().default([]),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  runtimeControlOverridesAllowed: boolean("runtime_control_overrides_allowed").notNull().default(false),
  createdBy: text("created_by").notNull().default("system"),
  updatedBy: text("updated_by").notNull().default("system"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
