import { pgTable, serial, text, timestamp, jsonb, integer, boolean, real } from "drizzle-orm/pg-core";

export const executionOrchestrationPlansTable = pgTable("execution_orchestration_plans", {
  id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), workflowId: text("workflow_id"), sourceRecommendationIds: jsonb("source_recommendation_ids").notNull().default([]), playbookId: text("playbook_id"), planType: text("plan_type").notNull(), status: text("status").notNull(), riskClassMax: text("risk_class_max"), blastRadiusScore: real("blast_radius_score").notNull().default(0), blastRadiusBand: text("blast_radius_band"), automationEligibility: text("automation_eligibility"), approvalRequired: boolean("approval_required").notNull().default(false), runtimeControlStatus: text("runtime_control_status").notNull().default("ALLOW"), createdByActorId: text("created_by_actor_id").notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), failureReason: text("failure_reason"), evidenceRef: text("evidence_ref"), correlationId: text("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const executionQueueItemsTable = pgTable("execution_queue_items", {
  id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), planId: integer("plan_id").notNull(), workflowStepId: text("workflow_step_id"), recommendationId: text("recommendation_id").notNull(), actionType: text("action_type").notNull(), targetEntityId: text("target_entity_id").notNull(), targetEntityType: text("target_entity_type").notNull(), status: text("status").notNull().default("PENDING"), sequenceIndex: integer("sequence_index").notNull().default(0), dependencyGroup: text("dependency_group"), batchGroup: text("batch_group"), riskClass: text("risk_class").notNull(), executionMode: text("execution_mode").notNull().default("APPROVAL_EXECUTE"), approvalStatus: text("approval_status").notNull().default("NOT_REQUIRED"), runtimeControlStatus: text("runtime_control_status").notNull().default("ALLOW"), attemptCount: integer("attempt_count").notNull().default(0), maxAttempts: integer("max_attempts").notNull().default(3), lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true }), nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }), lockedAt: timestamp("locked_at", { withTimezone: true }), lockedBy: text("locked_by"), executionResult: jsonb("execution_result"), failureReason: text("failure_reason"), rollbackAvailable: boolean("rollback_available").notNull().default(false), outcomeLedgerId: text("outcome_ledger_id"), correlationId: text("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const executionDependenciesTable = pgTable("execution_dependencies", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), planId: integer("plan_id").notNull(), queueItemId: integer("queue_item_id").notNull(), dependsOnQueueItemId: integer("depends_on_queue_item_id").notNull(), dependencyType: text("dependency_type").notNull(), status: text("status").notNull().default("PENDING"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), resolvedAt: timestamp("resolved_at", { withTimezone: true }) });

export const executionEscalationsTable = pgTable("execution_escalations", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), planId: integer("plan_id").notNull(), queueItemId: integer("queue_item_id"), escalationType: text("escalation_type").notNull(), severity: text("severity").notNull(), status: text("status").notNull().default("OPEN"), reason: text("reason").notNull(), assignedRole: text("assigned_role"), assignedActorId: text("assigned_actor_id"), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }), resolvedAt: timestamp("resolved_at", { withTimezone: true }), resolutionNotes: text("resolution_notes"), correlationId: text("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

export const executionOrchestrationEventsTable = pgTable("execution_orchestration_events", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), planId: integer("plan_id"), queueItemId: integer("queue_item_id"), eventType: text("event_type").notNull(), severity: text("severity").notNull().default("INFO"), actorId: text("actor_id"), source: text("source").notNull(), payload: jsonb("payload").notNull().default({}), correlationId: text("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });


export const executionBatchesTable = pgTable("execution_batches", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), planId: integer("plan_id").notNull(), status: text("status").notNull().default("DRAFT"), readiness: text("readiness").notNull().default("NOT_READY"), failurePolicy: text("failure_policy").notNull().default("PAUSE_ON_THRESHOLD"), blastRadiusScore: real("blast_radius_score").notNull().default(0), blastRadiusBand: text("blast_radius_band"), riskClassMax: text("risk_class_max"), isSampleBatch: boolean("is_sample_batch").notNull().default(false), parentBatchId: integer("parent_batch_id"), sampleBatchStatus: text("sample_batch_status"), sampleOutcomeVerified: boolean("sample_outcome_verified").notNull().default(false), promotionEligible: boolean("promotion_eligible").notNull().default(false), lastEvaluatedAt: timestamp("last_evaluated_at", { withTimezone: true }), cooldownUntil: timestamp("cooldown_until", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }) });
export const executionBatchItemsTable = pgTable("execution_batch_items", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), batchId: integer("batch_id").notNull(), queueItemId: integer("queue_item_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

export const executionAutomationCandidatesTable = pgTable("execution_automation_candidates", { id: serial("id").primaryKey(), tenantId: text("tenant_id").notNull(), actionType: text("action_type").notNull(), playbookId: text("playbook_id"), targetEntityType: text("target_entity_type").notNull(), currentMode: text("current_mode").notNull().default("RECOMMEND_ONLY"), recommendedMode: text("recommended_mode").notNull().default("RECOMMEND_ONLY"), promotionStatus: text("promotion_status").notNull().default("NOT_ELIGIBLE"), successfulRuns: integer("successful_runs").notNull().default(0), failedRuns: integer("failed_runs").notNull().default(0), verifiedSampleBatches: integer("verified_sample_batches").notNull().default(0), failureRatePercent: real("failure_rate_percent").notNull().default(0), lastRuntimeBlockAt: timestamp("last_runtime_block_at", { withTimezone: true }), lastCriticalEscalationAt: timestamp("last_critical_escalation_at", { withTimezone: true }), blastRadiusBand: text("blast_radius_band").notNull().default("LOW"), riskClass: text("risk_class").notNull().default("A"), rollbackAvailable: boolean("rollback_available").notNull().default(false), promotionEvidence: jsonb("promotion_evidence").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()) });
