import { index, jsonb, pgTable, real, serial, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const governedRecommendationsTable = pgTable("governed_recommendations", {
  id: serial("id").primaryKey(),
  recommendationId: text("recommendation_id").notNull(),
  tenantId: text("tenant_id").notNull(),
  playbookId: text("playbook_id").notNull(),
  targetEntityId: text("target_entity_id").notNull(),
  targetEntityType: text("target_entity_type").notNull(),
  actionType: text("action_type").notNull(),
  actionRiskClass: text("action_risk_class").notNull(),
  recommendationState: text("recommendation_state").notNull(),
  executionReadiness: text("execution_readiness").notNull(),
  confidenceScore: real("confidence_score").notNull().default(0),
  reliabilityBand: text("reliability_band").notNull(),
  discoveryLifecycleState: text("discovery_lifecycle_state").notNull(),
  projectedMonthlySavings: real("projected_monthly_savings").notNull().default(0),
  projectedAnnualSavings: real("projected_annual_savings").notNull().default(0),
  savingsConfidence: text("savings_confidence").notNull(),
  readinessReasons: jsonb("readiness_reasons").notNull().default([]),
  blockedReasons: jsonb("blocked_reasons").notNull().default([]),
  requiredApprovals: jsonb("required_approvals").notNull().default([]),
  evidencePointers: jsonb("evidence_pointers").notNull().default([]),
  graphNodeIds: jsonb("graph_node_ids").notNull().default([]),
  graphEdgeIds: jsonb("graph_edge_ids").notNull().default([]),
  sourceReferences: jsonb("source_references").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => [
  uniqueIndex("governed_recommendations_recommendation_id_uidx").on(t.recommendationId),
  index("governed_recommendations_tenant_idx").on(t.tenantId),
  index("governed_recommendations_tenant_state_idx").on(t.tenantId, t.recommendationState),
  index("governed_recommendations_tenant_readiness_idx").on(t.tenantId, t.executionReadiness),
  index("governed_recommendations_tenant_playbook_idx").on(t.tenantId, t.playbookId),
]);
