import { pgTable, serial, text, timestamp, jsonb, numeric, boolean } from "drizzle-orm/pg-core";

export const m365ConnectorConfigsTable = pgTable("m365_connector_configs", {
  id: serial("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  providerTenantId: text("provider_tenant_id").notNull(),
  clientId: text("client_id").notNull(),
  encryptedClientSecretRef: text("encrypted_client_secret_ref").notNull(),
  scopes: jsonb("scopes").$type<string[]>().notNull().default([]),
  mode: text("mode").notNull().default("READ_ONLY"),
  status: text("status").notNull().default("NOT_CONFIGURED"),
  lastValidatedAt: timestamp("last_validated_at", { withTimezone: true }),
  lastSyncStartedAt: timestamp("last_sync_started_at", { withTimezone: true }),
  lastSyncCompletedAt: timestamp("last_sync_completed_at", { withTimezone: true }),
  lastError: text("last_error"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const m365EvidenceRecordsTable = pgTable("m365_evidence_records", {
  id: serial("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  sourceSystem: text("source_system").notNull().default("M365_GRAPH"),
  sourceRecordId: text("source_record_id").notNull(),
  userId: text("user_id").notNull(),
  displayName: text("display_name"),
  department: text("department"),
  costCentre: text("cost_centre"),
  assignedLicences: jsonb("assigned_licences").$type<string[]>().notNull().default([]),
  monthlyLicenceCost: numeric("monthly_licence_cost", { precision: 10, scale: 2 }).notNull().default("0"),
  lastSignInAt: timestamp("last_sign_in_at", { withTimezone: true }),
  lastActivityAt: timestamp("last_activity_at", { withTimezone: true }),
  accountStatus: text("account_status").notNull().default("UNKNOWN"),
  mailboxType: text("mailbox_type").notNull().default("user"),
  copilotActivity: jsonb("copilot_activity").$type<Record<string, unknown>>().notNull().default({}),
  addOnUsage: jsonb("add_on_usage").$type<Record<string, unknown>>().notNull().default({}),
  desktopAppUsage: jsonb("desktop_app_usage").$type<Record<string, unknown>>().notNull().default({}),
  isAdmin: boolean("is_admin").notNull().default(false),
  isServiceAccount: boolean("is_service_account").notNull().default(false),
  evidenceCompleteness: numeric("evidence_completeness", { precision: 5, scale: 2 }).notNull().default("0"),
  evidenceFreshness: numeric("evidence_freshness", { precision: 5, scale: 2 }).notNull().default("0"),
  rawEvidence: jsonb("raw_evidence").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
