import { index, jsonb, numeric, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const policySimulationsTable = pgTable("policy_simulations", {
  id: serial("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  simulationName: text("simulation_name").notNull(),
  connectorType: text("connector_type").notNull().default("m365"),
  simulationScope: text("simulation_scope").notNull(),
  scopeEntityIds: jsonb("scope_entity_ids").notNull().default([]),
  simulationStatus: text("simulation_status").notNull().default("PENDING"),
  projectedMonthlySavings: numeric("projected_monthly_savings", { precision: 12, scale: 2 }).notNull().default("0"),
  projectedAnnualizedSavings: numeric("projected_annualized_savings", { precision: 12, scale: 2 }).notNull().default("0"),
  projectedAffectedUsers: numeric("projected_affected_users", { precision: 10, scale: 0 }).notNull().default("0"),
  projectedAffectedGroups: numeric("projected_affected_groups", { precision: 10, scale: 0 }).notNull().default("0"),
  projectedAffectedLicenses: numeric("projected_affected_licenses", { precision: 10, scale: 0 }).notNull().default("0"),
  blastRadiusScore: numeric("blast_radius_score", { precision: 5, scale: 2 }).notNull().default("0"),
  reversibilityRiskScore: numeric("reversibility_risk_score", { precision: 5, scale: 2 }).notNull().default("0"),
  governanceRiskScore: numeric("governance_risk_score", { precision: 5, scale: 2 }).notNull().default("0"),
  trustRiskScore: numeric("trust_risk_score", { precision: 5, scale: 2 }).notNull().default("0"),
  predictedRealizationConfidence: text("predicted_realization_confidence").notNull().default("MEDIUM"),
  predictedDriftRisk: numeric("predicted_drift_risk", { precision: 5, scale: 2 }).notNull().default("0"),
  predictedReversalRisk: numeric("predicted_reversal_risk", { precision: 5, scale: 2 }).notNull().default("0"),
  simulationReasoning: jsonb("simulation_reasoning").notNull().default({}),
  governanceReasoning: jsonb("governance_reasoning").notNull().default({}),
  trustReasoning: jsonb("trust_reasoning").notNull().default({}),
  blastRadiusReasoning: jsonb("blast_radius_reasoning").notNull().default({}),
  deterministicHash: text("deterministic_hash").notNull(),
  simulationEngineVersion: text("simulation_engine_version").notNull().default("policy-sim-v1"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("policy_simulations_tenant_scope_idx").on(t.tenantId, t.simulationScope),
  index("policy_simulations_tenant_created_idx").on(t.tenantId, t.createdAt),
  index("policy_simulations_tenant_status_idx").on(t.tenantId, t.simulationStatus),
]);
