import type { MicrosoftConnectorKey, MicrosoftOAuthConnection, MicrosoftTokenSet } from "./microsoft-auth-types";
import { EncryptedMicrosoftTokenStore } from "./microsoft-token-store";
type FetchLike = typeof fetch;
export class MicrosoftOAuthService {
  private states = new Set<string>();
  constructor(private readonly opts: { clientId: string; clientSecret?: string; redirectUri: string; authorityTenant?: string; tokenStore?: EncryptedMicrosoftTokenStore; fetchImpl?: FetchLike }) {}
  private get store() { return this.opts.tokenStore ?? new EncryptedMicrosoftTokenStore(); }
  generateAuthorizationUrl(input: { tenantId: string; connectorKey: MicrosoftConnectorKey; scopes: string[]; state: string }) { this.states.add(input.state); const tenant = this.opts.authorityTenant ?? "organizations"; const u = new URL(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize`); u.searchParams.set("client_id", this.opts.clientId); u.searchParams.set("response_type", "code"); u.searchParams.set("redirect_uri", this.opts.redirectUri); u.searchParams.set("response_mode", "query"); u.searchParams.set("scope", input.scopes.join(" ")); u.searchParams.set("state", input.state); return { authorizationUrl: u.toString(), state: input.state }; }
  async exchangeAuthorizationCode(input: { tenantId: string; connectorKey: MicrosoftConnectorKey; code: string; state: string; scopes: string[] }): Promise<MicrosoftOAuthConnection> { if (!this.states.delete(input.state)) throw Object.assign(new Error("Invalid OAuth state"), { code: "MICROSOFT_AUTH_FAILED" }); const token = await this.requestToken({ grant_type: "authorization_code", code: input.code, redirect_uri: this.opts.redirectUri, scope: input.scopes.join(" ") }); return this.store.store({ id: `msconn_${Date.now()}`, tenantId: input.tenantId, connectorKey: input.connectorKey, authFlow: "AUTH_CODE", grantedScopes: input.scopes, status: "CONNECTED", connectedAt: new Date().toISOString() }, token); }
  async connectClientCredentials(input: { tenantId: string; connectorKey: MicrosoftConnectorKey; scopes: string[] }) { const token = await this.requestToken({ grant_type: "client_credentials", scope: input.scopes.join(" ") }); return this.store.store({ id: `msconn_${Date.now()}`, tenantId: input.tenantId, connectorKey: input.connectorKey, authFlow: "CLIENT_CREDENTIALS", grantedScopes: input.scopes, status: "CONNECTED", connectedAt: new Date().toISOString() }, token); }
  async refreshAccessToken(tenantId: string, credentialRef: string) { const old = await this.store.getTokenSet(tenantId, credentialRef); if (!old?.refreshToken) throw Object.assign(new Error("Missing refresh token"), { code: "MICROSOFT_TOKEN_EXPIRED" }); const token = await this.requestToken({ grant_type: "refresh_token", refresh_token: old.refreshToken, scope: old.scopes.join(" ") }); await this.store.store({ ...(await this.store.getConnection(tenantId, credentialRef))!, credentialRef, status: "CONNECTED" }, token); return this.store.getConnection(tenantId, credentialRef); }
  async getAccessTokenForTenant(input: { tenantId: string; credentialRef: string }) { const token = await this.store.getTokenSet(input.tenantId, input.credentialRef); if (!token) throw Object.assign(new Error("Missing credentialRef"), { code: "MICROSOFT_AUTH_FAILED" }); if (new Date(token.expiresAt).getTime() <= Date.now()) { await this.store.updateStatus(input.tenantId, input.credentialRef, "EXPIRED", "access token expired"); throw Object.assign(new Error("Microsoft token expired"), { code: "MICROSOFT_TOKEN_EXPIRED" }); } return token.accessToken; }
  validateGrantedScopes(connection: MicrosoftOAuthConnection, requiredScopes: string[]) { const missingScopes = requiredScopes.filter((s) => !connection.grantedScopes.includes(s)); return { status: missingScopes.length ? "DEGRADED" : "PASS", missingScopes }; }
  async revokeOrDisableConnection(tenantId: string, credentialRef: string) { return this.store.revoke(tenantId, credentialRef); }
  private async requestToken(body: Record<string, string>): Promise<MicrosoftTokenSet> { const f = this.opts.fetchImpl ?? fetch; const tenant = this.opts.authorityTenant ?? "organizations"; const params = new URLSearchParams({ client_id: this.opts.clientId, ...body }); if (this.opts.clientSecret) params.set("client_secret", this.opts.clientSecret); const res = await f(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`, { method: "POST", body: params }); if (!res.ok) throw Object.assign(new Error("Microsoft token exchange failed"), { code: "MICROSOFT_AUTH_FAILED", status: res.status }); const json: any = await res.json(); return { accessToken: json.access_token, refreshToken: json.refresh_token, expiresAt: new Date(Date.now() + Number(json.expires_in ?? 3600) * 1000).toISOString(), scopes: String(json.scope ?? body.scope ?? "").split(/\s+/).filter(Boolean), microsoftTenantId: json.tid }; }
}
