import { randomUUID } from "node:crypto";
export class MicrosoftGraphHttpError extends Error { constructor(message: string, public readonly status: number, public readonly code: string, public readonly correlationId: string) { super(message); } }
type TokenProvider = () => Promise<string> | string;
export class MicrosoftGraphHttpClient {
  constructor(private readonly opts: { tokenProvider: TokenProvider; baseUrl?: string; allowBeta?: boolean; fetchImpl?: typeof fetch; timeoutMs?: number; maxRetries?: number; sleepMs?: (ms: number) => Promise<void> }) {}
  async get(path: string, options: RequestInit = {}) { const res = await this.request(path, options); const text = await res.text(); return text ? JSON.parse(text) : {}; }
  async getAllPages(path: string, options: RequestInit = {}) { const all: any[] = []; let next: string | undefined = path; while (next) { const page = await this.get(next, options); all.push(...(Array.isArray(page.value) ? page.value : [page])); next = page["@odata.nextLink"]; } return all; }
  async getReport(path: string, options: RequestInit = {}) { const res = await this.request(path, options); const text = await res.text(); return { text, rows: parseCsv(text) }; }
  private async request(path: string, options: RequestInit) { if (path.includes("/beta") && !this.opts.allowBeta) throw new MicrosoftGraphHttpError("Microsoft Graph beta endpoint not enabled", 400, "MICROSOFT_GRAPH_UNAVAILABLE", randomUUID()); const correlationId = randomUUID(); const url = path.startsWith("http") ? path : `${this.opts.baseUrl ?? "https://graph.microsoft.com/v1.0"}${path.startsWith("/") ? path : `/${path}`}`; const token = await this.opts.tokenProvider(); const headers = new Headers(options.headers); headers.set("Authorization", `Bearer ${token}`); headers.set("client-request-id", correlationId); const fetchImpl = this.opts.fetchImpl ?? fetch; const maxRetries = this.opts.maxRetries ?? 3; for (let attempt = 0; attempt <= maxRetries; attempt++) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), this.opts.timeoutMs ?? 30000); try { const res = await fetchImpl(url, { ...options, headers, signal: controller.signal }); if (![429, 503, 504].includes(res.status)) { if (!res.ok) throw new MicrosoftGraphHttpError(`Microsoft Graph request failed with ${res.status}`, res.status, res.status === 401 ? "MICROSOFT_TOKEN_EXPIRED" : "MICROSOFT_GRAPH_UNAVAILABLE", correlationId); return res; } if (attempt === maxRetries) throw new MicrosoftGraphHttpError(`Microsoft Graph throttled/unavailable after retry`, res.status, res.status === 429 ? "MICROSOFT_GRAPH_THROTTLED" : "MICROSOFT_GRAPH_UNAVAILABLE", correlationId); const retryAfter = Number(res.headers.get("Retry-After")); await (this.opts.sleepMs ?? ((ms) => new Promise((r) => setTimeout(r, ms))))(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 100 * 2 ** attempt); } finally { clearTimeout(timeout); } } throw new MicrosoftGraphHttpError("Microsoft Graph request failed", 500, "MICROSOFT_GRAPH_UNAVAILABLE", correlationId); }
}
export function parseCsv(csv: string) { const [headerLine, ...lines] = csv.trim().split(/\r?\n/).filter(Boolean); if (!headerLine) return []; const headers = splitCsv(headerLine); return lines.map((line) => Object.fromEntries(splitCsv(line).map((v, i) => [headers[i] ?? `column_${i}`, v]))); }
function splitCsv(line: string) { const out: string[] = []; let cur = ""; let quoted = false; for (let i = 0; i < line.length; i++) { const c = line[i]; if (c === '"') quoted = !quoted; else if (c === "," && !quoted) { out.push(cur); cur = ""; } else cur += c; } out.push(cur); return out; }
