import type { EconomicMemoryRecord, EconomicMemoryReport } from './economic-memory-types';
import { summarizeCalibrationMemory } from './calibration-memory-store';
import { calculatePlaybookReliability } from './playbook-reliability-engine';
import { calculateDomainReliability } from './domain-reliability-engine';
import { deriveForecastMemoryAdjustment } from './forecast-memory-engine';
import { deriveScenarioMemoryAdjustment } from './scenario-memory-engine';
import { deriveRecommendationMemoryAdjustment } from './recommendation-memory-engine';
import { deriveAttributionMemoryAdjustment } from './attribution-memory-engine';
export function computeEconomicMemoryReport(records:EconomicMemoryRecord[]):EconomicMemoryReport { const tenantId=records[0]?.tenantId??'UNKNOWN'; const summary=summarizeCalibrationMemory(records); const forecast=deriveForecastMemoryAdjustment(summary); const scenario=deriveScenarioMemoryAdjustment(summary); const recommendation=deriveRecommendationMemoryAdjustment(summary); const attribution=deriveAttributionMemoryAdjustment(summary); const playbooks=calculatePlaybookReliability(records).sort((a,b)=>b.reliabilityScore-a.reliabilityScore); const domains=calculateDomainReliability(records).sort((a,b)=>b.reliabilityScore-a.reliabilityScore); const memoryReadinessStatus=records.length<5?'INSUFFICIENT_MEMORY':summary.lowEvidenceRate>0.5?'READY_WITH_LIMITS':'READY_FOR_MEMORY_WEIGHTED_FORECASTING'; return { tenantId, totalMemoryRecords:records.length, forecastMemoryStatus:forecast.recommendedForecastTreatment==='MARK_SPECULATIVE'?'WEAK':forecast.recommendedForecastTreatment==='MAINTAIN_CONFIDENCE'?'LIMITED':'STRONG', scenarioMemoryStatus:scenario.recommendedScenarioTreatment==='MARK_SPECULATIVE'?'WEAK':scenario.recommendedScenarioTreatment==='MAINTAIN_CONFIDENCE'?'LIMITED':'STRONG', recommendationMemoryStatus:recommendation.recommendedDecisionTreatment==='DEMOTE_CONFIDENCE'?'WEAK':recommendation.recommendedDecisionTreatment==='MAINTAIN'?'LIMITED':'STRONG', attributionMemoryStatus:attribution.recommendedAttributionTreatment==='DEMOTE_CONFIDENCE'?'WEAK':attribution.recommendedAttributionTreatment==='MAINTAIN'?'LIMITED':'STRONG', strongestPlaybooks:playbooks.slice(0,3).map(p=>p.playbookId), weakestPlaybooks:playbooks.slice(-3).map(p=>p.playbookId), strongestDomains:domains.slice(0,3).map(d=>d.domain), weakestDomains:domains.slice(-3).map(d=>d.domain), recurringOverestimationAreas:domains.filter(d=>d.systemicBias==='OVER_ESTIMATION').map(d=>d.domain), recurringUnderestimationAreas:domains.filter(d=>d.systemicBias==='UNDER_ESTIMATION').map(d=>d.domain), recommendedConfidenceAdjustments:[...forecast.memoryReasons,...scenario.memoryReasons,...recommendation.memoryReasons,...attribution.memoryReasons], memoryReadinessStatus }; }
