export type MemoryDomain='M365'|'AI_ECONOMICS'|'CROSS_DOMAIN'|'ECONOMIC_FORECASTING'|'ECONOMIC_SIMULATION'|'OTHER';
export type MemorySourceType='FORECAST'|'SCENARIO'|'RECOMMENDATION'|'ATTRIBUTION'|'PLAYBOOK'|'DOMAIN'|'ENTITY';
export type CalibrationType='SPEND'|'SAVINGS'|'PRODUCTIVITY'|'GOVERNANCE'|'APPROVAL'|'ATTRIBUTION'|'OTHER';
export type BiasDirection='OVER_ESTIMATION'|'UNDER_ESTIMATION'|'BALANCED';
export interface EconomicMemoryRecord { tenantId:string; sourceType:MemorySourceType; sourceId:string; domain:MemoryDomain; entityId:string; entityType?:'user'|'team'|'department'|'tool'|'licence'|'vendor'|'model'|'workflow'; playbookId:string; forecastId:string; scenarioId:string; recommendationId:string; calibrationType:CalibrationType; expectedValue:number; realizedValue:number; errorRate:number; biasDirection:BiasDirection; confidenceBefore:number; confidenceAfter:number; evidenceRefs:string[]; replayCorrelationId:string; lineageCorrelationId:string; reversed?:boolean; recordedAt?:string; }
export interface CalibrationMemorySummary { tenantId:string; totalRecords:number; averageErrorRate:number; volatility:number; overestimationRate:number; underestimationRate:number; balancedRate:number; lowEvidenceRate:number; consistencyClass:'CONSISTENT_ACCURACY'|'VOLATILE_ACCURACY'|'LOW_EVIDENCE_MEMORY'; biasClass:'OVER_BIAS'|'UNDER_BIAS'|'BALANCED_BIAS'; }
export interface ForecastMemoryAdjustment { confidenceAdjustment:number; forecastBias:BiasDirection; uncertaintyPenalty:number; recommendedForecastTreatment:'BOOST_CONFIDENCE'|'MAINTAIN_CONFIDENCE'|'REDUCE_CONFIDENCE'|'MARK_SPECULATIVE'; memoryReasons:string[]; }
export interface ScenarioMemoryAdjustment { scenarioConfidenceAdjustment:number; assumptionRiskAdjustment:number; scenarioBias:BiasDirection; recommendedScenarioTreatment:'BOOST_CONFIDENCE'|'MAINTAIN_CONFIDENCE'|'REDUCE_CONFIDENCE'|'MARK_SPECULATIVE'; memoryReasons:string[]; }
export interface RecommendationMemoryAdjustment { recommendationConfidenceAdjustment:number; realizationRiskAdjustment:number; reversalRiskAdjustment:number; recommendationBias:BiasDirection; recommendedDecisionTreatment:'PROMOTE_CONFIDENCE'|'MAINTAIN'|'REQUIRE_MORE_EVIDENCE'|'DEMOTE_CONFIDENCE'; memoryReasons:string[]; }
export interface AttributionMemoryAdjustment { attributionConfidenceAdjustment:number; doubleCountRiskAdjustment:number; attributionBias:BiasDirection; recommendedAttributionTreatment:'PROMOTE_CONFIDENCE'|'MAINTAIN'|'REQUIRE_MORE_EVIDENCE'|'DEMOTE_CONFIDENCE'; memoryReasons:string[]; }
export interface ReliabilityScore { reliabilityScore:number; reliabilityBand:'HIGH'|'MODERATE'|'LOW'|'UNKNOWN'; }
export interface PlaybookReliabilityResult extends ReliabilityScore { playbookId:string; accuracyRate:number; overestimationRate:number; underestimationRate:number; reversalRate:number; evidenceStrength:number; }
export interface DomainReliabilityResult extends ReliabilityScore { domain:MemoryDomain; accuracyRate:number; volatility:number; evidenceStrength:number; systemicBias:BiasDirection; }
export interface EntityReliabilityResult extends ReliabilityScore { entityId:string; entityType:'user'|'team'|'department'|'tool'|'licence'|'vendor'|'model'|'workflow'|'unknown'; recurringBias:BiasDirection; reversalRate:number; confidenceAdjustment:number; }
export interface EconomicMemoryReport { tenantId:string; totalMemoryRecords:number; forecastMemoryStatus:'STRONG'|'LIMITED'|'WEAK'; scenarioMemoryStatus:'STRONG'|'LIMITED'|'WEAK'; recommendationMemoryStatus:'STRONG'|'LIMITED'|'WEAK'; attributionMemoryStatus:'STRONG'|'LIMITED'|'WEAK'; strongestPlaybooks:string[]; weakestPlaybooks:string[]; strongestDomains:MemoryDomain[]; weakestDomains:MemoryDomain[]; recurringOverestimationAreas:string[]; recurringUnderestimationAreas:string[]; recommendedConfidenceAdjustments:string[]; memoryReadinessStatus:'READY_FOR_MEMORY_WEIGHTED_FORECASTING'|'READY_WITH_LIMITS'|'INSUFFICIENT_MEMORY'; }
