export const JOB_TYPES = ["M365_SYNC","FLEXERA_SYNC","SERVICENOW_SYNC","PLAYBOOK_EVALUATION","RECONCILIATION_RUN","DRIFT_SCAN","PRICING_REFRESH","PRICING_DRIFT_DETECTION","OUTCOME_VERIFICATION","EXCEPTION_EXPIRY_SWEEP","OPERATIONALIZATION_ASSESSMENT","SERVICENOW_SAM_PACK_RUN","FLEXERA_VALUE_PACK_RUN","PROCESS_EXECUTION_ORCHESTRATION_QUEUE"] as const;
export type JobType = (typeof JOB_TYPES)[number];
export type JobStatus = "PENDING"|"RUNNING"|"SUCCEEDED"|"PARTIAL"|"FAILED"|"DEAD_LETTERED"|"SKIPPED";
