export const JOB_TYPES = ["M365_SYNC","FLEXERA_SYNC","SERVICENOW_SYNC","PLAYBOOK_EVALUATION","RECONCILIATION_RUN","DRIFT_SCAN","PRICING_REFRESH","PRICING_DRIFT_DETECTION","OUTCOME_VERIFICATION"] as const;
export type JobType = (typeof JOB_TYPES)[number];
export type JobStatus = "PENDING"|"RUNNING"|"SUCCEEDED"|"PARTIAL"|"FAILED"|"DEAD_LETTERED"|"SKIPPED";
