export type FinOpsSourceSystem='FLEXERA'|'APPTIO_CLOUDABILITY'|'SERVICENOW_CCM'|'AWS'|'AZURE'|'GCP'|'MANUAL'|'INTERNAL';
export type FinOpsRecommendationCategory='IDLE_RESOURCE'|'RIGHTSIZE_RESOURCE'|'COMMITMENT_OPTIMIZATION'|'STORAGE_OPTIMIZATION'|'ENVIRONMENT_SHUTDOWN'|'TAGGING_REMEDIATION'|'OWNER_REMEDIATION'|'GPU_AI_SPEND_REVIEW'|'DUPLICATE_SERVICE_REVIEW'|'ANOMALY_REVIEW';
export type FinOpsMode='READ_ONLY'|'RECOMMEND_ONLY'|'APPROVAL_REQUIRED';
export interface FinOpsSourceRecommendation { tenantId:string; sourceSystem:FinOpsSourceSystem; sourceRecommendationId:string; cloudProvider:'AWS'|'AZURE'|'GCP'|'OTHER'; accountId?:string; subscriptionId?:string; resourceId?:string; resourceType?:string; region?:string; serviceName?:string; recommendationCategory:FinOpsRecommendationCategory; recommendationSummary:string; estimatedMonthlySavings:number; savingsConfidence:number; ownerHints?:string[]; costCenterHints?:string[]; tags?:Record<string,string>; evidenceRefs?:string[]; sourceCreatedAt:string; sourceUpdatedAt:string; lineageCorrelationId:string; replayCorrelationId:string; }
export interface FinOpsNormalizedRecommendation extends Required<Omit<FinOpsSourceRecommendation,'accountId'|'subscriptionId'|'resourceId'|'resourceType'|'region'|'serviceName'|'ownerHints'|'costCenterHints'|'tags'|'evidenceRefs'>> { accountId:string; subscriptionId:string; resourceId:string; resourceType:string; region:string; serviceName:string; ownerHints:string[]; costCenterHints:string[]; tags:Record<string,string>; evidenceRefs:string[]; estimatedAnnualSavings:number; sourceReliability:'HIGH'|'MEDIUM'|'LOW'; evidenceCompleteness:'HIGH'|'MEDIUM'|'LOW'; ownershipCompleteness:'HIGH'|'MEDIUM'|'LOW'; savingsEstimateQuality:'HIGH'|'MEDIUM'|'LOW'; }
export interface FinOpsSavingsActionPlan { actionPlanId:string; tenantId:string; recommendationId:string; sourceRecommendationId:string; actionType:'REVIEW_IDLE_RESOURCE'|'RIGHTSIZE_REVIEW'|'COMMITMENT_REVIEW'|'STORAGE_CLEANUP_REVIEW'|'ENVIRONMENT_LIFECYCLE_REVIEW'|'TAGGING_FIX_REVIEW'|'OWNER_ASSIGNMENT_REVIEW'|'GPU_AI_SPEND_REVIEW'|'DUPLICATE_SERVICE_REVIEW'|'ANOMALY_INVESTIGATION'; actionSummary:string; requiredApprovals:string[]; requiredEvidence:string[]; preFlightChecks:string[]; rollbackConsiderations:string[]; operationalRisks:string[]; expectedSavings:number; implementationComplexity:'LOW'|'MEDIUM'|'HIGH'; recommendedMode:FinOpsMode; }
export interface FinOpsExecutionReadiness { readinessScore:number; readinessState:'READY_FOR_APPROVAL'|'NEEDS_OWNER'|'NEEDS_EVIDENCE'|'NEEDS_CHANGE_WINDOW'|'HIGH_RISK_REVIEW'|'BLOCKED'; blockingReasons:string[]; approvalEscalationReasons:string[]; requiredEvidence:string[]; recommendedNextStep:string; }
export interface FinOpsOwnerAccountability { ownerConfidence:number; ownerType:'business_owner'|'technical_owner'|'cloud_owner'|'assignment_group'|'unknown'; ownerId:string; ownerDisplayName:string; assignmentGroup:string; costCenter:string; accountabilityGaps:string[]; escalationRequired:boolean; }
export interface FinOpsServiceNowWorkPackage { workPackageId:string; tenantId:string; sourceRecommendationId:string; shortDescription:string; description:string; assignmentGroup:string; businessOwner:string; technicalOwner:string; approvalRequired:boolean; riskLevel:'LOW'|'MEDIUM'|'HIGH'; implementationSteps:string[]; preFlightChecks:string[]; rollbackNotes:string[]; evidenceRefs:string[]; expectedSavings:number; readinessState:FinOpsExecutionReadiness['readinessState']; }
export interface FinOpsRealizationForecast { realizationProbability:number; projectedRealizedMonthlySavings:number; projectedRealizedAnnualSavings:number; reversalRisk:number; implementationFriction:number; confidence:number; forecastReasons:string[]; }
export interface FinOpsRecurrencePreventionPolicy { policyId:string; tenantId:string; policyType:'OWNER_REQUIRED_POLICY'|'TAGGING_REQUIRED_POLICY'|'ENVIRONMENT_TTL_POLICY'|'IDLE_RESOURCE_REVIEW_POLICY'|'COMMITMENT_REVIEW_POLICY'|'GPU_AI_SPEND_GUARDRAIL'|'BUDGET_DRIFT_ALERT_POLICY'|'STORAGE_LIFECYCLE_POLICY'|'ANOMALY_REVIEW_POLICY'; policySummary:string; targetScope:string; triggerCondition:string; reviewCadence:'WEEKLY'|'MONTHLY'|'QUARTERLY'; ownerRequirement:string; evidenceRequirement:string; recommendedMode:FinOpsMode; }
export interface FinOpsSavingsRealizationRecord { realizationRate:number; realizedMonthlySavings:number; realizedAnnualSavings:number; shortfall:number; overperformance:number; reversalDetected:boolean; recurrenceDetected:boolean; calibrationSignal:'OVER'|'UNDER'|'ON_TRACK'; memorySignal:'CONFIDENCE_UP'|'CONFIDENCE_DOWN'|'MAINTAIN'; }
export interface FinOpsOperationalizationReport { tenantId:string; totalSourceRecommendations:number; normalizedCount:number; readyForApprovalCount:number; needsOwnerCount:number; needsEvidenceCount:number; blockedCount:number; totalEstimatedAnnualSavings:number; totalForecastedRealizedAnnualSavings:number; realizationConfidence:number; recurrencePreventionCoverage:number; ownerCoverage:number; serviceNowPackageCount:number; topOperationalizationRisks:string[]; topSavingsOpportunities:string[]; readinessStatus:'READY_FOR_GOVERNED_OPERATIONALIZATION'|'READY_WITH_LIMITS'|'HARDENING_REQUIRED'; }
